### ISSUE TITLE
Add Tomcat 10 to the buildpack

### ISSUE THREAD

**Issue by azee** [cloudfoundry/java-buildpack#1015]
Spring Boot 3 requires Servlet API 5.0.

Tomcat 9+ supports Servlet API 4.0 while Tomcat 10+ supports Servlet API 5.0.
We are unable to migrate to Spring Boot 3 as it requires Jakarta Servlet API 5.0 compatible container.

It is a critical issue as Spring boot 2.7+ has vulnerabilities.

Please release a buildpack version with Tomcat 10+.

**Comment by azee** [comment]
Seems that it could be done via tomcat.version parameter.

**Comment by dmikusa** [comment]
Yes, Tomcat 10 has been an option for a long time now. It's just not the default.

You just need to tell the buildpack you want Tomcat 10.

```
env:
  JBP_CONFIG_TOMCAT: '{ tomcat: { version: 8.0.+ } }'
```

**Comment by krismarc** [comment]
Is there any plan to set Tomcat 10 as a default? We relay on offline version of the buildpack and this prevents us from using optional ones.
