### ISSUE TITLE
Java Buildpack v4.62.0 build fails

### ISSUE THREAD

**Issue by ybykov-a9s** [cloudfoundry/java-buildpack#1034]
Build fails with a message: 

`Pinning app_dynamics_agent version to 
rake aborted!
Unable to resolve version '23.8.0_35032' for platform ''
/tmp/build/7edf843e/buildpack-repo/rakelib/dependency_cache_task.rb:153:in `block in get_from_cache'`

default_repository_root is set to `https://java-buildpack.cloudfoundry.org`
And this repo doesn't contain a record for version '23.8.0_35032':
https://java-buildpack.cloudfoundry.org/appdynamics/index.yml

**Comment by pivotal-david-osullivan** [comment]
Hi,

I think this might be an issue with caching/improper invalidation with Cloudfront. The `index.yml` does contain `23.8.0_35032` but the version of the index you are receiving is not the latest.

```
23.6.1_34894: https://download.run.pivotal.io/appdynamics/appdynamics-23.6.1-34894.tar.gz
23.7.0_34957: https://download.run.pivotal.io/appdynamics/appdynamics-23.7.0-34957.tar.gz
23.8.0_35032: https://download.run.pivotal.io/appdynamics/appdynamics-23.8.0-35032.tar.gz
```

We have run a fresh invalidation, could you try clearing your caches and try again?

**Comment by ybykov-a9s** [comment]
Hi,
even without cleaning any cache today it works. But at the moment of opening this PR it didn't work from several different locations. Thanks a lot for an attention to this small issue. I'm just thinking that the issue might appear in the future again.
