### ISSUE TITLE
Java 21 Support

### ISSUE THREAD

**Issue by jbennett2091** [cloudfoundry/java-buildpack#1035]
Java 21 is the new LTS version of Java.  Please provide cloudfoundry support for this JVM so that applications built for Java 21 can run in CF.

**Comment by pivotal-david-osullivan** [comment]
We are investigating adding 21 to the default list of version lines, the current problem with this is a size limitation on CF wrt buildpack size > 1GB.

The binaries for 21 have been added to the default repository already, so at the moment you just need to add `21` to the [version_lines](https://github.com/cloudfoundry/java-buildpack/blob/bb37d7cdedf0f4c840ba95a21becf96690aa3359/config/open_jdk_jre.yml#L20-L23) list, bundle the buildpack, and choose 21 with the OpenJDK config variable.

**Comment by anthonydahanne** [comment]
@pivotal-david-osullivan ,  according to @dsabeti buildpacks larger than 1GB have been successfully used in the field.

I think we could add `21` directly into the official Java buildpack

**Comment by candrews** [comment]
Any news?

I'm not clear on what, if anything, is blocking the resolution of this issue by merging https://github.com/cloudfoundry/java-buildpack/pull/1040

**Comment by anthonydahanne** [comment]
we're currently validating the size bigger than 1GB will not break the upload of JBP updates (we believe, as @pivotal-david-osullivan mentioned https://github.com/cloudfoundry/java-buildpack/issues/1035#issuecomment-1753051227 that it could be an issue in some cases)

**Comment by jaschenk** [comment]
Anyway we can get some traction on this?  I was able to build locally the build pack and to eliminate the size issues, removing JDK8 and JDK11, as you should have the options to build what you want.  Thank you for everyone's efforts.  But you should consider clipping out older JDKs.

**Comment by dsabeti** [comment]
Just updating this thread on the progress: 
- The [latest CAPI release](https://github.com/cloudfoundry/capi-release/releases/tag/1.167.0) includes a change to allow for larger file uploads.
- The develop branch of cf-deployment has [picked up the change](https://github.com/cloudfoundry/cf-deployment/blob/develop/cf-deployment.yml#L2785-L2788), and it's going through the pipelines currently.

@anthonydahanne, I think you're safe to start the work to integrate Java 21 in the buildpack.
