### ISSUE TITLE
unable to invoke layer creator, Unable to find built artifact in target/*.[ejw]ar

### ISSUE THREAD

**Issue by Rvarman0110** [cloudfoundry/java-buildpack#1044]
unable to invoke layer creator
unable to contribute application layer
unable to resolve artifacts
unable to find any built artifacts for pattern(s):/target/*.[ejw]

and in my pom.xml there is a modules section where we refer other pom.xml files which are located in the subfolders of main directory 

.
├── pom.xml
├── api
│   ├── pom.xml
│   └── target
└── web
    ├── pom.xml
    ├── target
    
    
now while building the build ends up success but it is unable to find any jar there

(say there are 2 modules in my pom.xml then it will build those 2 jars and 1 main jar totally 3 jars and it is unable to find those jars from there)
    
   I tried using BP_MAVEN_BUILT_ARTIFACT and set the location of jar explicitly /source/code/target/*.[ejw]ar
   
  how to resolve this issue

**Comment by dmikusa** [comment]
If you're having issues with Paketo Buildpacks, which it sounds like is the case, then please open a new issue here https://github.com/orgs/paketo-buildpacks/discussions.

**Comment by pivotal-david-osullivan** [comment]
Closing as the [discussion](https://github.com/orgs/paketo-buildpacks/discussions/227) continued in the correct org
