### ISSUE TITLE
NoSuchMethodError after upgrade of json-io

### ISSUE THREAD

**Issue by martinvisser** [cloudfoundry/java-buildpack#1062]
As mentioned in https://github.com/jdereg/json-io/issues/274, a `NoSuchMethodError` is triggered after `json-io` was updated. Would be appreciated if the compatibility could be fixed.

**Comment by martinvisser** [comment]
Hello @anthonydahanne, we upgraded the version ourselves, basically because there was an upgrade. During our builds we didn't have any issues, but whilst trying to deploy with the java-buildpack it failed with the aforementioned error.
So, I guess what I'm asking is if there are any plans to upgrade `json-io`. If that implies changes to `java-cf-env` then I guess that's where the change needs to be made?

**Comment by anthonydahanne** [comment]
> So, I guess what I'm asking is if there are any plans to upgrade json-io

eventually yes. 
But honestly, for now, as long as [there isn't any vulnerabilities](https://central.sonatype.com/artifact/com.cedarsoftware/json-io/versions) or major features missing, there's no rush I believe.

> If that implies changes to java-cf-env then I guess that's where the change needs to be made?

Yeah, according [to your issue](https://github.com/jdereg/json-io/issues/274) we'll have to change java-cf-env code (a minor upgrade I imagine)

A final note though: if you use [java-cfenv-all](https://central.sonatype.com/artifact/io.pivotal.cfenv/java-cfenv-all/3.1.5/dependencies), you'll notice that `json-io` is shaded into it; meaning you would not upgrade the version yourself (and you could actually ignore that dependency altogether) - maybe you have reasons not to use this "all in one" `java-cfenv` (the jar injected by the `java-buildpack` btw) , but in case you did not know about it, it's worth checking it I believe.

**Comment by martinvisser** [comment]
We are using the following dependency in our maven project, which does not use the "all" version unfortunately:
```xml
        <dependency>
            <groupId>io.pivotal.spring.cloud</groupId>
            <artifactId>spring-cloud-services-starter-config-client</artifactId>
        </dependency>
```
This dependency brings in json-io:
<img width="472" alt="image" src="https://github.com/cloudfoundry/java-buildpack/assets/3170236/d0387b58-2f10-488f-9076-44b1d8db08f1">

We got a notification this version of json-io contains a CVE, which is the main reason we upgraded it in the first place.
Do you know if there is an alternative for the config-client starter which would use the shaded version perhaps? It doesn't really solve the CVE issue of course, but it would help with compatibility.

**Comment by anthonydahanne** [comment]
> This dependency brings in json-io:

OK, then I guess the issue lies with https://github.com/pivotal-cf/spring-cloud-services-starters not consuming our latest release that relies on a java-cfenv free of CVEs

> Do you know if there is an alternative for the config-client starter which would use the shaded version perhaps? It doesn't really solve the CVE issue of course, but it would help with compatibility.

Hum, I don't know, we should ask them - cc @kvmw

**Comment by martinvisser** [comment]
The author of `json-io` added the API back, so after upgrading to its latest version the issue is gone. I guess we can close this one as the work should be done in the starters anyway.
