### ISSUE TITLE
JBP auto downloading  MariaDB JDBC driver though app package includes AWS MySQL driver aws-mysql-jdbc.jar

### ISSUE THREAD

**Issue by scottgai** [cloudfoundry/java-buildpack#1067]
After switching to use CSB provisioned RDS Mysql db from old pivotal aws services broker provisioned aurora mysql cluster and are having an issue with spring now injecting MariaDB JDBC driver.
Customer are running with the AWS MySQL driver (aws-mysql-jdbc.jar) which doesn't look to be in the [list](https://github.com/cloudfoundry/java-buildpack/blob/1ca7a11b757146a2d36617cc0431915355bd1e4b/lib/java_buildpack/framework/maria_db_jdbc.rb#L49C43-L49C52) that the MariaDB buildpack component is checking for.
Customer don't want the buildpack to download MariaDB JDBC driver as they are not going to use it. They will include AWS MySQL driver aws-mysql-jdbc.jar in app package instead.
Shall we consider adding `aws-mysql-jdbc*.jar` to the list as well?

**Comment by pivotal-david-osullivan** [comment]
Closed via #1068
