### ISSUE TITLE
Only SSL v3 downloads work

### ISSUE THREAD

**Issue by dhrapson** [cloudfoundry/java-buildpack#108]
Hi. We are using the Java buildpack with our own internal repository, which provides the binaries over HTTPs. In the wake of the Poodle SSL vulnerability we tried turning off SSL v3 on our repository server, however the java buildpack then failed to download binaries with the message:

ERR [DownloadCache]                  WARN  Unable to download https:/[serverhostname]/auto-reconfiguration/index.yml into cache /tmp: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: (null)

I think that perhaps the buildpack should default to TLS now?
I imagine the buildpack still works against download.pivotal.io, however it will cease to to work if the owners of that infrastructure protect against Poodle in the same way.

**Comment by jonathanamartin** [comment]
@dhrapson did you ever figure out the root cause?  I'm able to build the CF Java Buildpack from home.  However, when using Ubuntu on a VM behind a proxy I get the following:

```
me@me-VirtualBox:~/git-repos/cloudfoundry-java-buildpack$ bundle exec rake package OFFLINE=true PINNED=true
[DownloadCache]                  WARN  Unable to download https://download.run.pivotal.io/tomcat/index.yml into cache build/staging/resources/cache: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
[DownloadCache]                  WARN  default SSL context is SSLv23
rake aborted!
Unable to find cached file for https://download.run.pivotal.io/tomcat/index.yml
/home/me/git-repos/cloudfoundry-java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:74:in `get'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:169:in `get_from_cache'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:161:in `block (2 levels) in uris'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:159:in `each'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:159:in `block in uris'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:158:in `each'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:158:in `uris'
/home/me/git-repos/cloudfoundry-java-buildpack/rakelib/dependency_cache_task.rb:45:in `initialize'
/home/me/git-repos/cloudfoundry-java-buildpack/Rakefile:40:in `new'
/home/me/git-repos/cloudfoundry-java-buildpack/Rakefile:40:in `<top (required)>'
(See full trace by running task with --trace)
```
You can see I added the log statement you mentioned (`default SSL context is SSLv23`). Here are my versions:

OpenSSL 1.0.2g-fips
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
