### ISSUE TITLE
When creating offline java buildpack for v4.70.0, getting error: rake aborted! Unable to resolve version '24.4.1_35880' for platform ''

### ISSUE THREAD

**Issue by mohdazaruddin** [cloudfoundry/java-buildpack#1084]
# WHAT 
Getting the below error while creating the offline java buildpack for v4.68.0  to v4.70.0
rake aborted! Unable to resolve version '24.4.1_35880' for platform 

# Execution Output
$bundle exec rake package OFFLINE=true VERSION=v4.70.0         
rake aborted!
Unable to resolve version '24.4.1_35880' for platform ''
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:153:in `block in get_from_cache'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `block in cached'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `cached'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:81:in `get'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:147:in `get_from_cache'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:139:in `block (2 levels) in uris'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:137:in `each'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:137:in `block in uris'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:136:in `each'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:136:in `uris'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/rakelib/dependency_cache_task.rb:48:in `initialize'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/Rakefile:42:in `new'
/tmp/build/a6e410c9/tracker-repo/targets/java-buildpack/Rakefile:42:in `<top (required)>'
/root/.rbenv/versions/3.0.0/bin/bundle:23:in `load'
/root/.rbenv/versions/3.0.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

# INVESTIGATION
I suspect the problem with the version 24.4.1_35880 on config/app_dynamics_agent.yml.  Tried with little older version  24.2.0_35552 and it worked. 

$ bundle exec rake package OFFLINE=true VERSION=v4.70.0
[VersionResolver]                WARN  Discarding illegal version 1.28.0-RC2: Invalid micro version '0-RC2'
[VersionResolver]                WARN  Discarding illegal version 1.28.0-RC3: Invalid micro version '0-RC3'
Caching https://java-buildpack.cloudfoundry.org/groovy/index.yml
Caching https://java-buildpack.cloudfoundry.org/spring-boot-cli/index.yml
Caching https://java-buildpack.cloudfoundry.org/tomcat/index.yml
Caching https://java-buildpack.cloudfoundry.org/tomcat-lifecycle-support/index.yml
Caching https://java-buildpack.cloudfoundry.org/tomcat-logging-support/index.yml
Caching https://java-buildpack.cloudfoundry.org/tomcat-access-logging-support/index.yml
Caching https://java-buildpack.cloudfoundry.org/redis-store/index.yml
Caching https://java-buildpack-tomcat-gemfire-store.s3-us-west-2.amazonaws.com/index.yml
Caching https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/index.yml
Caching https://java-buildpack.cloudfoundry.org/openjdk/jammy/x86_64/index.yml
Caching https://java-buildpack.cloudfoundry.org/tomcat/index.yml
Caching https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/index.yml
cp config/app_dynamics_agent.yml build/staging/config/app_dynamics_agent.yml
Caching https://java-buildpack.cloudfoundry.org/jvmkill/jammy/x86_64/index.yml
chmod 644 build/staging/config/app_dynamics_agent.yml
.
.
.
Caching https://github.com/signalfx/splunk-otel-java/releases/download/v1.32.0/splunk-otel-javaagent.jar
Creating build/java-buildpack-offline-v4.70.0.zip

**Comment by pivotal-david-osullivan** [comment]
Are you still seeing this? I cannot reproduce it and the problem version but it may be caused by caching of the `index.yml` file for this component

**Comment by mohdazaruddin** [comment]
Yes Dave..The issue still exists when I try to generate the offline buildpack with the appdynamics version given on the release.

**Comment by mohdazaruddin** [comment]
@pivotal-david-osullivan  I am unable to see the latest versions of app dynamics versions when queried. Thats the reason it is unable to resolve the latest version.


root@68401054-9b21-4681-4f3e-af2845130a8b:/tmp/build/a6e410c9/tracker-repo/adapters/java-buildpack# curl https://java-buildpack.cloudfoundry.org/appdynamics/index.yml --resolve java-buildpack.cloudfoundry.org:443:104.22.5.232 
21.11.3_33314: https://download.run.pivotal.io/appdynamics/appdynamics-21.11.3-33314.tar.gz
21.11.4_33358: https://download.run.pivotal.io/appdynamics/appdynamics-21.11.4-33358.tar.gz
22.1.0_33445: https://download.run.pivotal.io/appdynamics/appdynamics-22.1.0-33445.tar.gz
22.2.0_33545: https://download.run.pivotal.io/appdynamics/appdynamics-22.2.0-33545.tar.gz
22.3.0_33637: https://download.run.pivotal.io/appdynamics/appdynamics-22.3.0-33637.tar.gz
22.4.0_33722: https://download.run.pivotal.io/appdynamics/appdynamics-22.4.0-33722.tar.gz
22.5.0_33845: https://download.run.pivotal.io/appdynamics/appdynamics-22.5.0-33845.tar.gz
22.6.0_33917: https://download.run.pivotal.io/appdynamics/appdynamics-22.6.0-33917.tar.gz
22.7.0_34044: https://download.run.pivotal.io/appdynamics/appdynamics-22.7.0-34044.tar.gz
22.8.0_34104: https://download.run.pivotal.io/appdynamics/appdynamics-22.8.0-34104.tar.gz
22.9.0_34210: https://download.run.pivotal.io/appdynamics/appdynamics-22.9.0-34210.tar.gz
22.9.1_34265: https://download.run.pivotal.io/appdynamics/appdynamics-22.9.1-34265.tar.gz
22.10.0_34344: https://download.run.pivotal.io/appdynamics/appdynamics-22.10.0-34344.tar.gz
22.11.0_34486: https://download.run.pivotal.io/appdynamics/appdynamics-22.11.0-34486.tar.gz
22.12.0_34603: https://download.run.pivotal.io/appdynamics/appdynamics-22.12.0-34603.tar.gz
23.1.0_34620: https://download.run.pivotal.io/appdynamics/appdynamics-23.1.0-34620.tar.gz
23.2.0_34668: https://download.run.pivotal.io/appdynamics/appdynamics-23.2.0-34668.tar.gz
23.3.0_34728: https://download.run.pivotal.io/appdynamics/appdynamics-23.3.0-34728.tar.gz
23.4.0_34758: https://download.run.pivotal.io/appdynamics/appdynamics-23.4.0-34758.tar.gz
23.5.0_34821: https://download.run.pivotal.io/appdynamics/appdynamics-23.5.0-34821.tar.gz
23.6.0_34839: https://download.run.pivotal.io/appdynamics/appdynamics-23.6.0-34839.tar.gz
23.6.1_34894: https://download.run.pivotal.io/appdynamics/appdynamics-23.6.1-34894.tar.gz
23.7.0_34957: https://download.run.pivotal.io/appdynamics/appdynamics-23.7.0-34957.tar.gz
23.8.0_35032: https://download.run.pivotal.io/appdynamics/appdynamics-23.8.0-35032.tar.gz
23.9.0_35116: https://download.run.pivotal.io/appdynamics/appdynamics-23.9.0-35116.tar.gz
23.9.1_35149: https://download.run.pivotal.io/appdynamics/appdynamics-23.9.1-35149.tar.gz
23.10.0_35234: https://download.run.pivotal.io/appdynamics/appdynamics-23.10.0-35234.tar.gz
23.11.0_35328: https://download.run.pivotal.io/appdynamics/appdynamics-23.11.0-35328.tar.gz
23.12.0_35361: https://download.run.pivotal.io/appdynamics/appdynamics-23.12.0-35361.tar.gz
24.1.0_35445: https://download.run.pivotal.io/appdynamics/appdynamics-24.1.0-35445.tar.gz
24.2.0_35552: https://download.run.pivotal.io/appdynamics/appdynamics-24.2.0-35552.tar.gz

**Comment by pivotal-david-osullivan** [comment]
I created an invalidation for the `/appdynamics` path and this seems to have resolved the issue
