### ISSUE TITLE
MongoDB with replica set AutoReconfiguration problems

### ISSUE THREAD

**Issue by thisismana** [cloudfoundry/java-buildpack#110]
We stumbled upon the following issue in a Spring Boot (4.1.1.RELEASE) project, probably caused by the AutoReconfiguration feature of this build pack.

We are using spring-boot-starter-data-mongodb, using the mongo java driver version 2.12.4.

Within our application, we are creating the 2 relevant beans:
    
    @Bean Mongo mongo() {...}
    @Bean MongoTemplate mongoTemplate() {...}

And of course we have a `MongoRepository` that is causing the problem. Normally, the `MongoRepository` should use the `mongoTemplate` bean to access the database. 

We have provided a mongoURI as a user provided services instance (upsi):

    cf cups upsi-mongo-xxx -p uri

The URI has the format `mongodb://user:pass@host1,host2,host3/db?replicaSet=xxx`

When the app is now startet, the following happens:

- the beans `mongo` and `mongoTemplate` that we instantiate point to the correct replicaSet (insert, find and so on is working fine)
- the `mongoRepository` points to `127.0.0.1:27017` (default address)

This seems to be auto configured during the startup, when listing all the existing beans, we see no unexpected stuff around the mongos.

The only thing that worked avoiding this behaviour was to change the JSON format of the `VCAP_SERVICE` string and not to use the term `uri`, but change it to something else like `masked_uri` and adapt the creation of our beans that parse this. This seems to keep the auto configuration from working and the `mongoRepository` uses the existing beans to access the database as configured.

We noticed that this only happens when the `mongoURI` contains multiple hosts. When we only put one of the replica set hosts into the `mongoURI`, it works as expected.

**Comment by scottfrederick** [comment]
Spring Cloud Connectors 1.1.1 has been released to Maven Central, including support for MongoDB replica sets.

**Comment by nebhale** [comment]
@thisismana We've just released `v1.6.0.RELEASE` of the auto-reconfiguration support.  This should allow you to use replica sets now.  If this does not work for you, please comment and we'll reopen the issue.

Thanks for your patience while we implemented this.
