### ISSUE TITLE
Parenthesis not allowed in JAVA_OPTS

### ISSUE THREAD

**Issue by svennela** [cloudfoundry/java-buildpack#120]
Hi,

We have customer deploying keystore with JAVA_OPTS variable. In password field he is using (, resulting in fail to deploy his application. I have tried ‘( and \( without any success. please help.

JAVA_OPTS: -Djavax.net.ssl.keyStore=/home/vcap/app/META-INF/extra-files/keystore -Djavax.net.ssl.keyStorePassword=password(123)

**Comment by cgfrost** [comment]
We have raised an issue in our tracker to follow this. 

https://www.pivotaltracker.com/story/show/86290602

**Comment by nebhale** [comment]
Completed in d69e2471be7067ab90bed5ac5752531e436147cb
