### ISSUE TITLE
Java buildpack fails for unsatisfied dependency

### ISSUE THREAD

**Issue by adicocco** [cloudfoundry/java-buildpack#123]
Hello,

I'm trying to use latest java-buildpack version with
cf push <app name> -p ~/helloworldJava/HelloWorld.war -b https://github.com/cloudfoundry/java-buildpack.git
It is a simple java application that worked since few hours ago (I noticed that new version of buildpack has been released), but now it is failing with the following error:
-----> Downloaded app package (4.0K)
Cloning into '/tmp/buildpacks/java-buildpack'...
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- zip (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/jre/open_jdk_like.rb:22:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/jre/open_jdk_jre.rb:19:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:177:in `require_component'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:152:in `block in instantiate'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:149:in `map'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:149:in `instantiate'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:118:in `instantiate_components'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:111:in `initialize'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:203:in `new'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:203:in `with_buildpack'
	from /tmp/buildpacks/java-buildpack/bin/compile:26:in `<main>'
Staging failed: Buildpack compilation step failed

FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

It seems that latest version has an unsatisfied dependencies from zip gem.

Can you help me on this?

Thank you.

Regards.
Antonio

**Comment by nebhale** [comment]
@adicocco Great catch.  I've reverted the recent change and we'll have another go at it.
