### ISSUE TITLE
JDK version issues

### ISSUE THREAD

**Issue by stopyro** [cloudfoundry/java-buildpack#125]
I have a war that has worked "forever". I pushed it recently and it no longer starts. 

Stagings shows we downloaded a 1.6 JDK. Looking at the app, it turns out the class has a magic number of 32, so this makes sense.
      Downloading Open Jdk JRE 1.6.0_27 from https://download.run.pivotal.io/openjdk/lucid/x86_64/openjdk-1.6.0_27.tar.gz (9.9s)

But the app fails to start because we're trying to load a 1.7 class. Most likely, Tomcat itself.
   ERR     Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/catalina/startup/Bootstrap : Unsupported major.minor version 51.0

I assume this is an unintended side effect of Java 8 support that appears to have been added recently.
I understand I can clone the BP and configure my way around the problem.

**Comment by cgfrost** [comment]
Hi Jim,

This isn't ideal. The buildpack should download the latest version of Java
for the highest compilation version found in you application. So if all the
application is compiled with Java 6 except 1 single class file that is
compiled with Java 7 for some reason, it should download and run the
application with the latest Java 7 JRE. If your confident that your entire
application is compiled with Java 6 then the behaviour you are seeing is
working as designed. In which case I'd like to understand why you are not
compiling with a higher level of Java. There may be some use cases we
haven't considered and supported very well. If there is any Java 7/8 class
code in your application then you have found a bug.

Chris.

On Tue, Jan 13, 2015 at 9:34 PM, Jim Stopyro <notifications@github.com>
wrote:

> I have a war that has worked "forever". I pushed it recently and it no
> longer starts.
>
> Stagings shows we downloaded a 1.6 JDK. Looking at the app, it turns out
> the class has a magic number of 32, so this makes sense.
> Downloading Open Jdk JRE 1.6.0_27 from
> https://download.run.pivotal.io/openjdk/lucid/x86_64/openjdk-1.6.0_27.tar.gz
> (9.9s)
>
> But the app fails to start because we're trying to load a 1.7 class. Most
> likely, Tomcat itself.
> ERR Exception in thread "main" java.lang.UnsupportedClassVersionError:
> org/apache/catalina/startup/Bootstrap : Unsupported major.minor version 51.0
>
> I assume this is an unintended side effect of Java 8 support that appears
> to have been added recently.
> I understand I can clone the BP and configure my way around the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/java-buildpack/issues/125>.
>



-- 
--
Christopher Frost - GoPivotal UK

**Comment by gaurav1416** [comment]
Hi Chris,

I tried deploying following war on CF(it worked seamlessly before)
https://github.com/cloudfoundry/cf-java-client/tree/master/cf-java-client-test-apps and it failed for same reason.

As far as my analysis goes, the reason for failure was, I built war on JDK 7 but pom has a dependency defined on org.apache.maven.plugins which was configured for Java version 1.6.
When I changed this dependency to version 1.7, war was successfully deployed using buildpack.

My question is can’t we build war\jar on higher version where internal dependency is defined on lower version?

Thanks & Regards,
Gaurav

**Comment by stopyro** [comment]
Hi Chris,

The war contains a single class (it's a hello world app) so it's easy to verify that all classes in the app are at V6. When I pull down the tomcat (https://download.run.pivotal.io/tomcat/tomcat-8.0.15.tar.gz) and take it apart, it contains classes that are at V7.

I can certainly recompile my simple app with a V7 JDK, in which case I'm confident the app will work, but that's really not the point. The current algorithm doesn't work. The current algorithm only looks for loose classes and does not  considers classes contained in jars or other archives. This means the algorithm is failing to account for:
- the appserver run-time, in this case Tomcat, typically comes as a collection of jars.
- third party jars that are embedded into the app (lib directory).

Additionally, I would be concerned about the performance impacts of apps with a large number of classes.

**Comment by cgfrost** [comment]
Hi Jim,

OK, I understand the issue. We will get something in place ASAP.

As for the performance issue, I tested the class file scanning on some
pretty big archives and performance isn't a problem, worst case scenario is
a couple of extra seconds during staging for the truly massive apps.

Chris.

On Wed, Jan 14, 2015 at 2:22 PM, Jim Stopyro <notifications@github.com>
wrote:

> Hi Chris,
>
> The war contains a single class (it's a hello world app) so it's easy to
> verify that all classes in the app are at V6. When I pull down the tomcat (
> https://download.run.pivotal.io/tomcat/tomcat-8.0.15.tar.gz) and take it
> apart, it contains classes that are at V7.
>
> I can certainly recompile my simple app with a V7 JDK, in which case I'm
> confident the app will work, but that's really not the point. The current
> algorithm doesn't work. The current algorithm only looks for loose classes
> and does not considers classes contained in jars or other archives. This
> means the algorithm is failing to account for:
>
>    - the appserver run-time, in this case Tomcat, typically comes as a
>    collection of jars.
>    - third party jars that are embedded into the app (lib directory).
>
> Additionally, I would be concerned about the performance impacts of apps
> with a large number of classes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/java-buildpack/issues/125#issuecomment-69922264>
> .
>



-- 
--
Christopher Frost - GoPivotal UK

**Comment by stopyro** [comment]
Hi Chris,

I've been looking at this a bit more. I think there's more detail here

1) Going back and looking at an un-tar'd Tomcat, there are "loose" classes included, not everything is in jars, so the failure to detect V7 based on Tomcat is likely a path issue. (the buildpack code is looking at the app directory but not the directory where Tomcat is located.) I imagine this issue could extend to frameworks also

2) The "jars included in the app" is a second, separate issue, I believe. More on that....I see the "version checking" looks explicitly for class versions of 32 and 33 (V6 and V7). Anything else is assigned to V8. If a jar happened to contain a V5 class that would get mapped as V8. Perhaps the check should be "anything less than or equal to 32 gets assigned V6"

 and if the version doesn

**Comment by cgfrost** [comment]
Hi Jim,

We had a chat about it and there are several issues with how this is
working. You make some very good points which we will bear in mind but
we're going to go back and look again at the problem we are trying to solve
with this version scanning and see if we can come up with a different
solution.

Chris.

On Wed, Jan 14, 2015 at 4:53 PM, Jim Stopyro <notifications@github.com>
wrote:

> Hi Chris,
>
> I've been looking at this a bit more. I think there's more detail here
>
> 1) Going back and looking at an un-tar'd Tomcat, there are "loose" classes
> included, not everything is in jars, so the failure to detect V7 based on
> Tomcat is likely a path issue. (the buildpack code is looking at the app
> directory but not the directory where Tomcat is located.) I imagine this
> issue could extend to frameworks also
>
> 2) The "jars included in the app" is a second, separate issue, I believe.
> More on that....I see the "version checking" looks explicitly for class
> versions of 32 and 33 (V6 and V7). Anything else is assigned to V8. If a
> jar happened to contain a V5 class that would get mapped as V8. Perhaps the
> check should be "anything less than or equal to 32 gets assigned V6"
>
> and if the version doesn
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/java-buildpack/issues/125#issuecomment-69948704>
> .
>



-- 
--
Christopher Frost - GoPivotal UK
