### ISSUE TITLE
truncating the content

### ISSUE THREAD

**Issue by svennela** [cloudfoundry/java-buildpack#131]
Hi,

Right now on PWS we are using 2.6(5cbaacb7) build pack, which is truncating the content. please use buildpack 2.4 for now,below is command that works on PWS. I will open issue with buildpack team.

you can use below repo.

https://github.com/Pivotal-Field-Engineering/PCF-demo

Below push works
cf push -b https://github.com/cloudfoundry/java-buildpack.git#7cdcf1a

Below push fails.
cf push -b https://github.com/cloudfoundry/java-buildpack.git#5cbaacb

Thank you,
Sridhar

**Comment by cgfrost** [comment]
Could you please explain what this issue is for, what content are you talking about.

**Comment by PatsyPhelan** [comment]
Hi Chris,
 I saw this one as well. When you start the demo app and go to it on the demo website the data in the "/" root page is truncated. Like the controller only sends half the HTML/Javascript of the page to the browser. Truncates about half way down the overall page. 

It was driving me nuts as I hadn't changed any of the demo code - just push / deploying it.  I did the workaround as Sridhar suggested and it fixed the problem. I also added the "buildpack" property in the manifest - just as I am doing an internal demo.

~Patsy

**Comment by svennela** [comment]
Hi Chris,

Below is response from Mark, it is bug in tomcat 8.0.17 version. Latest build pack(current in PWS) is using the same. Hope that helps.

All,
If any of your projects have a dependency on Apache Tomcat 8 I strongly recommend that you stick with 8.0.15 rather than upgrade to 8.0.17.
There is a regression in 8.0.17 that breaks any forwarded request where the response is larger than the output buffer (default 8k). [1]
A fix is in hand and I am working on a 8.0.18 release now. I'm going to try and fast-track it but the chances are that 8.0.18 will not be available until early next week.
Apologies if this causes any of you some hassle.
Mark

**Comment by cgfrost** [comment]
Thanks,

Other people tracked it down over night (UK time), Tomcat 8.0.17 has been pulled from the run.pivotal.io dependencies. We will upgrade to 8.0.18 as a matter of course. I'm closing this issue out as there is no extra action to be taken in the Buildpack.
