### ISSUE TITLE
Specs don't pass

### ISSUE THREAD

**Issue by davehr** [cloudfoundry/java-buildpack#137]
We've done a clean clone of the repo, and run `bundle exec rake spec`. We're seeing 9 failures on an Ubuntu machine, all of `no implicit conversion of nil into String` in `filtering_pathname.rb` on line 91.

It'd be good if the specs were clean so we could make modifications with a degree of confidence.

**Comment by cgfrost** [comment]
Hi, the failures occurred recently and we have a task in tracker to get them fixed. I'll leave this issue open and link to it so you know when we think it's fixed.

https://www.pivotaltracker.com/story/show/87621898

Thanks for raising, Chris.

**Comment by cgfrost** [comment]
Hi, could you check what version of Ruby is being used. We recommend that you use rbenv to allow each repository to use the correct version? I think this could be your problem.

**Comment by davehr** [comment]
For reference - whats the correct version?

**Comment by nebhale** [comment]
@davehr The correct version at any given commit is written in the `.ruby-version` file in the root of the project.  This file is used by both `rbenv` and `rvm` and I'd definitely recommend using the first one to get ruby onto a machine, regardless of its operating system.

**Comment by cgfrost** [comment]
@davehr Any luck getting to pass after checking the Ruby version, I'll probably have a look at this next week. FYI the current Ruby version is ```1.9.3-p551``` but as Ben says you should be using rbenv is inspect the ```.ruby-version``` file for you.

**Comment by davehr** [comment]
No - due to restrictions here we're developing on Windoze at the moment, and rbenv doesn't work there

**Comment by cgfrost** [comment]
Hi, I've had a go at recreating this issue and all the tests are passing for me. I grabbed a fresh copy of Ubuntu 14.04.2.LTS and installed it in a virtual machine using VMware fusion. Once in I did the following sequence of commands.

```sudo apt-get install git```
```git clone https://github.com/cloudfoundry/java-buildpack.git```
```cd java-buildpack```
```sudo apt-get install ruby-full build-essential```  (This resulted in Ruby 1.9.3-p551 being available to rbenv, using the slightly older version that came with Ubuntu resulted in a failure while installing the gems with ```bundle install```)
```gem install bundler```
```bundle install```
```rbenv rehash``` (I probably didn't need this one but including it as I did actually put it in)
```bundle exec rake```

Also, at this point you can check the Ruby version with both ```rbenv local``` and ```ruby --version``` to check you are on 1.9.3-p551.

Good things happened. I'm closing this issue out as I can't recreate, please re-open if you think I have missed something. 

Thanks, Chris.
