### ISSUE TITLE
Enabling local cache for GemFire could cause inconsistencies in state between multiple instances of an application

### ISSUE THREAD

**Issue by monkeyherder** [cloudfoundry/java-buildpack#152]
Consider the following scenario:

1. Assuming we have an app with > 1 instance using session replication.
1. Request is made which creates a session object `A` in instance 1. Because this is the first request, the session is written to the backend cache, but is also cached locally.
1. Next request comes in which hits the app instance 2. A request is made for session `A` which is retrieved from the backend cache server. Now each instance of the app has a locally cached version of the session object.
1. The problem surfaces when the session object is updated. Because it is cached locally, changes will only be propagated to the backend cache server but not to other client caches.

Setting `enableLocalCache => 'false'` should fix the problem and ensure consistency across instances.

This is a minor change, and I have a pull request ready if desired.

**Comment by cgfrost** [comment]
Hi @monkeyherder 
Can you submit the pull request. I'm happy with your reasoning for it and would like to look over delta.
Thanks.

**Comment by cgfrost** [comment]
Pull request accepted in #153
