### ISSUE TITLE
java-buildpack should provide the configuration to minimize memory fragmentation and JVM process RSS memory usage

### ISSUE THREAD

**Issue by lhotari** [cloudfoundry/java-buildpack#163]
There is a general problem with JVM resident memory usage. The memory usage grows slowly because of allocated memory fragmentation even the application doesn't have a memory leak and there isn't a native memory leak in the application. In most applications this memory usage creep is small, but for some applications, this can be a major problem. 

In CloudFoundry, the process gets killed by the OOM killer when it hits it's resource limit.

The memory fragmentation of the  "native" (non-heap) memory allocated by the JVM can be minimized with configuration. `java-buildpack` should provide the configuration to minimize memory fragmentation.

I have previously created these issues/pull requests that are related to this problem:
* [don't set -XX:MetaspaceSize= setting since it can prevent cleanup of allocated native memory](https://github.com/cloudfoundry/java-buildpack/issues/159)
* [Provide a way to set environment variables for the command and set MALLOC_ARENA_MAX=2 for all JVM apps to reduce the memory overhead](https://github.com/cloudfoundry/java-buildpack/issues/160)
* [JRE memory calculation doesn't take the maximum number of threads in to account](https://github.com/cloudfoundry/java-buildpack/issues/157)
* [Add sensible defaults for Tomcat http connector](https://github.com/cloudfoundry/java-buildpack/issues/158) - related to #157

I have been running the application in production without doing changes to the application. After using a buildpack with #159 changes, the RSS of the process doesn't grow as fast as without this change. This change solely didn't help prevent the process going over the container memory limit. The uptime was longer.

After applying #160, the `MALLOC_ARENA_MAX` change, I didn't notice a significant difference in uptime compared to the plain #159 change. This lead me to search for more sources of JVM native memory fragmentation.

The uptime is longest for what I've measured for now, by the time writing this I've got 32 hour uptime in the production app after adding some these parameters:
```
-XX:InitialCodeCacheSize=64M -XX:CodeCacheExpansionSize=1M -XX:CodeCacheMinimumFreeSpace=1M -XX:ReservedCodeCacheSize=200M

-XX:MinMetaspaceExpansion=1M -XX:MaxMetaspaceExpansion=8M 
```
It looks like these settings do reduce memory fragmentation overhead. The default for `CodeCacheExpansionSize` is 64k . That might be causing fragmentation.
It might cause differences in how the HotSpot compiler behaves if `InitialCodeCacheSize` is set to a high value so there might be tradeoffs involved. 

I also added a limit for `MaxDirectMemorySize` and `CompressedClassSpaceSize`, however I think these don't help in reducing memory fragmentation:
```
-XX:MaxDirectMemorySize=96M
-XX:CompressedClassSpaceSize=256M 
```

**Comment by cgfrost** [comment]
Considering the comment made here; https://github.com/cloudfoundry/java-buildpack/pull/159#issuecomment-124130463 , the changes coming to support configured initial memory sizes (https://github.com/cloudfoundry/java-buildpack/issues/200), the resolution for the Tomcat HTTP connectionTimeout (https://github.com/cloudfoundry/java-buildpack/pull/158) and that we still intend to add support for specifying the maximum number of threads (https://github.com/cloudfoundry/java-buildpack/issues/157). Could you update your requirements/concerns in this issue. Would changes and issues elsewhere cover this issue now? I'd just like to get an update on your thoughts here before deciding how to proceed.

**Comment by cgfrost** [comment]
Considering that the issues related to the 4 points raised in the original post have now been resolved/implemented I'm going to close this issue off.
