### ISSUE TITLE
JVM on Cloud Foundry tries to connect to the debugger twice

### ISSUE THREAD

**Issue by palonsoro** [cloudfoundry/java-buildpack#165]
Good morning.

I have been trying to debug Java applications on Cloud Foundry by following this [tutorial](http://docs.cloudfoundry.org/buildpacks/java/java-tips.html#debugging).

Everything seems to work fine except for the following: While the application is being staged, a JVM connects to my debugger (the one set up via the "Remote Java Application" run configuration described at the tutorial), then it disconnects. After that, while the application is starting, the JVM tries to connect again. Thus, I have to re-launch my "Remote Java Application" run configuration so that the JVM connects again. If I do so, there is no problem and debugging works fine, but I had to launch the "Remote Java Application" run configuration twice and not once, as the guide suggests.

This is not a big problem for me once I know what how to workaround it. However, it would be a good idea to either fix the guide or the buildpack, so that the buildpack does what the guide says.

Thank you in advance.

**Comment by cgfrost** [comment]
Thanks for pointing this out. Issue created in our tracker. https://www.pivotaltracker.com/story/show/90500196

**Comment by cgfrost** [comment]
Sorry, didn't mean to close that.

**Comment by nebhale** [comment]
@palonsoro You say the the problem happens during staging, but we don't actually run up a JVM during staging.  What makes you think that it happens during staging?

**Comment by palonsoro** [comment]
What I see is that someone connects to my debugger, then disconnects and then tries to reconnect again every time I deploy an application. 

I supposed that it happens during the staging process because of three reasons:
 
- The first connection try happens while staging-related messages are being emited at `cf push` standard output.
- If I stop the application via `cf stop` and start it again via `cf start`, the JVM tries to connect to my. However, if I restage the application via `cf restage`, the problem does occur as if I was pushing the application for the first time.
- The most important reason: If I push an application without starting my local debugger, the **app staging fails**.

I think that you are not right when you say that you do not run up JVM at staging phase. 
When I found that app staging fails if I configure `$JAVA_OPTS` for debugging without starting my debugging, I found the following log lines specially interesting:

```
2015-03-25T13:30:59.19+0100 [STG]     OUT -----> Downloading Tc Server Instance 3.0.0_RELEASE from https://download.run.pivotal.io/tc-server/tc-server-3.0.0_RELEASE.tar.gz (found in cache)
2015-03-25T13:30:59.82+0100 [STG]     OUT        Instantiating tc Server in .java-buildpack/tc_server 
2015-03-25T13:30:59.82+0100 [STG]     OUT Command '/tmp/d20150325-113-tdh2fp/tcruntime-instance.sh create instance --instance-directory /tmp/staged/app/.java-buildpack/tc_server --layout combined --template user-template' has failed
2015-03-25T13:30:59.82+0100 [STG]     OUT STDOUT: FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
2015-03-25T13:30:59.82+0100 [STG]     OUT STDERR: ERROR: transport error 202: connect failed: Connection refused
2015-03-25T13:30:59.86+0100 [STG]     ERR [Buildpack]                      ERROR Compile failed with exception RuntimeError
2015-03-25T13:30:59.87+0100 [STG]     OUT Staging failed: Buildpack compilation step failed
2015-03-25T13:30:59.97+0100 [API]     ERR Encountered error: App staging failed in the buildpack compile phase
```

The `tcruntime-instance.sh` file, executed during the staging process, can be found at the `tc-server-3.0.0_RELEASE.tar.gz` downloaded file. If you look at it, you can found this at line 50:
```
$JAVA_HOME/bin/java $JAVA_OPTS "-Druntime.directory=$RUNTIME_DIR" "-Ddefault.instance.directory=$INSTANCE_DIR" -classpath "$CLASSPATH" com.springsource.tcruntime.instance.TcRuntimeInstance "$@"
```
So, you do actually run a JVM with the `$JAVA_OPTS` (including the debugging ones) during the staging phase. It happens during `tcruntime-instance.sh` execution.

**Comment by nebhale** [comment]
Ah ha!  It's in the tc Server buildpack!  Yes, that does actually run up a VM during staging.  Since staging is given the same environment as runtime we're going to figure out how to strip the debugging arguments from the invocation of `create-instance`.  Thanks for the feedback.

**Comment by palonsoro** [comment]
Ok. I suppose that it would be a good idea not to pass the same `$JAVA_OPTS` variable to both environments. It may be a good idea to have something like a different `$STAGING_JAVA_OPTS` variable.

**Comment by nebhale** [comment]
Well, we don't have any control.  All environment variables set via `cf set-env` go to both environments.  So we just need to make sure that when we fork the `create-instance` command out, we clean out its environment as well.  Not too hard to sort I'm hoping...

**Comment by nebhale** [comment]
@palonsoro We've made the changes to fix this problem in the tc Server Buildpack.  Watch for the `3.0` release of that buildpack for the improved version.

**Comment by palonsoro** [comment]
Ok. I will be watching it. Thank you very much
