### ISSUE TITLE
[OpenJDK] - JVM Configuration 

### ISSUE THREAD

**Issue by julweber** [cloudfoundry/java-buildpack#169]
Hey guys,

what are the recommended settings in https://github.com/cloudfoundry/java-buildpack/blob/master/config/open_jdk_jre.yml for an instance with a quota of 3GB RAM running on a CF installation?

Could you provide us with some more information on how to set this up?

Cheers,
Julian

**Comment by nebhale** [comment]
You should not need to make any changes, the buildpack will automatically account for the amount of RAM it has available.  If you inspect the running application (or the command line that was used to start the process) you'll see what _actual_ sizes were chosen.

**Comment by julweber** [comment]
We are always getting this message when pushing applications:

2015-03-26T16:21:52.36+0000 [WeightBalancingMemoryHeuristic] WARN  The allocated Java memory sizes total 0 which is less than 0.8 of the available memory, so configured Java memory sizes may be too small or available memory may be too large

This could also be interesting.

2015-03-26T16:21:49.40+0000 [ConfigurationUtils]             DEBUG Configuration from /tmp/buildpacks/java-buildpack/config/open_jdk_jre.yml: {"repository_root"=>"{default.repository.root}/openjdk/{platform}/{architecture}", "version"=>"1.7.0_+", "memory_sizes"=>nil, "permgen"=>10, "memory_heuristics"=>nil, "heap"=>"2600m", "stack"=>5, "native"=>10}

We are experiencing application crashes when memory usage hits around 2.1-2.3 GB of the 3GB quota.

Do you have any advice here?

**Comment by julweber** [comment]
Thanks for your fast answer.

**Comment by nebhale** [comment]
I just pushed one of our test applications with `3G` specified and saw the following:

```
bhale-desktop master: cf push -m 3G -b https://github.com/cloudfoundry/java-buildpack.git
Using manifest file /Users/bhale/dev/sources/cloudfoundry/java-test-applications/java-main-application/manifest.yml

Updating app java-main-application in org bhale / space development as bhale@pivotal.io...
OK

Uploading java-main-application...
Uploading app files from: /Users/bhale/dev/sources/cloudfoundry/java-test-applications/java-main-application/build/libs/java-main-application-1.0.0.BUILD-SNAPSHOT.jar
Uploading 587.3K, 84 files
Done uploading               
OK

Stopping app java-main-application in org bhale / space development as bhale@pivotal.io...
OK

Starting app java-main-application in org bhale / space development as bhale@pivotal.io...
-----> Downloaded app package (15M)
-----> Downloaded app buildpack cache (85M)
Cloning into '/tmp/buildpacks/java-buildpack'...
-----> Java Buildpack Version: 50d9b5f | https://github.com/cloudfoundry/java-buildpack.git#50d9b5f
-----> Downloading Open Jdk JRE 1.8.0_40 from https://download.run.pivotal.io/openjdk/lucid/x86_64/openjdk-1.8.0_40.tar.gz (1.8s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.3s)
-----> Downloading Spring Auto Reconfiguration 1.7.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.7.0_RELEASE.jar (found in cache)
-----> Uploading droplet (59M)

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App java-main-application was started using this command `SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.7.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx2304M -Xms2304M -XX:MaxMetaspaceSize=314572K -XX:MetaspaceSize=314572K -Xss1M org.springframework.boot.loader.JarLauncher`

Showing health and status for app java-main-application in org bhale / space development as bhale@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 3G x 1 instances
urls: ben-java-main-application.cfapps.io
last uploaded: Thu Mar 26 17:11:19 UTC 2015

     state     since                    cpu    memory         disk         details   
#0   running   2015-03-26 05:12:16 PM   0.0%   869.4M of 3G   135M of 1G      
```

Based on that, `master` looks healthy.  We haven't done any work in the memory heuristics recently, so I don't think we've broken anything their either.  Have you made sure that your configuration file looks like what's in [`master`](https://github.com/cloudfoundry/java-buildpack/blob/master/config/open_jdk_jre.yml)?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
