### ISSUE TITLE
How do set metaspace size?

### ISSUE THREAD

**Issue by beku8** [cloudfoundry/java-buildpack#174]
I'm running out of metaspace, so I tried to increase it with the env variable ```JBP_CONFIG_OPEN_JDK_JRE: '[memory_sizes: {metaspace: 96}]'``` in my ```manifest.yml```, but it does not pick up. I had 512M memory, I tried increasing it to 600M, but still picking up the default 64M metaspace. If I have 1G memory it seems pick up much larger metaspace than I specified.

I've seen this [blog](http://www.haydonryan.com/java-8-increasing-metaspace-size-in-cloud-foundry/), I forked the buildback & changed the ```open_jdk_jre.yml``` file, and it works. But I don't want to manually sync the repo.

**Comment by cgfrost** [comment]
Hi,

You don't need to fork the buildpack any more. Your command is correct but try the following as well.
```
cf set-env my_app JBP_CONFIG_OPEN_JDK_JRE ‘[memory_heuristics: {metaspace: 128}]’
cf restage my_app
```
This will adjust the ratios as well. See https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory-weightings

If you have set the buildpack to run on Java 7 remember that it's permgen that needs to be set instead.

Chris.

**Comment by beku8** [comment]
Hey thanks,
I should have read the doc more carefully.

**Comment by beku8** [comment]
Hey I still can't set the variable. I've tried:
```cf set-env configserver-4 JBP_CONFIG_OPEN_JDK_JRE '[memory_heuristics: {metaspace: 128}, memory_sizes: {metaspace: 96}]'```
I also tried with letter `m` & `M` behind like 128m, 128M... 
but still getting default 64M
```App configserver-4 was started using this command SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.7.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx382293K -Xms382293K -XX:MaxMetaspaceSize=64M -XX:MetaspaceSize=64M -Xss995K org.springframework.boot.loader.JarLauncher```
Could you check my syntax again? 

P.S I'm using pivotal webservice.

**Comment by cgfrost** [comment]
Hi,
Can you confirm you are using a buildpack that includes the new reconfiguration feature. I would expect this to be up in PWS by now but it's possible it isn't.

```
buildpack: https://github.com/cloudfoundry/java-buildpack.git
```

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
