### ISSUE TITLE
Help - looking for pointers in the code for where the 'cloud.services.<dbservicename>.connection.uri' env variable gets exposed

### ISSUE THREAD

**Issue by mariobriggs** [cloudfoundry/java-buildpack#179]
Hi,
I am trying to add export of the env variable 'cloud.services.<dbservicename>.connection.uri' for DB2 database services in IBM bluemix using this buildpack. This is done for mysql and postgres as documented [here](http://docs.cloudfoundry.org/buildpacks/java/spring-service-bindings.html#properties). I am having a hard time figuring which piece of the code in this buildpack this gets done. So any pointers will be much appreciated. thanks in advance

**Comment by nebhale** [comment]
This is a [Spring Cloud](http://cloud.spring.io/spring-cloud-connectors/) feature, not a Java Buildpack feature.

**Comment by mariobriggs** [comment]
@nebhale in my case, i am pushing a Play framework generated .zip file which the java-buildpack is picking up to stage. The (app.conf)[https://github.com/cloudfoundry-samples/zentasks-scala-cloudfoundry/blob/master/conf/application.conf] references the cloud.services.xxx.connection.uri. Would appreciate if elaborate how the Spring Cloud feature kicks in via this

**Comment by cgfrost** [comment]
Hi, this isn't our area of knowledge so you will get better answers from the Spring Cloud people. Applications that make use of auto-reconfiguration get some extra support for services but I don't think this is doing what you are looking for. Worth a read though and there are some blog posts linked at the bottom of the readme. 

https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration

If your application is on Spring 3.1 or later and uses a certain bean definition then the Spring Cloud profile is applied and service connection information is added for you.

**Comment by mariobriggs** [comment]
thanks @cgfrost. I believe it is here https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-cloudfoundry-connector and will make the contributions there

**Comment by cgfrost** [comment]
Thanks for posting back.

**Comment by mariobriggs** [comment]
@cgfrost, so i have my [PR](https://github.com/spring-cloud/spring-cloud-connectors/pull/120) merged into master branch of spring-cloud-connectors, but not yet released. How do i get the buildpack to use my build of the spring-cloud-connectors or master branch from spring-cloud-connectors (i.e. use that feature before spring-cloud-connectors makes a release) ?

**Comment by cgfrost** [comment]
Hi,

You will need to host your version somewhere accessible via http along with an `index.yml` file and then use environment variables to change the version and repository root for the buildpack so that it downloads your version. See the top level readme for information about changing the buildpack config. Look at the `index.yml` files used by other dependencies to see how they are formatted.

**Comment by mariobriggs** [comment]
@cgfrost thank for that tip.I overrode JBP_CONFIG_PLAY_FRAMEWORK_AUTO_RECONFIGURATION in my app and it worked like a charm. I produced the reconfig jar using spring-cloud jars from repo.spring.io/lib-snapshot easily enough. 

fyi. However when i need to make some changes i used to pull the spring-cloud jars from my local maven repo, but the reshading process seemed to always use the one from repo.spring.io/lib-snapshot. So i had to go through a lot of hoops and finally had to do a manual re-shading. The whole re-shading thing seemed cryptic and painful to deal with

**Comment by cgfrost** [comment]
I sympathies with your Maven gripes, I tend to avoid shading if possible.
