### ISSUE TITLE
web.xml modification adds servlet init-param after load-on-startup

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry/java-buildpack#181]
If a web application has a servlet <load-on-startup> element in its declaration, the Spring Auto-Reconfiguration web.xml modification support will add the <init-param> below this element, which is invalid according to the web-app XSD.      

Tomcat appears to be lenient with this but other Java-buildpack derived containers are stricter (e.g. Weblogic) and fail deployment descriptor validation on deploy.

I'll follow up with a PR that includes a test case to demonstrate this.

**Comment by nebhale** [comment]
Great contribution.  Thanks.
