### ISSUE TITLE
lib/java_buildpack/repository/repository_index.rb rather tightly coupled /etc/redhat-release 

### ISSUE THREAD

**Issue by chrisumbel** [cloudfoundry/java-buildpack#183]
The handling on line `lib/java_buildpack/repository/repository_index.rb:88` for RH-based OSes has some interesting implications. 

1. the tests can't be run on non-centos RH-based OSes directly, which means it can't easily be built on Jenkins, which is fedora-based. This is due to the fact that the string "CentOS" is matched on. I realize we're not targeting a fedora stemcell, but it seems an unnecessary side-effect of tight-coupling. Also, seems silly to require someone to bring up a centos VM or some such to run the tests.
2. tests also can't be run on CentOS 7 because it's format includes the word "Linux" i.e. "CentOS Linux release 7.1.1503". I assume that would need fixed before this buildpack could be used on a CentOS 7 stemcell or am I off base?  
3. easy fix, this would parse "CentOS 10" as "CentOS 1" or "CentOS 20" as "CentOS 2" due to matching on (\d) rather than (\d+). 

I suppose none of these points have any effect whatsoever on production deployments right now, but seemed worth mentioning. If you deem it worth of being looked at I'd be more than willing to get a few commits in to help.

**Comment by nebhale** [comment]
Yeah, I guess we've never tested it on any of these other platforms as they aren't targets for Cloud Foundry itself.  I suspect this will have low priority, but we'll be happy to get to it, and take contributions.
