### ISSUE TITLE
Improperly specified VM option with memory calculator

### ISSUE THREAD

**Issue by lejeunen** [cloudfoundry/java-buildpack#186]
Hi,

There seem to be a problem with the memory calculator. I was unable to successfully push my apps on Pivotal Web Services using the latest version of the java build pack.

In the logs I saw errors like
>2015-05-11T17:21:28.54+0200 [App/0]      ERR     Improperly specified VM option 'MaxMetaspaceSize=104857K -XX:MetaspaceSize=104857K -Xss1M -Xmx768M -Xms768M'
>2015-05-11T17:21:28.55+0200 [App/0]      ERR Error: Could not create the Java Virtual Machine.

The result is that the instance fails to accept connections and is discarded during health check.

Nicolas

**Comment by cgfrost** [comment]
Hi,

Thanks for raising this issue. Could you provide us with your debug log please along with your .yml file/memory settings etc.. and we will look in to it.

Thanks, Chris.

**Comment by nebhale** [comment]
@lejeunen I can actually do you one better.  We've identified the bug (getting a bit quote happy) and have fixed it.  Let me know if `master` works for you now.

**Comment by lejeunen** [comment]
Retried using master (version 71ab82a) and the issue is gone.
Thanks for the quick fix!

**Comment by nebhale** [comment]
Our pleasure and sorry for the disruption.
