### ISSUE TITLE
JNDI Support?

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/java-buildpack#189]
Would there be any interest in supporting automatic configuration of JNDI through the build pack?

A couple ideas:

  - Parse VCAP_SERVICES and setup [DataSources for databases](https://tomcat.apache.org/tomcat-7.0-doc/config/context.html#Resource_Definitions) (possibly other service type too?)

  - Look for environment variables prefixed with JNDI_ and set them as [JNDI environment entries](https://tomcat.apache.org/tomcat-7.0-doc/config/context.html#Environment_Entries).

Thoughts?

**Comment by cgfrost** [comment]
Hi, 

This is something we could look at if people voiced interest in it but it's not been asked for so far. I will leave this issue open for a while for other people to voice interest in JNDI and take it from there.

**Comment by nebhale** [comment]
@dmikusa-pivotal We'd given some thought to this back when we started the buildpack (especially the `tc-server-buildpack`) and decided not to add it until we'd gotten requests for it.  It's now more than a year later and you're the first to ask.  In the end, I believe that our recommendation of making your application self-contained (e.g. `spring-session`, `spring-cloud-connectors`) has moved people off of using JNDI.

If you don't mind, I think we should close this issue out as it's unlikely to be worked at this point.

**Comment by dmikusa-pivotal** [comment]
Thanks for the background.  Not a problem to close this out.  I was more curious to see if anyone would second the suggestion.  Since no one has, it must not be something people are interested in seeing.

Thanks!

**Comment by kelapure** [comment]
We are looking at a PR to provide this function:  There are two use-cases here
1. CREATE: Generate the appropriate Resource stanzas in the server.xml based on the bound services
```xml
<Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource"
               maxTotal="100" maxIdle="30" maxWaitMillis="10000"
               username="javauser" password="javadude" driverClassName="com.mysql.jdbc.Driver"
               url="jdbc:mysql://cloud-aws.com:3306/javatest"/>
```
2. UPDATE: Update existing resource definitions with the  appropriate type of services bound to the application. For a 1:1 mapping of existing resource definition to service instance type this is easy; however if there are multiple resources of the same type pointing to vcap services of the same type we have to come up with some sort of protocol to ensure that the resources are pointing to the right endpoints in VCAP_SERVICES.

The code to generate the datasource XML definitions will be slightly differ based on the type of the backend service configured.

**Comment by kelapure** [comment]
WebSphere Liberty Profile Buildpack provides this function : see
https://www.ng.bluemix.net/docs/services/MySQL/index.html#MySQL

**Comment by kelapure** [comment]
Since this feature fosters non-cloud native development practices, it makes sense to provide this feature in a separate buildpack targeted explicitly for app-migration. Closing issue.

**Comment by INSUNG-BANG** [comment]
Hi,
JNDI connection is still not supported on CF environment so far?
