### ISSUE TITLE
Buildpack not loading the dynatrace agent

### ISSUE THREAD

**Issue by apclee** [cloudfoundry/java-buildpack#199]
We are trying to get the dynatrace agent working with a java application. We have compiled an offline buildpack of java.  So far, we have created a VCAP service:

```
{
    "name": "dynatrace",
    "label": "user-provided",
    "tags": [],
    "credentials": {
        "profile": "<our_profile>",
        "server": "<our_host:our_port>"
    },
    "syslog_drain_url": ""
}
```

The agent is not getting started. Looking at `cf files` and the dynatrace agent jars are not getting loaded. If we stage the app using the app-dynamics agent, the jars are loaded correctly.

**Comment by cgfrost** [comment]
Hi,

Can you tell me exactly which commit of the Java Buldpack you are using as some changes were made to the Dynatrace support at the end of last week. Dynatrace support is also disabled by default, you will need to fork the buildpack and re-enable it in the `config/components.yml` file if you haven't already done so. Otherwise your VCAP services payload looks good but with no server specified in the credentials the agent won't connect to any Dynatrace server.

**Comment by apclee** [comment]
Thanks for the quick response.  You are right, we have not enabled the framework in the components.yml.  Re-enable it, but now we are unable to compile an offline package. We are getting the following error:

$] bundle exec rake package OFFLINE=true
[DownloadCache]                  WARN  Unable to download /index.yml into cache build/staging/resources/cache: undefined method `request_uri' for #<URI::Generic:0x000000035b56f0 URL:/index.yml>
rake aborted!
Unable to find cached file for /index.yml

**Comment by apclee** [comment]
Chris,

Sorry to add on. I've created a repository server and configured (still would like to know if its possible to force a local cache copy rather than a repo server).  I was able to successfully compile the buildpack and deployed an app.  However, it doesnt seem to be initializing the dynatrace config.  Looking at the app/.java-buildpack.log through "cf files"

**Comment by cgfrost** [comment]
Hi,

You are correct that building the offline buildpack requires all the dependencies to be downloadable. It should be pretty clear in the logs if DynaTrace is being started. Is the application bound to a service that includes the string 'dynatrace' in it's name. This is the trigger required for Dynatrace being started. The console output should show Dynatrace as well, both in the logging output and where it displays the command used to start the application. Can you paste in the contents of `cf env` for the application to this thread. To be sure the service is correct.

**Comment by apclee** [comment]
Chris,

Thank you so much for responding.  We've gotten it up and running by completely wiping out the old app and bringing in a new version (likely some misconfig from all the testing). It looks like dynatrace agent is getting loaded now although we still have a last mile problem of getting it to connect to the server.

A different question - We noticed in the initialization that the agent is getting loaded with an "options string" that matches the format <appname>-<profile name>,server=<server:port>.  Is there any way to override this options string?  According to our dynatrace guys, they'd want to see the string just as "<profile name>,server=<server:port>".

2015-06-17 12:42:57 [53e66c39] info    [native] Agent library ............... /home/vcap/app/.java-buildpack/dyna_trace_agent/agent/downloads/6.1.0.8154/native/linux-x86-64/libdtagentcore.so
2015-06-17 12:42:57 [53e66c39] info    [native] Options string .............. <appname>-<profile>,server=<dynatrae server name>:10003
2015-06-17 12:42:57 [53e66c39] info    [native] Agent name .................. <appname>-<profile>

Thanks!
Anthony

**Comment by cgfrost** [comment]
Hi,

This will be set to what ever you put in the `server` property of the dynatrace service that the app is bound to. This string is provided as parameters on the agentPath specified to the JRE at startup, it will look like this.

```
-agentpath:<path to libdtagent.so>=name=<credentials:{profile}>,server=<credentials:{server}>
```

In my testing I set the `server` property to be `ubuntu:2021` and everything worked. I'm not clear if you need to set the string differently or that some functionality is missing.

**Comment by cgfrost** [comment]
How is this going, if you have everything working I'd like to close this issue out. Is that OK?

**Comment by apclee** [comment]
Chris,

Everythig is working as you suggested. We also ended up making changes on the dynatrace side.

Thank you so much for your help. I will close out the issue.

Thanks!
Anthony
