### ISSUE TITLE
Cannot specify stack or heap values for memory_calculator memory_sizes.

### ISSUE THREAD

**Issue by leachbj** [cloudfoundry/java-buildpack#202]
Using a value

    JBP_CONFIG_OPEN_JDK_JRE: '[jre: {version: 1.8.0_+}, memory_calculator: {memory_sizes: {metaspace: 64m, heap: 170m, stack: 512k}}]'

Results in the following errors during a push;

      ERR [ConfigurationUtils]             WARN  User config value for 'heap' is not valid, existing property not present
      ERR [ConfigurationUtils]             WARN  User config value for 'stack' is not valid, existing property not present

The documentation lists both heap and stack as parameters for memory_sizes along with metaspace.

**Comment by cgfrost** [comment]
Your value is slightly off. Try this.

```
JBP_CONFIG_OPEN_JDK_JRE: '[jre: {version: 1.8.0_+}, memory_calculator: {memory_sizes {metaspace: 64m}, memory_heuristics: {heap: 999, stack: 999}}]'
```

The new values you provide will always have to match the config files. It is not possible to specify `heap` and `stack` values to the memory calculator, only as memory heuristics.

**Comment by leachbj** [comment]
In which case the documentation is incorrect;

https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory-sizes

''The following optional properties may be specified in the memory_sizes mapping; heap,native,meta,stack''

It should be possible to specify a specific value for the stack size since that is dependent on the application not the available memory.

**Comment by cgfrost** [comment]
You have a good point there. I have raised an issue to look at the docs. https://www.pivotaltracker.com/story/show/98822486

The extra values you want to provide are calculated by the memory_calculator. It takes the memory_heuristics and the memory available to each instance of the application being deployed and calculates the amount of memory that should be allocated to stack, heap and so on. They can't be specified directly. The section in the docs about memory weighting is correct and explains how to adjust the memory values that get calculated.

https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory-weightings

**Comment by leachbj** [comment]
I understand the weightings parameters however as I mentioned it doesn't make sense for stack size as you don't need more stack when you increase the overall memory.  Even with a weight of 1 the stack size is still over 900k.

In other cases you may want to fix the heap size, for instance if all you allocations are off heap then a small fixed size heap suitable for local variables etc would make sense.

In general it seems odd to allow one value to be set and not all of them.

**Comment by nebhale** [comment]
Almost undoubtedly the problem is not that default values must be specified, it's that the memory calculator needs to accept values when configured.  Talk with @Zteve today about what's going on here that's preventing the configuration from being applied properly.

**Comment by nebhale** [comment]
Nope, I'm wrong.  I'll work with @cgfrost today to decide what we need to do here.

**Comment by leachbj** [comment]
When I tried to set them it says something like only default values can be overriden.  If the defaults provide sensible lower bounds then the percentage values should always take precedence.

**Comment by cgfrost** [comment]
The message you are getting is because the buildpack disallows any additions to configuration. Only existing configuration can be modified and no default values are provided for them. The memory calculator will actually accept them but we need to decide on some sensible defaults to enable user configuration via env variables.

**Comment by leachbj** [comment]
The commit referenced above (https://github.com/leachbj/java-buildpack/commit/fe2b36ac562b8b28be06d5f35ee4db2bda0e609a) adds in reasonable defaults.  Typically they would be overridden by the weight values however the defaults allow for explicit values to be provided.

**Comment by leachbj** [comment]
Tested with https://github.com/cloudfoundry/java-buildpack/commit/309e8c5e507ef8eed50dfb8ca79c62f9060a16ea and I can specify the fixed stack value as required.

**Comment by cgfrost** [comment]
@leachbj 
That's great, thanks for testing it.
