### ISSUE TITLE
Support aspectj loadtime weaving

### ISSUE THREAD

**Issue by sslavic** [cloudfoundry/java-buildpack#205]
Please support aspectj loadtime weaving of cf java apps which use java-buildpack. Buildpack could have default, while app itself could also provide aspectj-weaver.jar file.
Weaving could be enabled with an environment variable (e.g. ASPECTJ_WEAVER_ENABLED=true) and if only that would be specified then default path to buildpack provided aspectj-weaver.jar would be used, while a separate environment variable could allow to specify a path to app provided aspectj-weaver.jar (e.g. ASPECTJ_WEAVER_JAR_PATH).

Please also make sure that java-buildpack supports simultaneously enabling multiple java agents, e.g. aspectj and dynatrace.

**Comment by cgfrost** [comment]
Tracker issue created https://www.pivotaltracker.com/story/show/98944198

**Comment by cgfrost** [comment]
Hi,

We have discussed this issue in the team and decided that the work required to support this is quite high and so far no one else has requested it. For that reason, unless more people come forward requesting this support we aren't going to add it. There is still the option of forking the buildpack and adding support in to the fork.

**Comment by zachmarshall** [comment]
We (SAS) are also interested in this hypothetical feature. Is there a quick list of the concerns that make this a high amount of work so I can understand if a fork is a good idea or a rathole? I can’t see this particular tracker issue, so perhaps it’s included there.

**Comment by cgfrost** [comment]
Hi, There is nothing in the tracker issue. I've asked someone to explain what is required to support aspectJ loadtime weaving.

**Comment by nebhale** [comment]
@sslavic @zachmarshall Enabling LTW should be possible, without buildpack support by including the `aspectweaver.jar` and setting the `javaagent` (adjusting examples for _actual_ location of JAR) using either `cf set-env <APP_NAME> JAVA_OPTS '-javaagent:WEB-INF/lib/aspectjweaver.jar'` or specifying it in your `manifest.yml`:

```yaml
applications:
- name: <APP_NAME>
...
  env:
    JAVA_OPTS: -javaagent:WEB-INF/lib/aspectjweaver.jar
```

Is there a reason that this hasn't been sufficient for you so far?

**Comment by zachmarshall** [comment]
@nebhale thanks for the suggestion. I hadn't considered that. We are deploying spring-boot jars, so it may be a little more tricky. I need to look at whether `JAVA_OPTS` is available for the boot buildpack and if so, whether we can somehow reference an aspectj jar inside the boot repacked jar (probably not though).

**Comment by nebhale** [comment]
Yup, [it's avaiable](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-java_opts.md).  The only difference will be that you'll need to adjust the location of the JAR to (I believe) `lib/aspectjweaver-<VERSION>.jar`.  Just do a `jar tf | grep aspectjweaver` on the JAR you're deploying and you should get the correct answer.

**Comment by zachmarshall** [comment]
@nebhale Thanks very much! Will try and report results.

**Comment by poblin-orange** [comment]
If adding aspectj-weaver as a dependency in the pom, the jar is simply extracted in /home/vcap/app/WEB-INF/lib

I was successfully with the following property (cf set env) : 
* JAVA_OPTS: -javaagent:/home/vcap/app/WEB-INF/lib/aspectjweaver-1.8.5.jar
* aop.xml in /src/main/webapp/WEB-INF/classes/META-INF/aop.xml

Should work like a charm ;-)

**Comment by nebhale** [comment]
@poblin-orange The one thing I'd be careful using `-javaagent:/home/vcap/app`.  That's not a documented and contractual path and _could_ change.  You can be sure however, where the working directory is, and can safely use relative paths from there.

Am I correct in my belief that `aop.xml` is **not** required for LTW?

**Comment by poblin-orange** [comment]
@nebhale ur correct, should have used relative path.

I am not sure about a requirement for aop.xml. I used @AspectJ annotated aspect, and aop.xml permitted me to declare aspects and weaved classes packages, plus weaver instructions ("-XnoInline -verbose -showWeaveInfo -Xlint:ignore -Xset:weaveJavaPackages=true,weaveJavaxPackages=true").

My guess is it should be present in the Classpath.

**Comment by kelapure** [comment]
@nebhale I think it would be very useful to formalize the support for packaging javaagents in a war/jar file. There are often cases where developers want to bundle java-agents like [Jolokia](https://jolokia.org/reference/html/agents.html#agent-jvm-config) for monitoring or profiling agents.  These developers do not have the correct rights/access/permission to fork and modify the buildpack. 

The technique you  you have suggested does work. However due to the shell escaping of java options https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/java_opts.rb#L62-L75 there is no way to configure the javaagent to add extra options like host, port or other parameters. 
```yaml
 JAVA_OPTS:-javaagent:agent.jar=port=7777,host=localhost
```
I suggest we add a feature for Supporting app bundled javaagents.

**Comment by nebhale** [comment]
I'm pretty sure that you can specify anything you want to `JAVA_OPTS` and it works properly.  For example, I just started an application that specified the debug configuration:

```
$ cf set-env java-main-application JAVA_OPTS '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005'
$ cf env java-main-application

...
User-Provided:
JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
```

When the application attempted to start you see:

```
...
       Memory Settings: -Xss995K -Xmx382293K -Xms382293K -XX:MaxMetaspaceSize=64M -XX:MetaspaceSize=64M
-----> Downloading Spring Auto Reconfiguration 1.7.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.7.0_RELEASE.jar (0.1s)
-----> Uploading droplet (62M)
Starting app instance (index 0) with guid f13728d9-b860-43a8-b65f-33f4b3298e56
Listening for transport dt_socket at address: 5005
```

Which means that it honors the `JAVA_OPTS` configuration.

**Comment by kelapure** [comment]
@nebhale  My apologies I should have been clear. I needed to do something like this

```yaml
JAVA_OPTS:-javaagent:agent.jar=port=$PORT,host=localhost
```
The port that is provided to configure the Jolokia agent is the [port](http://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#PORT) the server listens on. This is passed into the droplet as an env. variable by CF.  I had trouble getting the droplet to start with the following command. Example follows shortly.

**Comment by aclement** [comment]
> Am I correct in my belief that aop.xml is not required for LTW?

You need a file to configure the weaver otherwise it won't do anything. But you don't necessarily need to set anything. By default for each class loader it will automatically take a look for a visible `META-INF/aop.xml` or `META-INF/aop-ajc.xml` file on the loaders class path and use those to configure itself. Or alternatively you can set the property `org.aspectj.weaver.loadtime.configuration` which should point to a configuration file to use. If the property value is prefixed 'file:' then it does not have to even be on the class path, if it is not prefixed file: then it will be searched for on the class path.

**Comment by cgfrost** [comment]
It is possible to get the escaping right but not obvious. Please can you try the following.

`cf set-env my-application JAVA_OPTS '-javaagent:agent.jar=port="'\\\$PORT'",host=localhost'`

**Comment by kelapure** [comment]
@cgfrost  still no dice

```java
$ cf set-env spring-music JAVA_OPTS '-javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port="'\\\$PORT'",host=localhost'
Setting env variable 'JAVA_OPTS' to '-javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port="\$PORT",host=localhost' for app spring-music in org pivot-rkelapure / space development as rkelapure@pivotal.io...
OK

bash-3.2$ cf restage spring-music
Restaging app spring-music in org pivot-rkelapure / space development as rkelapure@pivotal.io...


[Buildpack] DEBUG Release Payload:
---
addons: []
config_vars: {}
default_process_types:
  web: ! 'JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR
    -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx768M
    -Xms768M -XX:MaxMetaspaceSize=104857K -XX:MetaspaceSize=104857K -Xss1M -javaagent:$PWD/.java-buildpack/app_dynamics_agent/javaagent.jar
    -Dappdynamics.agent.applicationName=''spring-music'' -Dappdynamics.agent.tierName=''web''
    -Dappdynamics.agent.nodeName=$(expr "$VCAP_APPLICATION" : ''.*instance_index[":
    ]*\([[:digit:]]*\).*'') -Dappdynamics.agent.accountAccessKey=d767c6f6574e -Dappdynamics.agent.accountName=pivotaljo
    -Dappdynamics.controller.hostName=pivotaljo.saas.appdynamics.com -Dappdynamics.controller.port=80
    -javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port=$PORT,host=localhost
    -Daccess.logging.enabled=false -Dhttp.port=$PORT" $PWD/.java-buildpack/tomcat/bin/catalina.sh
    run'
-----> Uploading droplet (79M)
```

**Comment by nebhale** [comment]
@cgfrost @kelapure Can you please move this conversation to #209?

**Comment by kelapure** [comment]
@nebhale  yes.

**Comment by cgfrost** [comment]
This issue seems to have wandered a bit. As it is possible to support different agents without changes to the buildpack would you consider this issue resolved. If you would like us to look at some part of that support, make it better (i.e. escaping), document it etc... please say and we will happily do so. We don't want to leave issues hanging around with no clear objective.

**Comment by cgfrost** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by Anand321** [comment]
Hi, 
I have a Scala Application which works fine as a standalone App and binds to VCAP Host and port.
For monitoring, I tried the above option to run the AspectjWeaver dependency for Kamon. But whenever I use the javaagent for aspectjweaver, the application fails to startup. Any suggestions, would be helpful ! thanks !
