### ISSUE TITLE
newrelic config overrides app_name given in JAVA_OPTS

### ISSUE THREAD

**Issue by sks** [cloudfoundry/java-buildpack#206]
@cgfrost 

Carry forward from the discussion in https://github.com/cloudfoundry/java-buildpack/issues/173

Can we at the same time have a flexible way around setting ``` newrelic.config.app_name ``` ?
``` configuration['app_name'] = @application.details['application_name'] ```

In case the user have a [blue green deployment](http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/blue-green.html), the application_name always changes and it screws up the new relic dashboard .

I tried adding ``` JAVA_OPTS: -Dnewrelic.config.app_name=my-appname ``` to the ``` manifest.yml ```, but it gets overridden :crying_cat_face: 

What is the preferred way to do this ?

**Comment by jgawor** [comment]
Have you tried setting the `NEW_RELIC_APP_NAME` environment variable? According to the [New Relic Java agent configuration](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file) this has the highest precedence.

**Comment by sks** [comment]
@jgawor  : Thanks :+1: that works

**Comment by cgfrost** [comment]
Thanks @jgawor (I wouldn't of thought of that)
