### ISSUE TITLE
Consider gzipping memory_calculator in repository

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#208]
Go gzips very well.  I did a quick test with memory_calculator which is current 2350K and it Gzipped down to 645K.

That said it may get gzipped anyway when being downloaded but might still be nice if it were smaller.

**Comment by cgfrost** [comment]
I agree, I think future releases of the Memory calculator should be gzipped. There will be a change in the dependency downloader as well.

**Comment by nebhale** [comment]
The change shouldn't be in the dependency downloader (other than changing the file name pattern).  The packaging script for the memory calculator itself should gzip the application itself.  This allows us to keep the downloader as a simple downloader.

**Comment by cgfrost** [comment]
I wasn't very clear. I was talking about the file pattern in the downloader. The memory calculator itself should do the gzipping.

**Comment by cgfrost** [comment]
Version 2.0.0 has been released and the release is provided as a compressed tar. All future releases will be the same. https://github.com/cloudfoundry/java-buildpack-memory-calculator/releases/tag/v2.0.0.RELEASE
