### ISSUE TITLE
Java-Buildpack tests failed with "<Net::HTTP (class)> received :Proxy with unexpected arguments"

### ISSUE THREAD

**Issue by violetagg** [cloudfoundry/java-buildpack#213]
Hi,

I'm following the documentation for running the java-buildpack tests [1].

The tests failed with the following:
```
JavaBuildpack::Util::Cache::DownloadCache  uses HTTP_PROXY if specified
 Failure/Error: expect(Net::HTTP).to receive(:Proxy).with('proxy', 9000, nil, nil).and_call_original
   <Net::HTTP (class)> received :Proxy with unexpected arguments
	 expected: ("proxy", 9000, nil, nil)
		  got: ("proxy", 8080, nil, nil)
 # ./spec/java_buildpack/util/cache/download_cache_spec.rb:200:in `block (3 levels) in <top (required)>'

JavaBuildpack::Util::Cache::DownloadCache  uses HTTPS_PROXY if specified and URL is secure
 Failure/Error: expect(Net::HTTP).to receive(:Proxy).with('proxy', 9000, nil, nil).and_call_original
   <Net::HTTP (class)> received :Proxy with unexpected arguments
	 expected: ("proxy", 9000, nil, nil)
		  got: ("proxy", 8080, nil, nil)
 # ./spec/java_buildpack/util/cache/download_cache_spec.rb:234:in `block (3 levels) in <top (required)>'
```

May be I'm missing some configuration.
Can you please give me a hint how to overcome this?

Thanks,
Violeta Georgieva
[1] https://github.com/cloudfoundry/java-buildpack#running-tests

**Comment by cgfrost** [comment]
Thanks for raising this. Ref: https://www.pivotaltracker.com/story/show/101130824

**Comment by cgfrost** [comment]
I need to check a few things first. I assume the result of `bundle install` is good, it should show 11 gemfile dependencies having been installed. Can you also check your version of ruby `ruby -version`, this is set in the `.ruby-version` file at `1.9.3p551`, if you have a different version that could be the problem. 

The tests that are failing are checking for case sensitivity in environment variables. Two other identical tests that use `http_proxy` and `https_proxy` are passing for you. Do you know if there is something about your environment/shell that is/sn't case sensitive. FYI We are developing the buildpack on Macs with the bash shell.

**Comment by cgfrost** [comment]
Also, can you check your existing environment variables, if you have `http_proxy` set it will win over `HTTP_PROXY` and cause the test to fail. If you can test against master I just pushed a potential fix, could you let us know if it starts working for you.

**Comment by violetagg** [comment]
Hi,

With the latest changes the tests passed.

Thanks,
Violeta

**Comment by cgfrost** [comment]
That's great. Thanks for getting back to us.
