### ISSUE TITLE
As a user I want to supply arguments to Java main applications without forking the buildpack

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/java-buildpack#217]
I cannot do this because there is no `java_main.yml` config file to supply an `arguments` property to.

**Comment by cgfrost** [comment]
This should be very simple to implement by added the config file with an `arguments` property with no value. The new support for nil values in config will do the rest. While we are at it we should add a `java_main_class` property with an empty value to allow full configuration of Java main applications via environment variables. This will also require a small docs update.

Tracker Ref: https://www.pivotaltracker.com/story/show/101680106

**Comment by cgfrost** [comment]
Done in commit https://github.com/cloudfoundry/java-buildpack/commit/53f901b091ab9410bdd7528718148dcbc11a535c
