### ISSUE TITLE
Error in -totMemory flag: invalid memory size string '"1g"'

### ISSUE THREAD

**Issue by bigsurge** [cloudfoundry/java-buildpack#218]
Error in -totMemory flag: invalid memory size string '"1g"'

**Comment by cgfrost** [comment]
Can you give us more information on how you got this error message. Are you invoking the Memory Calculator directly or through the Java Buildpack. Either way can you provide the full console output including the command used to invoke the Memory Calculator. Finally, is there a reason for the extra quotes in your message `'"1g"'`.

**Comment by bigsurge** [comment]
Thanks, the problem has been resolved.
