### ISSUE TITLE
SSL certificate has expired and buildpack is failing

### ISSUE THREAD

**Issue by sszwed** [cloudfoundry/java-buildpack#224]
Buildpack is failing with exception:

-----> Downloaded app buildpack cache (44M)
[DownloadCache]                  WARN  Unable to download https://download.run.pivotal.io/auto-reconfiguration/index.yml into cache /tmp: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
[Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Spring Auto Reconfiguration error: Unable to find cached file for https://download.run.pivotal.io/auto-reconfiguration/index.yml>
Spring Auto Reconfiguration error: Unable to find cached file for https://download.run.pivotal.io/auto-reconfiguration/index.yml
Staging failed: An application could not be detected by any available buildpack

SSL certificate for domain download.run.pivotal.io was valid to: 2015-08-31.

Update buildpack to offline version can be workaround.

**Comment by nebhale** [comment]
We're on it.

**Comment by nebhale** [comment]
Certificate updated and PWS is staging.  Can you please verify that your system is also staging?

**Comment by sszwed** [comment]
yes, it's working :-)
