### ISSUE TITLE
Add ALPN Jar to the JVM bootclasspath

### ISSUE THREAD

**Issue by bclozel** [cloudfoundry/java-buildpack#225]
In order to enable SPDY or http/2 in a JVM app, it is required to add a JAR to the bootclasspath.
ALPN is not supported in JDK7 nor JDK8, but will be in JDK9.

The ALPN implementation provided by Jetty is used by many client and server implementations (Jetty, Undertow, OkHttp, etc).

Key points:
- the JAR should be hosted/provided by the CF infrastructure and not shipped with the application
- the JAR version depends on the JDK version (see [this page](https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions))
- this JAR must be added to the JVM BootClasspath (prepend): `-Xbootclasspath/p:<path_to_alpn_boot_jar>`
- Having `org.eclipse.jetty.alpn:alpn-api` in the application classpath may be a good trigger mechanism for this

**Comment by nebhale** [comment]
https://www.pivotaltracker.com/story/show/102470254

**Comment by yusuftor** [comment]
Is there currently a way to add alpn to the boot classpath through a pom.xml file?

**Comment by nebhale** [comment]
No, but it doesn't matter at the moment either.  The Cloud Foundry router will not route anything but `HTTP/1.1` requests to the router.  We're waiting on that team to start work on `HTTP/2` support before we move on it from our end.

**Comment by bclozel** [comment]
Here is something that could make the ALPN support a bit easier: https://github.com/jetty-project/jetty-alpn-agent

**Comment by nebhale** [comment]
@bclozel We're not going to be addressing this until the CF router itself can route `HTTP/2`.  If Tomcat isn't ready to route at that time we'll investigate other options for adding the functionality.

**Comment by vcrm** [comment]
perhaps  alpn-boot 8.1.9.v20160720 does not match jdk 1.8.0u102 ,this combination dosn't work for me:
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

but alpn-boot 8.1.9.v20160720 and jdk 1.8.0u101 work fine

**Comment by Ruchiri** [comment]
Can anyone tell me how to do this??
JAR must be added to the JVM BootClasspath (prepend): -Xbootclasspath/p:<path_to_alpn_boot_jar>

**Comment by Saif724U** [comment]
@Ruchiri  try "java -Xbootclasspath/p:<path_to_alpn_boot_jar>"

**Comment by Saif724U** [comment]
@Ruchiri try "java -Xbootclasspath/p:<path_to_alpn_boot_jar>"
