### ISSUE TITLE
Support APR connector for tomcat

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/java-buildpack#226]
The APR connector would provide better performance and lower memory usage for applications.

This may require libapr to be part of the rootfs rather than trying to compile on the fly inside the buildpack.

**Comment by nebhale** [comment]
@markt-asf Do you have any opinions on implementing this?  At the moment, SSL termination and edge routing is take care of by a custom router implemented in Go.  The connector used by Tomcat in our configurations is only used for communication between that router and the Tomcat instance running the the isolated container.  Will we see a benefit from changing connector for the communication for those two close (in network terms) components?

**Comment by nebhale** [comment]
https://www.pivotaltracker.com/story/show/102468524

**Comment by markt-asf** [comment]
APR will provide neither better performance nor better memory usage.

APR is significantly faster for TLS but for non-encrypted connections there is little difference between it and NIO. Which one has the edge depends on which benchmark you use. It varies depending on threads and file size and also - a little - with Tomcat version. At no point does either connector have a significant edge over the other.

I'm not aware that any claims have ever been made that memory usage is lower for APR. Given what I know about the code I doubt that is the case. It may be the case that less java heap memory is required but that will be offset elsewhere and the overall process heap will be near enough the same.

APR may provide a marginal benefit for some use cases but it is likely to be in the noise and not worth the additional complexity that would be required to support it.

My recommendation would be to not implement this request. If the CF architecture changes in the future so TLS is terminated in Tomcat then this should be revisited.

**Comment by nebhale** [comment]
@johnmcteague Based on @markt-asf's response, I'm going to close this out.  If you disagree with his assessment, please respond in this issue and I'll reopen it.
