### ISSUE TITLE
Consider adding a minimum stack size

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#228]
I've discovered that java8 requires a minumum of 228k for Xss in order for the jvm to start.  Perhaps openjdk config should be adjusted to add that minimum to enable more success with memory scaling.

```
memory_calculator:
  memory_sizes:
    stack: 228k..
```

To verify minumum simply try to start java with a smaller stack size:

```
java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

java -Xss128k

The stack size specified is too small, Specify at least 228k
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by youngm** [comment]
Actually it appears the minimum only matters when I have `stack_threads` set.  And it appears that if I provide a minimum without setting `stack_threads` then the stack size never increases beyond the minimum.  hmmm.....

**Comment by cgfrost** [comment]
It might be that we just want to add some documentation warning about this to the description of the `stack_threads` value.

I've opened a tracker issue. https://www.pivotaltracker.com/story/show/103782484

**Comment by cgfrost** [comment]
We talked about this earlier. We are happy to add a minimum value to the default buildpack config but don't want to do this without knowing what the behavior is on Java 7. Do you happen to know? The memory calculator will behave the same for all Java versions.

**Comment by cgfrost** [comment]
Hi Mike,

**Comment by youngm** [comment]
Sorry I dropped the ball on this one.  I'm getting values all over the map as well.  On Java8 Windows 32 bit I get a message saying stack size must be 108k.

Perhaps we should just close this and let it go.  I don't think setting a config minimum is the correct solution anyway since once a config minimum then the value never increases unless you set a stack_threads value.

If anything I think the only real value to be had here is to log a warning in the memory calculator if stack size is smaller than 100k or something to help explain why the app is crashing.  But, even that value is somewhat minimal.  I'm fine closing this issue with no changes.

**Comment by cgfrost** [comment]
Thanks Mike, I might make a note in the documentation but no actual code changes.
