### ISSUE TITLE
Consider support for auto-restaging of vulnerable droplets.TUF helpful ?

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/java-buildpack#231]
In addition to https://github.com/cloudfoundry/java-buildpack-dependency-builder/issues/6 to prevent injection of malicous code into the binary repository, I'm wondering how much [The 
Update Framework (TUF)](http://theupdateframework.com/) can be beneficial to the java buildpack when running in the easy or expert [mode](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/buildpack-modes.md), especially to protect against the [following attacks](https://github.com/theupdateframework/tuf/blob/bd757d67381b8d23b8b76f3510e075f5591d8d1e/docs/tuf-spec.txt#L133-L158). 

Is the HTTPS transport and high availability/throughput/Dos prevention of AWS S3 sufficient ? What about in the case of the expert mode, how hard is it reach such level in a private setting ?

Let me know if you prefer this discussion to happen over cf-dev@ instead.

**Comment by gberche-orange** [comment]
Thinking it through, I now realize that the link between TUF and the java-buildpack artifact downloading is a bit streched: even though the [repository](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md) is designed so that the latest available libs are visible as candidate when staging a java app, droplets are immutable, and therefore don't really update under the responsibility of the java buildpack. 

Therefore CF apps are hardly exposed to [TUF targetted attacks](https://github.com/theupdateframework/tuf/blob/bd757d67381b8d23b8b76f3510e075f5591d8d1e/docs/tuf-spec.txt#L133-L158), unless we consider an app restaging as an update process that could suffer from these attacks and benefit from TUF mechanisms. 

However, currently the restaging of an app is a manual operation, and cloudfoundry does not yet automate the detection that new updates are available in the java-buildpack easy mode, and that a staging could be desireable.

So while related to the java-buildpack and its "easy mode" that provides ability to serve new dependencies, this discussion should rather be made wider with MEGA/runtime/buildpacks team as a way to autodetect droplets that would require a restaging to benefit from pending available updates of some of their dependencies.

**Comment by cgfrost** [comment]
Added tracker issue - https://www.pivotaltracker.com/story/show/103661354

**Comment by nebhale** [comment]
@gberche-orange The wider buildpacks team is reviewing this.  I'm tempted to close this and simply handle it once a platform-wide system is delivered.  Thoughts?

**Comment by gberche-orange** [comment]
Thanks @nebhale for your review of this suggestion. To do have a pointer to a story on the buildpacks / MEGA tracker that could be followed ? If so, then sure it makes sense to close this conversation here.

**Comment by nealmcb** [comment]
These problems are tricky, as[TUF's list of attacks](https://github.com/theupdateframework/tuf/blob/bd757d67381b8d23b8b76f3510e075f5591d8d1e/docs/tuf-spec.txt#L133-L158) illustrates, and as the events of the last few years underscore. So I'm glad to see TUF brought into a conversation of secure Java packaging, installation, building and deployment.

Any updates on updating? Any pointers to a broader platform discussion of this?

**Comment by nebhale** [comment]
At this point we're not going to deal with this problem in the Java Buildpack.  With the advent of [Cloud Native Buildpacks](https://buildpacks.io) and their more [explicit dependency management](https://github.com/cloudfoundry/openjdk-buildpack/blob/master/buildpack.toml#L23-L33) future concerns about this will be handled there.
