### ISSUE TITLE
Testing cloud foundry S3 service connector

### ISSUE THREAD

**Issue by ArthurHlt** [cloudfoundry/java-buildpack#232]
I've made a Cloud Foundry connector for supporting S3 storage, you can see it here: https://github.com/Orange-OpenSource/cloudfoundry-s3-service-connector .
This one is working great with [p-riakcs service broker](https://github.com/cloudfoundry/cf-riak-cs-release).

It could be interesting to have test inside your https://github.com/cloudfoundry/java-buildpack-system-test repository but the main problem is that I don't know if those tests need to have a SaaS service broker which are available in `pivotal web service` like `ElephantSQL` or `ClearDb`.

So, the question is it possible to add test for this here?

**Comment by cgfrost** [comment]
Hi, you can run the java-buildpack-system-test yourself, the [readme](https://github.com/cloudfoundry/java-buildpack-system-test/blob/master/README.md) gives all the setup information required. I suggest you fork it and add in tests to use the S3 storage service. 

The java-buildpack-system-test is intended for testing the java buildpack on PWS so it does use all of the services available to make sure the buildpack sets applications up for them correctly.

**Comment by ArthurHlt** [comment]
hi @cgfrost thanks for the informations.
