### ISSUE TITLE
AppDynamics Service - Unclear node name

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/java-buildpack#233]
For AppDynamics service, with the current java-buildpack, we are addressing the node_name with instance_index.

In case of multi-tier applications, each tier having multiple nodes would have the same node_name across tiers. 

viz, Consider an application having two tiers(webtier1 & webtier2) and each tier has 2 nodes.
The node names would appear as 0,1,0,1 in AppDynamics controller, since the node names are instance_indexes

If we could prefix the node_name with tier_name, this would give some depth in understanding which node is under consideration when things fail at node level.
<node_name>=<tier_name>:<instance_index>

Thus, the node names in the above example would appear as:
webtier1:0, webtier1:1, webtier2:0, webtier2:1

This change would allow node-level visibility to AppDynamics customers with the default java-buildpack

**Comment by cgfrost** [comment]
This should be possible by changing the AppDynamics config in this file. https://github.com/cloudfoundry/java-buildpack/blob/master/config/app_dynamics_agent.yml

This can be easily done by specifying the new `default_node_name` in an environment variable in the applications manifest file.

**Comment by nkatre** [comment]
I think that instead of changing the config file for appdynamics, this file needs to be changed
https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/app_dynamics_agent.rb
such that we can pass the tier_name as one of the arguments to the node_name method and prefix the node_name with tier_name in the node_name method

The reason, I am proposing the change at the buildpack level instead of application manifest file is because this helps greater visibility for all AppDynamics customers and would help everyone. 

It would be great if this bug is fixed at the buildpack level !

**Comment by nebhale** [comment]
Closed in lieu of #243
