### ISSUE TITLE
DynaTrace agent - custom agent name

### ISSUE THREAD

**Issue by tom-collings** [cloudfoundry/java-buildpack#234]
The DynaTrace agent name is defaulted to the application name.  A client has asked to override this default behaviour.  We can accomplish this by setting an environment variable in the manifest, suggest DYNATRACE_AGENT_NAME as the env variable name.  If the environment variable exists, use that value, otherwise use the current method for setting the agent name.

**Comment by nebhale** [comment]
We'll actually stick with the environment variable configuration mechanism as described [here](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension).  [Issue opened](https://github.com/cloudfoundry/java-buildpack/issues/234)

**Comment by cgfrost** [comment]
Issue opened is actually here. https://www.pivotaltracker.com/story/show/104558394

@tom-collings I will implement this using the configuration mechanism we already have in place, you got the environment variable name correct but it should be added to the dyna trace config file as well. It's a small change.

**Comment by cgfrost** [comment]
It will now be possible to do this using an environment variable like this. 
```cf set-env my-app JBP_CONFIG_DYNA_TRACE_AGENT '[default_agent_name: "new-agent-name"]'```

The change is on the master branch and will get released in due course.
