### ISSUE TITLE
Passing environmental variables to JBP_CONFIG_JAVA_MAIN

### ISSUE THREAD

**Issue by shouah** [cloudfoundry/java-buildpack#236]
When passing environment variable to the command line arguments they seem to expand to blank. For example, in my manifest I have this:

env:
      JBP_CONFIG_JAVA_MAIN: '[arguments: " -console -p $PORT " ]'

But the standalone java application only sees "-console -p ". How can I pass environmental variables?

**Comment by cgfrost** [comment]
This should be a matter of escaping, the value is disappearing as the `$PORT` property is being evaluated too early, in an environment where `$PORT` isn't defined. Try placing it in single quotes `''$PORT''`, double required for yaml escaping or simply a back slash `\$PORT`. If this doesn't help I will take a deeper look at it.

**Comment by shouah** [comment]
the PORT environmental variable always exists in a Cloud Foundry container as it is created by CF, so if it is evaluated when the standalone application is started then it will contain a numerical value. I'm on a trip and can't get to a CF environment to test the suggestions -- I'll update in 10 days when I get back.

**Comment by cgfrost** [comment]
OK, no problem. 

I'm saying that it could be being evaluated prior to the CF droplet where `PORT` is defined. There are several environments the application and it's state will get passed through before the application is started.

**Comment by nebhale** [comment]
@shouah Specifically, `$PORT` is not set during staging because it is unique to each instance of the droplet.  Since the value must be written without evaluation during staging, it must be escaped as input.

**Comment by shouah** [comment]
Escaping the value worked. I'm guessing that I was expecting the buildpack to not perform any evaluation of the command line string since it is intended to be meaningful only for the application launch and not at buildpack staging nor compile time.

**Comment by nebhale** [comment]
We don't actually perform any evaluation of the command line during staging.  However, the arguments that you give the buildpack are first passed as output to `bash` from staging.  This output is then evaluated by `bash` at droplet startup time.  Because it's cycling through `bash` in a couple of places as part of its lifecycle, escaping is necessary, irrespective of the buildpack.
