### ISSUE TITLE
Support for Debug Mode

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#238]
It would be nice if there were an easy consistent way to enable debug mode for an application without adding a bunch of custom java opts.

This would be useful for tooling to simplify debugging using Diego ssh port forwarding.

Should support run and suspend modes.

**Comment by cgfrost** [comment]
I agree completely, tracker issue raised https://www.pivotaltracker.com/story/show/105552412

**Comment by nebhale** [comment]
@youngm Complete with b533b6c8caf53ff20d749e84860496ef4bcd85b9.  If you could give it a look and let me know if it works for you, that'd be great.

**Comment by youngm** [comment]
@nebhale Looks great!
