### ISSUE TITLE
cloud profile does not seem to be properly enabled

### ISSUE THREAD

**Issue by snicoll** [cloudfoundry/java-buildpack#240]
Using buildpack 3.3 the `cloud` profile does not seem to be enabled automatically. 

I have [created a sample project](https://github.com/snicoll-scratches/test-cloud-profile) that reproduces the problem.

**Comment by nebhale** [comment]
On hold while the Boot team diagnose the issue.

**Comment by snicoll** [comment]
After another round of checks this looks like a boot issue actually so closing this one. Sorry for the noise Ben.

**Comment by nebhale** [comment]
No worries.  Happy to help.

**Comment by snicoll** [comment]
For the record, we're going to  fix that in `1.2.8` and `1.3.0` see https://github.com/spring-projects/spring-boot/issues/4273
