### ISSUE TITLE
I suspect the detect script is timing out but I can't debug it.

### ISSUE THREAD

**Issue by dekozo** [cloudfoundry/java-buildpack#242]
I've been trying to deploy an application on my Cloud Foundry deployment without specifying the buildpack to be used. 
Whenever I enable the java-buildpack (so it's detect script is executed) the deployment times out.
I don't know how to approach the debugging process but I'd be glad to get some directions to do so.

**Comment by jtarchie** [comment]
@dekozo, how are you deploying your application? The java-buildpack requires that the build artifact from supported frameworks be pushed. For example, if you have  `myapp.war`, you'd be specifying `cf push myapp -p myapp.war`, or the equivalent in a `manifest.yml`.

**Comment by nebhale** [comment]
@dekozo you might try staging your application with the Java buildpack [in debug mode](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/debugging-the-buildpack.md).  Note however, that it's possible that your application isn't even making it to the Java Buildpack and there won't be any debug output from it.

**Comment by dekozo** [comment]
Sorry, I wasn't clear on my initial message.

The problem I'm having (supposedly) is with the java-buildpack detect script. 
Whenever I activate this buildpack (and its priority is higher than the one I would like to use) the detect.sh script seems to get into a loop, for my deployment always times out (15 minutes).

I've tried the cf push command with only two buildpacks enabled. The java-buildpack and the one that would be used (ruby-buildpack, for that matter) and it always times out when java-buildpack has a higher priority, so I suspect it's detect script is getting stuck somewhere.

@jtarchie I'm deploying the [fib-cpu sample application] (https://github.com/cloudfoundry-samples/fib-cpu) using simply  `cf push` in order to check the auto detection system for which buildpack to use.

@nebhale I've had a quick look on the link you've provided (thanks!). Do you think that this approach would give me something regarding the detect.sh script?

**Comment by nebhale** [comment]
@dekozo I just double checked and yes, `detect` should output the debug logs as well.  Almost immediately after invocation, the buildpack kicks out something like

```
DEBUG v3.3 | https://github.com/cloudfoundry/java-buildpack.git#378f420
```

So if you're not seeing that, it's unlikely that the buildpack is even being invoked properly.

**Comment by nebhale** [comment]
@dekozo Any progress on this?

**Comment by dekozo** [comment]
@nebhale Sorry but I had to put that aside for a while.
I'll get back to that in a while and give more feedback later.
Sorry for the trouble.

**Comment by nebhale** [comment]
I'm going to close this issue for now.  If you'd like to see it re-opened when you've got more information, please comment on the issue and I'll reopen it.
