### ISSUE TITLE
App Dynamics accountAccessKey with a $ doesn't work

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#248]
I was able to get the $ to correctly go into the java process as a system property by doing something like this:

-Dappdynamics.agent.accountAccessKey='mykey\$dude'

So, I had to add a `'` and escape $ `\$`.

I'd be happy to submit a PR but escaping is a tricky business.  The question is where should this be fixed?  Should we be escaping all javaopts values this way?  Should my PR only escape the app dynamics accountAccessKey?  Should I just be supplying the value to the JBP pre-escaped and leave escaping logic out of the JBP?

Thoughts?

**Comment by cgfrost** [comment]
There is already some complicated handling of escaping in the buildpack that is done in a general way for all java opts (and differently for other config). I think `escaping is a tricky business` is an understatement as I've done several loops looking at escaping, trying to get it right. The main problem is that we can't control where user provided values enter the buildpack (manifest file vs command line vs environment variables vs goes through a config file). We have to ensure common support regardless of where it's coming from but the escaping will always be different and have to be handled by the user. If you want to look for a better solution please do, I'm the first one to admit that escaping is a pain in the buildpack.

**Comment by youngm** [comment]
@cgfrost It sounds like I should probably just try to do what I need to do to escape this $ on the user side instead of attempting to do something in the buildpack.  Correct?

**Comment by nebhale** [comment]
@youngm Yeah, give that a try to start with.  If it's massively onerous, we'll take a look at doing something better, but we've struggled with this a bit so far and come to the current state of "we're not escaping anything, take care of it in the input".  As this isn't the best user experience, I'm still open to changing our minds on that.  It's been difficult.

**Comment by youngm** [comment]
I'll give it a try on the user side and close the issue if I can get it to work.

**Comment by youngm** [comment]
@nebhale @cgfrost So, I'm running into an issue because the escaping for a system property in a Spring Boot application is different from the escaping necessary for a tomcat .war application.

In the case of spring boot the system properties are going right onto the command line.  For a tomcat application the system properties are going into a `JAVA_OPTS` environment variable.  This is requiring another level of escaping for tomcat apps vs Spring Boot apps.

Perhaps we should change the Spring Boot java_opts handling to place it into an environment variable first so the escaping will match Tomcat?  Thoughts?

**Comment by nebhale** [comment]
That's certainly worth considering.  I'll take a look at this today and see what the "typical" case is for containers.  My concern is that it's actually a pretty invasive change as far as compatibility goes (all of a sudden escaping needs to change for some users).  So while I'm willing to make the change now (pending research), I think I'd be quick to roll it back if users start complaining.

**Comment by youngm** [comment]
@nebhale I think that's fair for a patch release.  Though if rolled back I hope you consider the lack of consistent encoding across containers a bug and hopefully put the fix back in a future major or possibly minor update.

**Comment by nebhale** [comment]
https://www.pivotaltracker.com/story/show/108647188

**Comment by nebhale** [comment]
@youngm Can you try `master` and see if that does what you expect?

**Comment by youngm** [comment]
@nebhale So, this is not quite working correctly.  If I have single quoted values with spaces within JAVA_OPTS then it gets lost in the java main case.  Here are my test cases:

`JAVA_OPTS="-Dfoo=bar" catalina.sh run` Works great
`JAVA_OPTS="-Dfoo=bar" && java $JAVA_OPTS Main` Works great
However:
`JAVA_OPTS="-Dfoo='bar baz' -Djoe=bob" catalina.sh run` Works
`JAVA_OPTS="-Dfoo='bar baz' -Djoe=bob" && java $JAVA_OPTS Main` Does not work

With my limited bash skills I have not yet been able to find the solution to how the right side must be manipulated for the Java main example to work.

**Comment by youngm** [comment]
@nebhale it appears that adding an "eval" similar to what tomcat does [0] makes the resolution correct like so:

`JAVA_OPTS="-Dfoo='bar baz' -Djoe=bob" && eval java $JAVA_OPTS Main`

Structured like that I can use the same escaping in both tomcat and java main to connect to app dynamics with an access key containing a $.

[0] http://svn.apache.org/repos/asf/tomcat/tc8.0.x/trunk/bin/catalina.sh

**Comment by nebhale** [comment]
Hmm...  We're getting ready to put an `exec` in front of a bunch of this stuff.  I wonder if that will affect it in a similar way.

**Comment by youngm** [comment]
@nebhale Not sure.  it appears some of the tomcat stuff does an eval and exec so my guess would be exec wouldn't affect the need for eval in this case.

**Comment by nebhale** [comment]
I'm not sure I've ever felt this much trepidation when changing code.  I totally do not understand what I'm doing with all these `evals` and `execs` :frowning:.

**Comment by nebhale** [comment]
OK @youngm.  Take a look.  I'm going to hold off on the `exec` changes until this is working correctly for you.

**Comment by youngm** [comment]
Works fine for me.  I'd feel more comfortable also if I know why eval suddenly makes it work. :)

Perhaps @markt-asf has some insight?  I believe he was maintainer over Tomcat 7 when this was fixed in the tomcat startup scripts.

**Comment by nebhale** [comment]
OK, I'll close this out and we can all brace ourselves for the `exec` change.
