### ISSUE TITLE
Parameterize enableLocalCache for session caching (GemFire)

### ISSUE THREAD

**Issue by sbawaska** [cloudfoundry/java-buildpack#252]
In the buildpack we have enableLocalCache set to false for session caching using gemfire. 

When sticky sessions is turned on, we should enable local cache within gemfire to have optimal performance, whereas we should disable localcache when stickyness is off. So, rather than hardcoding enableLocalCache to false, we should parameterize it.

**Comment by cgfrost** [comment]
Thanks for raising this request, we have created a tracker item for it.

https://www.pivotaltracker.com/story/show/108245804

**Comment by nebhale** [comment]
@sbawaska Sticky sessions is always enabled in CF.  Based on that, should we just set `enableLocalCache` to `true` at all times?

**Comment by sbawaska** [comment]
@nebhale Is there no way to turn off sticky sessions in CF?

**Comment by nebhale** [comment]
No, it's managed at the CF router layer and is, for all intents and purposes, always on.
