### ISSUE TITLE
no_proxy environment varbiable is ignored when downloading cache for resources behind a firewall for offline buildpacks

### ISSUE THREAD

**Issue by samwlui** [cloudfoundry/java-buildpack#257]
Currently all resources to be cached for offline buildpack creation is retrieved using the proxy configured in the http_proxy or https_proxy environment variable. In order to build a buildpack that contains a resource behind a firewall, the no_proxy environment variable needs to be considered so that the proxy can be bypassed.

**Comment by nebhale** [comment]
Closed in lieu of #258.
