### ISSUE TITLE
Server error, status code: 404, error code: 250003, message: The stack could not be found: The requested app stack cflinuxfs2 is not available on this system.

### ISSUE THREAD

**Issue by mridhuljp** [cloudfoundry/java-buildpack#259]
I am trying to push my app and it fails by throwing the above error.

I could see cflinuxfs2 getting listed when i do a "cf stacks". but somehow the stack is not picked up by the app. Any pointers on how to troubleshoot ?

**Comment by nebhale** [comment]
Unfortunately, I do not.  This seems to be a problem at the Cloud Foundry platform level rather than buildpack.  You might try asking on the [`cf-dev` mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/).
