### ISSUE TITLE
DownloadCache is failed when Persisting content to openjdk-1.8.0_65.tar.gz

### ISSUE THREAD

**Issue by IkuEisou** [cloudfoundry/java-buildpack#260]
It's failed to push war on the Ubuntu14.04 when step into  persisting content to `openjdk-1.8.0_65.tar.gz`.
Environment variable `https_proxy` has been correctly set up and works according to the debug info.

I also diffed the success debug log at this site https://gist.github.com/nebhale/83f3f37f81b789c88c33,
and there are some difference in the line 402 of the `web-application-1.0.0.BUILD-SNAPSHOT.war` .
It seems that there is some different to parse yml and tar.gz in the line 150 or 154 of the `java-buildpack/lib/java_buildpack/util/cache/download_cache.rb`.
I don't know more detail about that, so  could someone tell me the reason of this error? 

Debug info as follow:
```
[DownloadCache]                  DEBUG Request: /openjdk/trusty/x86_64/index.yml, {"accept"=>["*/*"], "user-agent"=>["Ruby"]}
[DownloadCache]                  DEBUG Status: 200
[DownloadCache]                  DEBUG Persisting etag: "83fbbe8dd20c8320be47f582b2b84083"
[DownloadCache]                  DEBUG Persisting last-modified: Mon, 26 Oct 2015 16:29:22 GMT
[DownloadCache]                  DEBUG Persisting content to /tmp/https%3A%2F%2Fdownload.run.pivotal.io%2Fopenjdk%2Ftrusty%2Fx86_64%2Findex.yml.cached
[DownloadCache]                  DEBUG Validated content size 2995 is 2995
[RepositoryIndex]                DEBUG {"1.7.0_06"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_06.tar.gz", "1.7.0_07"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_07.tar.gz", "1.7.0_08"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_08.tar.gz", "1.7.0_09"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_09.tar.gz", "1.7.0_10"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_10.tar.gz", "1.7.0_11"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_11.tar.gz", "1.7.0_12"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_12.tar.gz", "1.7.0_13"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_13.tar.gz", "1.7.0_14"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_14.tar.gz", "1.7.0_15"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_15.tar.gz", "1.7.0_17"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_17.tar.gz", "1.7.0_21"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_21.tar.gz", "1.7.0_25"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_25.tar.gz", "1.7.0_40"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_40.tar.gz", "1.7.0_45"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_45.tar.gz", "1.7.0_51"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_51.tar.gz", "1.7.0_55"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_55.tar.gz", "1.7.0_60"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_60.tar.gz", "1.7.0_65"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_65.tar.gz", "1.8.0_00"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0.tar.gz", "1.8.0_05"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_05.tar.gz", "1.8.0_11"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_11.tar.gz", "1.8.0_20"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_20.tar.gz", "1.8.0_RC1"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_RC1.tar.gz", "1.8.0_25"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_25.tar.gz", "1.7.0_71"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_71.tar.gz", "1.8.0_31"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_31.tar.gz", "1.7.0_75"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_75.tar.gz", "1.8.0_40"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_40.tar.gz", "1.8.0_45"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_45.tar.gz", "1.7.0_79"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_79.tar.gz", "1.8.0_51"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_51.tar.gz", "1.8.0_60"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_60.tar.gz", "1.8.0_65"=>"https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz"}
[DownloadCache]                  DEBUG Proxy: 10.167.227.38, 1080, ,
[DownloadCache]                  DEBUG Adding HTTP options for secure connection
[DownloadCache]                  DEBUG Adding HTTP options for secure connection
[DownloadCache]                  DEBUG Adding HTTP options for secure connection
[DownloadCache]                  DEBUG HTTP: download.run.pivotal.io, 443, {:use_ssl=>true}
[DownloadCache]                  DEBUG SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 29992181164F07AC053339B1F7805B8F6A2C1D5B12177C5EA0C373AD7F39AB52
    Session-ID-ctx:
    Master-Key: 686E271BD234387C7BA7A75E1C8E9874B8F98787E51A4A4EF527F87A6BECD1F0B14E3369DFE727DA21043AA99BBBFA18
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 10800 (seconds)
    TLS session ticket:
    0000 - 68 d8 1c 36 2d a1 c7 15-be 5e 16 e5 fd 0d 4e 31   h..6-....^....N1
    0010 - 5d 96 73 9f 68 68 48 b9-e6 ee ee dd 1b 0d a3 22   ].s.hhH........"
    0020 - 55 4c 70 e9 40 0d 0c ec-26 6d eb eb 99 fc 58 dd   ULp.@...&m....X.
    0030 - 28 7a 3d aa 61 15 6b 6d-fc 09 0e aa 4e f9 c3 92   (z=.a.km....N...
    0040 - 5a 44 c2 72 ec 32 87 4b-1c 12 1c 5c 9b f9 bc 71   ZD.r.2.K...\...q
    0050 - 6e fb d0 33 3e 8b 15 12-9c 8f 0e 70 5d ce e9 9b   n..3>......p]...
    0060 - f7 71 d3 fe e6 b0 54 e0-2a cf b7 d7 2e fd 63 bc   .q....T.*.....c.
    0070 - 4e 8a 8a c6 8a a7 1c 60-ec 6c a9 7e 94 f3 42 08   N......`.l.~..B.
    0080 - 85 d1 ad a9 7f f2 df 05-79 f7 bb 09 96 5b c4 e0   ........y....[..
    0090 - 42 9b 71 f8 a2 23 3c 1e-6a 99 5e a1 ec b5 d8 b3   B.q..#<.j.^.....
    00a0 - 5c f9 42 b1 a7 13 41 5a-df 7c 96 c5 06 c5 74 41   \.B...AZ.|....tA
    Start Time: 1448273865
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
[DownloadCache]                  DEBUG Request: /openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz, {"accept"=>["*/*"], "user-agent"=>["Ruby"]}
[DownloadCache]                  DEBUG Status: 200
[DownloadCache]                  DEBUG Persisting etag: "bd7d7b0db4e4c4d4815ff555896aa517-9"
[DownloadCache]                  DEBUG Persisting last-modified: Mon, 26 Oct 2015 16:28:57 GMT
[DownloadCache]                  DEBUG Persisting content to /tmp/cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fopenjdk%2Ftrusty%2Fx86_64%2Fopenjdk-1.8.0_65.tar.gz.cached
[DownloadCache]                  WARN  Request failure 1, retrying: Timeout::Error
[DownloadCache]                  WARN  Request failure 2, retrying: No route to host - connect(2)
[DownloadCache]                  WARN  Request failure 3, retrying: No route to host - connect(2)
[DownloadCache]                  WARN  Request failure 4, retrying: No route to host - connect(2)
[DownloadCache]                  WARN  Request failure 5, retrying: No route to host - connect(2)
[InternetAvailability]           WARN  Internet availability set to false: Request failed: No route to host - connect(2)
[DownloadCache]                  WARN  Unable to download https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz into cache /tmp/cache: No route to host - connect(2)
[DownloadCache]                  DEBUG https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz found in cache /tmp/cache
-----> Downloading Open Jdk JRE 1.8.0_65 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre
Command 'tar xf /tmp/cache/https%3A%2F%2Fdownload.run.pivotal.io%2Fopenjdk%2Ftrusty%2Fx86_64%2Fopenjdk-1.8.0_65.tar.gz.cached -C /tmp/staged/app/.java-buildpack/open_jdk_jre --strip 1 2>&1' has failed
STDOUT:
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
STDERR:
[Buildpack]                      ERROR Compile failed with exception RuntimeError
[Buildpack]                      DEBUG Exception RuntimeError backtrace:
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/shell.rb:37:in `block in shell'
/usr/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
/usr/lib/ruby/1.9.1/open3.rb:90:in `popen3'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/shell.rb:31:in `shell'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/base_component.rb:125:in `block (2 levels) in download_tar'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/base_component.rb:164:in `with_timing'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/base_component.rb:123:in `block in download_tar'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/base_component.rb:94:in `block in download'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/cache/cached_file.rb:53:in `call'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/cache/cached_file.rb:53:in `block in cached'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/cache/cached_file.rb:53:in `open'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/cache/cached_file.rb:53:in `open'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/cache/cached_file.rb:53:in `cached'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/util/cache/download_cache.rb:74:in `get'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/base_component.rb:92:in `download'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/base_component.rb:122:in `download_tar'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/versioned_dependency_component.rb:79:in `download_tar'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/jre/open_jdk_like_jre.rb:50:in `compile'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/modular_component.rb:49:in `each'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/component/modular_component.rb:49:in `compile'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/buildpack.rb:63:in `compile'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/bin/compile:27:in `block in <main>'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/lib/java_buildpack/buildpack.rb:215:in `with_buildpack'
/var/vcap/data/dea_next/admin_buildpacks/d0b68e0d-f9f6-436d-b45a-59d1af6e4ba9_c6f00e64e905963ea8499c87f5d97d8122071c23/bin/compile:26:in `<main>'
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed
```

**Comment by nebhale** [comment]
The key line in your logs is the following:

```
[DownloadCache]                  WARN  Request failure 2, retrying: No route to host - connect(2)
```

Persistence has failed because it's unable to connect to the specified host with your network configuration.

**Comment by IkuEisou** [comment]
Hi, nebhale. Thank you for your reply!
Obviously,  "No route to host - connect(2)" is a reason, but I don't think it's a root cause

Actually, I think there is no problem at the  network configuration，and there are two reasons。
1. If  network configuration was not OK, then the "Request: /openjdk/trusty/x86_64/index.yml"(debug info) can't be successful .
2. When coming to "Request: /openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz"  , "Status: 200"  is displayed at the debug info. That means HTTP response is OK according to the definition for Net::HTTPOK.

And I found that  error is happened until comes to the step "response.read_body { |chunk| f.write chunk }"(java_buildpack/util/cache/download_cache.rb) with more deeply debugging. 
Maybe it needs to connect to internet, but it seems not to read the value of "http_proxy" or "https_proxy" at that moment. And  it may be caused the error.

Of course , if you think it was caused by some miss of the network  configuration, 
could you tell me what  should I confirm. Thank you!

**Comment by nebhale** [comment]
@IkuEisou As you point out if the buildpack wasn't properly reading `http(s)_proxy`, then it couldn't have downloaded the `index.yml` file successfully.  I believe that everything is routing through the proxy correctly, including the failing request.  If you note:

```
[DownloadCache]                  DEBUG Status: 200
[DownloadCache]                  DEBUG Persisting etag: "bd7d7b0db4e4c4d4815ff555896aa517-9"
[DownloadCache]                  DEBUG Persisting last-modified: Mon, 26 Oct 2015 16:28:57 GMT
```

All of that data is part of the HTTP payload, and is being received successfully by the buildpack.  The first failure appears to be `Request failure 1, retrying: Timeout::Error`, which indicates that the proxy, after allowing the preamble and headers through, has caused a timeout with the rest of the body.

**Comment by IkuEisou** [comment]
@nebhale Thank you for your reply!
 I found the "Request: /openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz" should not be   "DEBUG Status: 200"(Net::HTTPOK).  
It should get "DEBUG Status: 304"(Net::HTTPNotModified) according to the OK log (https://gist.github.com/nebhale/83f3f37f81b789c88c33,  line404). 

If response's status was Net::HTTPOK , it means the response has a body and will be read.
And if it was Net::HTTPNotModified, it means the response has no body and needn't to be read.

When it was read( read_body) at the method“cache_content"  that should not be read,  so Timeout::Error was happened.
It seems caused by getting a wrong type of the cached_file at the method "request".
I don't know what's the right cached_file , and where  should be checked, cloud you give me some tips?

The source as follow.(java_buildpack/util/cache/download_cache.rb) 
        def attempt(http, request, cached_file)
          downloaded = false

          http.request request do |response|
            @logger.debug { "Status: #{response.code}" }

            if response.is_a? Net::HTTPOK
              cache_etag response, cached_file
              cache_last_modified response, cached_file
              cache_content response, cached_file
              downloaded = true
            elsif response.is_a? Net::HTTPNotModified
              @logger.debug { 'Cached copy up to date' }
            elsif redirect?(response)
              downloaded = update URI(response['Location']), cached_file
            else
              fail InferredNetworkFailure, "Bad response: #{response}"
            end
          end

          downloaded
        end

        def request(uri, cached_file)
          request = Net::HTTP::Get.new(uri.request_uri)

          if cached_file.etag?
            cached_file.etag(File::RDONLY | File::BINARY) { |f| request['If-None-Match'] = File.read(f) }
          end

          if cached_file.last_modified?
            cached_file.last_modified(File::RDONLY | File::BINARY) { |f| request['If-Modified-Since'] = File.read(f) }
          end

          @logger.debug { "Request: #{request.path}, #{request.to_hash}" }
          request
        end

**Comment by nebhale** [comment]
A `304` is only received if the buildpack has already cached a copy of the artifact.  In your log attached at the top, that is not what is happening; a `200` is being returned meaning that the bits do actually need to be downloaded, and that download is what's timing out.

You can reproduce this by getting your same logging, on the machine where it works, from a fresh application:

```
$ cf delete <APP>
$ cf push --no-start
$ cf set-env JBP_LOG_LEVEL DEBUG
$ cf restage <APP>
```

**Comment by IkuEisou** [comment]
Thanks for your advise.
I tried push a fresh one, but it's still  failed .
After adding the debug code and catching the exception for the block "response.read_body  { |chunk| f.write chunk }", I found read_body is working  for a while, then it throws  a "Timeout::Error" exception .

The open JDK package  has been downloaded successfully with "wget", so it doesn't look like a network problem.
May be it's caused by that some timeout set is too short, so I also tried to set  following Net::HTTP timeout  to be longer (600s), but it has no effect. 
      open_timeout 
      read_timeout 
      continue_timeout 

Could you give me some tips about  where  the "Timeout::Error"  is happened.

Debug info as follow:
[DownloadCache]       DEBUG Status: OK before reponse.read_body, ruby is 1.9.3 by yuyc
 [DownloadCache]      WARN  Exception: Timeout::Error,response status: 200 by yuyc
 [DownloadCache]      DEBUG Validated content size 10615888 is 45096447
[DownloadCache]                  WARN  Request failure 1, retrying: Content has invalid size.  Was 10615888, should be 45096447.
[DownloadCache]                  WARN  Request failure 2, retrying: No route to host - connect(2)
[DownloadCache]                  WARN  Request failure 3, retrying: No route to host - connect(2)
[DownloadCache]                  WARN  Request failure 4, retrying: No route to host - connect(2)
[DownloadCache]                  WARN  Request failure 5, retrying: No route to host - connect(2)

**Comment by nebhale** [comment]
Beyond the fact that the buildpack is attempting to download data and the data is not being received by it in a timely manner, I don't have any more insight.  The way that HTTP is downloaded (chunked or not, buffer sizes, gzip compression, etc.) and the way that proxies are handled, varies widely between different libraries so just because `wget` works, doesn't mean that other libraries and tools will as well.  It's pretty clear that the Ruby (remember that the buildpack is just using standard Ruby libraries) is not playing nicely with your proxy.  Short of solving that problem on the proxy side or removing the proxy from the equation completely, there's nothing we can really do.

**Comment by IkuEisou** [comment]
Thank you for your replies.
I think I found out the cause of the timeout, but now I'm not sure how to prove it ,
I need your help, and I think that's easy to you.

Could you  tell me where is the home directory of the ruby that used by java-buildpack?
It seems to use "/usr/lib/ruby/1.9.1/" according to the backtrace of the  debug info,
but I can't find it in the machine.I think that isn't a full path.

**Comment by nebhale** [comment]
That is a full URL, but the full URL within the container that the buildpack is executing in.  That filesystem is defined by both the Cloud Foundry Stack that the container runs on as well as the RootFS that the container mounts to begin execution.  In general, this is opaque to to users and there aren't any real tools to find out what exactly exists on the filesystem.

**Comment by IkuEisou** [comment]
Thank you for your help.
I'm sure the timeout is raised by the method  "rbuf_fill" according the following backtrace log when downloading the open jdk.
>  /usr/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill'
>  /usr/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
>  /usr/lib/ruby/1.9.1/net/protocol.rb:92:in `read'
>  /usr/lib/ruby/1.9.1/net/http.rb:2756:in `read_body_0'
>  /usr/lib/ruby/1.9.1/net/http.rb:2711:in `read_body'

The cause of the timeout is a IO::WaitReadable exception which comes from a method called "read_nonblock" in the ruby/1.9.1/openssl/bufferfing.rb.

There is a  warning comment on the "java_buildpack/util/cache/download_cache.rb" in the head of the "http_options" method that will be called before the "read_body" method. 
# Beware known problems with timeouts: https://www.ruby-forum.com/topic/143840

And there is another comment about the thread-safe on the cached files in the same file.
#Note: this class is thread-safe, however access to the cached files is not

I think it will be helpful to solve this issue, so cloud you tell me how to fix or avoid this  known problems?

**Comment by nebhale** [comment]
Other than your issue, we've never seen any timeout issues with downloading dependencies in the buildpack.  The problem almost certainly lies with a misbehaving proxy in the network path.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
