### ISSUE TITLE
Jrebel dependency download url loaded through insecure transport

### ISSUE THREAD

**Issue by bssie** [cloudfoundry/java-buildpack#262]
Hi,

when building the java Buildpack the URI to download the Jrebel dependency is loaded from 
`http://dl.zeroturnaround.com/jrebel/index.yml` which allows an malicious party to launch an 
Man in the Middle style attack against this dependency and possibly inject arbitrary code into
the Build. 
As Zeroturnaround also supplies a secure channel through `https://dl.zeroturnaround.com/jrebel/index.yml` the URI `http://dl.zeroturnaround.com/jrebel` from `https://github.com/cloudfoundry/java-buildpack/blob/master/config/jrebel_agent.yml` should be replaced with `https://dl.zeroturnaround.com/jrebel`

Greetings 
Benedikt

**Comment by cgfrost** [comment]
I can confirm that the https url also works. We will update this, thanks for spotting and raising the issue.

Tracker issue: https://www.pivotaltracker.com/story/show/109442964
