### ISSUE TITLE
Setting context and properties for the app.

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/java-buildpack#263]
Hey, all.

Not long ago I needed to deploy a java app without having its source code. This app is distributed by `war` files, that are deployed to Tomcat. It needs special properties and several data sources to be created. Since I can't configure this app to take this options from env variables, java buildpack seems to be the right place to handle it.

I see that there is a possibility to use [auto-reconfiguration](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration#what-is-auto-reconfiguration) project for the same purpose, but I can't take advantage of it in my case.

I solved this issue by adding possibilities to rewrite some buildpack resource in compilation phase ([here is the diff](https://github.com/allomov/java-buildpack/compare/master...allomov:override-resources?expand=1)). Using this feature, I rewrited `.java-buildpack/tomcat/conf/context.xml` file and added `.java-buildpack/application.properties` for properties.

Do you consider to add adding custom data sources and setting properties to this buildpack? This can allow to adopt some old applications to be deployed to CF.

Thank you,
Alex L.

**Comment by nebhale** [comment]
We don't consider the use of container-provided resources like properties and `DataSource`s to be "cloud native", so we don't provide support for doing it.  If you take a look at the [12 Factor](http://12factor.net) principals, [configuration](http://12factor.net/config) and [resources](http://12factor.net/backing-services) should come from the environment.

That being said, we're aware that not all applications in Cloud Foundry are cloud native and that sometimes the container does need to provide some of these things.  For this express purpose we've added the `resources` folder and you made exactly the right change to enable this use-case.

**Comment by allomov** [comment]
Oh, nice. I missed the feature with `resources` folder. 

Thank you for the answer.
