### ISSUE TITLE
JAVA_OPTS environment variables resolved to early

### ISSUE THREAD

**Issue by warroyo** [cloudfoundry/java-buildpack#264]
I am seeing an issue when using the buildpack with the introscope agent. I am attempting to set some `-D` options through the `JAVA_OPTS` environment variable. 

The problem is that when I use environment variables in my -D options, for example `-Dintroscope.agent.hostName=$(expr "$VCAP_APPLICATION" : '.*application_name[": ]*\([A-Za-z_-]*\).*') ` it gets resolved at what looks like the initial start of the builpack and not at the start of the JVM. This becomes a problem because I am trying to use the `CF_INSTANCE_INDEX` environment variable in my `-D` options. This variable is not available(from what I can telll) until the JVM starts. so the below example does not work, it just leaves the variable blank.

````
-Dcom.wily.introscope.agent.agentName=$(expr "$VCAP_APPLICATION" : '.*application_name[": ]*\([A-Za-z0-9_-]*\).*')-$CF_INSTANCE_INDEX

````

is there a way to get access the the instance variables though the `JAVA_OPTS` option? If not how can I get the environment variables to resolve at the time of the JVM starting rather than at the builpack run?

**Comment by youngm** [comment]
What version of the buildpack?

**Comment by warroyo** [comment]
3.3.1

**Comment by youngm** [comment]
Yeah, this is basically an extreme exercise in escaping through your local shell, CLI, CC, Stager, JBP, DEA and hoping there aren't any surprises along the way.

If you cannot get the variables in via the escaping jungle of an environment variable I am quite confident you could fork the buildpack and supply a less escaped value here: https://github.com/cloudfoundry/java-buildpack/blob/master/config/java_opts.yml#L19 similar to how it is escaped here: https://github.com/cloudfoundry/java-buildpack/blob/master/config/app_dynamics_agent.yml#L21  This would get you one level of abstraction closer to an app environment variable.

  Good luck. :)  I'd be interested in knowing what the result is.

**Comment by nebhale** [comment]
The problem is that you need a double escape since the value is exposed as an environment variable to the buildpack during staging.  This means that the buildpack can't get ahold of the pre-evaluated expression because the evaluation has happened before the buildpack is invoked.  We've made some changes to evaluation and execution of applications (especially Java Main ones) in yesterday's 3.4 release.  I'd encourage you to give a try with that for your escaping exercise.

In addition, after finding one of the most ridiculous limitations with `expr` [we've also changed](https://github.com/cloudfoundry/java-buildpack/commit/4985ea7dd8a7e6b1f759cf49d885a59edbb4de52) how values like that are created.  As @youngm's link shows we've moved to using simple Ruby expressions which are both easier to understand and easier to escape.  I'd encourage you to follow that path as well if you can.

**Comment by warroyo** [comment]
I have upgraded the buildpack to 3.4. Now I am trying to figure out the escaping. When trying to use the basic ruby expressions instead of `expr` I am seeing the following error. what is the basic ruby expression from the `JAVA_OPTS` environment variable suppose to look like?

error:

````
/bin/bash: command substitution: line 9: syntax error near unexpected token `('
Tue Dec 08 2015 15:21:09 GMT-0700 (MST) [STG] ERR /bin/bash: command substitution: line 9: `ruby -e \"require 'json' ; puts JSON.parse(ENV['VCAP_APPLICATION'])['application_name']\")"'

````

Here is what I am setting:

`-Dintroscope.agent.hostName=$(ruby -e "require 'json' ; puts JSON.parse(ENV['VCAP_APPLICATION'])['application_name']")`

**Comment by nebhale** [comment]
@cgfrost You want to have a crack at this?

**Comment by cgfrost** [comment]
Hi,

It depends what context your setting it in, command line, application
manifest or hard coded in the config/java_opts.yml file. Give this a try,
from the applications manifest.

env:
  JAVA_OPTS: '-Dintroscope.agent.hostName=$(ruby -e "require ''json'' ;
puts JSON.parse(ENV[''VCAP_APPLICATION''])[''application_name'']")'

I haven't tested this but it follows from other examples that I know work.
If you're still having problems then let me know where your trying to set
the java opts from and I'll dig in a bit more.

This may be useful:
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-java_opts.md#escaping-strings

Chris.



Christopher Frost - Pivotal UK
Java Buildpack Team

**Comment by cgfrost** [comment]
Hi,

It depends what context your setting it in, command line, application
manifest or hard coded in the config/java_opts.yml file. Give this a try,
from the applications manifest.

```
env:
  JAVA_OPTS: '-Dintroscope.agent.hostName=$(ruby -e "require ''json'' ;
puts JSON.parse(ENV[''VCAP_APPLICATION''])[''application_name'']")'
```

I haven't tested this but it follows from other examples that I know work.
If you're still having problems then let me know where your trying to set
the java opts from and I'll dig in a bit more.

This may be useful:
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-java_opts.md#escaping-strings

Chris.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
