### ISSUE TITLE
Provision to add custom root certificates

### ISSUE THREAD

**Issue by skuppa** [cloudfoundry/java-buildpack#27]
I am looking for a way to import custom root certificates into JVM's castore.  Is there any convention or hook available to add these certificates?  If this is not available, I would like to add this feature.  There are couple option available,

Option 1: 
Have a new directory under java-buildpack, `java-buildpack/resources/certs` and user can place custom certificates under this resource directory.  During the compile time, these certificates will be imported into JVM's castore.  The disadvantage is, user needs to fork and add certificates and it is not best idea  to add certificates under SCM.  Also, not all application require the extra root certificates.

Option 2:
Application `MANIFEST`'s can specify the certs location.  After compilation, during release cycle the java-buildpack can read the file and import into JVMS's castore.  This is most preferred way since application can specify its custom root certificate if require.

BTW, I am looking information what is the difference between compile and release life cycle in `java-buildpack.`

Thanks,
-Sridharan

**Comment by martjarvi** [comment]
if the custom buildpack is referenced from private git repository behind self signed SSL, where to put the certificate so during staging CF will download the buildpack from custom repository?
like https://myrepo.internal/CF/javabuild-pack.git

thanks,
Mart

**Comment by gberche-orange** [comment]
An alternative is to have the Java application itself programmatically manage the key store. 

If this may help, we had developed a spring boot library at https://github.com/Orange-OpenSource/spring-boot-ssl-truststore-gen for doing this, before realizing this had also been done into https://github.com/pivotal-cf/cloudfoundry-certificate-truster (with a [different config mechanism](https://github.com/pivotal-cf/cloudfoundry-certificate-truster/issues/1) )

/CC @s-bortolussi

**Comment by allomov** [comment]
@gberche-orange is there a way to load client keys in the same way you do it with trusted keys, I need to use CA cert to authenticate BOSH and at the moment I put keystore to jar file and use custom buildpack, which doesn't seem right to me. Thank you!
