### ISSUE TITLE
How to set the port in a Vertx app?

### ISSUE THREAD

**Issue by jabrena** [cloudfoundry/java-buildpack#271]
Good morning,

I am doing a test with VertX app for Java and i would like to get the port for the environment.

How to do it?

``` java
package io.vertx.example;

import io.vertx.core.Vertx;

public class HelloWorldEmbedded {

  public static void main(String[] args) {
    // Create an HTTP server which simply returns "Hello World!" to each request.
    Vertx.vertx().createHttpServer().requestHandler(req -> req.response().end("Hello World!")).listen(8080);
  }

}

```

Source:
http://vertx.io/
https://github.com/vert-x3/vertx-examples/tree/master/maven-simplest
https://github.com/vert-x3/vertx-examples/blob/master/maven-simplest/src/main/java/io/vertx/example/HelloWorldEmbedded.java

How to set the port from CF for Java?

Many thanks in advance

Juan Antonio

**Comment by nebhale** [comment]
The port number is exposed with the `$PORT` environment variable.

**Comment by jabrena** [comment]
What is the syntax to get that variable in Java?

With Node.js the syntax would be:

``` js
console.log("VCAP_APP_PORT" + process.env.VCAP_APP_PORT)
console.log("PORT" + process.env.PORT) // Diego
```

Sorry, I a newbie developer with this buildpack.

Juan Antonio

**Comment by nebhale** [comment]
A [quick search](http://stackoverflow.com/search?q=java+environment+variables) should answer that question.

**Comment by jabrena** [comment]
Many thanks for the clue.

Fixed:

``` java
public class HelloWorldEmbedded {

	public static void main(String[] args) {

		int port = 8080;
		if(System.getenv("PORT") != null){
			port = Integer.parseInt(System.getenv("PORT"));
		}

    	// Create an HTTP server which simply returns "Hello World!" to each request.
    	Vertx.vertx().createHttpServer().requestHandler(req -> req.response().end("Hello World!")).listen(port);
	}

}
```
