### ISSUE TITLE
Proxy service

### ISSUE THREAD

**Issue by dhrapson** [cloudfoundry/java-buildpack#279]
Hi,
I'm considering implementing a service broker that provides the proxy details, as an alternative to the current environment variables method. It would allow for finer-grained way of setting proxy details i.e. by protocol, including FTP support, also potentially allows for provisioning a custom proxy server on-the-fly e.g. via a service broker, which is the main use-case I'm thinking of.

The logic would go something like:
- the buildpack would look for services with a certain pattern in its name e.g. proxy-service
- if it finds one the buildpack would use the credentials of the service instance to configure the proxy into the Java layer
- the credentials of a service instance would most likely include: protocol, proxy URL, nonProxyHosts

If I were to implement that as PR, is there a chance it would be accepted?

thanks
DHR

**Comment by nebhale** [comment]
What exactly do you have in mind by
> ... into the Java layer

In general yes I'm receptive to this, but the answer to that question would probably affect my response.  Also note, that depending on your reasoning for it, a service broker might not be required as user-provided services would be supported automatically.

**Comment by dhrapson** [comment]
Thanks for the quick response. By 'into the Java layer' I mean by the addition of Java system properties as defined in https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html 

e.g. for plain http: -Dhttp.proxyHost, -Dhttp.proxyPort, -Dhttp.nonProxyHosts

I agree that if the buildpack looked for specific credentials then it wouldn't matter if the action were provided by a brokered service instance or a UPS. The agreed set of credentials is akin to a contract for implementation. In my case I want to provision a proxy server, so I would opt for implementation as a service broker.

**Comment by nebhale** [comment]
@dhrapson I am definitely open to a PR around this.  Why don't you start by including an example credentials payload that covered the HTTP, HTTPS, FTP, and SOCKS proxies.  I'm leaning towards a nested design for each of those.

**Comment by dhrapson** [comment]
Sure. I'm not 100% certain I'll want to go through with this yet, hence the 'what do you think'-style question but... if I was going to then the credentials could look like:

```
credentials: {
  http {
    proxyHost: "",
    proxyPort: "",
    nonProxyHosts: ""
    ssl {
      proxyHost: "",
      proxyPort: ""
    }
  },
  ftp {
    proxyHost: "",
    proxyPort: "",
    nonProxyHosts: ""
  },
  socks {
    proxyHost: "",
    proxyPort: ""
  }
}

```
Questions: is this kind of nesting a good idea in credentials? Can the Spring Cloud Connectory libraries handle this nesting?

**Comment by nebhale** [comment]
There's a bit of redundancy in the listing (e.g. `host` obviously means proxy host), so maybe:

```json
"credentials": {
  "http": {
    "host" : "test-host-1",
    "port": 1234,
    "non-proxy-hosts": ["test-host-2", "test-host-3"]
  },
  "https": {
    "host" : "test-host-4",
    "port": 5678,
    "non-proxy-hosts": ["test-host-5", "test-host-6"]
  },
  "ftp": {
    "host" : "test-host-7",
    "port": 9012,
    "non-proxy-hosts": ["test-host-8", "test-host-9"]
  },
  "socks" : {
    "host" : "test-host-10",
    "port": 3456
  }
}
```

There is no problem with nesting values inside of these payloads.  Since they are represented as a string in a `bash` environment variable, it is up to each user of them to convert them from that string into an internal representation via a JSON transform.  In the case of the Java Buildpack, Ruby will trivially convert these from `string` to a `Hash` which can then be referenced via `credentials['https']['host']`.

Also, it's important to note that these values are never going to be interpreted by the Spring Cloud Connectors as the contents of them will be used by the buildpack, not in Java.

**Comment by dhrapson** [comment]
Thanks for your help. I'll submit the PR if this work goes ahead.

**Comment by nebhale** [comment]
@dhrapson Did anything ever come of this work?
