### ISSUE TITLE
Ruby 1.9.3-p551 is old and not secure

### ISSUE THREAD

**Issue by srbry** [cloudfoundry/java-buildpack#280]
Currently the java buildpack is hard coded against ruby 1.9.3-p551, this ruby version is end of maintenance. It also only supports TLSv1 and not the newer TLSv1.1 and TLSv1.2 standards could be considered a security concern. Especially as Ruby is used during the "DownloadCache" phase.

Can this be migrated to ruby 2.x?

**Comment by nebhale** [comment]
It cannot be migrated as the only version of Ruby available to buildpacks during staging is `1.9.3`.  You might want to open a discussion with @flavorjones in the [Cloud Foundry Slack](https://cloudfoundry.slack.com/messages/buildpacks/) about it.  We've been preparing for the move to a later version for a couple of years now, by [testing against three versions](https://github.com/cloudfoundry/java-buildpack/blob/master/.travis.yml#L2-L5).

**Comment by flavorjones** [comment]
Please note that the next cf-release is likely to contain Ruby 2.2 on the rootfs, as detailed here:

> https://github.com/cloudfoundry/stacks/issues/29

The latest version of the rootfs has actually already been released with this:

> https://github.com/cloudfoundry/stacks/releases/tag/1.42.0

Cheers,
-m
