### ISSUE TITLE
Tomcat External Configuration component needs repository_root property

### ISSUE THREAD

**Issue by violetagg** [cloudfoundry/java-buildpack#281]
Hi,

The recent commit 
https://github.com/cloudfoundry/java-buildpack/commit/086b8703fbeb95ce70f2e3ea8d2de2188757ec74
breaks the idea of providing a repository with an external Tomcat configuration.

We need to have

```
external_configuration:
  version: 1.+
  respository_root: ""
```

so that we are able to do

```
env:
  JBP_CONFIG_TOMCAT: "{ tomcat: { external_configuration_enabled: true }, external_configuration: { repository_root: \"http://repository...\" } }"
```

Currently if I provide that environment variable, I'll receive

```
WARN  User config value for 'repository_root' is not valid, existing property not present
```

Can you please take a look?

Thanks a lot,
Violeta

**Comment by nebhale** [comment]
Resolved by 2f71821
