### ISSUE TITLE
Dynatrace integration question

### ISSUE THREAD

**Issue by jgawor** [cloudfoundry/java-buildpack#282]
The initial commit for the Dynatrace integration (https://github.com/cloudfoundry/java-buildpack/commit/d7ca8cf9cc87daa56c18e78867c462dbd5d29e71) indicates there was no public repository available at that time. I think there might be one available now: http://downloads.dynatracesaas.com/. However, the `index.yml` piece still appears missing. So, wondering if that's something Pivotal can host or Dynatract needs to publish? Either way, this would definitely make things much easier to setup.

**Comment by akirasoft** [comment]
@jgawor I have submitted a pull request as we have added an index.yml to our public facing download location. 

Hoping it gets approved!

**Comment by jgawor** [comment]
@akirasoft Awesome. Thank you!

**Comment by nebhale** [comment]
Resolved by 630fe906cec23ac857539a5944d4312a435babc8
