### ISSUE TITLE
ease of JCE support

### ISSUE THREAD

**Issue by imod** [cloudfoundry/java-buildpack#283]
As we use spring cloud config (http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html) and want to enable encryption of passwords within the configurations. We need to install "JCE Unlimited Strength". 
Because of the licensing around this topic, it is not allowed to have a public repository with the required files. On the other hand, we need to fork the official repository and make it available so CLI can actually use the buildpack at installation time.
I'm also opening this issue because https://www.pivotaltracker.com/n/projects/788065/stories/116038779 does not allow me to give feedback or add comments on the same topic.

Any simplification on this topic would greatly be appreciated.

**Comment by nebhale** [comment]
@imod I've been chatting with @dsyer a bit about this problem today and wanted to gather some requirements.  Where exactly do you intend to do decryption of passwords; on the config server or on the config client?  Second, what did you have in mind for the JCE hosting?  If it isn't in a fork (which can be hosted internally, or built into an offline buildpack, neither of which require the problematic hosting of JCE bits in GitHub) where would you see getting the JCE bits from?

**Comment by imod** [comment]
In our case, the decryption of the passwords  is done on the config server only. 
For JCE hosting (just the additional files, not the whole JRE) I was thinking about a private git repo. Let me explain my use case:

We run our apps on a PaaS (https://console.pivotal.io and https://developer.swisscom.com) so its not an internal network. In such a case I would like to provide a URL to a protect git repo (on GitHub or Bitbucket) and have the buildpack download the required files from there - sure, this requires me to be able to pass credentials to access this repo in some secure way.

**Comment by nebhale** [comment]
Ah yes.  Then you're already in business.  CF supports URI credentials in git repos.  So you can push with either a `-b` or a manifest `buildpack` entry that looks like `https://<GH-USERNAME>:<GH-PERSONAL-ACCESS-TOKEN>@github.com/<org>/<private-fork>.git`.  Does that satisfy the requirement?

**Comment by imod** [comment]
I don't think so - i still have to fork the buildpack, right?

**Comment by nebhale** [comment]
Ah, I see.  So you want to use private GH repo to host the artifacts themselves.  Really what you're saying is that you want the JCE downloaded from a repository somewhere (our repository support handles credentialed URIs).  We're tossing that idea around and that's the lead alternative.

**Comment by imod** [comment]
Yeah, thats it.

**Comment by nebhale** [comment]
@imod Before I did the work of adding this, I went and had a chat with our export compliance officer.  Good thing I did because she informed me that we were clear to distribute JCE Unlimited Strength JRE builds.  So, as of last weekend there's now an `OpenJDK 1.8.0_91-unlimited-crypto` JRE available and all future builds will include it.  I'll cut a 3.7.1 release later this week with this included.

Is this a reasonable solution to your problem or would you still like me to add the repository functionality?

**Comment by imod** [comment]
@nebhale that's really good news! The problem is, that we currently run with the Oracle JRE. 
When we where running with the OpenJRE we had some problems with the MySQL Connection which all suddenly disappeared when we switched to the Oracle JRE. ...that's 1.5 years ago, maybe we should have an other go with it.

So yes, from my current position I would love to see this implemented...

**Comment by nebhale** [comment]
@imod Based on my understanding, the Oracle JRE comes with JCE unlimited built in.  Is this not correct?

**Comment by imod** [comment]
@nebhale no, unfortunate this is not the case and has to be configured as described here: https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-oracle_jre.md#configuration

**Comment by imod** [comment]
@nebhale is there any documentation about the integration of `OpenJDK 1.8.0_91-unlimited-crypto` available where these build are available?

**Comment by nebhale** [comment]
The `1.8.0_91-unlimited-crypto` build are [found in the normal repository](https://download.run.pivotal.io/openjdk/trusty/x86_64/index.yml) along with all [other releases](https://github.com/cloudfoundry/java-buildpack-dependency-builder#available-artifacts).  These artifacts can be found packaged in the [v3.7.1 release](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.7.1) and unlimited crypto builds will be created (but named in the normal way) for all subsequent Java releases.  These builds will be found in the repository, and packaged in subsequent Java Buildpack releases.

**Comment by imod** [comment]
sorry for the real dump question, but how do I now switch to ``?

I tried this in my `manifest.yml`:

`JBP_CONFIG_OPEN_JDK_JRE: '{jre: { version: 1.8.0_91-unlimited-crypto }}'`

...but it fails with:

```
Unable to find cached file for https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz
```

**Comment by nebhale** [comment]
@imod Offline buildpacks only package a single version of the JRE (and all dependencies) within them, otherwise they'd be pushing 4TB these days.  So, unless you are using the online buildpack, setting a JRE version isn't supported.  However, all JREs packaged since Java Buildpack 3.8.1 have been unlimited crypto, so using the JRE packaged in 3.12 should be fine.
