### ISSUE TITLE
Pivotal Java Build Pack with UnlimitedJCEPolicyJDK8 jars to support AES 256 bit

### ISSUE THREAD

**Issue by user554** [cloudfoundry/java-buildpack#292]
Java by default will support AES 128 byts key.  if we need AES 256 bit  to be created, 
in a non-paas environment, we manually replace local_policy.jar and US_export_policy.jar into the java path and make it work.

How this usecase works in PCF environment. Is Pivotal providing a built in java build pack with the above mentioned jars or do we need to create one custom build pack and use.?

**Comment by nebhale** [comment]
The proper way to add JCE unlimited encryption to the build pack is with a fork.  This is documented [here](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#jce-unlimited-strength).

**Comment by nebhale** [comment]
In addition, as of last weekend, all OpenJDK JREs provided in the Java Buildpack (both online and offline versions) contain JCE Unlimited.  A `v3.7.1` will be released shortly to include this in an offline buildpack, but it is available to online buildpacks through the standard repository mechanism today.
