### ISSUE TITLE
Not able to update metaspace configuration changes while using java-buildpack

### ISSUE THREAD

**Issue by rahulsrivastava71** [cloudfoundry/java-buildpack#293]
currently we are not able to change the metaspace memory configuration while deploying our apps, as earlier we were able to do that , so is there any changes that have been done in the java-buildpack.
This is a critical issue for us so please revert back.
Currently we are using 
`JBP_CONFIG_OPEN_JDK_JRE: '[memory_calculator: {memory_sizes: {stack: 1M, metaSpace: 64M, heap: 128M}}]'`
while increasing this metaspace value its not updating in cloud foundry.

**Comment by nebhale** [comment]
@rahulsrivastava71 I've just tested the latest version of the buildpack against PWS.  With no modifications and a 512M container, the following results came from staging, indicating a 64M `metaspace`.

```
-----> Java Buildpack Version: 78c3d0a | https://github.com/cloudfoundry/java-buildpack.git#78c3d0a
-----> Downloading Open Jdk JRE 1.8.0_91 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_91.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.1s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=64M -Xss995K -Xmx382293K -Xms382293K
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
```

Adjusting the `metaspace` memory size to 128M using the environment variable returns the expected adjustment.

```
$: cf set-env java-main-application JBP_CONFIG_OPEN_JDK_JRE '{memory_calculator: {memory_sizes: {metaspace: 128M..}}}'
Setting env variable 'JBP_CONFIG_OPEN_JDK_JRE' to '{memory_calculator: {memory_sizes: {metaspace: 128M..}}}' for app java-main-application in ...
OK
TIP: Use 'cf restage' to ensure your env variable changes take effect
$: cf restage java-main-application
Restaging app java-main-application in org ..
...
-----> Java Buildpack Version: 78c3d0a | https://github.com/cloudfoundry/java-buildpack.git#78c3d0a
-----> Downloading Open Jdk JRE 1.8.0_91 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_91.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.0s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xss853K -Xms320M -XX:MetaspaceSize=128M -Xmx320M -XX:MaxMetaspaceSize=128M
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
```

From our testing, it appears that the memory calculator configuration is working as expected.

**Comment by rahulsrivastava71** [comment]
As Ben can you confirm me that this is the latest buildpack for java , and we are using the configuration size for 1G container so it will reflect according to you in that case also.

**Comment by rahulsrivastava71** [comment]
Now i am able to update the metaspace and i guess there is some change in the variable name as first it was metaSpace and now it is metaspace, so might be this issue with latest java-buildpack

**Comment by Zteve** [comment]
@nebhale @rahulsrivastava71 I don't remember us ever calling it `metaSpace`, but it is possible that earlier versions were tolerant of mixed case variants. I know we are for the size units (`m` or `M`, &c.).
I'll leave it to @nebhale to check this.

**Comment by nebhale** [comment]
The problem wouldn't actually be in the memory calculator but rather in how the buildpack configuration is overridden.  The configuration environment variables are designed to only work when overriding existing keys.  There has never been a `metaSpace` key, so if it did work and no longer does, I'd consider that a bug fix.  We haven't done anything explicitly to make that change, but there have been a number of changes to the root filesystem that the buildpack runs in (notably an upgrade from Ruby 1.9 to Ruby 2.2).
