### ISSUE TITLE
java build pack issue while deploying stream with Groovy processor

### ISSUE THREAD

**Issue by sachkk76** [cloudfoundry/java-buildpack#298]
I have groovy transform app which uses groovy script, when deployed stream with this groovy transform module, getting below error - 

```
 ERR [Buildpack] ERROR Compile failed with exception # 
 [STG] ERR Application can be run by more than one container: Java Main, Spring Boot CLI 
 ERR Failed to compile droplet 
 [STG] OUT Exit status 223
 [STG] ERR Staging failed: Exited with status 2231
```

**Comment by nebhale** [comment]
The buildpack uses a collection of detection criteria to determine how to run a given application.  In cases where an application satisfies two different execution styles, an error is returned to prevent ambiguity.  You can take a look at the documentation for the [Java Main Application](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-java_main.md) and [Spring Boot CLI](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-spring_boot_cli.md) detection criteria to determine where your application overlaps.  Once you've determined that, you should update your application such that it is unambiguous how you'd like the application to execute.
