### ISSUE TITLE
"user.home" system property different from $HOME environment variable

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#300]
```
user.home=/var/vcap
HOME=/var/vcap/app
```

Any idea why these are different?  It is causing some issues for some of my users who try to add custom fonts to `user.home` instead of `HOME`.

I haven't had a chance to dig into it but thought I'd file the issue anyway.

**Comment by nebhale** [comment]
Wow, that is super weird.  Using our sample application on PWS, if you look at the [environment variables](http://ben-java-main-application.cfapps.io/environment-variables), `HOME` is `/home/vcap/app` (which matches `PWD`, possibly coincidently).  If you look at the [system properties](http://ben-java-main-application.cfapps.io/system-properties) `user.home` is `/home/vcap` (while `user.dir` is `/home/vcap/app`).  To make this even weirder, `ssh`-ing into the container and echoing `$HOME` results in `/home/vcap`.

Our command line doesn't set `$HOME` and it seems like everything matches as I'd except for the results of `System.getEnv("HOME")`.  Maybe Garden/Diego is doing something weird when it executes the process?  I just can't make sense of how Java gets the `HOME` environment with one value, but `user.home` with another.

**Comment by youngm** [comment]
I have bumped into this another time or 2 since I filed this issue.  One work around was to set the user.home system property via the command line.  If we don't get to the bottom of the cause doing that standard in the buildpack could be a possible workaround I suppose.

**Comment by youngm** [comment]
Also I can confirm that DEA and Diego behave the same.

**Comment by nebhale** [comment]
I'm in the UK at the moment, but when I'm back in SF next week, I'll have a chat with the Diego team and figure out if there's anything they're doing that might cause it.

**Comment by nebhale** [comment]
@youngm I really should look through backlogs more.  I've chatted with Diego, and cannot figure out why they'd be different sadly.  Want me to keep it open and keep working on it?

**Comment by youngm** [comment]
@nebhale If we cannot explain it perhaps we can just fix it?  Add a -Duser.home to startup?  Doesn't seem like a bad workaround.

**Comment by youngm** [comment]
Or maybe I'll just add it to my default java opts since it appears nobody else has noticed or cares. :)  I'll leave it up to you.  If you want to do the workaround then great.  Otherwise go ahead and close this and I'll just workaround it myself.  If I find a root cause I'll open another issue.

**Comment by nebhale** [comment]
An awesome suggestion.  As a note it looks like the buildpacks team is taking over "staging" from the Diego team (run the same way, but defining where and what happens).  The work planned for that (look out for the proposal) is likely to touch things around this.  We might "accidentally" fix it in the future.

**Comment by youngm** [comment]
With a little googling I found the root cause.  Looks like java gets that value from /etc/passwd.  I'll start a conversation with Diego/Garden and see what they think.  Thanks.
