### ISSUE TITLE
Add back the example for changing memory heuristics

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry/java-buildpack#301]
The example was removed in this commit but the preceding passage still mentions "adjust the memory heuristics" : https://github.com/cloudfoundry/java-buildpack/commit/01862708d9d3df35d5e3228a7cc72a0b2289eca9#diff-04c6e90faac2675aa89e2176d2eec7d8L32 

It would be helpful to include an example for this.

**Comment by dburkhalter-pivotal** [comment]
here is the one I am using for my spring boot apps in my manifest file (do not know if optimal but avois OOM exceptions on heap) : 
JBP_CONFIG_OPEN_JDK_JRE: '[jre: {version: 1.8.0_+}, memory_calculator: {memory_heuristics: {heap: 75, metaspace: 10, stack: 5, native: 10}}]'
