### ISSUE TITLE
Add Azul Zulu OpenJDK to java-buildpack

### ISSUE THREAD

**Issue by Ekaterina001** [cloudfoundry/java-buildpack#303]
Currently java-buildpack supports two vendors: Oracle and plane OpenJDK build. We suggest to add Zulu JRE as a third option. Zulu is a tested and certified build of OpenJDK, see  [zulu.org](http://zulu.org/) for more details.

**Comment by nebhale** [comment]
That's for the contribution.  We'll start reviewing shortly.
