### ISSUE TITLE
Certain umask settings will cause build pack build script to produce a broken build pack bundle

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/java-buildpack#304]
Steps to recreate:
1. Set umask to `0027`
2. Run `git clone https://github.com/cloudfoundry/java-buildpack`
3. Run `bundle exec rake package OFFLINE=true version=v3.8`
4. Run `cf create-buildpack java_buildpack_test build/java-buildpack-offline-7a37ff3.zip 9 --enable`
5. Run `cf push spring-music -b java_buildpack_test`.

Output:

```
Downloading java_buildpack_test...
Downloaded java_buildpack_test (264.1M)
Creating container
Successfully created container
Downloading app package...
Downloaded app package (21.1M)
Staging...
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
```

Seems like a permissions issue on the `bin/*` scripts.  Can the build pack build scripts force permissions to 755 for those scripts?

**Comment by nebhale** [comment]
Grumble, grumble.  Yeah, we can do it.  Not a huge priority, as I think it's a reasonable expectation that you clone the repository with the permissions checked into source control, but I'll add it to the backlog.

**Comment by nebhale** [comment]
https://www.pivotaltracker.com/story/show/124698691
