### ISSUE TITLE
Tweak log output to highlight important messages

### ISSUE THREAD

**Issue by C-Otto** [cloudfoundry/java-buildpack#305]
When pushing a Java application using the buildpack, I see many messages that contain little (new) information:

```
-----> Java Buildpack Version: v3.8 | https://github.com/cloudfoundry/java-buildpack.git#0837bc3
-----> Downloading Open Jdk JRE 1.8.0_91-unlimited-crypto from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (2.0s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
[...]
```

However, in between there may be more important messages, like the following:

```
       There is more than 3 times more spare native memory than the default so configured Java memory may be too small or available memory may be too large
       Memory Settings: -Xss500K -Xms500M -XX:MetaspaceSize=100M -Xmx500M -XX:MaxMetaspaceSize=100M
```

It is hard to see this, and I think it is even harder to implement corresponding parsers.

I propose to re-format the log messages, possibly by re-routing more important messages to STDERR.

**Comment by nebhale** [comment]
Seems like a reasonable requirement.  We've just added another warning (#370) and will do the same when we update the memory calculator next.

**Comment by nebhale** [comment]
It turns out that this specific message is now obsolete.  A change was made to staging and now we can't tell what size will be available to runtime and therefore, running the memory calculator during staging doesn't actually generate a useful warning (`MEMORY_LIMIT` is always `1024M`).  I've removed the check since it doesn't matter, and will consider this closed.

**Comment by C-Otto** [comment]
@nebhale my comment wasn't concerning this particular messages, but important messages in general. If there are messages of similar importance, please re-open this issue.
