### ISSUE TITLE
Change in set-env functionality

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/java-buildpack#308]
This potential change in SCDF (https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/pull/132/files) was sparked when an update to JBP (https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/17dbf82658ff647c7bcd45a20194fc33700fda2e) appeared to allow the use of `lower.case` rather than `UPPER_CASE`. This may have been a coincidence and it has always been possible, but it would be worth investigating whether a change (perhaps https://github.com/cloudfoundry/java-buildpack/commit/727006ba288d238a481e16c23cdf1f9d6ffe0228) is now letting things through that were disallowed previously.

**Comment by nebhale** [comment]
The enforcement of environment variable naming structure is done by Diego and Garden, not by the buildpack.  Therefore the change that now allows this, is not related to any change in the buildpack.
