### ISSUE TITLE
///dev/urandom

### ISSUE THREAD

**Issue by ankursri1** [cloudfoundry/java-buildpack#309]
My Team is working on open source Cloud Foundry, and we are facing a challenge in here. We had successfully installed CFv237 on Openstack “Liberty”. After installation we have ran CF acceptance test given at https://github.com/cloudfoundry/cf-acceptance-tests .

The test results were fine. 

Problem we are facing: When we are pushing the application with default build pack or https://github.com/cloudfoundry/java-buildpack, then sometime it start properly and sometimes it fails. We searched for the problem and we are getting a resolution to use below parameter and after that application starts properly but faces one problem of high CPU usage.

JAVA_OPTS: -Djava.security.egd=file:///dev/urandom 

Secondly, we are seeing very high CPU usage after pushing the application with or without the above parameter.

Please give your suggestion on the given issue  we are facing.

What is the stable version of Cloud Foundry we should use?

Regards,
Ankur Srivastava.

**Comment by nebhale** [comment]
The change to `/dev/urandom` only solves the problem of slow start up on systems where entropy is slow on constrained.  It does not solve any issues related to CPU usage. As there is great debate on whether using `/dev/urandom` is safe, I do not recommend using it unless you are specifically solving that issue.  The [`cf-dev` list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/) is the appropriate place to ask about stable versions of CF.
