### ISSUE TITLE
Document how to (or implement) force HTTPS

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/java-buildpack#310]
Especially with some of the app servers (e.g. tomcat) a simple way to redirect all traffic to HTTPS is currently missing from the documentation. Ideally it would be even better to have a simple configuration switch that users can simply toggle to force all traffic to HTTPS.

From a cursory survey of the first google results it looks like we could build something off http://stackoverflow.com/a/6643306/414813

**Comment by send2r** [comment]
Is there really a simple way? We had to edit server XML on build pack to just block HTTP. Of course we could use some tricks in Web XML - however all those looked so out of place to me. Ideally we should be able to quickly configure these : HTTPS only, allowed http methods ( and other basic owasp recommended config)

**Comment by CAFxX** [comment]
Edited my initial post with a link to a possible lead for a solution

**Comment by send2r** [comment]
Thanks; and yes as I mentioned, 

> We had to edit server XML on build pack to just block HTTP

but it became an overhead to maintain that build pack and we had to finally give up and do everything in code/interceptors. If a deployment manifest entry could facilitate this, that will be super.

**Comment by nebhale** [comment]
As you can see we do actually [automatically add the `RemoteIpValve`](https://github.com/cloudfoundry/java-buildpack/blob/master/resources/tomcat/conf/server.xml#L24) already to handle the routing of secure requests to the containers.  In fact, the typically behavior of CF is terminate SSL at the routing layer and forward non-encrypted requests to the containers themselves.  Enforcement of "always SSL" policies are best enforced there.

**Comment by wildloop** [comment]
`java_buildpack` / tomcat configuration is ready to force HTTPS (check it: `cat /home/vcap/app/.java-buildpack/tomcat/conf/server.xml | grep x-forwarded-proto`).

The only thing you have to do is add `security-constraint` to your app `web.xml`:
```xml
<security-constraint>
    <web-resource-collection>
        <web-resource-name>Protected Context</web-resource-name>
        <url-pattern>/*</url-pattern>
    </web-resource-collection>
    <user-data-constraint>
        <transport-guarantee>CONFIDENTIAL</transport-guarantee>
    </user-data-constraint>
</security-constraint>
```
https://docs.oracle.com/cd/E19798-01/821-1841/bncbk/index.html
> Specify `CONFIDENTIAL` when the application requires that data be transmitted so as to prevent other entities from observing the contents of the transmission.

**Comment by b10s** [comment]
@wildloop thank you for the solution.

In case CF deployment has separate Load Balancer which does TLS termination, my app will infinitely response with 302 since app at the very end receives pure http without s.

However we can identify was there https with s or not by examine the X-Forwarded-Proto header.

The request's way:

**user** <--https--> **Load Balancer** <--http--> **go based http server (gorouter)** <--http--> **our own nginx on the same VM** <--http--> **java app**


Could you share how can we force https in such case?
