### ISSUE TITLE
Jar size is twice what it should be on upload

### ISSUE THREAD

**Issue by MTyson** [cloudfoundry/java-buildpack#311]
I have a standalone jar with deps that on disk is around 26 megs:

`-rw-r--r--    1 Matt     Administ 26066171 Jul 18 17:54 new-app-1.0.0.jar`

However, when I go to upload, the size has exploded to 56 megs:

```
Uploading app files from: target\new-app-1.0.0.jar
Uploading 52.5M, 17765 files
```

Is the build_pack or CF actually unpacking the jar to upload it?  Or am I missing something else?

**Comment by nebhale** [comment]
The CLI unpacks and does resource matching against the items within a JAR before uploading. If you're seeing an issue with that behavior, your best bet is to [open an issue there](https://github.com/cloudfoundry/cli/issues).
