### ISSUE TITLE
Update New Relic Agent dependency for security vulnerability 

### ISSUE THREAD

**Issue by scurry** [cloudfoundry/java-buildpack#315]
JBP current NR agent is 3.30.  Need to update to 3.30.1 for security issue. 

See https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3301-1 for details.

**Comment by nebhale** [comment]
Not only is 3.30.0 [available](https://java-buildpack.cloudfoundry.org/new-relic/index.yml), 3.31.0 is ready to go as well.

**Comment by clhynfield** [comment]
https://github.com/cloudfoundry/java-buildpack-dependency-builder/commit/8795a7e169b36797b07f99043dd561b00ca23039 updates the NR dependency, @scurry. Shouldn't be long now!
