### ISSUE TITLE
memory allocation issue

### ISSUE THREAD

**Issue by stavsap** [cloudfoundry/java-buildpack#318]
-----> Java Buildpack Version: 4c1e853 | https://github.com/cloudfoundry/java-buildpack.git#4c1e853
-----> Downloading Open Jdk JRE 1.8.0_91-unlimited-crypto from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz (6.2s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (0.9s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (0.6s)
       Cannot balance memory: Memory allocation failed for configuration: [stack:228K.. metaspace:64M..], : memory exceeded
[Buildpack]                      ERROR Compile failed with exception RuntimeError
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

it worked till today, then this issue started, can't find more information about this

**Comment by nebhale** [comment]
Have you successfully updated your application to handle the new memory calculation behavior?

**Comment by stavsap** [comment]
nope, don't use it anymore...

**Comment by nebhale** [comment]
Thanks for the update.
