### ISSUE TITLE
cf set-env JBP_CONFIG_OPEN_JDK_JRE '{jre: { version: 1.7.0_40 }}' failing

### ISSUE THREAD

**Issue by praveenponaganti** [cloudfoundry/java-buildpack#321]
My java app is running with java build pack with jre 1.8.0_71

When I set it jre 1.7 like   `cf set-env supplier  JBP_CONFIG_OPEN_JDK_JRE '{jre: { version: 1.7.0_40 }}'`
getting the following error.

```
Staging...
-----> Java Buildpack Version: v3.6 (offline) | https://github.com/cloudfoundry/java-buildpack.git#5194155
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Unable to find cached file for https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_40.tar.gz>
Unable to find cached file for https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_40.tar.gz
Failed to compile droplet
-----> Downloading Open Jdk JRE 1.7.0_40 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.7.0_40.tar.gz Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container
```

**Comment by nebhale** [comment]
You're using the offline buildpack.  That buildpack only packages the "latest" version of all of it's dependencies, which for [v3.6](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.6) was OpenJDK `1.8.0_71`.  You are configuring your application to use a version of Java 7, which is not packaged in that version of the buildpack, and offline buildpacks do not download from the internet which is causing the failure.  You need to either use the online version of the buildpack which can download [many versions](https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/index.yml) of the JRE or package your own version of the buildpack that contains the dependencies you need.

**Comment by praveenponaganti** [comment]
Thanks nebhale. your suggestion helped me.
