### ISSUE TITLE
Spring Boot 1.3.x incompatibility with latest Java Buildpack (currently Version: 5697f96)

### ISSUE THREAD

**Issue by poprygun** [cloudfoundry/java-buildpack#323]
Getting `ERR Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger`
deploying Spring Boot 1.3.5 app to PCF ERT 1.7.  Had to upgrade to SB 1.4 to fix the error.  Upgrading SB in sync with JBP might not be a possibility for some customers.

**Comment by nebhale** [comment]
Can you please post the rest of the stack trace?  I'd like to get an idea where in the code this class is being read.

**Comment by nebhale** [comment]
@awilkinson Is this an issue that's been reported before?  I'd wait for more information before you go looking for a bug.

**Comment by nebhale** [comment]
@poprygun I just pushed an application created by the Spring Initializr using Spring Boot 1.3.5.  You can find the source code for that application [here](https://github.com/nebhale/spring-boot-1.3-demo).  There were no problems during with staging or the startup.  As you can see, the same version of the buildpack was used:

```
Staging...
-----> Java Buildpack Version: 5697f96 | https://github.com/cloudfoundry/java-buildpack.git#5697f96
-----> Downloading Open Jdk JRE 1.8.0_91-unlimited-crypto from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz (0.5s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.1s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (0.0s)
       Memory Settings: -XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (0.0s)
```
