### ISSUE TITLE
App staging failed in the buildpack compile phase

### ISSUE THREAD

**Issue by patel1105** [cloudfoundry/java-buildpack#325]
**started to get below errors today.**

```
staging: -----> Java Buildpack Version: 1447aa9 | https://github.com/cloudfoundry/java-buildpack.git#1447aa9
staging: [Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Open Jdk JRE error: No version resolvable for '1.8.0_10+' in 1.7.0_01, 1.7.0_02, 1.7.0_03, 1.7.0_04, 1.7.0_05, 1.7.0_06, 1.7.0_07, 1.7.0_08, 1.7.0_09, 1.7.0_10, 1.7.0_11, 1.7.0_12, 1.7.0_13, 1.7.0_14, 1.7.0_15, 1.7.0_17, 1.7.0_21, 1.7.0_25, 1.7.0_40, 1.7.0_45, 1.7.0_51, 1.7.0_55, 1.7.0_60, 1.7.0_65, 1.8.0_00, 1.8.0_05, 1.8.0_11, 1.8.0_20, 1.8.0_M6, 1.8.0_M7, 1.8.0_M8, 1.8.0_RC1, 1.8.0_25, 1.7.0_71, 1.8.0_31, 1.7.0_75, 1.8.0_40, 1.8.0_45, 1.7.0_79, 1.8.0_51, 1.8.0_60, 1.8.0_65, 1.8.0_71, 1.8.0_73>
staging: Open Jdk JRE error: No version resolvable for '1.8.0_10+' in 1.7.0_01, 1.7.0_02, 1.7.0_03, 1.7.0_04, 1.7.0_05, 1.7.0_06, 1.7.0_07, 1.7.0_08, 1.7.0_09, 1.7.0_10, 1.7.0_11, 1.7.0_12, 1.7.0_13, 1.7.0_14, 1.7.0_15, 1.7.0_17, 1.7.0_21, 1.7.0_25, 1.7.0_40, 1.7.0_45, 1.7.0_51, 1.7.0_55, 1.7.0_60, 1.7.0_65, 1.8.0_00, 1.8.0_05, 1.8.0_11, 1.8.0_20, 1.8.0_M6, 1.8.0_M7, 1.8.0_M8, 1.8.0_RC1, 1.8.0_25, 1.7.0_71, 1.8.0_31, 1.7.0_75, 1.8.0_40, 1.8.0_45, 1.7.0_79, 1.8.0_51, 1.8.0_60, 1.8.0_65, 1.8.0_71, 1.8.0_73
staging: Staging failed: Buildpack compilation step failed
```

**Comment by nebhale** [comment]
Do you have a replicated internal repository?  If so, it's not up to date with the main repository which now contains `1.8.0_101`.

**Comment by patel1105** [comment]
We are pointing directly to cloudfoundry buildpack git url.

**Comment by nebhale** [comment]
Yes, you are downloading the buildpack itself from the GitHub url, however, the dependencies added to applications by the buildpack are downloaded from elsewhere.  The buildpack looks to a repository for indexes.  Those indexes offer versions and download URIs that the buildpack then chooses from using wildcarding.  Given the list of OpenJDK versions in your error message, it doesn't appear that you're looking at the [public repository](https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/index.yml).  Given that, I'd assume that you're using a cached copy of the repository (configured with an environment variable possibly) that is returning an outdated version of the OpenJDK index.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by neenika** [comment]
I am facing the same issue. Could you please provide the steps to resolve the issue as the issuer did not reply back on this?

**Comment by nebhale** [comment]
@neenika If i had to guess, you're using the buildpack with a `precise` based stemcell.  This is not a supported Cloud Foundry stemcell and the buidlpack may not (and in this case, does not) work with it.

**Comment by neenika** [comment]
Hi nebhale, thanks for the comment.
Actually I have now removed the buildpack entry from manifest.yml file and successfully deployed the services.
I dont know whats happening if I use https://github.com/cloudfoundry/java-buildpack. I hope it is referring to some old release?

**Comment by nebhale** [comment]
@neenika Your problem is the exact reverse of that.  The GitHub URI refers to the absolute latest, most up to date, and safest version of the buildpack.  When you remove it, you refer to the version shipped as part of your platform, which is none of those things.  The version that shipped with your platform unintentionally worked with the `precise`-based stemcell you're deploying on and we've made changes to the latest versions of the buildpack that now prevent that from happening.

**Comment by tejasmulay** [comment]
Hi @nebhale , I am also facing this issue. Can you provide a solution? We are blocked.
