### ISSUE TITLE
About deployment issue with libjvmkill.so

### ISSUE THREAD

**Issue by llv22** [cloudfoundry/java-buildpack#334]
Dear colleagues:

I use replace-killjava-script-with-jvmkill-agent-114796351 branch in my manifest.yml to deploy service to my cloud foundry envrionment.

for my understanding, in ruby https://github.com/cloudfoundry/java-buildpack/blob/replace-killjava-script-with-jvmkill-agent-114796351/lib/java_buildpack/jre/jvmkill_agent.rb here, you add 

 # (see JavaBuildpack::Component::BaseComponent#release)
      def release
        @droplet.java_opts.add_agentpath_with_props(jvmkill_agent, 'printHeapHistogram' => '1')
      end

so libjvmkill.so has been registered to JVM as agentlibrary.

I read carefully your implemnetation in https://github.com/cloudfoundry/jvmkill.
this so library could be registered with count=2,time=10, printHeapHistogram=1.
in my customized branch https://github.com/llv22/java-buildpack/blob/jvmkill-agent-114796351/lib/java_buildpack/jre/jvmkill_agent.rb, 
I add those two parameters.

However, during startup of service via this buildpack, I met with issue:
016-09-30T17:10:58.17+0800 [DEA/1]      OUT Starting app instance (index 0) with guid 51f8111b-020e-4077-8798-7bd8eda99462
2016-09-30T17:11:02.16+0800 [App/0]      ERR Unknown suboption 'printHeapHistogram=1'
2016-09-30T17:11:02.93+0800 [App/0]      OUT [CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Initializing ProtocolHandler ["http-nio-61758"]

for my understanding, in https://github.com/cloudfoundry/jvmkill/blob/master/parametersparser.c, it's design to check parameters, and deployment parameters as follow:

App hybris-dmemorydump-v1 was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.2_RELEASE -memorySizes=metaspace:64m..,stack:228k.. -memoryWeights=heap:65,metaspace:10,native:15,stack:10 -memoryInitials=heap:100%,metaspace:100% -stackThreads=300 -totMemory=$MEMORY_LIMIT) &&  JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR $CALCULATED_MEMORY -agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.0.2=printHeapHistogram=1 -Djava.endorsed.dirs=$PWD/.java-buildpack/tomcat/endorsed -Daccess.logging.enabled=false -Dhttp.port=$PORT" exec $PWD/.java-buildpack/tomcat/bin/catalina.sh run`

I think it shouldn't give such error in 

Showing health and status for app hybris-dmemorydump-v1 in org cec-prod / space ic as team-cecenter@sap.com...
30-Sep-2016 11:11:14	OK
30-Sep-2016 11:11:14	
30-Sep-2016 11:11:14	requested state: started
30-Sep-2016 11:11:14	instances: 1/1
30-Sep-2016 11:11:14	usage: 512M x 1 instances
30-Sep-2016 11:11:14	urls: hybris-dmemorydump-v1.us-east.internal.yaas.io
30-Sep-2016 11:11:14	last uploaded: Fri Sep 30 09:10:25 UTC 2016
30-Sep-2016 11:11:14	stack: cflinuxfs2
30-Sep-2016 11:11:14	buildpack: https://github.com/llv22/java-buildpack.git#jvmkill-agent-114796351

the library is downloaded from 

	-----> Downloading Jvmkill Agent 1.0.2 from https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/jvmkill-1.0.2.so (found in cache)

@glyn  could you take a look for this issue?

**Comment by llv22** [comment]
@glyn the error stack is cflinuxfs2, I also tested locally in my ubuntu environment.

**Comment by glyn** [comment]
I did introduce a bug into jvmkill [here](https://github.com/cloudfoundry/jvmkill/commit/e358c3f9cca184f8fcbdcd58e4bdb2b67bb951dc#diff-e16c0e8d104b51151746f9cf74168978R107) which would cause it to fail if unrecognised parameters are provided (printHeapHistogram is not yet supported in the version of jvmkill that is available for use with the Java buildpack). It should issue a warning instead and this has now been fixed. So I'm wondering if you somehow picked up this intermediate version with the bug.

But jvmkill 1.0.2 _should_ ignore the option.

Anyway, one workaround would be to avoid setting the option by forking the buildpack.

I work on the Java buildpack on Mondays, so please let me know by then how you get on.

**Comment by llv22** [comment]
@glyn I wonder if I can build jvmkill1.10 or master for ubuntu (cflinux) and store this so into my forked branch. then change the downloaded link in java buildpack just for jvmkill library.
As we really need to understand how heap/stack look like for identfing the root cause on our running cf system.

**Comment by glyn** [comment]
Yes, that should be possible. In the past, we've used public Dropbox to store index files and downloads and then pointed a fork of the buildpack at that location.

**Comment by glyn** [comment]
@llv22 Can this issue now be closed?

**Comment by llv22** [comment]
Hi @glyn, thanks for reminder. Already integrated with my project, ^_^
