### ISSUE TITLE
Buildpack can't decide how to launch my Boot app if it has a CRaSH groovy command

### ISSUE THREAD

**Issue by gregturn** [cloudfoundry/java-buildpack#335]
I created a Spring Boot application that included `spring-boot-starter-remote-shell` and a Groovy command found in src/main/resource/commands.

When I built and pushed to PWS, the buildpack couldn't decided if this a Java Main or a Spring Boot CLI app.

Can we tip the buildpack to NOT consider it a Spring Boot CLI app if the only Groovy files are found in src/main/resources/commands?

**Comment by nebhale** [comment]
Having Groovy files isn't sufficient to cause the ambiguity.  You'd need those Groovy files to have some other [specific attributes](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-spring_boot_cli.md).  Any idea which of the criteria your Groovy files meet?

**Comment by gregturn** [comment]
Heh. Reading the criteria list, it appears my code hits ALL of them. Here it is:

```
package commands

import org.crsh.cli.Command
import org.crsh.cli.Man
import org.crsh.cli.Usage
import org.crsh.command.InvocationContext
import org.springframework.beans.factory.ListableBeanFactory
import org.springframework.boot.actuate.endpoint.MetricsEndpoint
import org.springframework.boot.actuate.health.HealthIndicator

@Usage("Various commands to interact with Spring-a-Gram")
class springagram {

	@Usage("Print out Spring-a-Gram metrics")
	@Man("Iterate over all metrics")
	@Command
	void metrics(InvocationContext context) {
		ListableBeanFactory beanFactory =
				context.attributes['spring.beanfactory']

		beanFactory.getBeansOfType(MetricsEndpoint).each {
			name, metrics ->
				metrics.invoke().each { k, v ->
					out.println "${k} is at ${v}"
				}
		}
	}

	@Usage("Take a health check")
	@Man("Exercise all the health indicators")
	@Command
	void health(InvocationContext context) {
		ListableBeanFactory beanFactory =
				context.attributes['spring.beanfactory']

		beanFactory.getBeansOfType(HealthIndicator).each {
			name, healthIndicator ->
				def health = healthIndicator.health()
				out.println "${name} ... ${health.status} (${health.details})"
		}
	}

}
```
As can be clearly seen:

* It's a groovy file.
* It's a class (POGO).
* No main().
* No shebang.
* No WEB-INF folder.

If you feel like being listed inside `BOOT-INF`/classes/commands` like this:
```
  1185 Mon Oct 03 12:38:04 CDT 2016 BOOT-INF/classes/commands/springagram.groovy
```
...isn't specific enough of a signal, perhaps you could exclude on the criteria that it:

* has org.crsh imports
* has at least one `@Command` method
* ??

Thoughts?

**Comment by CalamarBicefalo** [comment]
As a related question is it possible at all to deploy in PCF a spring boot web app that also has CRASH (CLI) built in?

**Comment by nebhale** [comment]
@gregturn The problem with excluding the paths that Boot will look for commands in, is that they've changed in the past (1.3 to 1.4 with the addition of `BOOT-INF`) and could again in the future.  In fact, we were so concerned with the addition of `BOOT-INF` this time around, that we required Spring Boot to put a manifest entry in the JAR to tell us where things were.  This falls afoul of the same issue. On top of that, users can configure that location further hosing us.

So we need to find a better way to exclude them than what we've got so far.

**Comment by CalamarBicefalo** [comment]
@nebhale isn't good enough then as @gregturn said to look for crash import (or/and) a @command annotation? 

It's a bit of a shame but we can't deploy crash custom commands within our app.

**Comment by nebhale** [comment]
@CalamarBicefalo The problem is where to look for those to black list them.  You can't do a blanket exclusion of those things because one file that looked like that, sitting in the root of the filesystem, is a legitimate Spring Boot CLI application.

**Comment by CalamarBicefalo** [comment]
I understand @nebhale, I am wondering though, do I have some possibility then to tell the buildpack manually that it is not a cli app so I can deploy in CF? Or am I forced to remove crash altogether?

**Comment by nebhale** [comment]
@CalamarBicefalo Until we come up with a heuristic that is both exclusive and non-ambiguous no the application won't start.  There buildpack is designed to be very, very conservative about this so that there is never _any_ surprise about how an application is run.

**Comment by CalamarBicefalo** [comment]
@nebhale Mmm then we could argue that the spring boot cli heuristic is neither exclusive nor non ambiguous.

**Comment by nebhale** [comment]
Actually it is.  The fact that either Spring Boot CLI and Spring Boot startup at all means that they're non-overlapping.  When presented with an application that overlaps and there is ambiguity we do not start.  This is conservative behavior in the face of unknown applications, and we have in the past, and will in the future refine the heuristic to allow more applications to run without ambiguity.

**Comment by CalamarBicefalo** [comment]
That makes sense, I find difficult to understand why me as a developer cannot override the heuristic mechanism to resolve this ambiguity. But I now understand your concerns.

**Comment by CalamarBicefalo** [comment]
What about excluding the cli buildpack if ALL the groovy files reference crash @nebhale?

**Comment by gregturn** [comment]
@nebhale Can we at least have a manual switch on the buildpack so I can overrode the ambiguity?

**Comment by CalamarBicefalo** [comment]
Ey @gregturn, I workarounded this by using Java classes rather than groovy files. It's not ideal but at least it works and anyway there is not much movement with the issue...

**Comment by gregturn** [comment]
@nebhale Given the future of crashub and Spring Boot, I'm withdrawing this request.
