### ISSUE TITLE
Recursive unzip fails with jar in BOOT-INF/classes/

### ISSUE THREAD

**Issue by sleighsoft** [cloudfoundry/java-buildpack#340]
I have bundled a directory in `/BOOT-INF/classes/` which contains a `.jar` file.  
When pushing to cloudfoundry it tries to run `unzip -qq` on that jar and fails with
```
error [/tmp/app/BOOT-INF/classes/mylib/xalan-2.7.0.jar]:  missing 3258220029 bytes in zipfile
  (attempting to process anyway)
  appropriate BINARY mode and that you have compiled UnZip properly)
error [/tmp/app/BOOT-INF/classes/mylib/xalan-2.7.0.jar]:  attempt to seek before beginning of zipfile
```

I do not want those jar files to be unzipped.

**Comment by nebhale** [comment]
Can you give a bit more of the error trace for this?  We do unzip files in some of the framework components, but those are typically done with very explicit paths of files downloaded for each component.

**Comment by sleighsoft** [comment]
The bundled jar contains the following files (spring boot project):
```
BOOT-INF
|---classes
    |---application.properties
    |---mylib
        |---xalan-2.7.0.jar
|---lib
META-INF
org
```
During unpacking on the server it will try to unzip `xalan-2.7.0.jar`. But I need that file as a jar in order for other parts of my application to work.
Therefore I would like to exclude `mylib` from the unzipping.

**Comment by nebhale** [comment]
I don't understand what "during unpacking on the server" means.  The buildpack doesn't unpack applications, they are presented to the buildpack already exploded.  I'm looking for the output from the staging process as printed by the CLI, something like:

```
$: cf restage java-main-application
Restaging app java-main-application in org bhale / space development as bhale@pivotal.io...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (21.4M)
Downloading build artifacts cache...
Downloaded build artifacts cache (167.5M)
Staging...
-----> Java Buildpack Version: v3.8.1 | https://github.com/cloudfoundry/java-buildpack.git#7f47ec2
-----> Downloading Open Jdk JRE 1.8.0_91-unlimited-crypto from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.0s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
Exit status 0
Staging complete
```

**Comment by sleighsoft** [comment]
I think I found one of the bugs. Which is not related to cf at all. When maven copies the jar to the directory I had filtering set to true which corrupts the jar.
I will check if that makes it work.

**Comment by nebhale** [comment]
I would still be interested in determining which component in CF is trying to unzip the file in the first place.

**Comment by sleighsoft** [comment]
This is part of the output of cf push.
```
Downloading staticfile_buildpack...
Downloading php_buildpack...
Downloaded ruby_buildpack
Downloading go_buildpack...
Downloaded staticfile_buildpack
Downloaded php_buildpack
Downloaded nodejs_buildpack
Downloaded go_buildpack
Downloaded dotnet_core_buildpack_beta
Creating container
Successfully created container
Downloading app package...
Downloaded app package (183.4M)
Staging...
error [/tmp/app/BOOT-INF/classes/mylib/xalan-2.7.0.jar]:  missing 3258220029 bytes in zipfile
  (attempting to process anyway)
  appropriate BINARY mode and that you have compiled UnZip properly)
error [/tmp/app/BOOT-INF/classes/mylib/xalan-2.7.0.jar]:  attempt to seek before beginning of zipfile
```

**Comment by sleighsoft** [comment]
Ok, removing the filtering fixed that issue.

**Comment by nebhale** [comment]
So that's not conclusively the Java Buildpack involved (as it's not in that list).  Can you please run the push again (with the faulty JAR file) with `-b https://github.com/cloudfoundry/java-buildpack.git` and see if you get the same result?

**Comment by sleighsoft** [comment]
That still fails. It runs the build pack only after the error occurred.
```
ctory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
-----> Java Buildpack Version: 9bab398 | https://github.com/cloudfoundry/java-buildpack.git#9bab398
```

**Comment by nebhale** [comment]
Right, so that seems like CF itself, not the buildpack is at fault there.  If you're still concerned after you've fixed the filtering problem, you can [open an issue against the cloud controller](https://github.com/cloudfoundry/cloud_controller_ng/issues).
