### ISSUE TITLE
Server sent events buffered in cloud

### ISSUE THREAD

**Issue by athulrajeev** [cloudfoundry/java-buildpack#353]
Hi I am trying to get the server sent event in my spring boot app up and running in cloud. The current behavior is the proxy-server is buffering all the events and pushing it to the client after all the events are complete. It is behaving like a typical HTTP GET call.

What I suspect is proxy_buffering is on for the proxy server. Is there any way to turn of the proxy_buffering

**Comment by nebhale** [comment]
The buildpack doesn't include a proxy, so this is likely not the appropriate location to discuss this issue.

**Comment by athulrajeev** [comment]
Thanks Ben
