### ISSUE TITLE
problem about java-buildpack with jdk1.6

### ISSUE THREAD

**Issue by jiheyangying** [cloudfoundry/java-buildpack#354]
I try to create a java-buildpack with jdk1.6 and tomcat7. When i push an application to platform, i got an error with : "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout". I follow the solution page (https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#managing-entropy) and config the entropy source with "-Djava.security.egd=file:/dev/./urandom",but it does not work.....
So could any cloudfoundry professor give me some help? I search github about java-buildpack, and got the  earliest buildpack with jdk 1.7 , does cloud foundry support jdk1.6?  Thank you!

**Comment by nebhale** [comment]
We do not support Java 1.6 as it has been EOL for years and has a ton of security vulnerabilities in it.
