### ISSUE TITLE
Configurable memory heuristics values

### ISSUE THREAD

**Issue by sivabalans** [cloudfoundry/java-buildpack#361]
We have hit situations in our cloudfoundry java deployments where we need to allocated more metaspace or native memory to the app  than what is allocated by the memory allocator using the memory heuristics in open_jdk_jre.yml. I am aware than I can customize the buildpack, change the values and use that in my deployment. But to prevent maintaining custom buildpacks, I was wondering if there is a way to parameterize these values under "memory_heuristics" so it can be set in manifest.yml or using set-env or passed during "cf push" command.

**Comment by nebhale** [comment]
All configuration can be overridden using environment variables as described in the [Configuration and Extension](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension) section of the README.  This includes the `memory_heuristics` using something like `JBP_CONFIG_OPEN_JDK_JRE: '{memory_calculator: {memory_heuristics: {heap: 75, metaspace: 10, stack: 5, native: 10}}}'`
