### ISSUE TITLE
Ratpack distZip won't deploy because of ambiguous container detection

### ISSUE THREAD

**Issue by cschlegelmilch** [cloudfoundry/java-buildpack#364]
This seems related to #335 and #360, but I thought I would include this as an example.  When attempting to deploy a Ratpack application as a distZip using the latest version of the java-buildpack (f935bbc), I get the following error:

`Creating container`
`Successfully created container`
`Downloading app package...`
`Downloaded app package (15.1M)`
`Staging...`
`-----> Java Buildpack Version: f935bbc | https://github.com/cloudfoundry/java-buildpack.git#f935bbc`
`[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Application can be run by more than one container: Ratpack, Spring Boot CLI>`
`Application can be run by more than one container: Ratpack, Spring Boot CLI`
`Failed to compile droplet`
`Exit status 223`
`Staging failed: Exited with status 223`
`Destroying container`
`Successfully destroyed container`

`FAILED`
`Error restarting application: BuildpackCompileFailed`

`TIP: use 'cf logs citations-api-dev --recent' for more information`

I was able to get around this by disabling the Spring Boot CLI by adjusting the buildpack configuration by an environment variable in my manifest.yml:

`    JBP_CONFIG_COMPONENTS: '{"containers": ["JavaBuildpack::Container::DistZip","JavaBuildpack::Container::Groovy","JavaBuildpack::Container::JavaMain","JavaBuildpack::Container::PlayFramework","JavaBuildpack::Container::Ratpack","JavaBuildpack::Container::SpringBoot","JavaBuildpack::Container::Tomcat"]}'`

Given the known criteria for detecting [Spring Boot CLI](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-spring_boot_cli.md), I'm not surprised.  My groovy-based ratpack app meets all five of these published conditions.  I suspect that most do.

What's interesting is that we have an additional application, also a groovy-based ratpack app, that seems to deploy fine.  I have no idea as the differences don't seem obvious.  I've attached both the one that works (ThisWorks.zip) and the one that doesn't (ThisDoesNotWork.zip) for your reference. 

[ThisDoesNotWork.zip](https://github.com/cloudfoundry/java-buildpack/files/658114/ThisDoesNotWork.zip)
[ThisWorks.zip](https://github.com/cloudfoundry/java-buildpack/files/658115/ThisWorks.zip)

**Comment by nebhale** [comment]
This isn't likely to get done before the move to Cloud Native Buildpacks.  We have addressed the issue there already though.
