### ISSUE TITLE
Upload New Relic Agent 3.35.2 as an Available Version

### ISSUE THREAD

**Issue by samueltbrown** [cloudfoundry/java-buildpack#367]
New Relic recently released a new version of their Java agent (3.35.2) for download which may alleviate some errors we have been seeing in getting the agent to run with Spring AOP.  The latest versions is not currently available to be used with the java-buildpack so it may need to be uploaded to be available.

Listing of available versions (missing 3.35.2):

http://download.pivotal.io.s3.amazonaws.com/new-relic/index.yml

Latest agent can be downloaded at:

https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3352

If there is a way for me to upload it I would be happy to do so.  Thanks in advance for the help!

**Comment by cgfrost** [comment]
This has now been published, thanks for raising the issue.

http://download.pivotal.io.s3.amazonaws.com/new-relic/index.yml

**Comment by samueltbrown** [comment]
@cgfrost Huge thanks for the quick response!
