### ISSUE TITLE
Incompatibility with Pivotal Web Services' New Relic service

### ISSUE THREAD

**Issue by gbcm** [cloudfoundry/java-buildpack#368]
Hi, upon switching to the newest java-buildpack (v3.12) an application that I had in a Pivotal Web Services Cloud Foundry install started failing on boot. Investigation led us to the conclusion that when we have the New Relic service / tile enabled on the application we get the following error:
```
Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)
java.lang.VerifyError: Bad local variable type
...
Reason:
Type top (current frame, locals[17]) is not assignable to integer
```
Followed by a bunch of stack information and bytecodes.

**Comment by nebhale** [comment]
Is it possible that the application you're experiencing trouble with would fall afoul of [this problem](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3352)?  Specifically, does it use the libraries described there?
