### ISSUE TITLE
Display a warning when users request unsupported JRE versions

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/java-buildpack#370]
Since anything below JRE 1.8 is unsupported, we think it would be beneficial to show a warning during staging when users request a JRE version that is known to be unsupported. 
While JRE <1.8 being EoL should be a well-known fact, supporting EoL versions with no warnings can give users the impression that those versions are still supported by the platform.

**Comment by nebhale** [comment]
Yep, that's a great idea.  I'll make sure it makes it into the backlog quickly.
