### ISSUE TITLE
Fail to start a scala play app using CF Java Buildpack

### ISSUE THREAD

**Issue by sbcd90** [cloudfoundry/java-buildpack#380]
Hello,

I'm following the steps mentioned in the [tutorial](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/example-play_framework.md) to start a scala-play app in CF.

However, it throws an error like this..

```
ERR /home/vcap/app/play-approach-1.0-SNAPSHOT/start: 4: exec: java: not found
```

Can someone kindly help?

**Comment by nebhale** [comment]
What command and manifest did you push your application with?

**Comment by sbcd90** [comment]
Hi @nebhale ,

I used the command 

```
cf push play-approach4 -p target/play-approach-1.0-SNAPSHOT-dist.zip
```

& my simple play app is available [here](https://github.com/sbcd90/scala-cf-integration/tree/master/play-approach)

**Comment by nebhale** [comment]
I've fixed a bug around ensuring that `java` is on the path, and while that'll get you further it won't actually solve your entire problem.  The Play support (limited as it is), assumes that you'll have the "official" scripts from the Gradle build.  It attempts to [modify those scripts based on internal variable declarations](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/util/play/post22.rb#L37-L38).  Your scripts don't have those and therefore aren't updated properly.  Given that there is nearly no demand for Play support on Cloud Foundry, it's unlikely that we'll do much to solve this for you.

**Comment by nebhale** [comment]
Well, we used to have support for Play, but they broke compatibility again in 2.5 and I don't see anyone complaining about it, so I don't think that Play is used very much at the moment.  When it did work, using the official SBT/Gradle strategy was supported, so that'd be your best bet for trying it out.  Beyond that, I'm not sure there there's much Scala usage at all on Cloud Foundry.

**Comment by sbcd90** [comment]
Thanks @nebhale . Closing this issue.
