### ISSUE TITLE
AppD agents several versions behind 

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [cloudfoundry/java-buildpack#382]
Versions of the AppD agent available here (https://java-buildpack.cloudfoundry.org/app-dynamics/index.yml) are several versions behind what's available on the AppD website. The latest available on the cf.org site is 4.2.7_1 while the latest from AppD is 4.2.13.1. Is it possible to have those refreshed?

If this request belongs elsewhere, please advise...

**Comment by nebhale** [comment]
We cannot.  AppDynamics has recently canceled efforts towards a distribution agreement with the Cloud Foundry Foundation, resulting in the [disabling of the AppDynamics framework](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.11).  As an extension of this, we can no longer cache and distribute AppDynamics agents.  If you are an AppDynamics customer, you can create an [internal repository](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md) that provides the agent binaries you are legally entitled to use (see [expert mode](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/buildpack-modes.md)).

**Comment by Blackbaud-ChrisBlythe** [comment]
Thanks for the update!

**Comment by StBurcher** [comment]
Is there any news or anything official announcement about the cancellation?

**Comment by nebhale** [comment]
@StBurcher The discussion with AppDynamics were all private, and would be up to them to make an "official" announcement.  However, the notice to Java Buildpack users that AppDynamics would be disabled can be found in the [release notes](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.11) when it happened.
