### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by SvetlinZarev** [cloudfoundry/java-buildpack#383]
Hello,

The components.yml file and the docs for Oracle JRE imply that one has to fork the buildpack in order to change the default JRE and it's configuration (i.e. repository location). Yet, according to the Zulu JRE docs, it's possible to achieve the same using the `JBP_CONFIG_COMPONENTS` and  `JBP_CONFIG_[ORACLE|OPEN_JDK]_JRE` env variable. 

Is this gap in the documentation intentional and that comment in components.yml outdated ?

Best regards,
Svetlin

**Comment by nebhale** [comment]
Just outdated.
