### ISSUE TITLE
Add SAP JVM to the list of available JREs

### ISSUE THREAD

**Issue by SvetlinZarev** [cloudfoundry/java-buildpack#384]
Hello, 

Please add SAP JVM to the list of available JREs. The sap_jvm_jre.yml should be identical to the one for oracle/openjdk.

Kind regards,
Svetlin

**Comment by nebhale** [comment]
We do not have access to an SAP JRE to even do rudimentary testing against.  If SAP submits a PR (and does the testing for us) or provides us with a JRE to test with, we'll be happy to add it.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
