### ISSUE TITLE
Wrong version resolution for dependencies with wildcards for version qualifier

### ISSUE THREAD

**Issue by Anackreon** [cloudfoundry/java-buildpack#397]
This issue was discovered while working on a private cloud based on CF with an internal local repository for buildpack dependencies. For a particular dependency the buildpack is configured to use a version with a wildcard instead of version qualifier, like 1.7.0_+. Initially the local repository contained only versions with 2-digit qualifiers for a particular dependency, like 1.7.0_79. When the repository was updated with new artifacts having versions with 3-digit qualifiers, like 1.7.0_112, the buildpack was still choosing 1.7.0_79 during the application staging.

After inspecting the code became clear that Java buildpack compares qualifiers as strings and not numbers. Which is reasonable, because sometimes there are versions like 1.0.0_2a and 1.0.0_2b, in which case 1.0.0_2b should be chosen as the latest and the qualifiers should be compared as strings. As well as version 2.0.0_Q-7 don't have to be chosen over 2.0.0_3, so we can't just try to regex the first number from the qualifier and use it as a criteria.

In order to address all of these cases, I suggest that for comparing qualifiers as the primary criteria should be taken the number if it is located at the beginning of qualifier's string. Otherwise the qualifiers should be compared as strings.

This issue was solved for the private cloud. I would be happy to create a pull-request with the solution here. Can fill out the Contributor License Agreement if needed. Thanks!

**Comment by nebhale** [comment]
As [you can see](https://github.com/cloudfoundry/java-buildpack/commit/6f25b7e38a09188c9aeb2ff4f26dbbbaa8fdde5e), we've struggled with the same issues, opting for a _more specific wildcard_, but realistically that means that it isn't much of a wildcard with Oracle's current versioning policy.

Yeah, we should make a change to account for this and I'm happy to see a PR for it.

**Comment by Anackreon** [comment]
Ben, I've signed the CLA and sent it to contributors@cloudfoundry.org. Please review my pull request and let me know of any objections. Thank you!
