### ISSUE TITLE
Java Process Memory Configuration

### ISSUE THREAD

**Issue by SohilShahGE** [cloudfoundry/java-buildpack#401]
We are trying to configure the Memory Allocation for our Java/SpringBoot Apps based on the instructions detailed here: https://www.predix.io/support/article/KB0011507

JBP_CONFIG_OPEN_JDK_JRE: '[memory_calculator: {memory_heuristics: {heap: 1284, metaspace: 341, native: 574, stack: 1}}]'

option works just fine for a 512MB MEMORY_LIMIT. We are however, trying to use these instructions to scale this down further for a lower MEMORY_LIMIT. We tried 175MB with the following configuration:

JBP_CONFIG_OPEN_JDK_JRE: '[memory_calculator: {memory_heuristics: {heap: 1024, stack: 1}}]'

which results in: Memory Settings: -Xss228K -Xms44610K -XX:MetaspaceSize=64M -Xmx44610K -XX:MaxMetaspaceSize=64M

We tried different configurations but we noticed it is not possible to scale down the "MetaSpace" size to less than 64M.

As far as I understand, a metaspace that size is not needed for our Apps. On the local machine we can successfully run our Apps with a maximum metaspace of 10MB.

We would really appreciate it if you could throw some more light on the following:

    * Is there a way to lower down the metaspace allocation to less than 64MB in Cloud Foundry?

Thanks
Sohil Shah
GE, Aviation

**Comment by nebhale** [comment]
The 64M metspace limit you're seeing is [codified as part of the configuration](https://github.com/cloudfoundry/java-buildpack/blob/36011451f85a53abbdcead5d46438800a9a307cb/config/open_jdk_jre.yml#L28).  You can change this configuration parameter (even removing it) which will allow that number to shrink.

But in truth, JVMs actually require much larger memory spaces than that.  While you might be able to get the heap below 64M, metaspace (default unbounded) for storing classes that need to be loaded, thread stacks (defaulting to 1M x 200 threads by default in Tomcat = 200M), Compresed Class space (default 1G), Code Cache (default 240M), and direct memory (default unbounded) mean that the [_actual_ amount of memory consumed by the JVM](https://github.com/cloudfoundry/java-buildpack/issues/319) is significantlly higher than the 64M you're trying to aim for.  

We've been working on a new version of the memory calculator that accounts for all of these memory spaces and in our testing, it seems reasonable that the smallest container size (using JVM defaults) with any reasonable amount of heap is probably 768M, but that the Cloud Foundry default of 1G is probably the correct choice for most applications.  You can shrink those memory pools if you think your application can get away with it, but we've seen **significant** performance degradation in our experiments when we have done so with typical applications.

**Comment by SohilShahGE** [comment]
>The 64M metspace limit you're seeing is codified as part of the configuration. You can change this >configuration parameter (even removing it) which will allow that number to shrink.

Will this require a buildpack customization or can we do this via Manifest Configuration/Environment variable approach?

Just to add some context to the conversation,

I agree with you that high traffic Production Containers with a small Java heap (less than 768M) is not recommended. Correct me if I am wrong, but the same rule would probably apply to Production full blown apps in other platforms as well (Node.js, Golang, etc).

However, the use case for small Java containers is along the lines of low traffic, Development space containers that can even encompass HelloWorld like Apps. Allocating so much memory for such processes would most likely be on the excessive side. 

Ideally, we would like to allocate a small Java "heap" with a smaller "metaspace" for such processes.

For instance, I was trying to optimize the Memory Configuration for a 175MB Memory Limit, and with a bound "metaspace" of 64MB, I could only get a "heap" allocation of "50MB". If we could shrink the "metaspace", we could increase the "heap" allocation more, and may be even be able to shrink the overall Memory Limit.

I would like to know what your thoughts are for our use case and if I am making some wrong assumptions about allocating memory for the low footprint Java processes?

Thanks
Sohil

**Comment by nebhale** [comment]
All configuration in the buildpack can be accomplished by either a fork or environment variables as [described in the documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/README.md#configuration-and-extension).

However you've got a fundamental misunderstanding about how the JVM allocates memory. You've only accounted for heap and metaspace in your calculations. You also need to allocated 1M (default) for every thread your application could _possibly_ start (200 default for Tomcat) as well as Code Cache (240M default), Compressed Class Space (1G default), direct memory (unbounded default) and of course the native memory that the JVM requires to run. So saying that you only need 175M for heap and metaspace doesn't account for **most** of the memory used by the JVM. You can tune any of these numbers down (with massive performance penalties) but you absolutely must include them in your container size. Once you've done that, you'll find that small containers with JVMs aren't feasible, regardless of heap and metaspace calculations.

**Comment by SohilShahGE** [comment]
Thanks for the clarification.

I agree that small JVM containers in Production is not recommended. 

However, it may make sense to create small memory footprint JVM containers for minimal traffic Demo/Development spaces. 

It looks like the best option for that use case is to provide memory calculator settings via the JBP_CONFIG_OPEN_JDK_JRE environment variable. 

I am trying to accomplish your suggestion of 

 * The 64M metspace limit you're seeing is codified as part of the configuration. You can change this configuration parameter (even removing it) which will allow that number to shrink.

I cannot seem to find a way to "resize it" it through configuration via the JBP_CONFIG_OPEN_JDK_JRE Environment variable. Would you happen to have an example of what that configuration should look like?

Here is what I have tried:

[memory_heuristics: memory_sizes: {metaspace: 20m..}]

It still uses 64MB

I am using the following buildpack: https://github.com/cloudfoundry/java-buildpack.git#v3.12


Thanks
Sohil

**Comment by nebhale** [comment]
`cf set-env <APP> JBP_CONFIG_OPEN_JDK_JRE '{ memory_calculator: { memory_sizes: { metaspace: 16m } } }'`

Note that the value is a YAML document that matches the config file itself.  For ease of reading, we use the YAML "flow" style.

**Comment by SohilShahGE** [comment]
Thanks Ben. That worked

**Comment by nebhale** [comment]
Great to hear.
