### ISSUE TITLE
SpringBoot App start error

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/java-buildpack#406]
Hi team:
  I create a simple springboot app, when i use eclipse push , is success
  But when i use cf cli push spring boot app ,it can not start,
 I use maven create project
 ```
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer
 Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
```
I try build to war,but is same error.

**Comment by nebhale** [comment]
I believe that you've got a mismatch between the version of Spring Boot and the version of the buildpack.  Spring Boot 1.4 or later must be run with Java Buildpack [v3.9](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.9) or later.  Boot made a change to it's classloading that required an update to the buildpack to support.

**Comment by geekyzk** [comment]
I use spring boot 1.5.1.RELEASE
buildpack `buildpack: java-buildpack=v3.1.1-offline-https://github.com/cloudfoundry/java-buildpack#7a538fb java-main open-jdk-like-jre=1.8.0_51 open-jdk-like-memory-calculator=1.1.1_RELEASE spring-auto-reconfiguration=1.7.0_RELEASE`
when i use eclipse push app is success,
use cloudfoundry cli push same app,use same buildpack,is error.
On 03/20/2017 22:41，Ben Hale<notifications@github.com> wrote：

I believe that you've got a mismatch between the version of Spring Boot and the version of the buildpack. Spring Boot 1.4 or later must be run with Java Buildpack v3.9 or later. Boot made a change to it's classloading that required an update to the buildpack to support.

**Comment by nebhale** [comment]
You're clearly using Java Buildpack `v3.1.1` which does not support Spring Boot 1.5.1.RELEASE.  You'll need to ensure that you're using a more modern buildpack as this combination is not supported.

**Comment by geekyzk** [comment]
Thanks，using new Java Buildpack successfully solved the problem.
On 03/20/2017 22:59，Ben Hale<notifications@github.com> wrote：

You're clearly using Java Buildpack v3.1.1 which does not support Spring Boot 1.5.1.RELEASE. You'll need to ensure that you're using a more modern buildpack as this combination is not supported.

**Comment by rajavikram** [comment]
how do you specify a tag as build-pack. 
tried using `buildpack: https://github.com/cloudfoundry/java-buildpack/tree/v3.15`
But i am getting 

> fatal: repository 'https://github.com/cloudfoundry/java-buildpack/tree/v3.15/' not found ERROR

**Comment by geekyzk** [comment]
@rajavikram 

If your application requires a custom buildpack, you can use the buildpack attribute to specify it in one of three ways:

By name: MY-BUILDPACK.
By GitHub URL: https://github.com/cloudfoundry/java-buildpack.git.
By GitHub URL with a branch or tag: https://github.com/cloudfoundry/java-buildpack.git#v3.3.0 for the v3.3.0 tag.

**Comment by rajavikram** [comment]
Got the solution from this [SO answer](https://stackoverflow.com/questions/26116320/cloudfoundry-use-an-older-buildpack-version/26127753#26127753).
`buildpack: https://github.com/cloudfoundry/java-buildpack#v3.15`
