### ISSUE TITLE
dsm-advapi  and dsm-client_1.2: open source or commercial code?

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/java-buildpack#417]
Hi, I work in IBM, in the Bluemix legal team and currently I'm doing the clearance (legal analysis) of Java-Buildpack 3.13; it contains some new .jar files dependencies that I don't know if they are open source or commercial products:

- dsm-advapi
- dsm-client_1.2

I think that they are Dyadic EKM components, but I'm not sure if Dyadic EKM is an open source; in the case it's an open source I've to download their source code and scan it. 

So, I kindly ask you:

1. are those open source or under commercial license?
2. if they are open source, where I can download their source an license from?

Thanks.

**Comment by nebhale** [comment]
The [Dyadic](https://www.dyadicsec.com) Java Security Provider is not open source.  Per the recent directives from the Cloud Foundry Foundation

* https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/SN5AW5SUAMHDQAAPU45AURTBWEXWU2MN/
* https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/PLV44TLOBQVS7UEHRPQFCXPJMVQIA3T3/

IBM is now expected to execute a distribution agreement directly with Dyadic if they wish to distribute these binaries.  If you [email me](mailto:bhale@pivotal.io?subject=Dyadic%20Distribution%20Agreement%20Inquiry) I can put you in touch with the Dyadic team.

**Comment by luisapace** [comment]
Thanks a lot!

Best Regards/Cordiali saluti
                                           Luisa Pace

=========================================================================================================================

Ciò che è fuori è anche dentro; e ciò che non è dentro non è da nessuna 
parte. Per questo viaggiare non serve. Se uno non ha niente dentro, non 
troverà mai niente fuori.   È inutile andare a cercare nel mondo quel che 
non si riesce a trovare dentro di sé.  (Tiziano Terzani) 

==========================================================================================================================


Ing.  Luisa Pace
IBM Italy
Bluemix Legal Project Manager 
Via Sciangai, 53  (B1 - 508)
00144 Roma
Italy
Tel. +39.06.5966.3795
Fax. +39.06.5966.3489
mob. +39.335.7368629
e-mail:  luisa_pace@it.ibm.com
