### ISSUE TITLE
Unable to download latest AppDynamics Agent

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/java-buildpack#419]
The latest agent version for AppDynamics agent specified in [index.yml](https://packages.appdynamics.com/java/index.yml) file is 4.3.+
The [config](https://github.com/cloudfoundry/java-buildpack/blob/master/config/app_dynamics_agent.yml#L18) file specifies the agent version as 4+. However the agent downloaded is 4.2.15_0 rather than latest 4.3 agent.

Is there something I am missing ?

**Comment by nebhale** [comment]
If I had to guess, I don't believe that the CloudFront distribution has been properly [invalidated](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html) as you've updated the index underneath it.  If you run the following command

```
## Request
curl "https://packages.appdynamics.com/java/index.yml" \
     -H "Accept: */*" \
     -H "If-Modified-Since: Thu, 06 Apr 2017 06:57:34 GMT" \
     -H "Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3" \
     -H "If-None-Match: 00276f92a3f5896bda7bb619aa7531db" \
     -H "User-Agent: Ruby"
```

You'll received a response that only goes to `4.2.15_2`

```
---
4.1.3_1: https://packages.appdynamics.com/java/4.1.3.1/AppServerAgent-4.1.3.1.zip
4.1.7_1: https://packages.appdynamics.com/java/4.1.7.1/AppServerAgent-4.1.7.1.zip
4.1.7_2: https://packages.appdynamics.com/java/4.1.7.2/AppServerAgent-4.1.7.2.zip
4.1.8_1: https://packages.appdynamics.com/java/4.1.8.1/AppServerAgent-4.1.8.1.zip
4.1.8_2: https://packages.appdynamics.com/java/4.1.8.2/AppServerAgent-4.1.8.2.zip
4.1.8_3: https://packages.appdynamics.com/java/4.1.8.3/AppServerAgent-4.1.8.3.zip
4.1.8_4: https://packages.appdynamics.com/java/4.1.8.4/AppServerAgent-4.1.8.4.zip
4.1.8_5: https://packages.appdynamics.com/java/4.1.8.5/AppServerAgent-4.1.8.5.zip
4.1.8_6: https://packages.appdynamics.com/java/4.1.8.6/AppServerAgent-4.1.8.6.zip
4.1.8_7: https://packages.appdynamics.com/java/4.1.8.7/AppServerAgent-4.1.8.7.zip
4.1.8_8: https://packages.appdynamics.com/java/4.1.8.8/AppServerAgent-4.1.8.8.zip
4.1.8_9: https://packages.appdynamics.com/java/4.1.8.9/AppServerAgent-4.1.8.9.zip
4.1.8_10: https://packages.appdynamics.com/java/4.1.8.10/AppServerAgent-4.1.8.10.zip
4.1.8_11: https://packages.appdynamics.com/java/4.1.8.11/AppServerAgent-4.1.8.11.zip
4.1.8_12: https://packages.appdynamics.com/java/4.1.8.12/AppServerAgent-4.1.8.12.zip
4.1.8_13: https://packages.appdynamics.com/java/4.1.8.13/AppServerAgent-4.1.8.13.zip
4.1.10_1: https://packages.appdynamics.com/java/4.1.10.1/AppServerAgent-4.1.10.1.zip
4.1.10_2: https://packages.appdynamics.com/java/4.1.10.2/AppServerAgent-4.1.10.2.zip
4.1.10_3: https://packages.appdynamics.com/java/4.1.10.3/AppServerAgent-4.1.10.3.zip
4.1.10_4: https://packages.appdynamics.com/java/4.1.10.4/AppServerAgent-4.1.10.4.zip
4.1.10_6: https://packages.appdynamics.com/java/4.1.10.6/AppServerAgent-4.1.10.6.zip
4.2.0_1: https://packages.appdynamics.com/java/4.2.0.1/AppServerAgent-4.2.0.1.zip
4.2.0_2: https://packages.appdynamics.com/java/4.2.0.2/AppServerAgent-4.2.0.2.zip
4.2.1_1: https://packages.appdynamics.com/java/4.2.1.1/AppServerAgent-4.2.1.1.zip
4.2.1_2: https://packages.appdynamics.com/java/4.2.1.2/AppServerAgent-4.2.1.2.zip
4.2.1_3: https://packages.appdynamics.com/java/4.2.1.3/AppServerAgent-4.2.1.3.zip
4.2.1_4: https://packages.appdynamics.com/java/4.2.1.4/AppServerAgent-4.2.1.4.zip
4.2.1_5: https://packages.appdynamics.com/java/4.2.1.5/AppServerAgent-4.2.1.5.zip
4.2.1_6: https://packages.appdynamics.com/java/4.2.1.6/AppServerAgent-4.2.1.6.zip
4.2.1_7: https://packages.appdynamics.com/java/4.2.1.7/AppServerAgent-4.2.1.7.zip
4.2.1_8: https://packages.appdynamics.com/java/4.2.1.8/AppServerAgent-4.2.1.8.zip
4.2.2_1: https://packages.appdynamics.com/java/4.2.2.1/AppServerAgent-4.2.2.1.zip
4.2.2_2: https://packages.appdynamics.com/java/4.2.2.2/AppServerAgent-4.2.2.2.zip
4.2.3_1: https://packages.appdynamics.com/java/4.2.3.1/AppServerAgent-4.2.3.1.zip
4.2.3_2: https://packages.appdynamics.com/java/4.2.3.2/AppServerAgent-4.2.3.2.zip
4.2.3_3: https://packages.appdynamics.com/java/4.2.3.3/AppServerAgent-4.2.3.3.zip
4.2.4_1: https://packages.appdynamics.com/java/4.2.4.1/AppServerAgent-4.2.4.1.zip
4.2.12_2: https://packages.appdynamics.com/java/4.2.12.2/AppServerAgent-4.2.12.2.zip
4.2.15_1: https://packages.appdynamics.com/java/4.2.15.1/AppServerAgent-4.2.15.1.zip
4.2.15_2: https://packages.appdynamics.com/java/4.2.15.2/AppServerAgent-4.2.15.2.zip
```

[Properly invalidating the caches](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/common.sh#L1-L21) on each update of the index should solve the issue.

**Comment by Gomerie** [comment]
I see that it's now able to detect the newest version of the agent, but cannot resolve it. Throwing error when starting up:

`osxlttrupp:spring-music-master xxx$ cf restage spring-music
Restaging app spring-music in org appd / space dev as xxx@xxx.com...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (38.8M)
Downloading build artifacts cache...
Downloaded build artifacts cache (58.3M)
Staging...
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: App Dynamics Agent error: No version resolvable for '4.3.0_4' in 4.1.3_1, 4.1.7_1, 4.1.7_2, 4.1.8_1, 4.1.8_2, 4.1.8_3, 4.1.8_4, 4.1.8_5, 4.1.8_6, 4.1.8_7, 4.1.8_8, 4.1.8_9, 4.1.8_10, 4.1.8_11, 4.1.8_12, 4.1.8_13, 4.1.10_1, 4.1.10_2, 4.1.10_3, 4.1.10_4, 4.1.10_6, 4.2.0_1, 4.2.0_2, 4.2.1_1, 4.2.1_2, 4.2.1_3, 4.2.1_4, 4.2.1_5, 4.2.1_6, 4.2.1_7, 4.2.1_8, 4.2.2_1, 4.2.2_2, 4.2.3_1, 4.2.3_2, 4.2.3_3, 4.2.4_1, 4.2.12_2, 4.2.15_1, 4.2.15_2>
App Dynamics Agent error: No version resolvable for '4.3.0_4' in 4.1.3_1, 4.1.7_1, 4.1.7_2, 4.1.8_1, 4.1.8_2, 4.1.8_3, 4.1.8_4, 4.1.8_5, 4.1.8_6, 4.1.8_7, 4.1.8_8, 4.1.8_9, 4.1.8_10, 4.1.8_11, 4.1.8_12, 4.1.8_13, 4.1.10_1, 4.1.10_2, 4.1.10_3, 4.1.10_4, 4.1.10_6, 4.2.0_1, 4.2.0_2, 4.2.1_1, 4.2.1_2, 4.2.1_3, 4.2.1_4, 4.2.1_5, 4.2.1_6, 4.2.1_7, 4.2.1_8, 4.2.2_1, 4.2.2_2, 4.2.3_1, 4.2.3_2, 4.2.3_3, 4.2.4_1, 4.2.12_2, 4.2.15_1, 4.2.15_2
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

Failed to watch staging of app spring-music in org appd / space dev as xxx@xxx.com...
`

**Comment by nebhale** [comment]
@Gomerie Another example of an improperly invalidated cache; the various edge servers are out of sync with one another.

**Comment by Gomerie** [comment]
@nebhale I understand it's a cache problem and the solution is running the script you mentioned in your first comment?

When do you think will it be possible to get the latest agent / in what timeframes is the cache invalidated in general?

**Comment by nebhale** [comment]
@Gomerie the repository hosting AppDynamics artifacts is controlled by AppDynamics, not the Cloud Foundry Foundation.  It is up to them to invalidate their CloudFront distribution when artifacts are updated underneath it.  I'd have to look at the headers again, but if I recall correctly their current configuration means that the cache will never expire without explicit invalidation.  You'll need to contact them about the timeframe for invalidating their cached content.

**Comment by Gomerie** [comment]
@nebhale understood :)

My first comment with the problem above is when trying to startup the application with " cf push spring-music -b https://github.com/appdynamics/java-buildpack "

So, I'm using our appdynamics java-buildpack in this case and get the error thrown that the agent cannot be resolved (as it's not found because of the old cache).

When checking against the cloud foundry one, still the 4.2.15_2 is loaded.

The only difference so far I can see to our own buildpack, is that the config and index .yml was updated. But now it's not able to resolve the newest agent. See here:
https://github.com/Appdynamics/java-buildpack/commit/84728dc88975964cdc69204591c2557c9800c057

That's why I asked how often the cache is invalidated. Was it already done after reporting this issue?(the appdynamics one)
If yes, I assume it's a different issue then the cache :)


```

> Buildpack]                      ERROR Compile failed with exception #<RuntimeError: App Dynamics Agent error: No version resolvable for '4.3.0_4' in 4.1.3_1, 4.1.7_1, 4.1.7_2, 4.1.8_1, 4.1.8_2, 4.1.8_3, 4.1.8_4, 4.1.8_5, 4.1.8_6, 4.1.8_7, 4.1.8_8, 4.1.8_9, 4.1.8_10, 4.1.8_11, 4.1.8_12, 4.1.8_13, 4.1.10_1, 4.1.10_2, 4.1.10_3, 4.1.10_4, 4.1.10_6, 4.2.0_1, 4.2.0_2, 4.2.1_1, 4.2.1_2, 4.2.1_3, 4.2.1_4, 4.2.1_5, 4.2.1_6, 4.2.1_7, 4.2.1_8, 4.2.2_1, 4.2.2_2, 4.2.3_1, 4.2.3_2, 4.2.3_3, 4.2.4_1, 4.2.12_2, 4.2.15_1, 4.2.15_2>
> App Dynamics Agent error: No version resolvable for '4.3.0_4' in 4.1.3_1, 4.1.7_1, 4.1.7_2, 4.1.8_1, 4.1.8_2, 4.1.8_3, 4.1.8_4, 4.1.8_5, 4.1.8_6, 4.1.8_7, 4.1.8_8, 4.1.8_9, 4.1.8_10, 4.1.8_11, 4.1.8_12, 4.1.8_13, 4.1.10_1, 4.1.10_2, 4.1.10_3, 4.1.10_4, 4.1.10_6, 4.2.0_1, 4.2.0_2, 4.2.1_1, 4.2.1_2, 4.2.1_3, 4.2.1_4, 4.2.1_5, 4.2.1_6, 4.2.1_7, 4.2.1_8, 4.2.2_1, 4.2.2_2, 4.2.3_1, 4.2.3_2, 4.2.3_3, 4.2.4_1, 4.2.12_2, 4.2.15_1, 4.2.15_2
> Failed to compile droplet
> Exit status 223
> Staging failed: Exited with status 223
> Destroying container
> Successfully destroyed container
> 
> Failed to watch staging of app spring-music in org appd / space dev as xxx@xxx.com...

```

**Comment by nebhale** [comment]
It's the exact same issue.  They've just hard coded a specific version rather than allowing resolution.  But the end result is the same.  The cached version of `index.yml` has not been invalidated.  If there is a wildcard, then it'll pull the latest it can see (i.e. `4.2.15_2`).  If there is no wildcard, it'll pull what is hard coded (`4.3.0_4`).

As far as when the cache is invalidated that's something only AppDynamics can answer.  I'd suggest opening an issue with their support to have it rectified.

**Comment by Gomerie** [comment]
@nkatre Can you take care of this?

**Comment by nkatre** [comment]
@nebhale Is there an example on how to invoke [this](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/common.sh#L1-L21) method on every index.yml update ?

**Comment by nebhale** [comment]
@nkatre We invoke it as part of our [dependency builder scripts](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/new-relic.sh#L14), but I don't think you should use our code.  Instead, the release pipeline that you use to put your artifacts in the S3 bucket and update the `index.yml` there, should be extended to also make the appropriate CloudFront calls to generate an invalidation for the files you've modified.  It's a single REST call or a single command line call with the `awscli`, one of which you must already be using to upload the artifacts in the first place.

**Comment by nebhale** [comment]
This cache [appears to have been invalidated](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/java-buildpack/jobs/java-versions/builds/13) and this issue can be closed.
