### ISSUE TITLE
Improve coherence of JAVA_OPTS and other environment variable handling

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#424]
Since the `JAVA_OPTS` environment variable is more significant to the customizing of an application's memory config, it seemed somewhat less user friendly to require that changes to the `JAVA_OPTS` environment variable required a restage to take effect.

It would be nice if I wanted to change -Xss all I'd need to do is change the environment variable and restart.  Just like if I change app memory, all I need to do is scale the app and restart.

**Comment by youngm** [comment]
After thinking a bit more about this problem it would be nice if JAVA_OPTS and buildpack config was handled more cleanly in general.  In a perfect word, This is how I would think how different buildpack config should impact the need to restage/restart.

Changes to the buildpack config via `JBP_CONFIG` obviously should require a restage because it is obviously changing how the buildpack functions. Changes to buildpack config in buildpack `config` directory should obviously require a restage because you are changing the buildpack code.  Binding some services could effect how how the code is bundles so that might requires a restage.

However, it seems that customizing my application by applying any other environment variable should take effect at restart and not restage.  I'm not sure how many other non `JBP_CONFIG` environment variables the buildpack consumes besides `JAVA_OPTS`, but, I think it would be worth the effort to at least attempt to either make them all take effect at restart time.  Or change them to JBP_CONFIG to better fit the model.

I see that this would probably require the Memory Calculator to consume raw `JAVA_OPTS` instead of buildpack curated config.  But, I think it would be worth the effort to the end user.

Thoughts?

**Comment by youngm** [comment]
Another aspect of this to consider.  If you set `from_environment` in `java_opts.yml` to false.  Then set as an environment variable `JAVA_OPTS="-Xss256k -XX:MaxMetaspaceSize=64M" and restage.   Then the buildpack appears to utilize `JAVA_OPTS` to make memory calculations.  But, the actual configuration in `JAVA_OPTS` never actually makes it into the application's args.  Just another problem exhibited by the complexity going on with the JAVA_OPTS variable now.

**Comment by youngm** [comment]
For the above issue case I think it would make sense to not use `JAVA_OPTS` for memory calculation config if `from_environment` is false.

**Comment by youngm** [comment]
@nebhale Sounds great!  I'll give these changes a try soon.

**Comment by sslavic** [comment]
In java-buildpack 4.2 and older this worked:
```
JAVA_OPTS: "-Djava.security.auth.login.config='$PWD/jaas.conf'"
```
We used $PWD instead of $HOME because PWD was consistent between DEA and Diego, it helped in transition period. I don't recall well but it was suggested in some docs to prefer using env vars over ```/home/vcap```, e.g. not to rely on vcap username as it may change.

As of 4.3, and I believe because of this improvement, this no longer works. It seems env vars like $PWD do not get interpolated/replaced in the value of JAVA_OPTS, and it doesn't like quotes, especially around value of _java.security.auth.login.config_ Java system property.

What we found to be working now is to hardcode absolute path and remove all quotes, as in:
```
JAVA_OPTS: -Djava.security.auth.login.config=/home/vcap/app/jaas.conf
```

**Comment by nebhale** [comment]
@sslavic I'm actually wondering if something has changed in CF or the CLI.  I've just pushed an application with the following manifest:

```yaml
---
applications:
- name: java-main-application
  path: build/libs/java-main-application-1.0.0.BUILD-SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  env:
    JAVA_OPTS: -Djava.security.auth.login.config=$PWD/jaas.conf
```

There's no explicit escaping or anything, but when I SSH into the container, I see

```plain
$ export | grep JAVA_OPTS
declare -x JAVA_OPTS="-Djava.security.auth.login.config=\$PWD/jaas.conf"
```

and

```plain
$ echo $JAVA_OPTS
-Djava.security.auth.login.config=$PWD/jaas.conf
```

Note that none of this has to do with the buildpack; it's purely the CLI, Cloud Controller, and Diego.  We don't change the `JAVA_OPTS` environment variable, but rather add it to the command line that would start.  This tells me that something else must be up.

**Comment by nebhale** [comment]
I guess alternately, the way we used to include `JAVA_OPTS` caused an extra level of unwrapping that hid this behavior?

**Comment by sslavic** [comment]
We reproduced the difference in behavior using same CF and CLI, while varying buildpack version and JAVA_OPTS configuration only. It's fine if the old behavior was unintentional and that it's gone now, there's a working alternative. Feel free to close the issue.

**Comment by nebhale** [comment]
[Ugh](https://cloudfoundry.slack.com/archives/C032824SM/p1503612872000245).  Apparently it's always been illegal from the perspective of CAPI and Diego but an artifact of how we used to include `JAVA_OPTS` means that we got an extra level of unwrapping.  This might be pretty problematic.

**Comment by nebhale** [comment]
It seems that this change has existed without any serious issues, so I'm going to close this out as my worries were overblown compared to reality.

**Comment by owenfarrell** [comment]
@nebhale Was there ever a workaround introduced to support the previous behavior that did unwrap environmental variables?

For predictable values (e.g. `$PWD`), hardcoding entries in a manifest is fine. But we have some scenarios which require a more dynamic value be injected as a command-line property (e.g. `$CF_INSTANCE_INDEX`).

**Comment by owenfarrell** [comment]
@nebhale Any guidance on how to inject runtime environmental variables in to the command line after moving to version 4.2 of the buildpack?
