### ISSUE TITLE
Display resulting candidate calculated memory in buildpack output

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#425]
It is nice that the buildpack outputs the parameters that are going into memory calculation.  

`Loaded Classes: 8785, Threads: 300, JAVA_OPTS: '-Xss256K -XX:MaxPermSize=128M'`

But, I'd like to also be able to easily see what those parameters are going to result in when the application starts.  Today with 4.x it is not a trivial task to see the result of the memory configuration.  Unless I'm missing something you essentially have to ssh into the container and grep the running process to discover the resulting config.

I thought in 3.x we used to fail staging if the memory calculator predicted that the application wouldn't start.  It appears that isn't the case in 4.x.  I can see why that change could have been intentional.  But, I'd still like to see the result of the memory calculations and at the very least produce a warning (the runtime Memory calculator failure message could be sufficient) msg of some sort if the calculations predict failure.

Adding configured container memory to the output of the input parameters would be nice too.

**Comment by nebhale** [comment]
Sometime in the last year, the staging process was changed and there is a *different* `MEMORY_LIMIT` for the staging container than there is for the runtime container.  So outputting that value wasn't useful even in the 3.x branch and was eventually removed (I cannot for the life of me remember where I did it, but I did).  So, in the new 4.x branch, the [memory settings are printed](https://github.com/cloudfoundry/java-buildpack/commit/737093b6abfbd18e055a3b37349e5352ab572b1a) as the first line at start up.  Output should look like:

```
CELL/0] OUT Successfully created container
CELL/0] OUT Starting health monitoring of container
APP/PROC/WEB/0] OUT JVM Memory Configuration: -XX:MaxMetaspaceSize=103792K -XX:ReservedCodeCacheSize=240M -XX:CompressedClassSpaceSize=18689K -Xss1M -Xmx362894K -XX:MaxDirectMemorySize=10M
APP/PROC/WEB/0] OUT   .   ____          _            __ _ _
APP/PROC/WEB/0] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
APP/PROC/WEB/0] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
APP/PROC/WEB/0] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
APP/PROC/WEB/0] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
APP/PROC/WEB/0] OUT  =========|_|==============|___/=/_/_/_/
APP/PROC/WEB/0] OUT  :: Spring Boot ::        (v1.4.1.RELEASE)
...
```

Does this satisfy the requirement?

**Comment by youngm** [comment]
I had no idea about the staging memory change.  Yup, this is good enough.
