### ISSUE TITLE
Add IBM JRE as an option to the java-buildpack

### ISSUE THREAD

**Issue by dinogun** [cloudfoundry/java-buildpack#426]
Can you please consider adding IBM Java as an option in the java-buildpack. See the [knowledge center](https://www.ibm.com/support/knowledgecenter/SSYKE2/welcome_javasdk_family.html) for more details on IBM Java. We will be submitting a PR shortly for the same. Thank You !

**Comment by nebhale** [comment]
Will do.  Closing in lieu of PR #427.
