### ISSUE TITLE
4bab4ff Breaks the JDK Trust Store

### ISSUE THREAD

**Issue by huhlig** [cloudfoundry/java-buildpack#429]
Http Clients Can no longer make SSL Calls... Nothing in the Readme seems to addresses this.

**Comment by davidmeredith** [comment]
Urgent, I've needed to downgrade the buildpack to v3.16 temporarily get around this problem using: 
cf push -b https://github.com/cloudfoundry/java-buildpack.git#v3.16 -p target/someapp.jar

**Comment by Muuo** [comment]
This issue kept me up late last night. Hopefully there's a quick and easy solution. In the meantime I'll go with @davidmeredith's strategy.

**Comment by nebhale** [comment]
@huhlig Cany ou give me some more details on why you think they can no longer make SSL calls?  Error messages or anything?

**Comment by huhlig** [comment]
I receive the message "java.security.cert.CertificateException: No X509TrustManager implementation available" when using 3.16 when I try to connect to an SSL Site (Twitter API in my case) using Apache HttpClients. Reverting back to 3.15 works fine.

**Comment by nebhale** [comment]
Working on it now.  The change has been reverted out and I'll have an update to the next version of the Security Provider that will fix it.

**Comment by nebhale** [comment]
OK, this should be sorted.  The Security Provider has been reinstated but is not using a more portable way of getting the JRE's CA certs.

**Comment by nebhale** [comment]
@huhlig I'm planning on releasing the next version of the build pack with this change in it, early next week.  If you could verify the fix before then, it'd be helpful.
