### ISSUE TITLE
no_proxy hosts are not included.

### ISSUE THREAD

**Issue by mohanbabubb** [cloudfoundry/java-buildpack#438]
On the script, https://github.com/cloudfoundry/java-buildpack/blob/8aa5c04c3cde5d72826106c5a854e9625e680fb0/lib/java_buildpack/util/cache/download_cache.rb#L269-L276, if have environment variable for no_proxy for some hosts/localhost/local ip's which need to be skipped through proxy but the script had no option to evaluate the localhost and no_proxy environment variable.
Scenario:
If i host a local repo server and run the rake task to use the local repo server for build, its failing.
I think it would be good to add some condition to consider no_proxy during run.

**Comment by gberche-orange** [comment]
@nebhale I ran into this issue, and associated commit https://github.com/cloudfoundry/java-buildpack/commit/834c9785f440b1d3854c043be4e56f5924564cd1 as I was looking for example syntax of the NO_PROXY variable. 

I had a hard time understanding the spec which currently says the following but actually asserts the proxy is used.
> does not use proxy if host in NO_PROXY
> does not use proxy if host in no_proxy

I wonder whether you indeed meant:

`uses proxy if host is not in NO_PROXY`
`uses proxy if host is not in no_proxy`

and missed to implement the following cases ?

`does not use proxy if host in NO_PROXY`
`does not use proxy if host in no_proxy`
