### ISSUE TITLE
Memory configurations not getting applied for java-buildpack

### ISSUE THREAD

**Issue by souveekbose** [cloudfoundry/java-buildpack#441]
Hi,
I am using some specific memory configurations for my java spring-boot applications. I was able to configure the changes in buildpack v3.6 using JBP_CONFIG_OPEN_JDK_JRE. However am not able to use it in the current version as memory_sizes and memory_heuristics have been removed.
Please suggest how to make these changes effective in the latest buildpack

**Comment by nebhale** [comment]
Java Buildpack 4.0 (and therefore `master`) is using a new version of the memory calculator.  Details about this can be found, in the [documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory), the [memory calculator](https://github.com/cloudfoundry/java-buildpack-memory-calculator#java-buildpack-memory-calculator), and the [blog](https://www.cloudfoundry.org/just-released-java-buildpack-4-0/).

See #422
