### ISSUE TITLE
How to set runtime environment variable

### ISSUE THREAD

**Issue by PavelSosin** [cloudfoundry/java-buildpack#443]
Hello colleagues,
I'm trying to extend java buildpack by including additional component. Everything works fine unless 1 thing: I can't add runtime environment variable from my configuration file which conrains the following prop:

env:
  ..IPC: > 
       ....{"socket": { "in": 8991, "out": 8990 }}

In "compile" method _puts @configuration["env"]["IPC"]_ returns the correct value but in"release" method the following code has no effect:

        environment_variables = @droplet.environment_variables
        myIpc = @configuration["env"]["IPC"]
        environment_variables.add_environment_variable(IPC, myIpc)

I hoped that it will copy the corresponding conf value to running env variables but it doesn't happen. What is missed/wrong in my code?
The corresponding environment variable definition inside manifest achieves the expected effect but it is component related and, I think, shall be defined via component configuration.

**Comment by nebhale** [comment]
Looking at your sample code the problem may be that `environment_variables.add_environment_variable(IPC, myIpc)` actually refers to a variable for for the key in the environment (which is likely `nil`).  If you change it to `environment_variables.add_environment_variable('IPC', myIpc)`, this may fix the problem.

As far as different behavior in `compile` and `release`.  The `@configuration` value is [created](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/buildpack.rb#L170) the same way for both [`compile` and `release`](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/buildpack.rb#L127).

**Comment by PavelSosin** [comment]
Hi ,
the IPC constant is define few line below:

_private

      IPC = 'jdt-ipc'.freeze_

Yet another consideration:
when I added something wrong using **add_environment_variable** then application fails to start with the "_bash error: invalid statement 'jdt-ipc'={something wrong}_" message.

**Comment by nebhale** [comment]
@PavelSosin Is it possible that the contents of that environment variable aren't properly escape or protected in some way?  You should look at the contents of the command to be executed and be sure that you've got the proper contents as the environment variable is set.

**Comment by PavelSosin** [comment]
Hi Ben,
It appears, that escaping which used in env definition is not the only issue and it can be easily corrected. When I enforce debugging for my application I was really surprized to see the Release Payload result:

### 2017-06-11T14:07:22.39+0300 [STG/0]      ERR [Buildpack]                      DEBUG Release Payload:
2017-06-11T14:07:22.39+0300 [STG/0]      ERR ---
2017-06-11T14:07:22.39+0300 [STG/0]      ERR addons: []
2017-06-11T14:07:22.39+0300 [STG/0]      ERR config_vars: {}
2017-06-11T14:07:22.39+0300 [STG/0]      ERR default_process_types:
2017-06-11T14:07:22.39+0300 [STG/0]      ERR   web: 'CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.8.0_RELEASE
2017-06-11T14:07:22.39+0300 [STG/0]      ERR     -totMemory=$MEMORY_LIMIT -stackThreads=300 -loadedClasses=15696 -poolType=metaspace)
2017-06-11T14:07:22.39+0300 [STG/0]      ERR     && IPC={ ''socket'' : {''in'' : 8991, ''out'' : 8990 } } workdir=language_server_bin_exec_jdt/
2017-06-11T14:07:22.39+0300 [STG/0]      ERR     JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR
...etc., etc.

I.e. my environment variables are injected inside java_opts, preceded by "&&" and delimited by nothing. As expected it results in the following error during application startup:

[APP/PROC/WEB/0]ERR bash: socket: command not found

**Comment by nebhale** [comment]
@PavelSosin That does look like an escaping issue.  You see the double ticks everywhere because of how YAML is rendered in that view.  If you de-YAML it (there's an [alias](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/debugging-the-buildpack.md#aliases) for that, it'll look closer to what you're looking for.  But even then, you'll find that `IPC` is not escaped correctly. I'd give a go to something like `environment_variables.add_environment_variable(IPC, "\"#{myIpc}\"")`.

**Comment by PavelSosin** [comment]
Hi Ben,
It didn't solve the problem(s). Even, I use the following code I don't succeed to "un-yaml" my JSON:
```
        environment_variables.add_environment_variable(IPC, "\"#{myIpc}\"")
        environment_variables.add_environment_variable("workdir", myWorkDir)
        @logger.debug { "JDT Env vars:#{environment_variables}" }

```
I switched to Folded block but regardless which type of quotas I use I get wrong result. 
But most critical is the absence of command delimiters between shell commands which defines environment variables when more then 1 add_environment_variable is used:

  web: 'CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.8.0_RELEASE
    -totMemory=$MEMORY_LIMIT -stackThreads=300 -loadedClasses=15696 -poolType=metaspace)
    **&&** jdt-ipc="{''socket'': {''in'': 8991, ''out'': 8990}}" workdir=language_server_bin_exec_jdt/

Double ampersend is placed before both commands and not between them.

**Comment by nebhale** [comment]
Yes, the double ampersand is in the proper place.  Environment variables are defined at the head of a command (this is legal `bash` syntax that isolates the environment variable to a specific process).  The `CALCULATED_MEMORY` is a special case because it must be calculated in a separate process with captured output and multiple uses.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
