### ISSUE TITLE
v4.x.x offline java-buildpack

### ISSUE THREAD

**Issue by BenjaminBrandmeier** [cloudfoundry/java-buildpack#444]
To leverage the new features of 4.x.x we need to include it as an offline package in our PCF instance.

Is there a reason why no offline buildpack is released for the new major version 4.x.x?

**Comment by nebhale** [comment]
There is a new [Cloud Foundry Foundation policy](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/SN5AW5SUAMHDQAAPU45AURTBWEXWU2MN/) (related to US export controls) that has caused us to stop.  The 3.x line will continued to get theirs until June 1, but we made the decision that 4.x would never get them (only two releases were candidates).

**Comment by BenjaminBrandmeier** [comment]
Thanks for the quick reply @nebhale.
Since we are using PCF I found that Pivotal provides an offline version (https://network.pivotal.io/products/buildpacks#/releases/5657). So we will go with that.

**Comment by nebhale** [comment]
Wise 😄
