### ISSUE TITLE
Lots of exception cause app blocked

### ISSUE THREAD

**Issue by jiheyangying** [cloudfoundry/java-buildpack#445]
hi 
(java-buildpack version 3.13)
I got a problem, when java app call "e.printStackTrace()" in exception, and throw lots of exceptions, the app will blocked. When it happened, the warden status is right,but did not provide service. I get in warden call "jstack <pid>" and find that all threads of app are blocked by printStackTrace().And then,I find answer in warden and dea source code. Stderr can not received by log module. Fix file "lib/java_buildpack/container/tomcat.rb" can resolve the problem. Exchange “'run‘” to “'run 2>/dev/null | tee'” in line 46. I dont know if this problem is a real bug, if not, please ignore my issue.
Thank you very much!

**Comment by nebhale** [comment]
The contents of `stderr` are received by loggergator from all processes.  If you're having an issue there (note that Warden has been EOL'd) then you might post to the `cf-dev` mailing list for help.
