### ISSUE TITLE
"MEMORY_LIMIT" variable vs. "memory" manifest option

### ISSUE THREAD

**Issue by pushkaraj-ge** [cloudfoundry/java-buildpack#447]
`java-buildpack v3.6`

As per the docs, the `MEMORY_LIMIT` variable controls the total memory available to a service instance. We can also specify another memory limit using the [`memory`](https://docs.run.pivotal.io/devguide/deploy-apps/manifest.html#memory) property in manifest.yml or the `-m` option on `cf push`.

What is the relationship between these two values? Can we set them both to be exactly equal? Which one takes priority when one value is smaller than the other?

Thanks in advance!

**Comment by nebhale** [comment]
`$MEMORY_LIMIT` is the container manifestation of the `memory` property or `-m` on `push` or `scale`.  The environment variable is how applications know how much memory they can utilize before they are terminated.

**Comment by pushkaraj-ge** [comment]
Thanks for the quick response, @nebhale. I couldn't find much information about this, so making sure we use the right settings.

So the build-pack/application should work fine if we set both to the same value? Currently we have to set both separately - they don't pick up values from each other.

**Comment by nebhale** [comment]
No, you never set `$MEMORY_LIMIT` ever.  That value is updated, but the container based on what you've configured.  Setting it doesn't do anything other than confuse everything inside of the container.  Note when you set the value:

```
$: cf set-env java-main-application MEMORY_LIMIT 2G
Setting env variable 'MEMORY_LIMIT' to '2G' for app java-main-application in org bhale / space development as bhale@pivotal.io...
OK
TIP: Use 'cf restage java-main-application' to ensure your env variable changes take effect

$: cf restage java-main-application
Restaging app java-main-application in org bhale / space development as bhale@pivotal.io...
Creating container
Successfully created container
Downloading build artifacts cache...
Downloading app package...
Downloaded app package (21.4M)
-----> Java Buildpack Version: 95f52d1 | https://github.com/cloudfoundry/java-buildpack.git#95f52d1
...

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: ben-java-main-application.cfapps.io
last uploaded: Fri Jun 16 16:53:04 UTC 2017
stack: cflinuxfs2
buildpack: https://github.com/cloudfoundry/java-buildpack.git

     state     since                    cpu      memory         disk           details
#0   running   2017-06-16 09:57:00 AM   437.5%   792.1M of 1G   157.4M of 1G
```

The container still thinks that it's 1G and will continue to kill any process that exceed that, regardless of what you set `$MEMORY_LIMIT` to.  Scaling the container is how that value is changed:

```
$: cf ssh java-main-application -c 'echo "Memory Limit: $MEMORY_LIMIT"'
Memory Limit: 1024m

$: cf scale java-main-application -m 2G

This will cause the app to restart. Are you sure you want to scale java-main-application?> y

Scaling app java-main-application in org bhale / space development as bhale@pivotal.io...
OK
Stopping app java-main-application in org bhale / space development as bhale@pivotal.io...
OK

Starting app java-main-application in org bhale / space development as bhale@pivotal.io...

...

requested state: started
instances: 1/1
usage: 2G x 1 instances
urls: ben-java-main-application.cfapps.io
last uploaded: Fri Jun 16 16:53:04 UTC 2017
stack: cflinuxfs2
buildpack: https://github.com/cloudfoundry/java-buildpack.git

     state     since                    cpu      memory         disk           details
#0   running   2017-06-16 10:02:41 AM   307.5%   790.8M of 2G   157.4M of 1G

$: cf ssh java-main-application -c 'echo "Memory Limit: $MEMORY_LIMIT"'
Memory Limit: 2048m
```

**Comment by pushkaraj-ge** [comment]
Ah, I see. That makes sense. I'll update our settings.
Thanks again for your help. I'll close out this issue.

**Comment by nebhale** [comment]
No worries.

**Comment by sivabalans** [comment]
Hi Ben,
I spoke to you regarding this issue after your JBP session at the CF Summit. Here is my understanding of the MEMORY_LIMIT env variable. If my container size is 2GB as set by -m  or "memory" parameter in my manifest.yml, and if I set MEMORY_LIMIT to 1300M, the heap size distribution will be applied on top of 1300M and not 2GB. I understand your explanation above that there is no point in setting MEMORY_LIMIT greater than the container memory. But if its set to less than the container memory, it does seem to have some effect. Here is how I was able to prove it. 

With container memory at 2GB and MEMORY_LIMIT = 1300M, I restaged my service and below is my "cf app" output after it was restaged:
``
     state     since                    cpu    memory         disk           details
#0   running   2017-06-16 11:56:58 AM   0.7%   645.4M of 2G   214.5M of 1G
#1   running   2017-06-16 11:56:46 AM   0.1%   642.9M of 2G   214.5M of 1G
``

With container memory at 2GB and unsetting the MEMORY_LIMIT variable, I restaged my service and below is my "cf app" output after it was restaged:

``
     state     since                    cpu    memory         disk           details
#0   running   2017-06-16 11:53:01 AM   0.5%   794.1M of 2G   214.5M of 1G
#1   running   2017-06-16 11:52:51 AM   0.2%   779.1M of 2G   214.5M of 1G
``

Now, in the output above, the only way to explain the difference in the memory column is that, setting the MEMORY_LIMIT value does have an effect on how much memory is allocated to the heap. 

Please let me know your thoughts on it.
