### ISSUE TITLE
Update properties in introscope_agent.rb

### ISSUE THREAD

**Issue by DMevada** [cloudfoundry/java-buildpack#449]
Hi,

There is a new property available for the Introscope agent:

- `agentManager.url.1`

Essentially, what this property does is it contain the scheme (http/s), hostname, and port to connect to the Enterprise Manager (EM). For example, the new property can be specified as:

`agentManager.url.1=http://localhost:5001`

The scheme in this case is http, but can be any of the following:

- `http`
- `https`
- `ssl`

Can you update the `introscope_agent.rb` file (and any others that depend on it) to support this new property? 

Also, please do not change the current properties for host (`introscope.agent.enterprisemanager.transport.tcp.host.DEFAULT`) and port (`introscope.agent.enterprisemanager.transport.tcp.port.DEFAULT`), as those are required to handle the previous versions of the Introscope agent.

**Comment by nebhale** [comment]
The inputs into the buildpack are defined by the service broker or user provided service.  Today, that credential payload is documented as [this](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-introscope_agent.md#user-provided-service-optional).  Based on those inputs, the set of properties that cover scheme host and port are already available.  What is the advantage of changing the expected payload to set a property who's components are already covered?

**Comment by DMevada** [comment]
The current "host-name, port" as specified in the link will not change.

$ cf cups -p "host-name,port"  <------------- Remains as is
 
It is the property that these credentials are mapped to, that should change.
Currently, host-name will map to the property 

"introscope.agent.enterprisemanager.transport.tcp.host.DEFAULT"

And the port will map to the property 

"introscope.agent.enterprisemanager.transport.tcp.port.DEFAULT"

In addition to this mapping, to ensure that the java buildpack works with the newer versions of the agent, I am asking that host-name, port be combined and also mapped to the new property, agentManager.url.1

Something like this:

```Ruby
java_opts.add_system_property 'agentManager.url.1', host_name:port  if ...
```

If the user chooses to provide ssl, also map the ssl to the agentManager.url.1 property.

**Comment by nebhale** [comment]
So is are `introscope.agent.enterprisemanager.transport.tcp.[host | port | socketfactory].DEFAULT` properties being deprecated or removed?

**Comment by DMevada** [comment]
No, these properties are not being deprecated or removed.
These properties are required to work with the older versions of the agent. The newer property (agentManager.url.1), is used for handling newer versions of the agent.

There is no need to remove the older properties, because then older versions of the agent will not work. Since the same Java buildpack is used for both new and old versions of the agent, it is best to keep the older properties, while also adding support for the new property.

As an aside, in the future, is there any way to set additional properties, without having to open issues for each new property? What is the best way to deal with situations like this?

**Comment by nebhale** [comment]
There seems to be some contradiction in the statements

> No, these properties are not being deprecated or removed.

> The newer property (agentManager.url.1), is used for handling newer versions of the agent.

That seems to indicate that the properties are being deprecated and/or removed from the newer agents.

As far as setting additional properties, this is typically done by the providers as PRs to the buildpack itself.  In the absence of a provider owning the code, that responsibility falls to our team and we generally vet changes very carefully to ensure that there is no impact to existing customers.

**Comment by DMevada** [comment]
Oh I understand the confusion now.

On the agent side, the old properties for host and port are deprecated in the newer agents.
On the buildpack side however, since the same build pack supports different versions of the agent, we do not want to deprecate the old host and port properties, even though they are deprecated for the newer agents. 

This way, older agents use the older properties that are available in the buildpack, and the newer  agents use the new property.

Would you like to have a webex session with us, to go over any doubts/questions you might have?

**Comment by nebhale** [comment]
No need for a WebEx, my questions are now answered.  I'll schedule this in for update.

**Comment by DMevada** [comment]
Alright, thank you for scheduling this in for update.
When will this next release, 3.18, will be released?

**Comment by nebhale** [comment]
Later today probably.

**Comment by ptamma** [comment]
@DMevada Hi Dhruv, are there any plan to get Introscope agent added to Liberty Buildpack https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack ?? . Its good to have specially for private (on prem) CF deployments taking advantage of EM 10.+.

**Comment by DMevada** [comment]
Hi @ptamma,

Yes, we plan to add support for the liberty buildpack, amongst other CF related enhancements.
Please reach out to us in case you are interested, for early access builds.

What is your email address?

**Comment by ptamma** [comment]
Thanks for considering the request and message. my official email is
prashantvaddadi@hsbc.co.in

Regards, Prashant
