### ISSUE TITLE
Resource Exhaustion triggers Thread Dump

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/java-buildpack#451]
Currently, when resource exhaustion is reached, a histogram and an optional heap dump are created.  When exhaustion is reached, a thread dump should be triggered as well.

This issue is to investigate how easily this can be done and is split from the larger #70.

**Comment by nebhale** [comment]
@gberche-orange We've added a thread-dump to the buildpack.  The output looks like [this](https://gist.github.com/nebhale/f74b8363501b3ac2ecfb016fc8869166#file-thread-dump-log-L116).

**Comment by gberche-orange** [comment]
thanks @nebhale and @glyn ! This looks great.
