### ISSUE TITLE
What is the best way to get hs_err_pid log for JVM crash in cloud foundry ?

### ISSUE THREAD

**Issue by pradeepkusingh** [cloudfoundry/java-buildpack#455]
Currently, one of my apps keeps crashing and profiler and thread dumps don't have much details. It is crashing with OOM and when I ran Visual VM, I don't see any leak(seeing only 1.2 GB of memory usage out of 3 GB). I am suspecting it is JVM crashing and might be generating a hs_err_pid file.. how to gather it in cloud foundry world? How to get heap dump any link ?

**Comment by pradeepkusingh** [comment]
any help would be highly apprecaited.

**Comment by nebhale** [comment]
Using one of the 4.x build packs will [now generate a heap histogram on OOM](https://www.cloudfoundry.org/just-released-java-buildpack-4-0/).  In addition, the latest version of the buildpack ([4.2](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.2)) supports the [writing of heap dumps to Volume Services](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#jvmkill).
