### ISSUE TITLE
Consider exposing number of configured threads to application

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#456]
Perhaps an environment variable or system property?  So, that applications who wish can configure themselves to function properly within the number of threads the java buildpack calculated for the app.

It might also be a good idea to automatically configure a tomcat thread pool for .war artifacts taking into account the number of threads configured in the java buildpack.

Doing so may make it easier to scale down the base memory footprint.  This may also eventually make it possible to scale down the default from 300 to less threads.

**Comment by nebhale** [comment]
It's a good idea and I'll give it some thought, but the tough bit is that there are a ton of "unaccounted" for threads.  If I told the application that I'm expecting 300, the application would need to know how to divvy those up across of it's thread pools.  This is not only the container and the connection pools (coordinating that would be hard enough), but GC threads, main thread, etc. from the JRE.

Since it's the one thing we *can't* predict from the application itself, I think there's value in exposing our assumption at runtime, though so we'll do something with this.

**Comment by youngm** [comment]
I can see how this could get complicated and may not be worth the effort to do anything.  But it is also very tempting to try. :)

I've provided a slightly more in depth (and probably overly involved) proposal for you to consider as you think through it.

## Proposal

The buildpack would provide the application (via, ENV, System Property, other) the number of threads it believes should be available to the application code to do with as it pleases.  It would come up with this number by reducing the memory calculator configured threads with numbers provided by the jre and detected container and frameworks.  The individual components can come up with their thread needs however they want.  Either from configuration, or automatically.

In the case of the JRE it may be best to simply use a configurable best guess thread count that is a safe guess including main thread, GC Threads, code compilation thread, etc.

In the case of tomcat we can add a configuration value for the number of request handling threads we want tomcat to have.  The container would add to that any other "system" threads it uses and provide that value.  The container would configure its server.xml with the number of request threads configured.

App Dynamics takes a thread or 2 and provide its needs, etc.

In the end the jre would fail the buildpack if the number of threads calculated is more than the number of threads configured by the memory calculator.

The difference would then be made available to the application.

**Comment by youngm** [comment]
Thinking about this a little more.  It probably makes more sense for the application to tell the buildpack how many application threads it needs rather than the buildpack tell the application how many threads it can use.  The buildpack would then add onto the number of application threads, the number of threads the buildpack is aware of (e.g. Container, frameworks, etc).  A default number of application threads could be configured on the buildpack.  I think this approach is conceptually simpler and more straight forward.

The problem is the default number of application threads may vary greatly depending on the container used.  A tomcat application may require only a handful, if any, application threads because the tomcat container would provide most execution threads needed.  But, a spring boot app would need to consider tomcat threads as part of its allotment of application threads.

So, although I think it makes more sense for the application to declare the number of application threads it needs it could lead to less efficient memory utilization rather than more.  But, another approach to consider.

**Comment by nebhale** [comment]
Well, we do kind of do that already, right?  It's verbose, but `cf set-env <APP> JBP_CONFIG_OPEN_JDK_JRE '{memory_calculator: {stack_threads: 100}}'` is the application declaring the number of threads it needs to run.  It does need to take into account Tomcat's threads if it's a WAR, but that default is the same as in Spring Boot (200).

**Comment by youngm** [comment]
Yeah, I was thinking the same thing. :)  This setting combined with the addition of a Tomcat thread configuration might be enough to satisfy my needs.  Though that would be not as optimal of a situation as I'd like to get to.  Allow me to keep spewing my thoughts a bit more as I continue work through this myself.

So, my main goal in this request is to make it reasonably straight forward for applications to tune their memory.  The 200 default today may work well enough for Tomcat containers and spring boot applications using tomcat.  But the story is less direct for customers to use less tomcat threads or for spring  boot applications that want to be reactive with a netty server.

Anyone who wants to reduce the number of threads needs to know how to change tomcat config to use less threads (not possible today without a fork), how many threads it should reserve for the jvm, how many threads it should reserve for App Dynamics or other buildpack provided frameworks they may be using.  It would be nice if the buildpack could help reduce the number of things a user had to calculate to come up with a thread count for memory calculations.

Continuing to think through this here is another proposal. (That again I acknowledge may be too complex for the benefit provided trying anyway.)

## Proposal 2.0

Essentially this proposal moves user configured thread counts to container configuration.  Adds a mechanism for frameworks and jres to declare how many threads they need in ways they deem appropriate.  Use the sum of the detected container, jre, and frameworks to arrive at a thread count for memory calculations.

* For JRE perhaps add a configurable thread count (with a default) to the JRE that would include typical base overhead for any jre application.
* For tomcat containers perhaps add 2 configurations.  One for Tomcat request processing threads and another for application threads.  Set the server.xml to the request processing value.
* For Spring boot containers have a single configurable value for "threads". (Could default to something safe that assumes use of tomcat).  But easily changed for boot apps that don't use tomcat.
* Do similar for the other containers.
* Allow for each detected framework to provide to the buildpack the number of threads they require.
* Add up the provided JRE, container, and framework threads to get the thread count to be used in memory calculation.

If I am a tomcat user and have a simple low load app I can easily set the number of tomcat executor threads to a low number and set application threads to near 0 if I know my app doesn't create any threads.  This is relatively simple because I don't need to worry about trying to figure out how many threads the JRE or other frameworks may be using because they're already factored in.

If I am a spring boot user using netty and doing everything async I can simply configure the spring boot container to allocate the number of threads I know my netty server will use.  Again, I won't need to worry about calculating overhead for JRE, or other frameworks because the buildpack will take care of that.

Thoughts?

**Comment by nebhale** [comment]
In practice I don't think this has ended up being necessary for this buildpack.  Rather than continue to let this dangle, I'm going to close this out.  If you think that there's a compelling reason for me to reopen let me know.
