### ISSUE TITLE
Java-Main - Failed to start accepting connections

### ISSUE THREAD

**Issue by Samuel1989** [cloudfoundry/java-buildpack#46]
Hi,

I have created a simple hello world executable jar and have pushed this to a CloudFoundry instance using the java-buildpack, which has resulted in the application failing to stage.

The "hello world" print is available in the logs which indicates that the java-main container has been used and the jar has been executed, however, the application fails to stage with "failed to start accepting connections".

From what I have read there is no prerequisite step(s) in configuring your application to accept connections.

I may have completely misunderstood the user scenario for the java-main support, any information you could provide on this would be greatly appreciated.

Thank you,
Sam

**Comment by petermumford** [comment]
I've been having this issue for days in **Ruby** until I came across @nebhale comment mentioning about the root URL (i.e. `/`). Thank you! I was using a very simple Rack app but now using Sinatra which gives me the root url. Now its all working. 

I can't believe this is still a problem, over 3 years later.
