### ISSUE TITLE
bluemix java application cannot be deployed anymore with latest version

### ISSUE THREAD

**Issue by jboissard** [cloudfoundry/java-buildpack#460]
We have had a java application that's been running on bluemix for more than a year that we update periodically (a few times a week). In the last few days however, even though the build is successful, we cannot launch it. The error is the following (we never saw this before):

```
App/0 Error occurred during initialization of VMJul 10, 2017 12:13:14.002 PM
App/0 Could not find agent library /home/vcap/app/.java-J-buildpack/open_jdk_jre/bin/jvmkill-J-1.9.0_RELEASE in absolute path, with error: /home/vcap/app/.java-J-buildpack/open_jdk_jre/bin/jvmkill-J-1.9.0_RELEASE: cannot open shared object file: No such file or directory
```

The deploy cmd is

```
cf push "${CF_APP}" -p target/universal/myapp-SNAPSHOT.zip -b https://github.com/cloudfoundry/java-buildpack.git -k 2G
```

The problem is solved by using `#e0915ee`

https://stackoverflow.com/questions/45021795/bluemix-java-application-cannot-be-deployed-anymore

**Comment by nebhale** [comment]
What kind of application are you running?

**Comment by jboissard** [comment]
It is a jar (compiled from scala sources - play framework) on bluemix DEA

jar is output of : https://www.playframework.com/documentation/2.5.x/Deploying#Using-the-dist-task
