### ISSUE TITLE
Bluemix Java application cannot be deployed

### ISSUE THREAD

**Issue by MukulSharma2007** [cloudfoundry/java-buildpack#462]
I have a Java application running on Play framework for past 8 months. Since last week, we are not able to deploy the application. The cmd command we are are using is:
cf push apadev -p apadev-1.0-SNAPSHOT.zip -b https://github.com/cloudfoundry/java-buildpack.git

The error message we are getting:
 ERR     Cloning into '/tmp/buildpacks/java-buildpack'...

App/0 Could not find agent library /home/vcap/app/.java-J-buildpack/open_jdk_jre/bin/jvmkill-J-1.9.0_RELEASE in absolute path, with error: /home/vcap/app/.java-J-buildpack/open_jdk_jre/bin/jvmkill-J-1.9.0_RELEASE: cannot open shared object file: No such file or directory

App/0 Error occurred during initialization of VM

App/0

DEA/34 Instance (index 0) failed to start accepting connections

**Comment by nebhale** [comment]
His is being tracked in #460.  Please follow the progress there.
