### ISSUE TITLE
Tomcat access logs are not getting dumped

### ISSUE THREAD

**Issue by souveekbose** [cloudfoundry/java-buildpack#463]
I need to ensure that relevant inforamtion and no sensitive data is being dumped in DEA by tomcat's access logs. However, I nothing is being written to the access logs. I checked this path:
_/var/vcap/data/warden/depot/<warden_handle_id>/tmp/rootfs/home/vcap/app/.java-buildpack/tomcat/logs_
My valve configuration in server.xml is:
`<Server port='-1'>

    <Service name='Catalina'>
        <Connector port='${http.port}' bindOnInit="false" proxyPort="443" scheme="https" secure="true"/>

        <Engine defaultHost='localhost' name='Catalina'>
            <Valve className='org.apache.catalina.valves.RemoteIpValve' protocolHeader='x-forwarded-proto'/>
            <Valve className='com.gopivotal.cloudfoundry.tomcat.logging.access.CloudFoundryAccessLoggingValve'
                   pattern='[ACCESS] %{org.apache.catalina.AccessLog.RemoteAddr}r %l %t %D %F %B %S vcap_request_id:%{X-Vcap-Request-Id}i'
                   enabled='${access.logging.enabled}'/>
            <Host name='localhost'
                  failCtxIfServletStartFails='true'>
                <Listener className='com.gopivotal.cloudfoundry.tomcat.lifecycle.ApplicationStartupFailureDetectingLifecycleListener'/>
            </Host>
        </Engine>
    </Service>

</Server>
`
Buildpack version: 3.17
Please let me know if there is any configuration miss or if more info is required on this. Thanks in advance.

**Comment by nebhale** [comment]
In Cloud Foundry, the filesystem is ephemeral and therefore it is unsafe to log anything to it.  Therefore all logging is sent to either `stdout` or `stderr`, which are captured by the platform and presented to the user via `cf logs` or sent to a log warehouse via a syslog service binding.  The access logs are no different; they [print to `stdout`](https://github.com/cloudfoundry/java-buildpack-support/blob/master/tomcat-access-logging-support/src/main/java/com/gopivotal/cloudfoundry/tomcat/logging/access/CloudFoundryAccessLoggingValve.java#L34) and can be viewed with `cf logs` or in your log warehouse with via a syslog service binding.

**Comment by souveekbose** [comment]
@nebhale neither cf logs nor the service binding (to elasticsearch) is printing the logs. Is there any config in cloudfoundry that is preventing this?

**Comment by nebhale** [comment]
Nope, we have many people already using this functionality (it is [the default](https://github.com/cloudfoundry/java-buildpack/blob/master/resources/tomcat/conf/server.xml#L25) for all WARs).

**Comment by nebhale** [comment]
Actually I'm wrong on a couple of counts.  You do actually have to [enable it](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#configuration).  In addition, it's never been updated for Tomcat 8+ (it was created for a user on Tomcat 7).  [This change](https://github.com/cloudfoundry/java-buildpack-support/commit/fe3cf21c65287129c6f6eb364dbdfb79d72f4a0c) fixes it and a release will be forthcoming.

**Comment by mrkk** [comment]
I have a reverse problem, I see access logs by default and I dont want to
