### ISSUE TITLE
Extend memory calculator options to set class_count 

### ISSUE THREAD

**Issue by j-musca** [cloudfoundry/java-buildpack#464]
Currently I am only able to set the the number of threads via "stack_threads" option like this.

`JBP_CONFIG_OPEN_JDK_JRE: "{memory_calculator: { stack_threads: 40 }}"`

It would be nice to also set the number of loaded classes via "class_count" option (it already exists in the memory calculator).

Example:
`JBP_CONFIG_OPEN_JDK_JRE: "{memory_calculator: { stack_threads: 40, class_count: 1000 }}"`

**Comment by nebhale** [comment]
As described in the [documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory), this can already be set.  Your example already works today.

**Comment by j-musca** [comment]
@nebhale I would not have created this issue if it would work. :)

Using the options like in the example results in a warning during deployment of my app.

`[ConfigurationUtils]             WARN  User config value for 'class_count' is not valid, existing property not present
-----> Java Buildpack Version: v4.2 | https://github.com/cloudfoundry/java-buildpack.git#5f4dbd7`

And I checked the code and did not find any "logic" that would handle the "class_count" option.

**Comment by nebhale** [comment]
The code that handles `class_count` from the configuration is [here](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/jre/open_jdk_like_memory_calculator.rb#L83).  The environment variable style configuration is equivalent to the YAML-based configuration (this is why the naming is a perfect match to the files), so anything you can configure with one, you can configure with the other.  There may be a bug, so I’ll leave this open and investigate.
