### ISSUE TITLE
GZIP Non-Embedded Tomcat

### ISSUE THREAD

**Issue by jonathanamartin** [cloudfoundry/java-buildpack#465]
I know the mantra is make "JAR not WAR".  However, we have a need to use the non-embedded Tomcat found in the Java buildpack so we can quickly patch Tomcat for all applications on our PaaS.

What would you think about adding a configuration to enable/disable GZIP compression on the non-embedded Tomcat?

**Comment by nebhale** [comment]
You should either fork the buildpack and define a `server.xml` or use the support for [External Tomcat Configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#external-tomcat-configuration).

**Comment by jonathanamartin** [comment]
I'll look at a fork for now.  Thanks.
