### ISSUE TITLE
Provide JDBC database URL environment variable

### ISSUE THREAD

**Issue by samcrang** [cloudfoundry/java-buildpack#467]
For Java applications that don't support automatic configuration of database connections it would be useful to be able to read a JDBC URL from the environment without having to additionally parse JSON from `VCAP_SERVICES`.

[Heroku provides a `JDBC_DATABASE_URL` environment variable](https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-jdbc_database_url) for this purpose.

Is this something that makes sense for the `java-buildpack` to also provide?

Thanks,

**Comment by nebhale** [comment]
It is not something that the buildpack could also provide.  Service credentials, including a possible `JDBC_DATABASE_URL` are managed by the [cloud controller](https://github.com/cloudfoundry/cloud_controller_ng/issues).  You can request this feature with that project, but I seem to remember that not only did we have something like this in the past (`DATABASE_URL` I believe), but it was intentionally removed.
