### ISSUE TITLE
Contributing to java-buildpack 

### ISSUE THREAD

**Issue by chook** [cloudfoundry/java-buildpack#471]
Hi,

I would like to sign the Contributing Licensing Agreement for my pull request.

Thanks

- Chen

**Comment by nebhale** [comment]
On submission of a PR the @cfdreddbot will leave instructions in your PR (like [this](https://github.com/cloudfoundry/java-buildpack/pull/470#issuecomment-317117861)) about how to sign a CLA.

**Comment by chook** [comment]
Thanks @nebhale i'll go ahead and submit my PR.

P.s. not sure if I'm misinterpreting your tone, but the https://github.com/cloudfoundry/java-buildpack/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement did point me into creating this issue. Perhaps it make sense to change the doc and explain about the (new?) process
