### ISSUE TITLE
Java Buildpack v4.0 has AppDynamic version 4.3.x instead of 4.2.x

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry/java-buildpack#474]
Hi Team, though the release note says AppDynamics v 4.2.15_2 shipped with [java buildpack_v4](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.0), we are getting AppDynamic v 4.3.3_6 after pushing the code. Please check the attached image. 

![appd-java-4](https://user-images.githubusercontent.com/9046793/28944289-0ab6950a-7870-11e7-985c-fd3f7fffa2f3.jpg)

Is there something we are missing here?

Thanks,
Chandan

**Comment by nebhale** [comment]
4.0 was definitely fixed to [`4.2.15_2`](https://github.com/cloudfoundry/java-buildpack/commit/5f5c4b1e6ce11ad951cb65f06cf3a93074a9a712).  4.1 has [`4.3.1_3`](https://github.com/cloudfoundry/java-buildpack/commit/c1cf7c93554351b179d52bb7c46ddb3bc8694465), 4.2 has [`4.3.2_2`](https://github.com/cloudfoundry/java-buildpack/commit/aeb5a89495be4fc4a112502f200ef8caaa6d23b9), and 4.3 has [`4.3.3_3`](https://github.com/cloudfoundry/java-buildpack/commit/3c06df42d3ba7433c77bb987ccb874526b4866bf).

If you’re using an online buildpack you’ll get a version from [the repository](https://packages.appdynamics.com/java/index.yml), governed by the [version wildcard](https://github.com/cloudfoundry/java-buildpack/blob/master/config/app_dynamics_agent.yml#L18).  Given that you’re using 468dbff which is not a tagged release, this is almost certainly the case.

**Comment by nebhale** [comment]
That's not an offline buildpack.  As you can see from [previous releases](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.17) offline buildpacks are specifically labeled as such.  As [directed by the Cloud Foundry Foundation](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/SN5AW5SUAMHDQAAPU45AURTBWEXWU2MN/) offline buildpacks are no longer distributed as of 1 June, 2017.

**Comment by eodchop** [comment]
Ben, can we specify version: wildcard '4.2' instead of version: '4.+', or how would that look, if we want to specify a specific version?

Best,
Ryan S.

**Comment by nebhale** [comment]
@eodchop `4.2.+` would be a reasonable wildcard version.  You can see the documentation that [describes the wildcard scheme](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md#version-wildcards) and [how to configure](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension).

**Comment by nebhale** [comment]
No problem.
