### ISSUE TITLE
Introscope Agent service broker?

### ISSUE THREAD

**Issue by DMevada** [cloudfoundry/java-buildpack#477]
Hi @nebhale,

Is there a way to create a service broker that automates the introscope agent deployment?
Does it have anything related to the buildpack?
I was thinking, if I can somehow integrate the service broker with the buildpack, it would simplify the configuration process for our end users.

Thanks,

-Dhruv

**Comment by nebhale** [comment]
Absolutely you can, and I'd highly recommend it.  Can you please [email me](mailto:bhale@pivotal.io) and I'll put you in touch with a team that can help you get going.
