### ISSUE TITLE
Support service lookup by service name/label/tag in combination with needed credentials

### ISSUE THREAD

**Issue by stipx** [cloudfoundry/java-buildpack#489]
In order to be able to define multiple services with the same name pattern, but with different credentials we would need a service lookup which filters by service name/label/tag and mandatory credentials in combination.

The current implementation (in `Services.one_service?`) first looks up exactly one service with a name pattern and afterwards checks if this one service has the needed credentials set. If more services match the name pattern it return false even though only one service with the given pattern and needed credentials would be present.
What we would need: Be able to match multiple services by name, but only one containing the needed credentials.

Additionally it would be needed to get a service selected by these criterions to be able to read its credential values. `Services.find_service` only takes the name pattern and returns the first match without taking the needed credentials into account.

Example code:
```
    candidates = @application.services.select do |candidate|
          (
            candidate['name'] =~ regex_filter ||
            candidate['label'] =~ regex_filter ||
            candidate['tags'].any? { |tag| tag =~ regex_filter }
          ) &&
          candidate['credentials']['credential1'] && candidate['credentials']['credential2']
        end
```
if above code results in exactly one service contained in `candidates` it would be considered as "service found".

As reference: #487

**Comment by stipx** [comment]
@nebhale Is there anything I can/should provide to get this in?

**Comment by nebhale** [comment]
Nope, just fell behind some other pressing matters.  On it today for the 4.6 release this afternoon.

**Comment by stipx** [comment]
Thanks for closing this.
I've just seen that the line
https://github.com/cloudfoundry/java-buildpack/blob/88b210e1c68740a05525179029a33925a2c2f632/lib/java_buildpack/framework/dynatrace_one_agent.rb#L49
was not changed.
Should I create a PR or Issue?

**Comment by nebhale** [comment]
Damnit, thought I'd gotten them all.  Let me do it now.

**Comment by stipx** [comment]
No worries. Thanks for the fast fix.
