### ISSUE TITLE
Not able to push spring boot app through cmd

### ISSUE THREAD

**Issue by Meghajit** [cloudfoundry/java-buildpack#491]
I made a simple spring boot app using STS IDE. I am able to push the app to PCF from the IDE, however when I try to push from the cmd prompt, it gives an error -
No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.
Failed to compile droplet: Failed to run finalize script: exit status 1.

Any help is appreciated.

**Comment by nebhale** [comment]
If I had too guess, you’re probably pushing the source folder for your application.  The Java Buildpack expects fully compiled artifacts (JARs, WARs, DistZips, etc.) to be pushed, not source folders.  You can look at the [documentation for the container types](https://github.com/cloudfoundry/java-buildpack#additional-documentation) which indicate what kinds of artifacts can be run.  Note that this fact (that we expect compiled binaries) is hidden by the STS interface; it transparently packages up what’s necessary and sends it along.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
