### ISSUE TITLE
How to specify Spring Boot Cloudfoundry Actuator Endpoint

### ISSUE THREAD

**Issue by sworisbreathing** [cloudfoundry/java-buildpack#492]
Relevant to the discussion on spring-projects/spring-boot#9081, if I have specified a different `server.context-path`, how do I tell Cloudfoundry to use `/my-context-path/cloudfoundryapplication` for the actuator endpoint instead of just `/cloudfoundryapplication`? I can't seem to find where this is specified in the Java buildpack.

**Comment by nebhale** [comment]
You cannot.  First and foremost Cloud Foundry Actuator integration is handled by the Apps Manager application.  It expects to be able to hit a particular URI from your web browser (properly secured of course) and the buildpack is unaware of this fact.  I don’t believe that we’ve got any plans for Spring Boot to be able to expose a change to that location through the internals of Cloud Foundry (adding something that Spring Boot-specific is justifiably a non-starter) so https://github.com/spring-projects/spring-boot/issues/9081 is the only real solution.  Apps Manager needs to be able to access its endpoints at a dependable well-known location, regardless of user configuration.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
