### ISSUE TITLE
EclipseLink Cluster Cache

### ISSUE THREAD

**Issue by jimpete** [cloudfoundry/java-buildpack#496]
Have any of you implemented the [EclipseLink Cluster cache](https://wiki.eclipse.org/EclipseLink/Examples/JPA/CacheCoordination) in support of instance scaling or as part of the blue-green deployment?  If yes, what were your investigation results?  

Since JNDI is not replicated across instances, does that only leave the Spring containers for destinations for RMI cluster cache coordination?  Would you recommend RabbitMQ for this coordination?  What about JGroups?

_Background: EclipseLink L2 cache maintains datastore objects in (an instances) memory to be shared by multiple sessions.  When scaling out a java-buildpack's service using a JPA managed datastore, it is important to either turn off the L2 cache (all together or by table) or implement notifications so that every instance of the service knows when to invalidate their L2 cache for specific objects. This prevents the services from working with stale or outdated objects._

_By implementing cluster cache coordination of the L2 cache through a Message Service, RMI, or JGroups, the L2 cache remains an important performance improvement._

**Comment by jimpete** [comment]
Well, since no one has done it may I suggest initiating the cluster cache by obtaining a restful host and port for each of the application instances using the [CF API /v2/apps/{guid}/stats](https://apidocs.cloudfoundry.org/272/apps/get_detailed_stats_for_a_started_app.html)
Then initiating cluster caching with restful interfaces between microservice instances?

**Comment by jimpete** [comment]
No Interest in this topic.  Closing discussion.

**Comment by zhrm0110** [comment]
Hi @jimpete , 

Is there any update for this issue? Recently I'm looking for the method to adapt eclipselink cache coordination for multi application instances. Do you have any idea on this topic?

Thanks a lot.
Rina
