### ISSUE TITLE
Problems with auto class calculator and custom packaging types

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#499]
In our forked buildpack we have a custom application packaging types that don't work well with the new auto class calculator.

The custom packaging type allows for users to deploy 1 or more .war files that get placed in a tomcat container.  Currently the class counter doesn't look inside of .war files let alone .jar files inside of .war files.  Now, I know this isn't really a JBP issue but it did expose some interesting edge cases that I wanted to present to the project.

I first thought; Not a problem we'll just have these users specify `-XX:MaxMetaspaceSize` and they'd be good to go.  However, we quickly discovered that we need to also specify some value for `-XX:CompressedClassSpaceSize` because that is also poorly auto calculated with the count classes failure.  This caveat was not very obvious to my users.

Should the jbp attempt to be smart here and know, if the user specifies a custom MaxMetaspaceSize and not a CompressedClassSpaceSize, auto calculate CompressedClassSpaceSize from the provided MaxMetaspaceSize instead of the class count?  And vise versa?  Not a big deal but could help reduce pain for users who are providing a useful value because they already know the class count logic won't work for them?

Or, I'm just throwing that out there, could the class counting logic be enhanced to support nested .wars, .ears, .rars, .jars, etc.?  Could help more generally handle other weird use cases?  For example, perhaps there is a JBoss that supports deploying .ears that might benefit from this?   I know this is a long shot but thought I'd throw it out there as a possible option. :)

**Comment by youngm** [comment]
I'm aware these users could also provide a custom class count value through `JBP_CONFIG`.  However, this value is difficult for users to calculate.  My users tend know how much metaspace they want.  They don't really know how many classes their app has or the formula the JBP uses to determine metaspace from that number.

**Comment by youngm** [comment]
Does CompressedClassSpaceSize even need to be set to anything other than the default of 1gb?  This document seems to think that MaxMetaspaceSize sets a limit for compressed class space and class metadata:

> The MaxMetaspaceSize applies to the sum of the committed compressed class space and the space for the other class metadata.

https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/considerations.html

**Comment by nebhale** [comment]
@youngm We do [actually look inside of archives](https://github.com/cloudfoundry/java-buildpack/blob/ed12cde6167a4be216cdc45297c3a5e169717f11/lib/java_buildpack/jre/open_jdk_like_memory_calculator.rb#L74) (albeit ones ending in `.jar` which could be loosened) for class counts.  I believe that if your custom packaging pre-exploded your your WARs, etc. the class counter would do the right thing (for at least one level down).  I’d also argue that this pre-exploded is actually the right thing to do as it speeds up startup time for the droplet; no need for each instance to go through multiple identical unzips on each start.

**Comment by youngm** [comment]
Thanks for your input @nebhale .  I was hoping not to touch this legacy format too much, but, I agree exploding the .wars is probably the right route to take.  I'll leave the issue open if you and @glyn want to further consider .ear like use cases or if `CompressedClassSpaceSize` is a value you need to customize or not.  Thanks.

**Comment by youngm** [comment]
Thinking about the `CompressedClassSpaceSize`.  I had an app that recently moved to jbp4 run out of metaspace.  The jbp detected a `CompressedClassSpaceSize` of ~32M.  If it is true that CompessedClassspace does go into Metaspace then that could mean that Metaspace in the jbp is currently being under allocated.  I'm pretty confident that adding another 32M to the detected Metaspace size for this application would have resulted in enough Metaspace for it to run stable.

**Comment by glyn** [comment]
@youngm I've been playing with and thinking about the relationship between compressed class space and metaspace. Even if compressed class space is included in metaspace, which I cannot really confirm or refute by experiment, I believe the memory calculator calculations of compressed class space and metaspace size are reasonable. That's because they were based on measuring these (among other) values for various applications and then extrapolating formulae. 

I suppose one possible downside of setting `-XX:CompressedClassSpaceSize` to a value which approximates the amount of compressed class space needed is that an application that needed more than the expected amount of compressed class space but which had metaspace to spare would still hit `OutOfMemoryError: compressed class space`. But this, hopefully rare, problem can be solved by setting, e.g. `-XX:CompressedClassSpaceSize=1g`. The upside of this behaviour is that it enables the user to differentiate between running out of compressed class space and running out of (other) metaspace.

In terms of your app that ran out of metaspace, my guess is that it is simply hungrier for metaspace than the memory calculator expects and that you therefore need give it some more metaspace by overriding `-XX:MaxMetaspaceSize`.

That all said, if compressed class space _is_ included in metaspace, the memory calculator calculates the heap size (`-Xmx`) incorrectly because it subtracts **both** compressed class space and metaspace from the available memory when calculating the heap size. However, on the sample applications I measured, and therefore also in terms of the memory calculators estimations, compressed class space is usually less than 1% of the heap size and never more than 1.2% of the heap size, so the impact of any miscalculation on heap size is minimal. If we can confirm independently of [1] that compressed class space is included in metaspace, we could adjust the memory calculator to avoid subtracting metaspace when calculating the heap size.

[1] https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/considerations.html

**Comment by youngm** [comment]
@nebhale A quick update on this.  I updated our buildpack fork to unzip the .war files and I think that works well.  One hiccup, it appears the `compile` phase jre memory calculator is run before the container `compile` phase is executed.  This causes staging to log an incorrect class count.  Luckily the class count is recalculated during `release` so everything works out well.  But, I thought I'd let you know of that caveat in case you ever consider caching the class count done at compile time to improve release performance or something.

If it were possible for the `compile` time memory calculator to run after container `compile` so that the buildpack displayed an accurate class count that would be great, but, not not a high priority.

**Comment by nebhale** [comment]
@glyn 
> That all said, if compressed class space is included in metaspace, the memory calculator calculates the heap size (-Xmx) incorrectly because it subtracts both compressed class space and metaspace from the available memory when calculating the heap size.

is my biggest concern really.  Given the beating I take a couple of times a week on how big a JVM container has to be, trimming it at all is always good.  That being said, if we can't work out the answer definitively, then I favor being conservative with our calculation. 

What's preventing you from experimentally confirming this?  Just unable to create an application that generates a sufficient amount of usage of `CompressedClassSpace`?

**Comment by glyn** [comment]
@nebhale The worry I have is that I can generate `OutOfMemory: compressed class space` by lowering the compressed class space size, but what I really want to know is whether making compressed class space size large (e.g. 1g) and restrictiing max metaspace size can also produce an `OutOfMemory: compressed class space`. So far my experiments have ended in `OutOfMemory: metaspace` or equivalent. So I need an application that consumes lots of compressed class space but relatively small amounts of metaspace. I haven't explored this seriously yet, but do you have any suggestions off the top of your head?

**Comment by youngm** [comment]
@glyn I believe `CompressedClassSpaceSize` is used to store pointers when `UseCompressedClassPointers` is true.  If you create a test with a bunch of classes and compare metaspace size with `UseCompressedClassPointers` is on and off perhaps that might tell us?

**Comment by youngm** [comment]
The above assumption can also be validated by turning off/on `UseCompressedClassPointers` and setting `CompressedClassSpaceSize` to a very low value and see if we run out of compressed class space size when off?

**Comment by glyn** [comment]
@youngm If we turn off `UseCompressedClassPointer`, then I would imagine that any class pointers in metaspace would be implemented differently, so I'm not sure what the experiment could tell us. Or am I missing something?

**Comment by youngm** [comment]
@glyn I suppose you're right.

**Comment by youngm** [comment]
At this time of this blog's writing CompressedClassSpaceSize was a different memory space though he mentions merging it with MetaSpace as a possible enhancment in the future.

http://java-latte.blogspot.com/2014/03/metaspace-in-java-8.html

**Comment by youngm** [comment]
OK, I think I can confirm that Metaspace and CompressedClassSpaceSize are managed separately despite what the oracle doc says.

If I set `-XX:MaxMetaspaceSize=35000K` a value too low for the application to load.  In this case `jvmkill` produces a memory dump.  In that memory dump If compressed class pointers is enabled I see:

```
Metaspace       used 34049K, capacity 34422K, committed 34992K, reserved 49572K
class space    used 4209K, capacity 4379K, committed 4528K, reserved 18852K
```

Notice that Metaspace and class space (the memory region that holds compressed class pointers) add up to a value much higher than 35000K.  To be double sure I turned off compressed pointers by adding ` -XX:-UseCompressedOops -XX:-UseCompressedClassPointers` to `JAVA_OPTS`.  Now when the application dies all I see is:

```
Metaspace       used 34096K, capacity 34504K, committed 35000K, reserved 36864K
```

Metaspace has a value very similar to the one when compressed pointers is enabled.  Also note the lack of a class space entry since compressed pointers was turned off.

I think this is enough evidence to show that the oracle article I referenced is either wrong or I misunderstood it and the JBP is right to reserve metaspace and compressed pointers separately and that this issue can now be closed.  Any objections?

**Comment by glyn** [comment]
@youngm I don't think that evidence supports your conclusion. If compressed class space is included in metaspace:
1. It's not appropriate to add the two values together in the first memory dump because that would count compressed class space twice.
2. All we can observe is that metaspace committed has (nearly) reached its limit and compressed class space has contributed 4528K towards the committed metaspace value. 

So the jury is still out. I've been pondering this and I think it would be reasonable to assume that the Oracle document is correct _and cite that_ in jvmkill's documentation (and in the memory calculator's documentation). Would you be comfortable with that @youngm & @nebhale?

**Comment by youngm** [comment]
@glyn Dang! You're right again.

You are right.  In the memory example they provide in the same document they do show compressed class space tabbed in under Metaspace:

```
  Metaspace       used 2425K, capacity 4498K, committed 4864K, reserved 1056768K
    class space   used 262K, capacity 386K, committed 512K, reserved 1048576K
```

> Would you be comfortable with that?

So, other than documentation changes what other changes might assuming this information mean to jvmkill and the memory calculator?

* Letting compressed class size go back to default?  So, users only have one nob to twist for class loading.
* Not including it in the overall memory calculation?
* Not adding hints for class in jvmkill to increase this value?

Does @ipsi have any thoughts?

**Comment by glyn** [comment]
@youngm I agree with the first two bullets, but I think we should implement the hint in case the user sets the compressed class space size to too low a value. Users are so unpredictable.

**Comment by nebhale** [comment]
I'm just barely hanging on to this discussion, so just double check me here based on @youngm's bullets

* The default is variable, but is based on the meatspace, which we are still in control of.
* Yay, 20M regained!
* The hint would be, if it's at 95%, warn the user so that they can then set it

**Comment by youngm** [comment]
@nebhale I think the default for `CompressedClassSpaceSize` becomes the jvm default.  The buildpack doesn't worry about it anymore.  Metaspace calculation doesn't change.  20M regained

**Comment by nebhale** [comment]
Right, bullet one was more that the default couldn’t ever be larger than the `metaspce`, right?  Staying with the JVM default wouldn’t cause us to miscalculate.  By controlling the `metaspace` value, we’re _effectively_ controlling the `CompressedClassSpace` value, even if we aren’t setting it directly?

**Comment by youngm** [comment]
Right.  That is my understanding.

**Comment by nebhale** [comment]
OK, then let’s go with this.  Let’s remove the `CompressedClassSpace` from the calculation complete, but leave it in for hinting.  If there are any other memory spaces that we don’t hint on, but can observe 95% consumption, let’s put hints in for those as well.

**Comment by glyn** [comment]
Implemented: the memory calculator no longer sets `-XX:CompressedClassSpaceSize` as of https://github.com/cloudfoundry/java-buildpack-memory-calculator/commit/eaee1ff1c2fcae2f0a8f4270ef59259a95b131d1.
