### ISSUE TITLE
Oracle JDBC drivers or classpath extension

### ISSUE THREAD

**Issue by d-sauer** [cloudfoundry/java-buildpack#502]
Is there any plans to add Oracle JDBC drivers in the buildpack as default?

Or maybe to build some mechanism that can enable adding extra JARs to the app classpath from some shared resources (e.g. NFS volume service)?

**Comment by nebhale** [comment]
There is no plan to add the OracleJDBC driver.  Neither the Cloud Foundry Foundation nor Pivotal have distribution agreements for Oracle software it's unlikely we ever could.

If an application needs these drivers, they should be included in the application itself.  The auto-contribution of MariaDB and PostgreSQL notwithstanding, the preferred way to contribute application-critical dependencies is to  package them as part of the application.
