### ISSUE TITLE
AWS CloudHSMv2 support not available in JavaBuildpack

### ISSUE THREAD

**Issue by jatin-desai** [cloudfoundry/java-buildpack#504]
AWS recently released CloudHSMv2, which uses Cavium LiquidSecurity. The Java Buildpack currently only support CloudHSM Classic (which use SafeNet LunaHSM).

The JavaBuildpack needs to be updated to include support for CloudHSMv2/Cavium LiquidSecurity

Link to CloudHSMv2 user guide for java - http://docs.aws.amazon.com/cloudhsm/latest/userguide/java-library-install.html

**Comment by nebhale** [comment]
Until we have an engineering relationship with the Cavium team, this isn’t likely to be implemented.  I’ve started the process of getting that relationship in place.

**Comment by nebhale** [comment]
In the last 7 months I've seen no further requests for this integration so I'm closing this issue out.  I'm happy to look into it again more interest arrises.
