### ISSUE TITLE
Adding certificates to offline buildpack

### ISSUE THREAD

**Issue by sundarsrini** [cloudfoundry/java-buildpack#506]
Hello,

We are currently using java buildpack 3.11 version which has open_jdk_jre and oracle_jre folders inside resources to place the security related certificates. 

But in the latest version 4.6, i am unable to find directory for open_jdk_jre and oracle_jre. 

Could you please help on the path to place the security certificates?

Thanks
Sundar

**Comment by nebhale** [comment]
You just create the folders as necessary and the contents will be copied as they always were.  However, I strongly encourage you to use [BOSH trusted certs](https://bosh.io/docs/trusted-certs.html) (or the Ops Manager Trusted Certificates, if you're a PCF user) to get certificates to applications.  It's a much more scalable solution to the use case you're working with.

**Comment by sundarsrini** [comment]
Thank you @nebhale for the information!
