### ISSUE TITLE
Reserving Thread space memory off of Xss doesn't account for system thread and their different stack size

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#511]
# Problem

I have a sample application that is running 84 system and application threads combined (found using a thread dump). I'm using -Xss256K yet Java is using 41808KB of memory for stack allocation (found using Native Memory Tracking). 30 of my 84 threads are System threads which -Xss doesn't apply to.  There is a different config value that dictates the size of these system threads.  I think it defaults to 1MB, is customizable using the `-XX:ThreadStackSize`, and probably shouldn't be touched.  In addition, many of those system threads are GC threads which will vary based on the GC type used.

# Possible Solution?

Allow for a configurable System Thread static base value that can be used to provide a best guess buffer considering GC type used and stack size of native threads. Then add onto that the configured thread value multiplied by Xss value. In the case of G1GC This value would probably be about 30MB.

As an alternative, perhaps more difficult approach, The java memory calculator could start up a dummy java application using the jvm args the application will use and derive System threads and other things, like GC memory, from that.  See this comment for details: https://github.com/cloudfoundry/java-buildpack/issues/494#issuecomment-334525372

**Comment by nebhale** [comment]
I'm a bit loath to add another configuration knob to the outside of the `jvmkill`. I think we got into quite a bit of trouble with the the last time.  Let's put together a proposal of what this change might look like and then see what the end result is.

**Comment by youngm** [comment]
If we're doing study on the effects of native memory use for different GC types we could solve this one the same way.  See the number of system threads created with different typical GC types.  Then it becomes different flat values of native memory allocated.

**Comment by tstuefe** [comment]
Please note that NMT, before https://bugs.openjdk.java.net/browse/JDK-8199067, notoriously overstated thread stack memory, since it equaled reserved == committed. So, 41MB of combined thread stack size for VM internal threads plus java threads does not mean, by any stretch, RSS+=41MB, it means 41MB reserved address space.

Current jdk11u should be able to show more correct values - it probes the thread stacks with mincore() to find out mapped pages on Linux - however, issues have been rised and I would not completely trust it either (good enough for an estimate though).

**Comment by nebhale** [comment]
@tstuefe Thanks for the input here.  I'm going to close this issue out for now as, in practice, our estimates are close enough.  With all of the changes around Oracle and OpenJDK, we're going to be engaging more directly with the JVM's development team on issues such as this.
