### ISSUE TITLE
GC Size Not accounted for in memory calculations

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#512]
# Problem

I have a sample application that is using the G1 GC configured with a 2.5GB Heap.  With a heap this size Native Memory Tracker shows this heap is using 106352KB of memory for GC management. It doesn't appear that GC memory overhead isn't accounted for in JBP4 at all. Running some tests it appears that the GC area grows and shrinks with the Heap size specified.

# Possible Solutions??

The JBP should account for GC memory size by using a percentage of total heap size allocated. This percentage should be configurable because it will change based on the GC used. SerialGC uses much less memory. Some testing needs to take place to determine a proper factor for the default GC.

An application using G1GC and a heap of 2.5GB could use a GC Memory factor of ~5%.

As an alternative, perhaps more difficult, approach, the java memory calculator could start up a dummy java application using the jvm args the application will use and derive GC memory size, and perhaps other things like System thread size, from that. See this comment for details: #494 (comment)

**Comment by nebhale** [comment]
We should be able to identify the type of GC being used, first by knowing the default, and second checking `JAVA_OPTS`.  Some experimentation should be able to identify reasonable start values.

**Comment by glyn** [comment]
hotspot-dev provided the [following advice](http://mail.openjdk.java.net/pipermail/hotspot-dev/2017-November/029032.html) on estimating the GC memory size:

> GC memory is mainly data structures used by GC runtime. It can be varied 
> by collector used, size of the Java heap, the number of GC threads and 
> etc. and, of course, the application itself.
> 
> Some are *fixed* costs, which can be estimated. E.g. two marking bitmaps 
> used by G1, each costs 1/64 of heap size (assuming default object 
> alignment).
> 
> Some are *semi-fixed*, e.g. taskqueue's fixed cost is about 1M for each 
> queue on 64-bits VM, but it can overflow. And the number of task queues 
> is proportional to the number of GC threads.
> 
> Then there are factors from application itself,  such as object mutation 
> rate, inter-generation/region references, etc.
> 
> 
> I don't see a single formula for estimating GC memory size. If you are 
> using G1, the biggest overhead comes from 2 bitmaps (1/32 * heap size).
> 

So it seems like it won't be feasible to estimate GC memory size accurately.

**Comment by glyn** [comment]
@nebhale After some pondering, and discussion with @Zteve, the best solution would appear to be to estimate an _upper bound_ for the amount of spare space for “GC” storage etc. initially as a linear function of the heap size:
```
spare = m * heapSize + c
```` 
for some constants `m` and `c`. We would subtract this spare space value from the heap size.

If necessary, we could refine this later to be a linear function of the heap size and the number of logical processors:
```
spare = m * heapSize + n * numLogicalProcessors + d
```
for some constants `m`, `n`, and `d`.

The aim would be to produce an upper bound without going too far and wasting memory. The point of aiming for an upper bound is to reduce the dependency on implementation details of G1GC _et al_.

We would _not_ make the formula configurable, so the only reasonable mitigation for someone who hits a container OOM would be to set the heap size lower than the calculated value. (Forking the memory calculator, in order to tweak the constants, and the buildpack would probably be an _unreasonable_ mitigation.)

We could start off conservatively (in the sense of not wasting too much memory, which is consistent with the fact that we currently allocate no spare space at all) and then _increase_ the spare space if users hit further problems. This is consistent with @youngm’s proposal of setting aside around 5% of the heap size, although the initial value of `m` should probably be `1/32` based on the previous comment.

**Comment by nebhale** [comment]
Am I correct in my math if I believe that in a 1GB container (~350M heap), we're likely to see ~11M reserved for this?

**Comment by youngm** [comment]
@glyn So, let me restate so I'm clear.  You said this wouldn't be configurable right.  So, you would initially target an "upperbound" of the most memory hungry GC, being G1GC, but start with a conservative value, correct?

So, if someone wanted to maximize heap space at the cost of GC power by configuring the serial GC they'd have to fork things in order to see the heap benefit of that more efficient GC.  Correct?

**Comment by glyn** [comment]
@nebhale Your math(s) is correct if `m` is `1/32` and `c` is `0`.

**Comment by glyn** [comment]
@youngm Forking would be one solution, but they could also set the heap size higher than the calculated value if they didn't want to fork the buildpack.

**Comment by nebhale** [comment]
Let me mull this idea over a bit.  But given that we're talking about ~10M (unless someone thinks that `c` is going to be a large number), I'm leaning towards going with this.  I can't imagine that someone is going to fork just to regain 5-10M from a JVM when there are other, much larger wins, using JVM flags.

**Comment by youngm** [comment]
Here is a different number right from NMT.  91600KB from a 1GB Heap.  Significantly bigger than 10MB.  Not sure why NMT numbers are so much bigger than the data you got from the mailing list.  See output below:

```
java -Xmx1G -Xms1G -XX:+UseG1GC -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Native Memory Tracking:

Total: reserved=2486579KB, committed=1185179KB

-- snip --

-                        GC (reserved=91600KB, committed=91600KB)
                            (malloc=19920KB #6355)
                            (mmap: reserved=71680KB, committed=71680KB)

-- snip --

```

**Comment by youngm** [comment]
Sorry @nebhale I miss read your estimate.  So, looking at a 350M Heap here is the data.  Still 63M is a lot more than 10M.  Seems like there should be some value for c perhaps?

```
java -Xmx350M -Xms350M -XX:+UseG1GC -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Native Memory Tracking:

Total: reserved=1765316KB, committed=465264KB
-                        GC (reserved=63682KB, committed=63682KB)
                            (malloc=17614KB #2311)
                            (mmap: reserved=46068KB, committed=46068KB)

```

**Comment by glyn** [comment]
I've [captured](https://gist.github.com/glyn/f10b7dea77994ad0f5589a416fbc77fe) all the other flags and raised this anomaly on hotspot-dev. I'll report back if any light is shed there.

**Comment by glyn** [comment]
Someone on hotspot-dev pointed out that some of the GC space is accounted for in the NMT details:
* the two marking bitmaps, each 1/64 of heap size.
* a mark stack of 32 MB which is 8* MarkStackSize (but which could grow to 8* MarkStackSizeMax or 128 MB in this example). 
* three 700 KB areas, although I'm not sure what these are used for or how to predict their total size.

This leaves the malloc portion of GC space `17615KB #2312` which I think was due 2312 calls to malloc. Again, not sure what these are used for or how to predict their total size except that I presume they include the task queues mentioned previously.

Outstanding questions:
1. Is the mmap space which consumed three 700 KB areas above fixed, proportional to heap size, or what?
2. How many task queues are there for a given number of GC threads?
3. Task queues can overflow, so what is the maximum space each one can occupy?
4. Of the malloc space not consumed by task queues, how much is fixed and how much proportional to heap size, number of GC threads, etc.?

[Raw data](https://gist.github.com/glyn/a3bd944eb2943f4f5a98b5ac712efeb6).

**Comment by youngm** [comment]
Here is another bit of sample data.  This test using SerialGC helps us see the difference in memory consumption between the 2.  In this test the serial GC is only using ~1MB.  I actually have a fork of the GC that is tuned this way for very lite use cases where low memory consumption is more important than performance.  It would be nice if I could continue to maintain this fork without significant effort. :)

```
java -Xmx350M -Xms350M -XX:+UseSerialGC -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Native Memory Tracking:

Total: reserved=1679503KB, committed=380151KB
--snip--
-                        GC (reserved=1179KB, committed=1179KB)
                            (malloc=7KB #79)
                            (mmap: reserved=1172KB, committed=1172KB)
--snip--
```

**Comment by nebhale** [comment]
Closing in lieu of #583.
