### ISSUE TITLE
Consider making ReservedCodeCacheSize variable based on number of classes loaded

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#513]
Similar to metaspace.  Using NTM it is trivial to see how much code cache an application with a given number of classes loaded is using.  Perhaps if we gather enough data we can come up with proper percentage to factor into a variable code cache size.

Here is the example out put from one of my production applications.

```
Native Memory Tracking:

-                     Class (reserved=123978KB, committed=108234KB)
                            (classes #18699)
                            (malloc=3138KB #36002)
                            (mmap: reserved=120840KB, committed=105096KB)

-                      Code (reserved=264581KB, committed=89081KB)
                            (malloc=14981KB #19379)
                            (mmap: reserved=249600KB, committed=74100KB)
```

It shows that with 18699 loaded classes after running in production for several days only 89081KB of code cache is being used.  So, this application could benefit from a smaller code cache which it seems would change depending on the number of classes being loaded.

Before doing this we would need to understand the risk of starving a jvm of code cache.  Will it simply not optimize some code paths as much as it could?  Or would it cause the app to crash?  Could help dictate how aggressive we can be with the factor picked.

**Comment by youngm** [comment]
Here is an example of another one of my applications.  Larger this time.

```
-                     Class (reserved=242825KB, committed=236889KB)
                            (classes #35681)
                            (malloc=8645KB #96539)
                            (mmap: reserved=234180KB, committed=228244KB)
-                      Code (reserved=280804KB, committed=201764KB)
                            (malloc=31204KB #31659)
                            (mmap: reserved=249600KB, committed=170560KB)
```

**Comment by youngm** [comment]
There is some interesting info in this article: https://docs.oracle.com/javase/8/embedded/develop-apps-platforms/codecache.htm

Most notably applications could enable `ExitOnFullCodeCache` to crash the process (Like OOME) if they want to be sure code cache never is too small.  Another option is to enable `UseCodeCacheFlushing` which seems that should do a decent job of making sure only the hottest code ends up in the code cache and the jvm will interpret the rest.

**Comment by glyn** [comment]
One risk of starving a JVM of code cache is high CPU consumption. The memory calculator originally set `-XX:ReservedCodeCacheSize`, but this resulted in some applications consuming 20% CPU and was dropped. See the [design doc](https://docs.google.com/document/d/1vlXBiwRIjwiVcbvUGYMrxx2Aw1RVAtxq3iuZ3UK2vXA/edit) for details including the formula we used.

Applying the formula to the above example with 18699 loaded classes would set the code cache size to 31.5 Mb, which is way below the 87 Mb actually needed. So it seems the sample applications are not sufficiently representative of the real world.

**Comment by nebhale** [comment]
I am also **super** paranoid about this particular setting.  I’ve read a couple of blog posts (which of course, I cannot find this mornin) of people taking real world applications and reducing the Java 8 default of 240M back to the Java 7 default of 100M and just having horrific performance decreases.

The downside of getting this wrong isn’t that the application will OOM or fail to start, but rather that your application will use a lot more CPU and still perform a lot worse.  As this is a perfect space/time tradeoff, I’m super wary of trying to identify how much the JIT will be able to optimize a given application and so we’ve stuck with the defaults.

I’m open to being convinced that we might be able to do this in a safe way, but I think we want to trend very lightly here, lest Cloud Foundry be identified as a lesser performing platform.

**Comment by youngm** [comment]
@glyn @nebhale Thanks for showing me the doc.  I've been looking for that.

Doing a little more searching I found that the doc I referenced above is for Embedded Java and the `ExitOnFullCodeCache` isn't a valid option for regular javase.  Thanks for the info.
