### ISSUE TITLE
Staging Process ERROR Oracle jre-8u152

### ISSUE THREAD

**Issue by ptamma** [cloudfoundry/java-buildpack#515]
cf push fails staging process reporting ERROR Compile failed with exception #<RuntimeError: Oracle JRE error: undefined method `keys' for #<String:0x0055683d3606c8>>. 

The issue is observed using latest Oracle JREs version (both Oracle Server JRE and JDK) 
1.8.0_151 https://internalsystem.org/oracle/jre/server-jre-8u151-linux-x64.tar.gz
1.8.0_152 https://internalsystem.org/oracle/jre/jdk-8u152-linux-x64.tar.gz

However the buildpack deploy successfully with older version of Oracle jdk-8u60-linux-x64.gz. To rule out issue with archive files md5 checksum performed. 
Java buildpack version v3.17 and v4.1
PCF 1.9
Tried using cf-sample-app-java

**Comment by nebhale** [comment]
I'm not sure what resolution you are looking for here.  The JREs are built based on the [tagged versions of the JRE](http://hg.openjdk.java.net/jdk8u/jdk8u/tags) matching what [Oracle releases](http://www.oracle.com/technetwork/java/javase/documentation/8u-relnotes-2225394.html).  Given that many users have and all of our testing is against [1.8.0_152-b16](http://hg.openjdk.java.net/jdk8u/jdk8u/rev/7a25d12cd94f) and we've seen no wide-spread issues, it is unlikely that Cloud Foundry will be reverting to a previous version of our JRE.
