### ISSUE TITLE
Apache Geode Tomcat Session Store

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/java-buildpack#522]
The java buildpack 3.19 calls as dependency - with the name Apache Geode Tomcat Session Store - the zip file at:https://java-buildpack.cloudfoundry.org/geode-store/geode-store-0.0.2.tar.gz, that in turn include some jar files that seems to be NOT open source, but commercial code, Pivotal proprietary:

geode-core-9.0.3.jar
geode-modules-9.0.3.jar
geode-modules-tomcat8-9.0.3.jar
pcc-client-auth-0.0.1.jar

Could you please confirm me if they are commercial code or opensource?

If they are opensource could you please point me to the download location of their source.

As additional info:

- the first 3 geode jars contain the file
<img width="512" alt="image" src="https://user-images.githubusercontent.com/27818611/32735918-665c21ba-c896-11e7-8272-0b3f1cabf5a6.png">
that is Pivotal-EULA commercial license.

- the last file does not contain any license, nor I was able to find it on the net, so I cannot say nothing more.

**Comment by nebhale** [comment]
@pivotal-Jammy-Louie Please respond.

**Comment by luisapace** [comment]
Hi, any news on this issue? thanks.

**Comment by pulkitpivotal** [comment]
I believe this issue has been fixed with commit https://github.com/cloudfoundry/java-buildpack/commit/67b5da51783264946ab5dd65c26bd0fab59b2e37 which is released with version 4.7. Please let me know if you see any issues with it. For pcc-client-auth module https://github.com/pivotal-cf/pcc-client-auth is the sourced already. We will include the license files in the later versions.

**Comment by luisapace** [comment]
@pulkitpivotal  I tried to access the source code of pcc-client-auth at that link but I've obtained 404 browser error, could you please tell me the right link and what is the  license type that is planned to be included in the later version. Thanks.

**Comment by pulkitpivotal** [comment]
@luisapace Please try again you should be able to access the link. About the licenses, it going to be apache 2.0.

**Comment by nebhale** [comment]
@luisapace If this satisfies your inquiry, please close this issue out.

**Comment by luisapace** [comment]
Yes, I can access the link now. Thanks!
