### ISSUE TITLE
Retry download of a dependency with back off

### ISSUE THREAD

**Issue by stipx** [cloudfoundry/java-buildpack#524]
Hi,

as far as I can see there is a retry mechanism in on downloads of dependencies. The thing is that there seems to be no back off strategy implemented. The retry is just done right away:
https://github.com/cloudfoundry/java-buildpack/blob/9d3bc1968af27bf96deeb1688a8438d5ba95a2f4/lib/java_buildpack/util/cache/download_cache.rb#L330-L336
It might make sense to have some kind of exponential back off there to give the download endpoint some time to recover if there are some serverside problems.

Please share your thoughts on this.

Best
stipx

**Comment by nebhale** [comment]
Seems reasonable.

**Comment by nebhale** [comment]
Any thoughts about the backoff intervals you'd see as helpful in practice?

**Comment by stipx** [comment]
I always find the exponential back off pretty useful. It reduces backpressure but also picks up small hiccups pretty fast.

The function to get the wait interval is:
sleep = min(cap, base + 2 ** attempt)

I usually use a pretty small 'base' like 5 seconds and a 'cap' of around 60 to 90 seconds.

**Comment by nebhale** [comment]
Right, I was wondering if you were thinking of a cap in the single second range or larger.  Let me poll around some others and see what the consensus is and I’ll put something in.
