### ISSUE TITLE
Unable to build an offline buildpack

### ISSUE THREAD

**Issue by kjhawar** [cloudfoundry/java-buildpack#53]
Hi, 
I am trying to build an offline buildpack and upload it to my CF PaaS(installed using CF Nise installer) so that my CF wont need internet when i push my Java webapp.

Bundler version: 1.6.2
Ruby version: ruby 1.9.3p545 (2014-02-24) [i386-mingw32]

i cloned this repo, did a 'bundle install', followed by 'bundle exec rake package OFFLINE=true'. i am getting the following error:

C:\Users\kjhawar\ws\java-buildpack>bundle exec rake package OFFLINE=true > log
.txt
The system cannot find the path specified.
The system cannot find the path specified.
[DownloadCache]                  WARN  Request failure 1, retrying: Content has
invalid size.  Was 4041, should be 3976.
[DownloadCache]                  WARN  Request failure 2, retrying: Content has
invalid size.  Was 4041, should be 3976.
[DownloadCache]                  WARN  Request failure 3, retrying: Content has
invalid size.  Was 4041, should be 3976.
[DownloadCache]                  WARN  Request failure 4, retrying: Content has
invalid size.  Was 4041, should be 3976.
[DownloadCache]                  WARN  Request failure 5, retrying: Content has
invalid size.  Was 4041, should be 3976.
[InternetAvailability]           WARN  Internet availability set to false: Reque
st failed: Content has invalid size.  Was 4041, should be 3976.
[DownloadCache]                  WARN  Unable to download http://download.run.pi
votal.io/groovy/index.yml into cache build/staging/resources/cache: Content has
invalid size.  Was 4041, should be 3976.
rake aborted!
Unable to find cached file for http://download.run.pivotal.io/groovy/index.yml
C:/Users/kjhawar/ws/java-buildpack/lib/java_buildpack/util/cache/download_cache.
rb:65:in `get'
C:/Users/kjhawar/ws/java-buildpack/rakelib/dependency_cache_task.rb:144:in`bloc
k (2 levels) in uris'
C:/Users/kjhawar/ws/java-buildpack/rakelib/dependency_cache_task.rb:141:in `each
'
C:/Users/kjhawar/ws/java-buildpack/rakelib/dependency_cache_task.rb:141:in`bloc
k in uris'
C:/Users/kjhawar/ws/java-buildpack/rakelib/dependency_cache_task.rb:140:in `each
'
C:/Users/kjhawar/ws/java-buildpack/rakelib/dependency_cache_task.rb:140:in`uris
'
C:/Users/kjhawar/ws/java-buildpack/rakelib/dependency_cache_task.rb:42:in `initi
alize'
C:/Users/kjhawar/ws/java-buildpack/Rakefile:40:in`new'
C:/Users/kjhawar/ws/java-buildpack/Rakefile:40:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by ilatypov** [comment]
```
cp LICENSE build/staging/LICENSEcp NOTICE build/staging/NOTICE

chmod 644 build/staging/NOTICEchmod 644 build/staging/LICENSE

[DownloadCache]                  WARN  Request failure 1, retrying after 5s.  Failure: Net::ReadTimeout
[DownloadCache]                  WARN  Request failure 2, retrying after 10s.  Failure: Net::ReadTimeout
[DownloadCache]                  WARN  Request failure 3, retrying after 20s.  Failure: Net::ReadTimeout
[DownloadCache]                  WARN  Request failure 4, retrying after 40s.  Failure: Net::ReadTimeout


[DownloadCache]                  WARN  Request failure 5, retrying after 60s.  Failure: Net::ReadTimeout
[InternetAvailability]           WARN  Internet availability set to false: Request failed: Net::ReadTimeout
[DownloadCache]                  WARN  Unable to download http://files.cf-hsm.io/protectapp-installer/protectapp-jce-8.4.0.zip into cache build/staging/resources/cache: Net::ReadTimeout
rake aborted!
Unable to find cached file for http://files.cf-hsm.io/protectapp-installer/protectapp-jce-8.4.0.zip
/home/latypil/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:77:in `get'
/home/latypil/java-buildpack/rakelib/dependency_cache_task.rb:103:in `block in cache_task'
Tasks: TOP => package => build/java-buildpack-offline-9f97630.zip => http://files.cf-hsm.io/protectapp-installer/protectapp-jce-8.4.0.zip
(See full trace by running task with --trace)
````

Removing config/protect_app_security_provider.yml helped complete the install today.  The file was added in February 2017, and looks surprising: a security application was offered over the unencrypted HTTP connection.
