### ISSUE TITLE
enable Client Certificate Mapper by default on Tomcat web app

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/java-buildpack#531]
In a conversation with @nebhale, he said that this mapper is enabled by default for Spring apps, but not on Tomcat because on (older versions of ) Tomcat there was no way to do it without editing the user's web.xml.
But Servlet 3.0 introduces web fragments that could allow this to work.

Personally, I wonder if it could be implemented using a ServletFilter, which could be enabled in $CATALINA_HOME/conf/web.xml (see https://stackoverflow.com/a/15986046/1227328) to apply to all apps automatically.

Please consider.

**Comment by nebhale** [comment]
Completed with the inclusion of [Client Certificate Mapper v1.5.0.RELEASE](https://github.com/cloudfoundry/java-buildpack-client-certificate-mapper/releases/tag/v1.5.0.RELEASE).
