### ISSUE TITLE
Out of memory when using the Takipi Agent

### ISSUE THREAD

**Issue by christophe-f** [cloudfoundry/java-buildpack#534]
Hi,

We have about 40 Java microservices deployed on PWS. Last week, I have enabled OverOps/Takipi agent on a few of these services. All the apps using the agent where crashing (due to Out of memory error) every few minutes/hours. The others apps were fine without it.

About 24 hours ago, I've removed the agent from the crashing apps and everything is fine.

I'm using the buildpack v.4.7

Would be nice to be able to use it without any crashes :) Is there any memory tweak recommendation for this agent?

Thanks,
Christophe

**Comment by nebhale** [comment]
What does the Out of Memory error look like?  Is it a Java OOM (complete with a stack trace and our `jvmkill` output) or is it a container out memory error (`exit 137`)?

**Comment by christophe-f** [comment]
Hi Ben,

This is the error:
`index: 0, reason: CRASHED, exit_description: APP/PROC/WEB: Exited with status 137 (out of memory)`

It's a exit 137

**Comment by nebhale** [comment]
@christophe-f I don't know a whole lot about the OverOps agent, but given the very large number of native libraries is it possible that agent is using a large amount of off-heap memory for itself?  The error message you've provided indicates that the JVM is fine, but something outside of the JVM has requested enough memory that the container's memory limit has been exceeded.

/cc @glyn

**Comment by christophe-f** [comment]
Hey Ben,

Looks like it running a local collector alongside the agent. I will try with a remote collector and let you know the outcome.

**Comment by christophe-f** [comment]
Quick update on the issue. I got everything running fine using the remote collector. The Takipi agent configuration page could be updated from "optional" to "highly recommended" :)

**Comment by nebhale** [comment]
Happy to take a PR for it.

More generally, side cars are problematic for Java applications because we configure the JVM to occupy the _entire_ memory space of the container (value for money and all that).  There's some work being done to make buildpacks more sidecar aware in the future which would help with this, but remote collector is certainly the way to go today.
