### ISSUE TITLE
multi-buildpack framework failing unit tests and faulty assumptions

### ISSUE THREAD

**Issue by rhardt-pivotal** [cloudfoundry/java-buildpack#535]
Hi, 
I ran across a couple of issues trying to make the multi-buildpack framework work on on a pre-CAPI v3 CF install using the 'multi-buildpack' buildpack from the 'cloudfoundry' repo.  

Some of these issues correspond to failing unit tests for the multi-buildpack framework within the JBP.

1.  For better or for worse, there can be multiple 'deps' directories.  I'm still digging into why this happens.  In my tests, this results in 2 directories that get picked up by the JBP.  For example, you would see something like this in the staging container:
```
/tmp/contents12345/deps <-- empty dir
/tmp/contents23456/deps <- contains /1 /2 etc.
``` 
By arbitrarily choosing the first directory returned by the glob command, the JBP's multi-buildpack functionality fails ~50% of the time because the empty directory was arbitrarily chosen. 

2.  The multi-buildpack unit tests apply the multi-buildpack fixture to the application directory provided by the 'application helper' context.  This causes a couple of problems.  First, this is analagous to saying the multi-buildpack deps directories would get copied to `/var/vcap/app/0`, `/var/vcap/app/1`, etc.  In reality, they're at `/var/vcap/deps/0` and `/var/vcap/deps/1` - the spec needs to create the tmpdir, mkdir {tmpdir}/deps, and then explode the fixture there.  This accurately models how things actually work and allows for accurate unit tests.

3.  Furthermore, for the functionality whereby a supplying buildpack's /bin and and /lib are added to PATH and LD_LIBRARY_PATH respectively, the JBP's specified directories: $PWD/0/bin and $PWD/0/lib respectively are incorrect.  This doesn't work because in the context of a running CF app, $PWD evaluates to /var/vcap/app and the deps aren't at /var/vcap/app/0, they're at /var/vcap/deps/0

4.  The documentation implies that the /bin and /lib dependencies will automatically be copied into the app container.  However, if the supplying buildpack lacks a config.yml, they will not be copied.

**Comment by nebhale** [comment]
Closed in lieu of #536.
