### ISSUE TITLE
Multi-buildpack of Java & Python with additional dependencies are not working

### ISSUE THREAD

**Issue by kavithamadhavaraj** [cloudfoundry/java-buildpack#537]
Hi,
I'm having a Java Application which uses ProcessBuilder to call few python scripts. My manifest file looks like this:

```
applications:
  - name: eventprocessor
    memory: 768MB
    buildpack: https://github.com/cloudfoundry/multi-buildpack
    services:
      - mongoinstance
```

multi-builpack.yml file like this:

```
buildpacks:
- https://github.com/cloudfoundry/buildpack-python
- https://github.com/cloudfoundry/java-buildpack
```

If I push the app to CloudFoundry, I get this error:

```
-----> Java Buildpack 9f97630 | https://github.com/cloudfoundry/java-buildpack#9f97630
[Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. 
       **ERROR** Unable to run all buildpacks: Failed to compile droplet: Failed to run finalize script: exit status 1
Failed to compile droplet: Failed to compile droplet: exit status 13
Exit status 223
```

But if I add path attribute in manifest.yml, it doesn't detect the multi-builpack.yml itself and getting the error as follows:
```
-----> Download go 1.9.1
-----> Running go build compile
-----> Multi Buildpack version 1.0.2
       **ERROR** A multi-buildpack.yml file must be provided at your app root to use this buildpack.
Failed to compile droplet: Failed to compile droplet: exit status 11
Exit status 223
```
So I assume the issue is with the path attribute. How should I specify the path in case of multi-buildpack environment?

**Comment by rhardt-pivotal** [comment]
Here's an example of using MBP to call python from Spring Boot.  Note the somewhat inelegant plugin in pom.xml to move multi-buildpack.yml to the root of the generated jar file.

https://github.com/rhardt-pivotal/python-mbp-demo/

**Comment by kavithamadhavaraj** [comment]
@rhardt-pivotal  Thanks it worked !

> move multi-buildpack.yml to the root of the generated jar file 
was the point. 

For anyone who might face the same in future:

manifest.yml file says which jar to be uploaded and it does not look for multi-buildpack.yml in the same directory (I assumed it to be). The jar being uploaded must include multi-builpack.yml in its root and so as the requirements.txt, if exists.

**Comment by kavithamadhavaraj** [comment]
So got the issue with python dependencies now. requirements.txt with list of dependencies are not actually installed and usable. Any reason to fix this? 

https://github.com/cloudfoundry/python-buildpack/issues/94
