### ISSUE TITLE
No container can run this application | Buildpack Cloud Foundry Error

### ISSUE THREAD

**Issue by naramiss** [cloudfoundry/java-buildpack#538]
I am new in Cloud Foundry and I am trying to push a simple application. But when I use the `cf push` command line, it fails even if I mentioned in the `manifest.yml` the buildpack. There is the logs : 

```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (52.1K)
-----> Java Buildpack 9f97630 | https://github.com/cloudfoundry/java-buildpack.git#9f97630
[Buildpack]                      **ERROR Finalize failed with exception #<RuntimeError: No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.** 
Failed to compile droplet: Failed to run finalize script: exit status 1
Exit status 223
Stopping instance 0948fab9-0d97-43c9-be32-36a986490e8f
Destroying container
Successfully destroyed container

ECHEC
Erreur lors du redémarrage de l'application : BuildpackCompileFailed
```

**Comment by naramiss** [comment]
Could you please help me correct this error ? Here is the manifest.yml : 
---
applications:
- name: employee-service
  memory: 1G
  random-route: true
  buildpack: https://github.com/cloudfoundry/java-buildpack.git

**Comment by nebhale** [comment]
The error message describes the problem well.  You've pushed an artifact that is not a Java application as understood by the Java Buildpack.  The [documentation](https://github.com/cloudfoundry/java-buildpack#additional-documentation) about Containers describes what artifacts the buildpack understands.  Just taking a quick look at your manifest, it appears that you're pushing the directory that your manifest is in, which means you're likely pushing a directory full of source files.  This is not an artifact that the Java Buildpack understands.  Your manifest should point at a `path` of the compiled artifact you'd like to run.

**Comment by naramiss** [comment]
That means that I have to put a path attribute in the manifest ?

Le 5 janv. 2018 à 18:19, Ben Hale <notifications@github.com<mailto:notifications@github.com>> a écrit :


The error message describes the problem well. You've pushed an artifact that is not a Java application as understood by the Java Buildpack. The documentation<https://github.com/cloudfoundry/java-buildpack#additional-documentation> about Containers describes what artifacts the buildpack understands. Just taking a quick look at your manifest, it appears that you're pushing the directory that your manifest is in, which means you're likely pushing a directory full of source files. This is not an artifact that the Java Buildpack understands. Your manifest should point at a path of the compiled artifact you'd like to run.

**Comment by nebhale** [comment]
You can either specify a path to an artifact [on the command line](http://cli.cloudfoundry.org/en-US/cf/push.html) or [in the manifest](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#path).

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by Bezly** [comment]
Getting the same error. Can you please tell me what did you change @naramiss, @nebhale, @Tanvishah1

**Comment by Tanvishah1** [comment]
@Bezly It was an application issue as it was not getting the main class

**Comment by cookieMonster21** [comment]
This change helps me:

command: cf push -p path/to/your/jar/file
manifest: `path:  yourpath\app\target\filename.jar`

**Comment by Anil2703** [comment]
![image](https://user-images.githubusercontent.com/39698174/62833948-fdf53300-bc63-11e9-95f5-94dc46b7f5cf.png)

**Comment by nguyentuanduc** [comment]
Anil2703 : cf push bootjava -p target/gs-spring-boot-0.1.0.war
replace "bootjava" with your app name 
"target/gs-spring-boot-0.1.0.war" path to your war file.
good luck.
