### ISSUE TITLE
Improve documentation for zip dist start script

### ISSUE THREAD

**Issue by chefhoobajoob** [cloudfoundry/java-buildpack#541]
The publicly visible documentation for the [dist zip container](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-dist_zip.md) does not define any requirements for the 'start script' that it mentions. Rather, it is necessary to dig into the code to find [this description](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/util/start_script.rb#L21-L22).

Even with this description, it's still not clear what the requirements are for the behavior of the script. Should it return control to the process that launched it once the application is started? Is it ok for the script to block indefinitely while the application runs, returning only when the application has exited? If it is supposed to return immediately with the application left running in the background, how does the application get shutdown in an orderly fashion? Is there a separate 'stop' script that will initiate an orderly shutdown? If so, what are its requirements?

**Comment by nebhale** [comment]
The requirements for `distZip` are not that any script will do, but rather that artifacts created by the [Gradle Application Plugin](https://docs.gradle.org/4.4.1/userguide/application_plugin.html) (the underlying task name is `distZip`) will run.  It turns out that there are a number of other build systems (Play Framework, Ratpack, etc.) that either build on this facility or mirror it directly leading to support of those specific scripts, rather than a more general “scripted start” container type.

**Comment by chefhoobajoob** [comment]
I gotcha - the use of the term 'distZip-style' in the documentation seemed (to me, anyway) to be just saying 'hey, your zip distribution should have a start script, like this one does'.

The app I'm working with could easily use that plugin (it's already using the 'distribution' plugin), but I would still have a need to customize the start script, which is explicitly supported by the 'application' plugin.

What are the answers to the questions about whether the start script is required or not to return control back to the buildpack? Is either behavior acceptable? And what about clean shutdowns? Does the buildpack participate in shutdown at all? Is this topic documented elsewhere in the CF documentation?

I'm new to Cloud Foundry, so trying to get oriented.

**Comment by nebhale** [comment]
The buildpack isn't involved after staging completes (well, some of the things we contribute are, but the buildpack itself isn't).  We write a command line that will be executed by Diego (the container manager), so the process that is result of that command needs to stay alive from the perspective of the container.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
