### ISSUE TITLE
Single Line Stacktraces

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/java-buildpack#544]
If a stack trace is on a single line, then the loggregator system can more easily get the entire stack trace (and in proper order) to the end user. The loggregator README used to have a way to do this for java applications, but it seems more reasonable to have those docs here. The following is what used to be in the README:

### Multi-line Java message workaround

Having log lines out of order can be painful when monitoring Java stack traces. There is a work around involving modifing the Java log output to have your app reformat your stacktrace messages so any newline characters are replaced by a token; and then have your log parsing code replace that token with newline characters again. The following example is for the Java Logback library and ELK, but you may be able to use the same strategy for other Java log libraries and log aggregators.

With the Java Logback library you do this by adding `%replace(%xException){'\n','\u2028'}%nopex` to your logging config , and then use the following logstash conf.
```
# Replace the unicode newline character \u2028 with \n, which Kibana will display as a new line.
    mutate {
      gsub => [ "[@message]", '\u2028', "
"]
# ^^^ Seems that passing a string with an actual newline in it is the only way to make gsub work
    }
```
to replace the token with a regular newline again so it displays "properly" in Kibana.

**Comment by nebhale** [comment]
This is a logging framework-specific configuration and we generally don't document application-specific configurations in the Java Buildpack documentation.  I'm open to being convinced that there's an obvious place for this to go, but this feels like something that is just part of application development, no matter what the platform, logging framework, or log warehousing system.

**Comment by apoydence** [comment]
I think it belongs somewhere in https://docs.cloudfoundry.org/buildpacks/java/

**Comment by nebhale** [comment]
Those docs are run by a separate team and can be found [here](https://github.com/cloudfoundry/docs-buildpacks).  You can open an issue or submit a PR there for changes.
