### ISSUE TITLE
Agent repo suddenly does not contain the latest agent packages

### ISSUE THREAD

**Issue by vijayantony** [cloudfoundry/java-buildpack#557]
Hi,
The agent repo does not contain all the latest agent versions. It was listing upto agent version 4.4.x a week ago but suddenly now I can see only agent version upto 4.3.7_2 . Can you please check why?

https://packages.appdynamics.com/java/index.yml

**Comment by nebhale** [comment]
@nkatre Any idea what's going on here?

**Comment by nkatre** [comment]
Not sure why this is not getting updated. I have transitioned to a different team. But I have notified the dev team to on this, and a JIRA is created for tracking purpose.

**Comment by nebhale** [comment]
Thank you @nkatre.  Can you please also have that team reach out on this issue so that I have a new contact point?

**Comment by nkatre** [comment]
Yes, they have been communicated about this link. Someone should reach out on this issue and comment here.

**Comment by pavankrish123** [comment]
I believe this has something to do with our not so recent transition to teamcity from jenkins. We are looking into it.

**Comment by Saniya6** [comment]
Hi all ,
Is there an update on this issue?

**Comment by pavankrish123** [comment]
We have identified the issue and it is been worked on. Should be resolved soon. Thanks

**Comment by Saniya6** [comment]
Thanks Pavan for the update, let me know once it is resolved.

**Comment by Saniya6** [comment]
Hi There, Is this issue resolved? please provide us an update on this issue..

**Comment by pavankrish123** [comment]
Hi, we are done with the fix, index.yml should be updated soon (ETA tomorrow) on packages.appdynamics.com - Thanks

**Comment by Saniya6** [comment]
okay, thanks. Please keep it posted with the update.

**Comment by Saniya6** [comment]
Hi @pavankrish123 ,
do we have an update now for this issue ?

**Comment by pavankrish123** [comment]
Hello @Saniya6 the fix is shipped and is now with release engineering - Should be out soon - COB today

**Comment by Saniya6** [comment]
Thanks @pavankrish123 , please keep us posted as soon as it is resolved.

**Comment by pavankrish123** [comment]
hi @Saniya6, unfortunately, we hit a hiccup with our build pipelines today - We are working to get it resolved. Please expect the fix tomorrow - If there is an update i will let you know

**Comment by Saniya6** [comment]
ohk, @pavankrish123 we have production deployment tonight where we wanted to deploy Appd with the latest version and we were getting issue as that version was not available in the build pack..

Please try to get it resolved by EOD if possible.. Thanks..

**Comment by pavankrish123** [comment]
Sure @Saniya6, I will let release team know about it. However, the ball is in their court.  A jira has been filed for the same.

**Comment by Saniya6** [comment]
Hi @pavankrish123 , any update ?

**Comment by pavankrish123** [comment]
@Saniya6 the index.yml @ packages.appdynamics.com/java/index.yml should have been updated. 

Thanks,
Pavan

**Comment by Saniya6** [comment]
You mean the issue should have resolved after this update ? @pavankrish123

**Comment by pavankrish123** [comment]
yes that is correct - the repo now contains latest agent packages

**Comment by nebhale** [comment]
The index looks reasonable to me and the next tagged release of the buildpack will contain a 4.5.x release it appears).  @Saniya6 have you been able to verify that the releases you need are available now?

**Comment by youngm** [comment]
I don't want to derail the real issue, but I'm seeing what appears to be a cache issue with the new version.  If I request with the command below I don't see version `4.4.2_22394`.
```
curl https://packages.appdynamics.com/java/index.yml -H "accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3" -H "accept: */*" -H "user-agent: Ruby"
```

If I request like the following I see `4.4.2_22394`.
```
curl https://packages.appdynamics.com/java/index.yml
```

Is this just a cache thing?  Any idea when the cache will expire so the java-buildpack will be able to see 4.4.2?

**Comment by nebhale** [comment]
Yep, almost sure that the aforementioned build changes mean that the fix for #419 has been lost.

**Comment by youngm** [comment]
Alerting @pavankrish123 to the cache issue.

**Comment by pavankrish123** [comment]
I believe the CF cache is currently set to be invalidated every 24 hrs. Let me know. We spoke to the folks maintaining the build scripts they are working on an enhancement to invalidate cache synchronously on every push of index.yml to s3 bucket

**Comment by nebhale** [comment]
@pavankrish123 For [reference](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/common.sh#L2)
