### ISSUE TITLE
Cannot build offline buildpack due to HTTP 404 for introscope agent 10.6

### ISSUE THREAD

**Issue by ivandavidov** [cloudfoundry/java-buildpack#561]
Let's start from scratch:

```
git clone https://github.com/cloudfoundry/java-buildpack.git
cd java-buildpack
bundle exec rake package OFFLINE=true PINNED=true
```

The result:

```
[DownloadCache]                  WARN  Unable to download https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar into cache build/staging/resources/cache: 404 Not Found
The requested path was not found.
rake aborted!
Unable to find cached file for https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar
/home/apama/projects/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:79:in `get'
/home/apama/projects/java-buildpack/rakelib/dependency_cache_task.rb:105:in `block in cache_task'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:227:in `block (2 levels) in invoke_prerequisites_concurrently'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/promise.rb:64:in `chore'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/promise.rb:46:in `work'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/thread_pool.rb:104:in `process_queue_item'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/thread_pool.rb:124:in `block (2 levels) in start_thread'
Tasks: TOP => package => build/java-buildpack-offline-4446775.zip => https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar
```

The artifact [IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar](https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar) doesn't exist and as result the build fails. If we open the [apm-agents](https://ca.bintray.com/apm-agents/) URL we see the following files there:

```
CA-APM-PHPAgent-10.6.0_linux.tar.gz
CA-APM-PHPAgent-10.7.0_linux.tar.gz
IntroscopeAgentFiles-NoInstaller10.0.0_16default.unix.tar
IntroscopeAgentFiles-NoInstaller10.1.0_15default.unix.tar
IntroscopeAgentFiles-NoInstaller10.1.0_70tomcat.unix.tar
IntroscopeAgentFiles-NoInstaller10.2.0_27default.unix.tar
IntroscopeAgentFiles-NoInstaller10.3.0_15default.unix.tar
IntroscopeAgentFiles-NoInstaller10.5.0_20default.unix.tar
IntroscopeAgentFiles-NoInstaller10.5.1_6default.unix.tar
IntroscopeAgentFiles-NoInstaller10.5.2_15default.unix.tar
ca-eula.silent.txt
ca-logo-world.png
index.yml
readme.txt
```

The [index.yml](https://ca.bintray.com/apm-agents/index.yml) file contains entry for introscope agent version 10.6:

```
---
10.6.0_0: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar
10.5.2_15: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.5.2_15default.unix.tar
10.5.1_6: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.5.1_6default.unix.tar
10.5.0_20: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.5.0_20default.unix.tar
10.3.0_15: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.3.0_15default.unix.tar
10.2.0_27: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.2.0_27default.unix.tar
10.1.0_15: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.1.0_15default.unix.tar
10.0.0_16: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.0.0_16default.unix.tar
```

However, the referenced file is not present and I believe that's the root cause of the issue.

Could you please assist me and provide me with information how to fix that? Or better, could you fix that somehow?

Thank you!

**UPDATE:** For now I workarounded the issue by hardcoding the version of the introscope agent to ``10.5.2_15`` in the ``config/introscope_agent.yml`` file.

```
diff --git a/config/introscope_agent.yml b/config/introscope_agent.yml
index 885424b..1dd7394 100644
--- a/config/introscope_agent.yml
+++ b/config/introscope_agent.yml
@@ -16,5 +16,5 @@
 # Configuration for the CA Wily framework
 ---
 repository_root: https://ca.bintray.com/apm-agents
-version: 10.+
+version: 10.5.2_15
 default_agent_name: $(ruby -e "require 'json' ; puts JSON.parse(ENV['VCAP_APPLICATION'])['application_name']")
```

However, this is only a temporary solution. It would be great if there is some kind of permanent solution for this issue.

**Comment by nebhale** [comment]
@DMevada it appears CA has broken their agent repository by putting links to files that do not exist in their `index.yml`.  Can you please either fix, or bring someone onto this issue that can fix, this problem.

**Comment by DMevada** [comment]
Hi @nebhale 

This has been fixed, please check now.

**Comment by ivandavidov** [comment]
I see the reference to the 10.6 version has been removed and as result the artifact should be resolvable. I'll have confirmation in approximately 12 hours.

**Comment by nebhale** [comment]
Thanks for the update @ivandavidov.  I'll hold this open until you confirm.

**Comment by ivandavidov** [comment]
From our side everything looks good. The issue has been fixed. Thank you for the assistance!

**Comment by sumitAtDigital** [comment]
Hi All,
Wanted to set up oracle java buildpack. followed the steps below and deployed "oracle-cache" app.
-----
Downloading the Oracle JRE binary (in TAR format) to an HTTP-accesible location
Uploading an index.yml file with a mapping from the version of the JRE to its location to the same HTTP-accessible location
Configuring the config/oracle_jre.yml file to point to the root of the repository holding both the index and JRE binary
Configuring the config/components.yml file to disable the OpenJDK JRE and enable the Oracle JRE
----
Even tried without forking java-buildpack, set environment variable.

(I am following the article: https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-oracle_jre.md#configuration )

But in both case I am getting below error. Please suggest?

ERROR Detect failed with exception #<RuntimeError: Oracle JRE error: Unable to find cached file for https://oracle_cache.cfapps.xxxx.com/index.yml
