### ISSUE TITLE
HTTP access logs modification in the CF java buildpack

### ISSUE THREAD

**Issue by sureshreddygovindu** [cloudfoundry/java-buildpack#565]
@dmikusa-pivotal I would like to add my custom parameter into HTTP access logs and also I would like to parse access logs like **Key and Value** pair. like below. suggest me how can achieve in the CF. I tried to edit Java Build pack, but it's was not impacted .
`[07/Mar/2018:16:39:28 -0500] [datacenter=local] [env=dev] [cluster=no] [logLevel=access] [[07/Mar/2018:16:39:28 -0500]:???c???] [app-name=xhAccountInfoPortal] ???X???{moneyTrace} [MethodType=GET /img/account-information-logo.png HTTP/1.1] [uuuuu:/img/account-information-logo.png] [sssss:200] [bbb:1644] [kkk:0:0:0:0:0:0:0:1] [yyy:0.003] [useragent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36] [referer=http://localhost:8080/xhAccountInfoPortal/portal/index]`

**Comment by nebhale** [comment]
Access logging is only performed by the router in Cloud Foundry.  You can tell this because of the `[RTR/#]` discriminator in the log line:

```
2018-03-09T08:51:44.36-0800 [RTR/1] OUT ben-test-application.cfapps.io - [2018-03-09T16:51:43.890+0000] "GET / HTTP/1.1" 404 0 121 "-" "curl/7.54.0" "10.10.2.193:36457" "10.10.148.140:61220" x_forwarded_for:"204.15.0.254, 10.10.2.193" x_forwarded_proto:"https" vcap_request_id:"2c9c5f27-71f1-4976-4630-03ef360023fd" response_time:0.477408716 app_id:"e93264bc-69d7-4a7a-b541-675c33d6190a" app_index:"0" x_b3_traceid:"fa0251f5ca3c3ab6" x_b3_spanid:"fa0251f5ca3c3ab6" x_b3_parentspanid:"-"
```

Since this happens above the application layer, it's unlikely you can add application-specific information to it.

**Comment by sureshreddygovindu** [comment]
Thank you @nebhale for your quick response. 
you are right, this is HTTP access log. below is the actual format of access log `xxxxxxx.net - [2018-03-09T18:15:31.958+0000] "GET /img/ajax-loader.gif HTTP/1.1" 200 0 5369 "xxxxxxx.net/css/jquery.mobile-1.2.0.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" "10.54.141.244:53116" "10.54.141.80:64280" x_forwarded_for:"10.36.109.208" x_forwarded_proto:"https" vcap_request_id:"758cd721-9ebd-43b4-4c99-36c325279add" response_time:0.005080074 app_id:"f08549a9-e2ec-45f5-bc1f-ae8ca3dc3b95" app_index:"0" x_b3_traceid:"040c1ceaa454a295" x_b3_spanid:"040c1ceaa454a295" x_b3_parentspanid:"-"  
`
 I would like to inject some more properties to this access log. how can we add new properties into access log(RTR logs)? 
I can able to inject new properties in the application logs(APP) because application has control on the log patterns. I'm unable to add new properties into HTTP logs(RTR). Can you suggest me how we can add new properties?

**Comment by nebhale** [comment]
I'm not sure how you're getting application-level access logs.  They are disabled by default in CF's contributed Tomcat as they are often redundant with the router's access logs.  If you using our Tomcat instance and enabling access logging, then you need to fork the buildpack and update the Tomcat configuration in `resources/tomcat`.  If you are packaging Tomcat within your application (like Spring Boot, then the configuration is done in the application's configuration).

**Comment by sureshreddygovindu** [comment]
Thank you @nebhale locally(dev workstation) HTTP access logs are working fine as we defined format, whenever I deploy application in the CF access log pattern is not working.  I've forked my own Java Build pack and changed log patterns in `resources/tomcat` even though I'm unable to change access log formats.  this is my forked Java Buildpack https://github.com/sureshreddygovindu/java-buildpack-2.git

**Comment by nebhale** [comment]
The modification to your fork seems accurate, but again access logging is disabled by default. You'll need to [configure](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#configuration) your [buildpack](https://github.com/sureshreddygovindu/java-buildpack-2/blob/master/config/tomcat.yml#L35) to enable access logging if you want the **additional** Tomcat access logging as well as the router's logging.
