### ISSUE TITLE
getting jacoco coverage data

### ISSUE THREAD

**Issue by tdrury** [cloudfoundry/java-buildpack#567]
I have a question about getting the coverage data out of CF: um, how do you do it? I've always used tcpserver mode on my (non-cloud) servers and it's fairly easy.

Is it possible to configure jacoco for tcpserver mode or is only tcpclient allowed?

I've never used tcpclient mode. When does it send coverage information? Reading the jacoco docs (and googling) on tcpclient mode, it's not clear.

**Comment by nebhale** [comment]
My understanding is that you run a server that acts as a collector.  The connection information for that server is passed in via the service binding.  That server typically exists outside of the CF footprint.  Perhaps @jonathanamartin has some pointers to documentation.

**Comment by konstantinblaesi** [comment]
https://github.com/cloudfoundry/java-buildpack/pull/715#issuecomment-492109959
