### ISSUE TITLE
Add opt-in support for outputing configureable HTTP access logs to loggregator

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/java-buildpack#57]
Following up https://github.com/cloudfoundry/java-buildpack/issues/30#issuecomment-43521595 

The gorouter currently generates non configureable http access traces of the following format (see [access_log_record.go](https://github.com/cloudfoundry/gorouter/blob/2137a9fa4ce792c6d521dcafa85fb48522f9283e/access_log/access_log_record.go#L39) for desc of each field)

```
2014-05-16T14:10:10.80+0200 [RTR]     OUT php-info-gberche.cfapps.io - [16/05/2014:12:10:10 +0000] "GET /info.php?=PHPE9568F35-D428-11d2-A769-00AA001ACF42 HTTP/1.1" 200 2146 "http://php-info-gberche.cfapps.io/info.php" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0" 10.10.2.122:62465 vcap_request_id:c8a81f5e-77d7-4d6e-7f99-288f07ee0345 response_time:0.004421576 app_id:65b6cb42-10b1-48f5-9722-e79df58c34ec
```

This has the following limitations for app-dev or app-ops:
- when trying to troubleshoot rooter to buildpack issues (e.g. timeouts, hanging connections, latencies ...) app-ops need to ask both actors for their truth. Currently, they only have the gorouter version. 
- the verbosity of the log can not be controlled. For example, some apps implementing some REST APIs might be quite sensitive to HTTP headers that are not currently logged.
- inability to temporary enabling verbose logs on a app (all instances or a subset) to perform some debugging
- the format can not be controlled, and since it does not currently map to standard format, this may forces log archiving tools to parse it explicitely (e.g. https://github.com/logsearch/logsearch-filters-cf if I understand it correctly)

Fortunately, the gorouter now generates a `X-Vcap-Request-Id` (may be ultimately `X-Request-Id` see cloudfoundry/gorouter#29 ) in the HTTP header of requests send to apps and logs this request in the router access logs. This enables correlation with more detailed access logging that can be done in apps themselves or with support from the java-buildpack.

This is consistent with the heroku approach documented at https://devcenter.heroku.com/articles/http-request-id

Currently, the java-buildpack allows to tune the tomcat configuration files (e.g. server.xml and to turn on the [access valve](http://tomcat.apache.org/tomcat-7.0-doc/config/valve.html) ) by [forking the buildpack](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#additional-resources) and placing customized file into the `resources/tomcat` directory.

To make it easier for java-buildpack users, I'm suggesting to offer the configuration by default in the javabuildpack and limit the amount of configuration work in required by app-ops.

I'm therefore suggesting the java-buildpack to allow ops to opt-in access logs:
- dumped to stdout to be collected by the loggregator, 
- with a default sensible format:
  - with a `[ACCESS]` prefix to differentiate access logs from app logs (`[STDOUT]`) or container logs (`[CONTAINER]`)
  - with the `X-Vcap-Request-Id=<value>` 
  - with remaining standards fields in one of the standard format (e.g. apache access logs)
- opt-in controlled by `config/tomcat.yml` with new property such as `access_login.enabled=true` (and ideally in the future ENV var controlled opt-in as to avoid most forks for turning on access logs)

App-ops can then still fork the buildpack to tune the access logs format (or ideally control it with an env var in the future)

App-ops that require to dynamically turn the access logs can embed JMX remoting app such as jolokia ( related discussion into the tracker [46897105](https://www.pivotaltracker.com/story/show/46897105) ) to control [the RemoveValve bean](https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/valves/mbeans-descriptors.xml#L62)

Ideally in the future, the following details would be added to the gorouter, to fully enable debugging the router/app http chain (feature parity with [heroku router log format](https://devcenter.heroku.com/articles/http-routing#heroku-router-log-format) ):
- router adds connect: amount of time spent establishing a connection to the backend web process
- router adds service: amount of time spent proxying data between the backend web process and the client (if that's different from r.ResponseTime())

**Comment by imod** [comment]
I have read the whole thread on the [ML](http://cf-dev.70369.x6.nabble.com/cf-dev-Allow-gorouter-to-log-random-headers-td800.html), but I don't understand why this has been implemented in a way that obnly operators can use/configure it. This makes this feature pretty much useless for all hosted environments like 'run.pivotal.io' or 'swissom'. Or do you expect the hosters to do such a configuration for each app on request?
