### ISSUE TITLE
can't find jstat to track gc

### ISSUE THREAD

**Issue by simonzhong1985** [cloudfoundry/java-buildpack#570]
Hi, 
I can't find jstat tool to track gc. 
Is there another way to track gc?

![image](https://user-images.githubusercontent.com/29529035/38028192-bbcec1b4-32c4-11e8-972d-e7f33e7a0194.png)

**Comment by nebhale** [comment]
I think you'll find that `jstat` is a tool that is only included in the JDK, not the JRE.

```
$: ls -1 /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/bin
java
jjs
keytool
orbd
pack200
policytool
rmid
rmiregistry
servertool
tnameserv
unpack200

$: ls -1 /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin
appletviewer
extcheck
idlj
jar
jarsigner
java
javac
javadoc
javafxpackager
javah
javap
javapackager
jcmd
jconsole
jdb
jdeps
jhat
jinfo
jjs
jmap
jmc
jps
jrunscript
jsadebugd
jstack
jstat
jstatd
jvisualvm
keytool
native2ascii
orbd
pack200
policytool
rmic
rmid
rmiregistry
schemagen
serialver
servertool
tnameserv
unpack200
wsgen
wsimport
xjc
```

That being said, we do [add some JDK tools to our JREs](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/openjdk.sh#L37) to help with diagnostics like this.  We could add `jstat` but it wouldn't show up until the Java release when we build the new JRE.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by saurav28** [comment]
Is jstat included in build pack...this is needed for profiling/monitoring tools
