### ISSUE TITLE
Java 10 Roadmap

### ISSUE THREAD

**Issue by thorntonrp** [cloudfoundry/java-buildpack#572]
Java 10 is now GA and major frameworks like Spring Boot 2 are ready for it. What is the roadmap for Java 10 inclusion in the buildpack?

**Comment by nebhale** [comment]
Unclear at this time.  We've had effectively zero uptake of Java 9 even though we aimed to support it as quickly as possible.  It's not clear that our effort was well spent there, and the question arises as to whether we should be pushing hard for Java 10 either.  At some point soon we'll start building Java 10 JREs, but if there's a lot of overhead to make that happen, we'll have to really think about the priority of that versus other efforts.  In addition, it will likely be an extended time before it becomes the default JRE shipped as part of the buildpack.

**Comment by youngm** [comment]
@nebhale A couple additional notes.  My org has created a fork of the buildpack that uses java9 as the default which can be selected as an alternative to our primary java8 buildpack.  We have gotten several users working with/testing java9.  We mirror the aws repository so you might not see our usage in those metrics if that is how you are determining uptake.

Once you are able to prioritize getting a java10 builds up we will do the same for java10 and actually deprecate our java9 branch soon with java10 as the replacement.  We will not change the default jdk ever to java10 but will change the default to java11 when it is out and JBP support for it is stable.  I think making support for java9 and subsequently java10 is important to be available for users to test with to help for a smooth transition for java11 as the default.

Anyway, there is some additional info on how my org is making java9 and plan to make java10 available in case any of that info helps you to determine how to prioritize java10 builds.

**Comment by nebhale** [comment]
Java 10 JRE's are now available for testing.  I suggest that we close this issue out, and open individual issues on anything that doesn't work.

**Comment by Quietghost** [comment]
Hi there, I have a quick follow-up question. 

Where can I find the newest information about the roadmap - if something like that exists - about the support of Java 10 in an official buildpack? - I haven`t found any othe issues related to it here ...

Thanks in advance!
