### ISSUE TITLE
CF - Container OOM 137 

### ISSUE THREAD

**Issue by veeraviswam** [cloudfoundry/java-buildpack#573]
Hi,

Currently using cf version 6.34.1+ and the latest Java buildpack from 

https://GitHub.com/cloudfoundry/java-buildpack.git

The app instance is using 10gb memory with the default memory calculation by the buildpack and it crashes with the following error randomly under load and multiple times. Also it seems like heap memory is not utilized completely at the time of crash and something outside of app requesting more memory (native??) and the crash happens.

```
OUT App instance exited with guid 9bd973a3-2d0b-40e0-b76d-c49201c674cb payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 137 (out of memory)\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1522778790158864443, "version"=>"5465213b-839f-4972-aeed-93cb6787bf8f"}
```

Heard suggestions about explicitly mentioning Xmx and direct memory options instead of using the default settings but would like to get a guidance on this issue as nothing seems to work based on those threads suggestions from the internet.

Thanks in advance!

**Comment by nebhale** [comment]
We've found that the JVM memory (specifically internal JVM native memory) is very difficult to reason about above about 4G.  The memory calculator is a best effort that we can make, but unfortunately, it is impossible for us to pick a configuration on startup that is guaranteed to never exceed the container's memory limit above that.  We'll keep focusing on the "typical" case of <4G heaps and working hard there, but if you're going above that you'll need to manage your memory settings manually.  You can do this with [standard Java memory configuration flags](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#java-options).
