### ISSUE TITLE
JBP v4.10 release marked as AppDynamics Improvements instead of CA Introscope

### ISSUE THREAD

**Issue by ptamma** [cloudfoundry/java-buildpack#575]
@nebhale  JBP v4.10 release marked as AppDynamics Improvements instead of CA Introscope APM . The release info is misleading. I learned looking at commit log. Please can you correct release info. Thanks.

@DMevada  any plans to get CA Introscope agent to Liberty buildpack ? Happy to loop in IBM and CA relation manager if needed. Please share your email id. I have few hundred app running on PCF with liberty BP. Thanks

**Comment by DMevada** [comment]
Hi @ptamma,

Please send me an email at dhruv.mevada@ca.com, and I will be happy to discuss this further.

**Comment by nebhale** [comment]
Thanks for pointing that out.  Fixed now.
