### ISSUE TITLE
Health checks fail when thread-bound

### ISSUE THREAD

**Issue by bobbyhubbard** [cloudfoundry/java-buildpack#580]
We had a second complete outage of our app due to PCF containers flapping and restarting when we open the flood gates. I think I know why but I need some direction as to how to fix it...

In both outages we were able to bring it back up by first directing traffic to VMs (which sucks because we're trying to get rid of the VM). What is different? Well there they have the same 100 (or 200?) max-threads set but they have a 15 second timeout vs the default PCF 1 sec health check.

Theory: 
When we release the flood gate, typically connections at HAProxy (outside of PCF) are at about 2000/s. So 2000 connections /sec flood ~100 instances with 100 max-threads set. The app essentially is a proxy so it then turns around and makes outbound calls to internal micro-services. Initially, those dependent services are laggy (300-600ms) response times. Eventually those high latency requests  even out as the downstream apps get full cached and warm. The problem is that initial start period. We see after 15-30 seconds post flood gates that the instances start to flap. But CPU prior to the flap seemed fine. The guess is that we've hit the max-threads limit and the health check gets queued. Now the app is waiting on the laggy responses and is doing virtually nothing but the health check then fails and the instance is killed. Causing fewer containers to take the volume, more maxed threads... and it just snowballs out of control.

Options: 
1. More instances. Ugh. No. Not addressing the problem.
1. We could obviously increase the max-threads. But I dont have any way to estimate how high to go. Honestly I really dont want MORE pressure on the API teir at this point anyway... we're ok with the backpressure building behind PCF while we wait for the volume to come off its initial peak (mobile apps all getting line for an update). So increasing threads is actually not helpful. 
1. We could move to a "process" health check but then I dont have a way to truly test the health of my spring boot app. Not ideal and seems like a hack. 
1. Circuit breaker. Its on our list but I'm still not sure it would fix this. 5, 1 second dependent service calls could still back up threads. 
1. Async/Reactor - We're also looking at that. Not a huge appetite at the moment for that big of a change in the app. 
1. Figure out a way to give priority to the health check during a thread-bound scenario. Boot+actuator technically allows you to do this if you specify a `management.server.port. Now tomcat is configured with a separate connector and thus an independent thread pool. Perfect.

I prefer option 6 but PCF/java_buildpack (as far as I am aware) doesn't allow me to a) map multiple ports and b) specify a custom port+path for the http health check. Other options?

So surely we're not the only ones with this problem. What is the recommendation? How do we ensure the instance is not killed in a thread-bound scenario?

Spring Boot 1.5 
PCF 1.10 
Java_Buildpack 4.9

**Comment by bobbyhubbard** [comment]
Feels like WebFlux is gonna be the answer...

**Comment by bobbyhubbard** [comment]
Well I chatted with a support team and it sounds like this is by design. I personally think its crap. The app IS healthy and IS doing its job. The downstream services combined with huge volume mean the health check never gets a chance to load in the 1 sec that is required for it to respond. I’m perfectly ok in this situation waiting longer than 1000ms for a web app to respond to a health check. PCF isn’t for some reason… and NO it doesn’t know better than us. ☺ Failing the health check and restarting the container in this scenario only makes the problem worse. Resulting in a downtime and a team that HATES CF. 

CF and having ZERO flexibility on the health check timeout is a major contributing factor. To the appropriate team: this usecase is evidence for a configurable health check timeout or an alternate connector in tomcat for health checks (ensuring the health check happens on a separate thread pool).

**Comment by giner** [comment]
Heathcheck endpoint should be considered as a communication channel between the platform an application. While it is easy to agree on a way of _communicating_ the application status it is not so easy to make a generic interface for comprehensive monitoring.

My attempt to add a warning is here https://github.com/cloudfoundry/docs-dev-guide/pull/326.
