### ISSUE TITLE
Support for TCPKeepAlive setting in Luna Security Provider

### ISSUE THREAD

**Issue by gm2552** [cloudfoundry/java-buildpack#584]
In some networks, the connection to a Luna device may get severed due various configuration options.  In these cases, a Java application using the Luna JCA/JCE provider cannot reconnect without restarting the application.

One possible mitigation is using the `TCPKeepAlive` option which can be set in the `Chrystoki.conf` file.  

Ex:

```
LunaSA Client = {
   TCPKeepAlive = 1;
   ReceiveTimeout = 20000;
   SSLConfigFile = /usr/safenet/lunaclient/bin/openssl.cnf;
   ClientPrivKeyFile = /usr/safenet/lunaclient/cert/client/xx.xx.xx.xxKey.pem;
   ClientCertFile = /usr/safenet/lunaclient/cert/client/xx.xx.xx.xx.pem;
   ServerCAFile = /usr/safenet/lunaclient/cert/server/CAFile.pem;
   NetClient = 1;
   HtlDir = /usr/safenet/lunaclient/htl/;
   ServerName00 = xx.xx.xx.xx;
   ServerPort00 = 1792;
   ServerHtl00 = 0;
}
```

Luna Documentation (page 117):  https://knowledgelayer.softlayer.com/sites/default/files/hardware_security_module_hsm/configuration_guide.pdf

The current Luna Security Provider in the Java build pack does not currently have an method to set this option without creating a fork.  It would be beneficial to have a method to set this option to mitigate issues caused by network disruptions.

**Comment by gm2552** [comment]
Quick update:  A dialog has been started on the lists site [1] and a candidate solution committed [2] into a fork.

[1] https://lists.cloudfoundry.org/g/cf-dev/topic/proposal_network_connection/18127295
[2] https://github.com/gm2552/java-buildpack/commit/09a089efca0c94279691eb476ec2447ee09f609a

**Comment by nebhale** [comment]
Happy to include this.  A quick look over your change looks good as well, so feel free to submit a PR and I'll include it.

**Comment by gm2552** [comment]
Thanks.  I ran the unit tests, and I needed to fix a couple of things up (some formatting, one error, and I added one test for the new functionality).  I'll get a pull request put together tonight or tomorrow morning.

Thanks again.

**Comment by nebhale** [comment]
Closing in lieu of the PR.
