### ISSUE TITLE
Allow configuring a custom NewRelic App Name

### ISSUE THREAD

**Issue by stephanerenou** [cloudfoundry/java-buildpack#598]
Quite identical to what was done on php: https://github.com/cloudfoundry/php-buildpack/issues/92
it would be good to allow to set the app name to report data to new relic for example in case of blue green deploiement.
Maybe this would just be something that needs to be documented as this was done for php:
https://docs.run.pivotal.io/marketplace/services/newrelic/#php
But I can't find which env variable could be used, or what should be the name of the config file if we don't want to fully rewrite all of the standard new relic config file.

**Comment by nebhale** [comment]
Doesn’t setting `cf set-env <APP> JAVA_OPTS ‘-Dnewrelic.config.app_name=<NAME>’` allow you to do this?

**Comment by stephanerenou** [comment]
thanks that made the trick for me. Could that get added to the doc? I was confused as I wanted to also define the newrelic config extension dir and that needed to be an env varaiable and not a JAVA_OPTS.

**Comment by stephanerenou** [comment]
ok thanks, I created a PR on the pivotal docs.
