### ISSUE TITLE
jvmkill Agent 1.12.0_RELEASE

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/java-buildpack#601]
Hi, our team would like to use Java-buildpack 4.9 but to approve that I've to analyze the source code of the Java-buildpack 4.9 along with the chain of all its dependencies (to verify that there aren't  not-approved licenses), but I cannot find the source code location of the jvmkill Agent 1.12.0_RELEASE.

Is it commercial code? 

Instead, if it's open source could you please tell me what is the download location of its source? 

Thanks.

**Comment by nebhale** [comment]
https://github.com/cloudfoundry/jvmkill

**Comment by luisapace** [comment]
thanks!
