### ISSUE TITLE
Support for throttling of console output

### ISSUE THREAD

**Issue by vsfalexanderpilch** [cloudfoundry/java-buildpack#615]
One of our application has created an unexpected amount of log entries (several TB within an hour), which were sent to stdout. The central log processing (splunk/graylog) was not able to handle it as a result. Would it be possible to introduce some rate throttling in order to limit the output of an application? 

This is basically just a feature request in order to increase the stability of the platform overall.

Here's an example, which is working fine in the shell, but I'm not sure if stg similar could be integrated with cf/the java buildpack. It's basically applying back pressure to the producer:

dummy.sh:

```
#!/bin/bash
i=0
while true
do
        echo -n "SPAM_$i "
        i=$((i+1))
done
```

The following command will reduce the console output to 10 bytes/s by using pipe viewer:

`./dummy.sh | pv -q -L 10 -B 10`

**Comment by nebhale** [comment]
In general, no I don't think we'd introduce something like this.  The major reason why is that there's no single point in a JVM that I can intercept and throttle console output.  Any class can `System.out.print()` (this is all that logging frameworks are doing in the end), so there's no reasonable intercept point that can actually watch all output.  The secondary reason is that while throttling might be needed for your Splunk installation, it isn't necessarily needed for all Splunk installations, and not for all log warehouses.

The proper location to do this kind of throttling is at the nozzle that ingests logs into Splunk itself.

**Comment by vsfalexanderpilch** [comment]
It depends imo
1) The jvm isn't able to control the output, but the surrounding platform is able to. As cf is supporting php and other languages as well, there's probably some way to influence the rate of output (e.g. by launching it with a throttling pipe)
2) The logging platform is sized reasonably for standard loads. There're several gb of logs per day and it's able to handle that. Noone was expecting traffic in the area of tb. One misbehaving app can cause a lot of trouble and this could easily happen to others too. Fixing it in splunk is possible, but it would be easier if this amount of data wouldn't be created at all. 

I guess it would be nice to have more fine grained control over the resource usage. There's QoS for networking, memory limits and also cpu limits on other platforms. This request is basically similar to those by just adding another dimension of restrictions.

**Comment by nebhale** [comment]
I don't have any arguments with those points, but in both cases, those are platform concerns not buildpack concerns.  I'd suggest that you open issues against the projects that govern the areas you're referring to (Diego and Loggregator respectively).

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
