### ISSUE TITLE
How to use cf run-task?

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/java-buildpack#616]
What is the recommended way to use tasks with the java buildpack?

The buildpack generates a lot of command line parameters for java when running an app. I think especially the memory options and the certificate stuff should be reused when running a task. Is there a helper function we can use when running cf run-task "..."

As this buildpack has special support for Spring applications: are there any features to use it with Spring Cloud Tasks?

**Comment by nebhale** [comment]
Unfortunately, as things in the Cloud Controller and CLI exist today, the answer is copy-and-paste.  You are correct that the command, as defined by the Java Buildpack, should be used in its entirety to run a task.  There is no concept of an "alias" or a shortcut around the command for a task; it must be defined explicitly on each invocation.

There is no special support for Spring Cloud Tasks, other than what we provide to all Spring applications.  What did you have in mind that we might build?

/cc @cloudfoundry/cf-cli

**Comment by mayrstefan** [comment]
I'm only an operator but I have seen our developers copy&pasting the command line options from apps to tasks. This is fine as long as no library version changes. But after a buildpack update with updated librarys I expect their tasks will fail. They have to update to the new filenames. That looks to unstable for a long term usage of tasks. That would prevent a wider adoption of cf tasks.

I look for something like /bin/release that can be extended to task parameters. Thinking about it maybe this is already usable this way if the application is compiled to a jar
`cf run-task '$(/bin/release) myparam'`

I guess I should do some experiments.

Anyway, using task seems still quite inconvenient. What would be the correct project to address tasks as a topic in buildpack definition? Maybe to add some metadata for pre-named tasks in an application?

**Comment by mayrstefan** [comment]
After some first test I found this generic solution to extract the details from the compiled droplet
`cf run-task demotask "source <(jq -r .\"start_command\" /home/vcap/staging_info.yml)"`
(Windows-Quoting)

Still quite ugly and it's missing custom parameters

**Comment by abbyachau** [comment]
cc @zrob for visibility
