### ISSUE TITLE
Feature Request: Please add support for JProfiler

### ISSUE THREAD

**Issue by anwarchk** [cloudfoundry/java-buildpack#617]
Just like YourKit support in JBP, it would be great to have support for JProfiler. There are many organizations that has already invested in JProfiler licenses and would be really helpful if we could add support for that.

**Comment by nebhale** [comment]
License and distribution seem to be amenable to inclusion when distributed by commercial distributions.

**Comment by nebhale** [comment]
* [How to connect to remote](https://www.jvmhost.com/articles/connect-remote-jvm-jprofiler/)
* [Donwload](https://www.ej-technologies.com/download/jprofiler/files)

**Comment by anwarchk** [comment]
Thanks @nebhale !!!!
