### ISSUE TITLE
Support for Application Insights Java Agent

### ISSUE THREAD

**Issue by HDYA** [cloudfoundry/java-buildpack#620]
Hi, 

I've been working on Java/Monitoring related stuffs for a while and recently we noticed that GCP StackDriver add Java agent to their application through frameworks inside Java Buildpack. ([StackDriver Debugger](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-google_stackdriver_debugger.md) and [StackDriver Profiler](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-google_stackdriver_profiler.md))

Customers will also need a Java agent to be included in the invocation to enable full capability of Azure Application Insights, which can only be done inside the buildpack. Was it also acceptable if we implement similar mechanism for Application Insights?

Thanks.

**Comment by nebhale** [comment]
Absolutely!  The key thing that we prefer is that the agent be publicly available (preferrably open sourced) and versioned and that the license is such that it can be distributed by the Cloud Foundry Foundation and Cloud Foundry commercial distributions.

**Comment by HDYA** [comment]
That's very nice of you Ben!

The agent is located in [Application Insights Java SDK repository](https://github.com/Microsoft/ApplicationInsights-Java) (in the "agent" folder) distributed in MIT license.

You may find the binary in releases of the same repository and the document [here](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent).
As it currently requires some configuration on methods to monitor exceptions and execution time, we might need some discussion on the implementation?

**Comment by nebhale** [comment]
Agent [replicated](https://java-buildpack.cloudfoundry.org/azure-application-insights/index.yml).

We'll use the [system property style](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started#alternative-ways-to-set-the-instrumentation-key) to set the instrumentation key from a service payload.

We can put the [`Ai-Agent.xml`](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent#configure-the-agent) file into place, but modifying it is likely to be difficult for most users.  In general, we take the opinion that the authors of the integration (technical me, but you for these purposes) know what the "best" configuration is for applications running on Cloud Foundry.  So ideally, you'll provide me with a "best" configuration file to include, and we can discuss exactly how much flexibility a user will need to modify that file.

**Comment by HDYA** [comment]
I have saw the commit, that's amazingly agile Ben.

For most users I think current default configuration file should cover their needs. 

Given that the rest of the configuration file is to select methods to be monitored, users should be able to decide it. (And we will have no idea what they are going to name methods they fell interested). Do we have a best practice solution reference for the circumstance that "professional" user wish they could provide their own configuration file?

**Comment by HDYA** [comment]
Thanks Ben, I think current implementation can handle most of customer requirements except methods metrics. 
I'm still checking with corresponding developers to see if we can have all methods monitored. If not, may I implement some kind of configuration mechanism to generate this part of configuration file in next version of buildpack?

At last, I think we can assume that if user specify a instrumentation key in the application's environment variable, AppInsights is supposed to be enabled for it. So can we enable the java agent once there is a environment variable "APPLICATION_INSIGHTS_IKEY"?

**Comment by nebhale** [comment]
Let’s discuss method mornitoring once we know a bit more about what the trade offs are.

We use service bindings (either from a service broker or a user provided service) in order to communicate endpoints and credentials to integrations like this.  In [this case](
https://github.com/cloudfoundry/java-buildpack/commit/40dfec8f08251f6e56829cb012c9182b37925f8f#diff-e31e605749fcdeb5291208d38d4b362bR3), we look for any service that has a name, label or tag with `azure-application-insights` in it and contains the `instrumentation_key` credential.  That credential information is then used to set the `APPLICATION_INSIGHTS_IKEY` system property.

So in this case, the declaration of intent is the binding of a service, not the setting of an environment variable.  This allows the most flexibility, especially when it comes to rotating credentials with a Service Broker and CredHub.

**Comment by HDYA** [comment]
Hi @nebhale , 
Thanks for your explanation on the design principle.
BTW, I've got the response that we currently don't have a wildcard style of configuration to monitor all methods. So I guess the default configuration file your implementation is currently using should be the most suitable solution for now.
What will be our next step for this? Shall we draft a document like [this](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-google_stackdriver_profiler.md)?

**Comment by dhaval24** [comment]
@HDYA and @nebhale I am a core developer in Azure Application Insights for Java, and I just came to look into this thread and the integration with CloudFoundry. This is amazing. Now answering the questions on the discussion here.

I would like to let you know, that it is indeed not needed to configure each method in the java agent. 

AI-Agent automatically instruments the methods in the libraries like MySQL, MsSQL, Oracle DB, Apache HTTP Client and Redis. Therefore you will get out of the box instrumentation for all the key methods in these libraries and you should be able to see the dependencies light up without any additional configuration. 

The section to configure custom methods is only meant for users to have the ability to instrument any mission critical methods that they might have in their application and get that timed. There is absolutely no need to do this from build pack perspective. That flexibility is totally meant for users. It is practically totally impossible to instrument every method by default in a project. There are tons and tons of them in a boot project. Also purely from the timing perspective I think it's better to have this data as metric (which Application Insights can now get with the help of Micrometer Azure Monitor Extension, a work which was done recently, and can help getting `@Timed` methods in SpringBoot send metrics with timing data) and should abide to use that, as that is very native in SpringBoot. 

With respect to agent, we would continue to invest in collecting core dependencies and expand our autocollection suite over time. 

Regarding, the need to place AI-Agent.xml in the (it is not indeed needed). The AI-Agent is a JVM agent and it binds to JVM. The agent can reside else where in the container in any other folder where the user application is deployed on CloudFoundry. The only constrain we have today is that the AI-Agent.xml file and the AI-Agent jar file should be in the same folder. As long as that constrain is satisfied it should be good to go!

Let me know if you have any additional questions.

**Comment by nebhale** [comment]
@dhaval24 Then I think we're probably ready to merge.  If you could take a look at [the implementation](https://github.com/cloudfoundry/java-buildpack/commit/53233bfd0fb2bacbccea087f52a9d1b6c597cf8a#diff-e31e605749fcdeb5291208d38d4b362bR35) (you shouldn't need to be a Ruby developer to understand what's going on) and give your blessing, I'll get it in.  Note that the `copy_resources` command will copy the "default" `AI-Agent.xml` into the same directory as the agent JAR, as you described.

**Comment by dhaval24** [comment]
@nebhale overall it seems fine to me. However, I am a bit confused or actually not sure if you are educated about this part - Application Insights Java Agent cannot run, if user app doesn't have Application Insights Java SDK. By "cannot run" I mean it would be essentially noop.  So inorder to get the full monitoring you need Application Insights Java SDK (as project dependency) and Application Insights Java Agent to instrument dependencies. I would like to make sure that SDK is also provided via build pack before you merge and make a release with this.

**Comment by nebhale** [comment]
How is a user supposed to include this library? As a dependency in Maven or Gradle?

**Comment by dhaval24** [comment]
Yes, this is a maven / gradle dependency as usual.

**Comment by nebhale** [comment]
OK, then I don't think there's anything we can do.  We're not likely to contribute that dependency and I wouldn't prevent the application from staging if it was missing.  Since it's almost impossible to tell, after compilation whether a dependency is present (is it located in a distZip location, is it located in a Spring Boot location, is it exploded into an uber-JAR like Gradle used to do, etc.) then we have to make it best effort.  In this case, best effort is that you've created a service binding (an explicit opt-in by the application developer) and so we'll contribute and configure the agent.  If you, the application developer, forgot the dependency, then you'll need to add it in on your next push.

**Comment by dhaval24** [comment]
That makes sense to me. I think it safe to assume that if user chooses application insights and follows the instructions, then he would have the dependency.

**Comment by nebhale** [comment]
OK, then I'm ready to merge and make available in the next release.  @dhaval24 Have you had a chance to talk to the team doing the [Azure Service Broker](https://github.com/Azure/meta-azure-service-broker)?  The best scenario for you users is that you get included there and the credential payload is written automatically.

**Comment by dhaval24** [comment]
@nebhale I am not sure if that is the exact team I have ever touch based with. I have been talking to multiple folks trying to enable Azure Application Insights with Cloud Foundry, however I don't know the name of the team per say is "Azure Service Broker".

**Comment by nebhale** [comment]
I would highly recommend reaching out to them.  The service broker is the facility to that allows users to do:

```
$ cf create-service my-apm azure application-insights
$ cf bind-service my-app my-apm
$ cf restage
```

and have everything just work transparently.  I'm not going to hold this PR for that, but it is something I recommend for improved usability.

**Comment by dhaval24** [comment]
That makes total sense. Thanks @nebhale . Do you know the core engineer on that team? If you do know please mention him or her on this PR and then I can just talk to him or her.

**Comment by HDYA** [comment]
Hi @dhaval24 ,meta Azure Service Broker is also owned by our team and we are actually discussing it. As there is another broker named Open Service Broker for Azure and technically we are looking for replacing MASB with OSBA.

**Comment by HDYA** [comment]
Hi @nebhale , is the framework supposed to pick up version number in user-provided-service's tag? I tried tag it "azure-application-insights-agent=2.1.2" but it still downloads agent version 2.2.0. Will try again later.

**Comment by nebhale** [comment]
@HDYA No it does not pick up versions there.  Versions are defined as [part of configuration](
https://github.com/cloudfoundry/java-buildpack/blob/master/config/azure_application_insights_agent.yml#L18) and are modified using the buildpack’s [various configuration mechanisms](
https://github.com/cloudfoundry/java-buildpack#configuration-and-extension).  Note that as part of the CF way of doing things, we expect users to be moving forward with the latest and most secure versions of dependencies at all times.  Some users will pin to specific versions, but it should be rare and is compatibility (e.g. the the buildpack will configure old dependencies correctly) is generally not guaranteed.

**Comment by Rajasimhan** [comment]
@nebhale : This is exactly what I was looking for. Thanks. 

per microsoft, the recommended approach (since last year) is codeless agents, https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

When this fix was made, there was a requirement to have Azure insight SDK as a code dependency, for the instrumentation to work. @dhaval24 It should not be anymore right?

So @nebhale & @dhaval24 , with the latest java buildpack, can we seamlessly integrate with Azure insight with the recommended Azure insight agent (3.0) without any code dependency from maven or gradle and pass instrumentation key via user provided service? if not, can be this addressed in any of your future releases?

**Comment by dmikusa-pivotal** [comment]
@Rajasimhan It looks like the buildpack is bundling the latest 2.x (2.6 at this time) version of Azure App Insights. Version 3.0  is just not set as the default version. 

If you wanted to pull in version 3, you could by modifying the [config file](https://github.com/cloudfoundry/java-buildpack/blob/main/config/azure_application_insights_agent.yml#L18). See [this section for instructions on how to modify config](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension) or you can `git clone`, check out a releases branch, modify the config file & build a version of the buildpack you can upload to Cloud Foundry with `cf create-buildpack.

If that doesn't work for any reason, feel free to open a new Github issue. This one is very old, so please start with a new thread. Thanks

**Comment by Rajasimhan** [comment]
@dmikusa-pivotal Thanks, will do
