### ISSUE TITLE
Supply additional libraries into tomcat/lib

### ISSUE THREAD

**Issue by mjnorman** [cloudfoundry/java-buildpack#621]
I have a proprietary framework that is normally operated by standing up a windows server, installing tomcat, and installing framework libraries into tomcat/lib. These are shared by all applications running on that server. Then the application itself has a few libs that it needs to compile. 

I'm trying to convert this to being able to using CF.  I know I can just build a docker image containing all of my custom libs but I like the customization available within JBP like memory calculator, etc. Is there a way to supply these extra libs to JBP during a push ?

**Comment by jhliptak** [comment]
You basically have two options:
1. Fork the buildpack and add an additional component.  We have done this not only to have jar files in tomcat/lib, but also to use native shared libraries as well.  If you know Ruby this is pretty easy, if you are teaching yourself Ruby just for this one task it can be an issue.
2. Use the .profile.d script to move jar files from your application deployment to tomcat/lib.

**Comment by making** [comment]
@mjnorman my example will help you
https://github.com/making/demo-payara-micro5/blob/hazelcast/pom.xml#L67-L73
https://github.com/making/demo-payara-micro5/blob/hazelcast/.profile

**Comment by nebhale** [comment]
I think one of the first things to take into account is that only a single application will ever run in a Tomcat instance on Cloud Foundry.  Therefore, including libraries in `$CATALINA_HOME/lib` is unnecessary as they'll never be shared.  Instead, all of the libraries required by an application should be container and versioned with that application.  This prevents the lock-step upgrade problem that has been so prevalent in enterprise Java development to date.

If you still need to include libraries within your `$CATALINA_HOME/lib` directory (and again, we strongly discourage this), [External Configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#external-tomcat-configuration) would be the proper way to handle it.

**Comment by mjnorman** [comment]
Oh I get it, trust me.  I know they won't be shared across apps, because each in it's own instance, etc.  However the libraries are engineered in such a way that if you include the runtime libraries in the app/lib, it will cause a conflict because some of those classes are also defined in the libraries in tomcat/lib.  It is what it is.  So I am going down the path with External Configuration.  

Using this method I was able to include my dependent jars.  Thanks all!

**Comment by jhliptak** [comment]
If you fork the buildpack, you are not limited to a single war file anymore.  We had an internal format with ./apps/*.war ./lib/*.jar and ./config/*.[xml|properties]  directories in a tar file which I extended pretty easily with a fork of the buildpack.

As always, the real question you have to ask yourself is maintaining that customization work the functionality you get - usually the answer is no.  But for transition support, saying that you can just drop your old builds into PCF and it just works can overcome a lot of resistance.
