### ISSUE TITLE
http2 not working on tomcat 9

### ISSUE THREAD

**Issue by ShinojShayin** [cloudfoundry/java-buildpack#624]
Hi, It seems Apache Tomcat Native library is not configured for java_buildpack tomcat 9

Because of that APR connector is not working. http2 is something we do need to improve our application performance please look into this and add in your future release

**Comment by nebhale** [comment]
The contents of the `rootfs` are managed by another team.  If you’d like to have a new library added, please open an issue against [`cflinuxfs2`](
https://github.com/cloudfoundry/cflinuxfs2) or [`cflinuxfs3`](
https://github.com/cloudfoundry/cflinuxfs3)
