### ISSUE TITLE
Page not found error 

### ISSUE THREAD

**Issue by shivahare** [cloudfoundry/java-buildpack#629]
When I click 'Running Cloud Foundry locally' under https://github.com/cloudfoundry/java-buildpack#running-tests , It tries to access below link and fails with page is not found error.
https://docs.cloudfoundry.org/deploying/boshlite/index.html in not accessible.

**Comment by shivahare** [comment]
We are looking in to https://github.com/cloudfoundry/java-buildpack and in section “Running Tests”     To run the tests, do the following:  
$ bundle install 
 $ bundle exec rake    

Running Cloud Foundry locally is useful for privately testing new features.    

 The link “Running Cloud Foundry locally” shows “page not found”. Will be requiring your help in how to setup env to “unit test” the changes so that we can contribute to Java Build Pack. Will really appreciate your help here.

**Comment by nebhale** [comment]
Yep, link has gone stale.  New best link is https://github.com/cloudfoundry/cf-deployment/tree/master/iaas-support/bosh-lite
