### ISSUE TITLE
Support core Class-Data Sharing

### ISSUE THREAD

**Issue by shakuzen** [cloudfoundry/java-buildpack#636]
Inspired by the JavaZone talk [Java in a World of Containers by Matthew Gilliard](https://2018.javazone.no/program/f732c34b-8293-4b36-b66f-4ff894ee3407), I thought it would be nice if the Java buildpack supported [Class-Data Sharing](https://docs.oracle.com/en/java/javase/11/vm/class-data-sharing.html), either by default or at least as an option. This issue focuses on Java core class-data sharing; I will open a separate one for Application Class-Data Sharing.

### Common Class-Data Sharing

The core Java classes themselves can be cached. I'm not sure if this can be made a layer in the container so that it is shared among JVMs (of the same version) on the same host cell VM. Regardless, this will improve startup times since the common Java classes will be cached. How much it helps will depend on the characteristics of the application (how many core vs non-core classes it loads during startup).

The procedure would be calling `java -Xshare:dump` during staging after setting up the JRE, I believe. This will generate a `classes.jsa` file in `$JAVA_HOME/lib/server`, which will be used at runtime if present and CDS is on: `-Xshare:on` or `-Xshare:auto` (default since Java 11).

**Comment by nebhale** [comment]
Beyond the potential of sharing the layer, what performance improvement will this bring?  How is this any more performant than reading the core classes from the new module archive format?

**Comment by nebhale** [comment]
> As far as I understand, sharing the layer would reduce memory usage for (all but one of the) JVMs on the same host cell.

How exactly do you believe that this would be achieved.  None of the containers on a cell have any visibility into other, or common, filesystems or memory spaces.  By design, these containers are all heavily isolated to prevent exactly this kind of behavior.

**Comment by shakuzen** [comment]
> How exactly do you believe that this would be achieved? None of the containers on a cell have any visibility into other, or common, filesystems or memory spaces. By design, these containers are all heavily isolated to prevent exactly this kind of behavior.

I think it depends on the implementation of how identical read-only image layers are handled. From [the linked blog](https://mjg123.github.io/2017/10/02/JVM-startup.html):

> The other big advantage of CDS is that the cache file is `mmap`-ed read-only, so can be shared between multiple JVMs. This has a nice consequence if you’re running JVMs in containers, that the shared-page usage only counts towards one of the cgroup limits (although _which_ one seems to be [difficult to predict](https://github.com/torvalds/linux/blob/master/Documentation/cgroup-v1/memory.txt#L195-L199)).

I don't know how much of this applies to the containers that the buildpack produces and how they run on Cloud Foundry (which also depends on the specific deployment, probably). However, with Docker, each line in the Dockerfile makes a read-only layer, which in the case of `java -Xshare:dump` would result in the same layer for the same JRE. So I would think (depending on the implementation) this identical read-only image layer would be effectively shared on the host among running containers with that same layer.

From [Docker's documentation on storage drivers](https://docs.docker.com/storage/storagedriver/):

![](https://docs.docker.com/storage/storagedriver/images/container-layers.jpg)

> Multiple containers may share some or all read-only image data. Two containers started from the same image share 100% of the read-only data, while two containers with different images which have layers in common share those common layers.

Perhaps my understanding is incorrect, or maybe none of this works the same with CF buildpack containers, but I'm not sure.

**Comment by nebhale** [comment]
No, this wouldn't work with Cloud Foundry because the containers are not Docker-style containers with shared layers as you might imagine them.  Instead the containers are created against a single rootfs that is standard for all containers and then a tarball containing the "droplet" (the application plus all contributions from a single staging) are streamed into the container and executed.  There is no sharing (other than that single rootfs).

**Comment by shakuzen** [comment]
Even without the memory savings, it still would give a slight improvement to startup time. From Java 12, there won't be anything to do since CDS will be enabled by default ([since 11](https://bugs.openjdk.java.net/browse/JDK-8197967), actually) and the default classlist CDS archive will be included in the JRE (see [JEP 341](https://openjdk.java.net/jeps/341)). But for Java Buildpack users on Java 11 to benefit from this, `java -Xshare:dump` would need to be run before running the user's application.
