### ISSUE TITLE
Support Application Class-Data Sharing

### ISSUE THREAD

**Issue by shakuzen** [cloudfoundry/java-buildpack#637]
This issue is a follow-up to #636. This seems not as easy to support but worth considering.
[JEP 310](http://openjdk.java.net/jeps/310), released with Java 10, added the ability to do CDS with application classes. Many applications will have significantly more non-core Java classes loaded than core classes, and would therefore get more benefit to start-up time from Application Class-Data Sharing (note: they can be used together).

#### List of classes to archive

A list of classes to archive is required. This could be user-provided but usually it is generated using `-XX:DumpLoadedClassList=<class_list_file>`. However, this requires running the application to see what classes it loads. I'm not sure it would be alright in general to start the application during staging to generate this file. Also, it isn't clear when the process should be stopped since it is expected it doesn't exit itself after startup.

#### Classpath-specific archives

I'm not sure how to use AppCDS when running as an exploded JAR (which I believe the Java buildpack does for Java Main applications). The class-data archive must be made with the classpath specified without wildcards and must match at runtime, as far as I understand. You can generate a shared archive with the classpath as the JAR (`java -Xshare:dump -XX:SharedClassListFile=classes.lst -XX:SharedArchiveFile=app-cds.jsa --class-path myapp.jar`) but then can only use that shared archive with the unexploded jar (`java -Xshare:on -XX:SharedArchiveFile=app-cds.jsa -jar myapp.jar`). Using it with an exploded JAR gives an error like the following:

```
An error has occurred while processing the shared archive file.
A jar/jimage file is not the one used while building the shared archive file: zipkin.jar
Error occurred during initialization of VM
Unable to use shared archive.
```

**Comment by nebhale** [comment]
Same difficulties you'd expect from #636.
