### ISSUE TITLE
setting VCAP tags new-relic-agent=4.6.0 on release branch tags/v3.9

### ISSUE THREAD

**Issue by kmacpher67** [cloudfoundry/java-buildpack#640]
The default version in release `v3.9` for New Relic is: 
File: `config/new_relic_agent.yml` - `version: 3.31.1`

Trying to overwrite this with to newer NR version: `4.6.0`
Shows as supported: `https://download.run.pivotal.io/new-relic/index.yml`

```
cf update-user-provided-service newrelic -t 'new-relic-agent=4.6.0' -p '{"licenseKey":"xxxx"}'
```

am I doing the syntax wrong? 
Does this VCAP setting for the new-relic-agent actually work? 
I tried reading the ruby code to figure out what its doing how they get from ${version} from the .yml file to overriding the newrelic component ${version} with the new-relic-agent from VCAP, but the code is highly condensed abstracted, I wonder if there's some magical ruby convention bending going on. 

Am I trying too new of version for the Build Pack release level that we are using?

**Comment by nebhale** [comment]
The version of a dependency user by the buildpack has never been configured as part of a service credential payload.  Please see the [Configuration and Extension documentation](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension) for the proper way to configure the version of New Relic you'd like to use.

Please also note that using v3.9, released over two years ago, and on a branch that is EOL is totally unsupported.  Further using vastly newer versions of New Relic with a buildpack that old is likely not to work, and will not be supported.  You should be on the latest version of the Java Buildpack.

**Comment by kmacpher67** [comment]
Duly noted on EOL version, working on moving forward to a newer latest version of the buildpack.
3.9 is EOL. 
The current master for the New Relic Agent Framework suggests overriding the version by updating the VCAP_SERVICES payload. 
Is that true or valid interpretation of this readme? 
What does the syntax of overriding the default .yml version look like. 
Is this the syntax to override `newrelic` component ${version} only capable on an application by application? 
`cf set-env my-application JBP_CONFIG_NEW_RELIC '{ new-relic-agent: { version: 4.6.0 } }'
What does the 
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-new_relic_agent.md#new-relic-agent-framework
mean by: 
`Tags | new-relic-agent=<version>`
This is the current documentation from master, can the service VCAP over-ride default .yml version value?

**Comment by nebhale** [comment]
> The current master for the New Relic Agent Framework suggests overriding the version by updating the `VCAP_SERVICES` payload.   Is that true or valid interpretation of this readme? 

This is incorrect.  The [Service Payload](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-new_relic_agent.md#user-provided-service-optional) and [Component Configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-new_relic_agent.md#configuration) are two different things.

> What does the syntax of overriding the `default .yml` version look like.  Is this the syntax to override `newrelic` component ${version} only capable on an application by application? 

Configuration is scoped by how you do it.  A given developer can configure using application-specific environment variables.  A given operator can configure using a Staging Environment Variable Group.  A given operator can configuring using a fork of the buildpack.

> What does the 
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-new_relic_agent.md#new-relic-agent-framework
mean by: 
`Tags | new-relic-agent=<version>`

As the documentation clearly states:
> Tags are printed to standard output by the buildpack detect script
