### ISSUE TITLE
update new relic configuration file with the latest newrelic.yml

### ISSUE THREAD

**Issue by shahramk** [cloudfoundry/java-buildpack#645]
Hello @nebhale, 

The new relic config file (newrelic.yml) is about 2 years old, and ever since, there has been some properties added to it. One of the most recent ones is Distributed Tracing stanza. Would it be possible to refresh newrelic.yml with the [latest agent's config file](http://download.newrelic.com/newrelic/java-agent/newrelic-agent/4.7.0/newrelic.yml)?

thank you

**Comment by RamakrishnanArun** [comment]
Would this allow me to do this? I tried this setting but it was not working. I see the manifest doesn't have a version property.
```
    JBP_CONFIG_NEWRELICAGENT: "version: 4.6.0"
    JAVA_OPTS: '-Dnewrelic.config.distributed_tracing.enabled=true'
```

**Comment by nebhale** [comment]
@RamakrishnanArun As the [New Relic Framework Documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-new_relic_agent.md#user-provided-service-optional) states, you can add arbitrary keys to the credential payload and those keys will be set as system properties with `newrelic.config.` prepended to them.  Therefore, in your example a System property of `-Dnewrelic.config.distributed_tracing=true` will be set.
