### ISSUE TITLE
java buildpack needs to provide a "name" and "version" field for its own config.yml

### ISSUE THREAD

**Issue by punalpatel** [cloudfoundry/java-buildpack#649]
the JBP `config.yml` interface is described [here](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-multi_buildpack.md).

the buildpack needs to provide a `name` and `version` field for its own `config.yml`
so that it matches what the other buildpacks do [here](https://github.com/cloudfoundry/libbuildpack/blob/0f28470a5391e0d3a1a3433e6bff692f849d6bee/stager.go#L75).

Currently java buildpack returns:-

```
"buildpacks": [
    {
      "buildpack_name": "",
      "detect_output": "",
      "name": "java_buildpack_preview",
      "version": null
    }
```

non-java buildpack returns:-

```
"buildpacks": [
    {
      "buildpack_name": "nginx",
      "detect_output": "nginx",
      "name": "nginx_buildpack_preview",
      "version": "1.0.2"
    }
  ],
```

**Comment by nebhale** [comment]
I'm pretty sure that we don't write a `config.yml` at all.  Do you believe that we do?

**Comment by nebhale** [comment]
This is unlikely to get to get done before our move to Cloud Native Buildpacks.
