### ISSUE TITLE
AppDynamics agent config overlay not working as expected

### ISSUE THREAD

**Issue by jonathanamartin** [cloudfoundry/java-buildpack#652]
To overlay an `app-agent-config.xml` file the documentation states:

> The framework can also be configured by overlaying a set of resources on the default distribution. To do this, add files to the `resources/app_dynamics_agent` directory in the buildpack fork. For example, to override the default `app-agent-config.xml` add your custom file to `resources/app_dynamics_agent/conf/app-agent-config.xml`.

However, we found that we had to add the overlay `app-agent-config.xml` file to a versioned folder.  For example: `resources/app_dynamics_agent/[version]/conf/app-agent-config.xml` folder.

**Comment by nebhale** [comment]
Yep, looking into the agent zip, this seems likely.  We can update the documentation but unfortunately, there's no good way to get around the fact that the directory name is going to change with every single release.  You might talk to AppDynamics about making this more general, but beyond docs, there's nothing we're going to be able to do.

**Comment by jonathanamartin** [comment]
Thanks @nebhale.  Looks like the updated doc is missing `/` after `<version>`.
