### ISSUE TITLE
Question : How to investigate OOM?

### ISSUE THREAD

**Issue by NineWoranop** [cloudfoundry/java-buildpack#654]
Hello,

I'm quite new with cloudfoundry.
I could not find a link that help me to describe on how to configure and investigate logs when JVM crash from OOM.
Could you please give me some guide?
I found this link but I could not understand on how to configure this and where is the location of heap dump.
https://github.com/cloudfoundry/java-buildpack/issues/451

Regards,
Tom

**Comment by nebhale** [comment]
Containers in Cloud Foundry are ephemeral and disappear as soon as the processes within them die.  Therefore, there is no easy way to extract a heap dump from a process as it is crashing.  The buildpack adds a [`jvmkill` agent](
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#jvmkil)l that prints a histogram of the heap to the logs as the process dies.  While this isn’t a heapdump, we find that it’s enough for most people to get a pointer at where the problem might lie.  Once that information is available, standard [JMX](
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-jmx.md) and [YourKit](
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-your_kit_profiler.md) or [JProfiler](
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-jprofiler_profiler.md) techniques are used to do pinpointed diagnostic work.
