### ISSUE TITLE
Unrecognized VM option 'ActiveProcessorCount=8'

### ISSUE THREAD

**Issue by mshalo** [cloudfoundry/java-buildpack#658]
Getting this error when the application tries to start. We are using java 8.

**Comment by shakuzen** [comment]
I believe this would happen if you're using the `master` branch of the buildpack now after #650 with a version of Java 8 before update 191. Is that the case? I don't have such a version of Java locally installed to easily test. Is this causing your application to fail to startup? As a workaround, you can use the previously released version of the buildpack (4.16.1) that doesn't have #650 or you can use the latest update version of Java 8 which recognizes the VM option.

**Comment by mshalo** [comment]
Thank you using the previous version of the build pack works.
