### ISSUE TITLE
JRE 11 official support required

### ISSUE THREAD

**Issue by ericis** [cloudfoundry/java-buildpack#669]
JRE 11 was released in September 2018. JRE 12 is in Early Access for this summer. I would expect the buildpack to be slightly ahead of these releases in order to coincide with an official release now that Java has a 6 month cadence.

**Comment by nebhale** [comment]
The policy of the Java Buildpack is to have currently supported LTS versions and the latest non-released LTS.  Since Java 11 was released, the buildpack has shipped with the latest releases of Java 8 and 11.  Once an official release of Java 12 is available, we’ll ship that as well.

**Comment by shakuzen** [comment]
Specifically, [version 4.16](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.16) of the buildpack added support for JRE 11.

**Comment by ericis** [comment]
Thanks @nebhale and @shakuzen 

I've submitted a doc fix. Let me know if there's anything else I can do

**Comment by ericis** [comment]
Ah! I need to sign the Individual CLA. Will fill out and submit...

**Comment by ericis** [comment]
Submitted the CLA. I will close and re-open the PR #670 once it processes.

Also, *Official Release for Java 11* can be found here: https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.16 (for others)
