### ISSUE TITLE
Runtime not available during deployment

### ISSUE THREAD

**Issue by Anubhav007** [cloudfoundry/java-buildpack#675]
Hi,
I am getting this error while deploying my application to cloud foundry:-
"**SEVERE: Unhandled exception in Buildpack main method: None of the available runtimes: [Tomee, Tomee7, Tomcat, Java Main] support the application in the specified path. Failed to compile droplet: Failed to compile droplet: exit status 9**"
Other applications which are using the same buildpack are running fine.
Could you tell what could possibly be wrong.

**Comment by nebhale** [comment]
This does not appear to be the Java Buildpack as the Java Buildpack does not contain TomEE.
