### ISSUE TITLE
need a concrete example for setting up JaCoCo Service to work with java-buildpack

### ISSUE THREAD

**Issue by zyjibmcn** [cloudfoundry/java-buildpack#677]
We are trying to use jacoco to collect API test coverage information in cloud foundry environment. 

And we found this open source framework, but there isn't any concrete example or sample to guide  me setup a JaCoCo Service in cloud, and not very clearly on how to use  java-buildpack.

It would be better to provide some success example.

**Comment by nebhale** [comment]
Shouldn’t this be located in the JaCoCo documentation?  The integration in the Java Buildpack exists to hook into features provided by integrating project, we don’t provide the functionality on the server-side nor do we document how each of our integrations work; the overhead is simply too great.  A quick Google returns [this example](
https://github.com/jacoco/jacoco/blob/master/org.jacoco.examples/src/org/jacoco/examples/ExecutionDataServer.java) for how to run a server that the client sends data to.

**Comment by konstantinblaesi** [comment]
https://github.com/cloudfoundry/java-buildpack/pull/715#issuecomment-492109959
