### ISSUE TITLE
Provide possibility to sent http headers in download request

### ISSUE THREAD

**Issue by DTMad** [cloudfoundry/java-buildpack#685]
We would like to provide http headers when using the download function (e.g. change User-Agent, provide additional headers, ...) to get more detailed information.

Please provide an option to make this possible.

**Comment by mreider** [comment]
@nebhale - sorry to harass you :) - we're wondering if you can look at this PR which was prompted by our sec/ops team.

**Comment by nebhale** [comment]
As we're closing in on the migration to [Cloud Native Buildpacks](https://buildpacks.io), we're not going to make any change this invasive to the main buildpack.  The code that all downloads route through is located [here](https://github.com/cloudfoundry/java-buildpack/blob/e06e00b8fba534e7c7c89dd089df8c3095aa76c9/lib/java_buildpack/util/cache/download_cache.rb#L289), but beware that any modification to this area of code **is unsupported** and bugs against buildpacks with modifications against non-public API (that's what this is) will not be investigated.
