### ISSUE TITLE
Include latest New Relic agent versions in future buildpack releases

### ISSUE THREAD

**Issue by TG-KK** [cloudfoundry/java-buildpack#693]
Latest newrelic  agent version is `4.11.0`, but most recent buildpack(4.17.2) contains `4.9.0` which is 2 months old.

Please include latest agent versions in future buildpacks.

**Comment by nebhale** [comment]
The buildpack chooses the latest available version of each dependency when it is packaged for release.  Online buildpack always select the latest available version.

**Comment by kmacpher67** [comment]
FYI 

`export app="yourAPPName"
cf set-env $app JBP_CONFIG_NEW_RELIC_AGENT "{ version: 5.14.0 }"
cf restage $app`
