### ISSUE TITLE
Additional Integration Point - Multi-Buildpack Support

### ISSUE THREAD

**Issue by mainephd** [cloudfoundry/java-buildpack#695]
In the buildpack documentation there are two supported integration points `/bin` and `/lib`. Are there any thoughts on whether there will be support for `/profile.d` as an integration point?

https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-multi_buildpack.md

I am asking because the [binary-buildpack](https://github.com/cloudfoundry/binary-buildpack) will allow buildpacks like [metrics-buildpack](https://github.com/mainephd/metrics-buildpack) to contribute to the final `/profile.d` directory. The goal of all of this is to allow `telegraf` to [startup](https://github.com/mainephd/metrics-buildpack/blob/master/src/metrics/data/data.go#L5) in the background to export metrics out of the java application

**Comment by nebhale** [comment]
There are problems with `profile.d` generally in Java applications which is what has held it out for this long.  While addition to a multi-buildpack integration might be appropriate finally, we're not going to add any additional multi-buildpack functionality to the Java Buildpack any more.  Instead, all effort is focused on converting the Cloud Foundry ecosystem to the new [Cloud Native Buildpacks specification](https://buildpacks.io).  That specific supports `profile.d` natively (buildpack coordination not required).

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
