### ISSUE TITLE
Unable to find files of an app

### ISSUE THREAD

**Issue by shamhub** [cloudfoundry/java-buildpack#698]
To run a task on an app, I create a zero instance app as shown below:

`cf push some-db-task-app -i 0 -b java_buildpack_offline`

Did not mention route name, as it is not required

Below is the error:

```Getting app info...
No app files found in '/app/jenkins/workspace/abc'
```

Main idea to create this  zero instance app is to run `mvn` command on this app that has java_buildpack supporting maven commands

**Comment by nebhale** [comment]
The Java Buildpack does not build applications from source (despite it's name).  It expects you to push a deployment artifact and the [list of containers](https://github.com/cloudfoundry/java-buildpack#additional-documentation) describes the many artifact types that are supported.
