### ISSUE TITLE
Please update java-buildpack-auto-reconfiguration version

### ISSUE THREAD

**Issue by MaTr74** [cloudfoundry/java-buildpack#700]
Hello,

java-buildpack-auto-reconfiguration was updated to v2.6.0.RELEASE . Please provide this new version in java-buildpack. 

Many thanks!

Martin Tröger

**Comment by nebhale** [comment]
Unfortunately we won’t be able to do that. There is a regression in the Spring Cloud Connectors that [breaks auto-reconfiguration](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/java-buildpack).

**Comment by MaTr74** [comment]
Thanks for your trial! Is there anything I can do?

**Comment by nebhale** [comment]
Still working on it.  CI is green, apparently another Spring Cloud Connectors release is imminent.  Trying to determine whether we should wait.
