### ISSUE TITLE
Stack Awareness?

### ISSUE THREAD

**Issue by jregehr** [cloudfoundry/java-buildpack#704]
Most CF Buildpacks are stack aware. Are there plans to make the Java buildpack stack-aware as well?

**Comment by jimconner** [comment]
Java buildpack in only available as an online BP, so the assets are fetched dynamically after loading. The assets which are fetched are available in both cflinuxfs2 and cflinuxfs3 flavours from the repo servers and it will intelligently choose the correct ones as required. As such, there's no need for java buildpack to be pinned to a single stack.

**Comment by aegershman** [comment]
Interesting. We're using PCF and taking the buildpacks provided by PAS tile upgrades. Not 100% sure what "stack-awareness" is, and not sure if Pivotal is doing something behind the scenes to create the `java_buildpack_offline`, but just for information here's the layout for us:

```
$cf buildpacks | grep java

buildpack                position   enabled   locked   filename                                             stack
java_buildpack_offline   2          true      false    java-buildpack-offline-cflinuxfs2-v4.16.1.zip        cflinuxfs2
java_buildpack_offline   13         true      false    java-buildpack-offline-cflinuxfs3-v4.16.1.zip        cflinuxfs3
```

Apologies I'm almost definitely misunderstanding something

**Comment by jregehr** [comment]
@aegershman you're right on the money.

@jimconner I think you may not have the full story. The java buildpack can be built in either online or offline modes. Reference: [docs in this repo](https://github.com/cloudfoundry/java-buildpack#offline-package)

With Pivotal Cloud Foundry / PivNet I have the option to download either the online _or offline_ version of the buildpack. [See link](https://network.pivotal.io/products/java-buildpack/). Aaron and I both use the offline version of the buildpack. That way all the dependencies come prepackaged. It's a larger download on the front side but it makes `cf push` faster since all the dependencies are pre-packaged in the buildpack.

**Comment by DonBower** [comment]
@jregehr Which stack are you using with your offline buildpacks?
we pre-download the offline buildpacks for our developers, and put them in artifactory.
But I don't se any stack info.  if we use the pivnet offline version of the buildpack, will it have cflinuxfs3?

**Comment by nebhale** [comment]
The Java Buildpack (when built in offline mode) [includes dependencies](https://github.com/cloudfoundry/java-buildpack/blob/master/rakelib/package.rb#L36) for all currently supported stacks.  So the online buildpack can download for both `cflinuxfs2` and `cflinuxfs3` and the offline buildpack (packaged and shipped by Pivotal and other vendors) includes everything necessary for both `cflinuxfs2` and `cflinuxfs3`.

There is no need to have multiple versions of the buildpack (online or offline) because a single buildpack can satisfy _all_ supported versions.
