### ISSUE TITLE
Spring boot App needs to have access to tools.jar for loadtimeweaving

### ISSUE THREAD

**Issue by mrtinkz** [cloudfoundry/java-buildpack#708]
My spring boot app needs access to tools.jar for loadtimeweaving, until Java Buildpack v4.16.1 I had no issues running my application but any other later versions seems to have not provided tools.jar in the bin folder anymore. This seems to be a problem upgrading to the latest buildpacks.

`2019-04-02T11:12:47.804-04:00 [APP/PROC/WEB/0] [ERR] Caused by: java.lang.AssertionError: [No tools.jar found in [/home/vcap/app/.java-buildpack/open_jdk_jre/bin, /home/vcap/app/.java-buildpack/open_jdk_jre/lib]. Please make sure a JDK is installed and JAVA_HOME points there.] `

**Comment by nebhale** [comment]
The buildpack has always only included a JRE, not a JDK.  JREs have never included `tools.jar`, so I'm not sure how your LTW has ever worked.  Either way, we have no plans to introduce `tools.jar` to the JRE, therefore creating a hybrid between the two.

**Comment by chestnutt** [comment]
According to Oracle, you can include certain parts of the JDK with the JRE - and still be in compliance with licensing. https://www.oracle.com/technetwork/java/javase/readme-142177.html#redistribution 
To summarize: it's never just tools.jar - it's always that plus other files for these capabilities:
- javac compiler
- Annotation Processing tools
- Dynamic Attach
- Java Debugger

I wonder if you might be wanting the Annotation tools.

**Comment by mrtinkz** [comment]
Interesting... LTW is working with the v4.16.1 buildpack and not the newer ones. I wonder what has changed.
