### ISSUE TITLE
Offline Buildpack missing Webflux compatible AppD Agents version 4.5.8.25346

### ISSUE THREAD

**Issue by GregChartier** [cloudfoundry/java-buildpack#709]
We cannot access Webflux compatible AppD Agents version 4.5.8.25346 from CloudFoundry java buildpack even using specific manifest config as we are pointing to the offline buildpacks and it has latest version available as 4.5.7_25056. Could you please update the offline buildpacks to have AppD Agents version 4.5.8.25346?
The updates doesn’t look like it has any breaking changes in it https://docs.appdynamics.com/pages/viewpage.action?pageId=45505655#MachineAgentNotes-4.5.8(Agent)Updates
We have no alternative but to use the offline buildpacks and need the enchanced webflux support it brings.
Thanks, Greg

**Comment by nebhale** [comment]
The latest version of each dependency will be shipped with each release of the buildpack.  The version you desire is available and will be shipped when the next release goes out.  In general we don't do releases for each of the dependencies (there are ~30 integrations so we'd be releasing nearly every day) but we do release regularly so you shouldn't have to wait long.
