### ISSUE TITLE
Question: OpenJDK origin repo?

### ISSUE THREAD

**Issue by bobbyhubbard** [cloudfoundry/java-buildpack#710]
Random question, where does the current OpenJDK 8 binaries originate from? Documentation for trusty shows `http://download.pivotal.io.s3.amazonaws.com/openjdk/trusty/x86_64/index.yml` but I'm wondering where these come from. If I look at ubuntu's repo, the latest available there is 8u191. 

Thanks.

**Comment by nebhale** [comment]
* Available artifacts can be found at https://github.com/cloudfoundry/java-buildpack-dependency-builder#available-artifacts
* We build from source, and the execution of those builds can be found at https://java-experience.ci.springapps.io/teams/java-experience/pipelines/dependency-builder?groups=openjdk
* The scripts that do the builds can be found at (you'll notice peers for each version) https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/openjdk8.sh
* And the source they come from is at (again, check out the peers) http://hg.openjdk.java.net/jdk-updates/jdk11u/tags

**Comment by bobbyhubbard** [comment]
Thanks Ben!
