### ISSUE TITLE
Different "buildpack_name" when specifying java_buildpack explicitely in cf push manifest

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry/java-buildpack#719]
Hi,

`cf curl /v3/apps/:app_id/droplets/current` shows different buildpack_name`s depending on wether the cf push specified a fixed buildpack with the buildpack config parameter in manifest.yml or auto detected the java buildpack.

cf push with `buildpack: java_buildpack` in `manifest.yml`:
```
...
"buildpacks": [
      {
         "name": "java_buildpack",
         "detect_output": "",
         "buildpack_name": "",
         "version": null
      }
   ],
...
```

cf push with auto detect of the java buildpack:
```
... 
"buildpacks": [
      {
         "name": "java_buildpack",
         "detect_output": "client-certificate-mapper=1.8.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=\u001B[34mv4.17.2\u001B[0m-https://github.com/cloudfoundry/java-buildpack.git#47e68da java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk-like-jre=1.8.0_2...",
         "buildpack_name": "client-certificate-mapper=1.8.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=\u001B[34mv4.17.2\u001B[0m-https://github.com/cloudfoundry/java-buildpack.git#47e68da java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk-like-jre=1.8.0_2...",
         "version": null
      }
   ],
...
```

In both cases the same buildpack was applied.

Furthermore the buildpacks show no version  but this seems to be related to #649. 

__java buildpack version__: v4.17.2
__stack__: cf_linuxfs3

**Comment by nebhale** [comment]
This is a behavior of the Cloud Controller.  Buildpacks can output any string they desire during the detect phase of the buildpack lifecycle.  The Java Buildpack has, for at least five years, output a string describing the dependencies added to the droplet.  When detection is used, that data is automatically consumed as the "name" of the buildpack.  When detection is not used, the declared buildpack name is used instead.

If you'd like to see a different behavior here, you'll need to contact the CAPI team for a change.
