### ISSUE TITLE
Allow Configuration of Arguments Passed to a DistZip Startup Script

### ISSUE THREAD

**Issue by sethcleveland** [cloudfoundry/java-buildpack#721]
I noticed the Java Main supports passing arguments through this environment variable.

```
JBP_CONFIG_JAVA_MAIN: '[arguments: " -console -p $PORT " ]'
```

How do we achieve the same thing with distZip?

**Comment by nebhale** [comment]
It is not currently possible to add arguments to the startup script in a distZip-style application.  I'll repurpose this issue to request that feature.
