### ISSUE TITLE
Recent builds of openjdk don't contain some utilities that previous builds did

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#722]
Namely `jcmd`, `jmap`, `jstack`.  These tools are useful.  Hopefully we can get them back.

Example JDK that contains the binaries:
https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-1.8.0_201.tar.gz

Example JDK that doesn't contain the binaries:
https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-1.8.0_212-bionic.tar.gz

**Comment by camattin** [comment]
Your second link is to the JRE, not the JDK, which is why it does not have the tools inside of it (along with all the other JDK "bloat").  Not sure why, but the index.yml was pointing to the JDK for version 1.8.0_201, but then for 1.8.0_202 and above it's pointing to the JRE-only tarball.

The non-JRE-only tarball is still available (https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-1.8.0_202.tar.gz), but if you're using the online buildpack, I'm not sure that you can override it to fetch this one instead of the JRE-only one.

**Comment by youngm** [comment]
Thanks @camattin we are using the online buildpack and there isn't a very simple way to override it to point to a custom index.yml referencing the JDK instead.  the online buildpack used to exclusively provide jdks and it appears it switched to jres since there is no jdk for 212: https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-1.8.0_212.tar.gz

I'd still assert the openjdk builds switching from jdks to jres is a regression.

**Comment by camattin** [comment]
@youngm I'd agree that there should be a way for the user to select. Where I am we build our own custom offline buildpacks and it lets me forget some of the hardcoded gotchas with the online versions.

**Comment by youngm** [comment]
Had a conversation with @nebhale on slack: https://cloudfoundry.slack.com/archives/C03F5ELTK/p1561137578011600

Apparently jmap and jstack were removed from the jre build for legal reasons.  If you need those tools you can use a JDK instead available at `repository_root: "{default.repository.root}/openjdk-jdk/{platform}/{architecture}"`.  Although you should note that it may be considered bad security practice to run your application with a jdk instead of a jre.

I consider this issue closed.

**Comment by TimGerlach** [comment]
If anyone else is wondering how to explicitly set a JDK via plain environment variables without forking the whole buildpack, this example using `JBP_CONFIG_OPEN_JDK_JRE` worked well for me:

```yaml
---
applications:
- name: spring-music
  memory: 1G
  random-route: true
  path: build/libs/spring-music-1.0.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
  env:
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { repository_root: "https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64", version: 11.+ } }'
```

Note that this requires to use an online buildpack (configured in the `buildpack` property) as staging obviously fails with cache issues when system buildpacks are used which don't have the JDK cached.

Also note that this shall not be considered a recommendation to use a full JDK per se. It's just an option to get tools like `jcmd` and `jmap` back for troubleshooting when you need them, e.g., when using the [cf java plugin](https://github.com/SAP/cf-cli-java-plugin).
