### ISSUE TITLE
Tomcat8 override config not working on v4.19 release

### ISSUE THREAD

**Issue by mohanbabubb** [cloudfoundry/java-buildpack#723]
i have been trying to use the latest buildpack( 4.19 ) with the env variable to use the tomcat 8, but it fails with below error.
Also, the document instruction [here ](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension ), points to use the environment variable to  override default tomcat which doesn't work.

Below, is the error I'm seeing while pushing an app with latest buildpack (4.19)
```
> [STG/0] [ERR] Unable to find cached file for https://java-buildpack.cloudfoundry.org/tomcat/tomcat-8.5.39.tar.gz
[STG/0] [ERR] [Buildpack] ERROR Finalize failed with exception #<RuntimeError: Unable to find cached file for https://java-buildpack.cloudfoundry.org/tomcat/tomcat-8.5.39.tar.gz>
[STG/0] [ERR] Failed to compile droplet: Failed to run finalize script: exit status 1
```

This environment variable doesn't work for latest release 4.19
```
env:
  JBP_CONFIG_TOMCAT: '{ tomcat: { version: 8.0.+ } }'
```

**Comment by nebhale** [comment]
Offline buildpacks only contain a **single** version of each dependency.  Version 4.19 _only_ [contains Tomcat 9.0.17](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.19) so changing the configuration is possible, but won't have a dependency to satisfy it.  If you would like to use a different version of a given dependency, you'll need to use either an online buildpack or [build your own offline buildpack](https://github.com/cloudfoundry/java-buildpack#offline-package) with a different version of the dependency.
