### ISSUE TITLE
JVM insufficient memory issue

### ISSUE THREAD

**Issue by yasminpierazo** [cloudfoundry/java-buildpack#732]
I'm getting this when I try to push my project to IBM Cloud:

> Cannot calculate JVM memory configuration: There is insufficient memory remaining for heap. Memory available for allocation 256M is less than allocated memory 578931K(-XX:ReservedCodeCacheSize=240M,-XX:MaxDirectMemorySize=10M, XX:MaxMetaspaceSize=66931K, Xss1M * 250 threads)

I **cannot increase the memory limit**. I tried using JVM flags to reduce the JVM’s memory usage in manifest.yml file:

 ```
env:
     JAVA_OPTS: '-XX:MaxMetaspaceSize=80780K -Xss160k -Xmx200M -XX:ReservedCodeCacheSize=16M -XX:MaxDirectMemorySize=16M'

```

and tried to use an older version of java buildpack, also in manifest.yml file: 

 `buildpack: https://github.com/cloudfoundry/java-buildpack#v3.19.2
`
but  I got errors doing both things. What can I do to solve this?

**Comment by nebhale** [comment]
As long as you are using a version of the buildpack in the 4.x line, setting the `JAVA_OPTS` as you have done is all you need to do to modify your configuration.  Each time you restart it will tell you what your configuration is (and show you what has been calculated versus what you specified).

Just looking over your configuration there though, you're still above your goal of 256M:

```
Metaspace:  79M
Threads:    41M
Heap:      200M
JIT:        16M
Direct:     16M
---------------
Total:     352M
```
