### ISSUE TITLE
Unable to find cached file served by service broker

### ISSUE THREAD

**Issue by fwanggg** [cloudfoundry/java-buildpack#733]
I wonder this has to do with our changes to download artifact from the service broker.
`2019-06-24T14:50:13.78-0400 [STG/0] ERR [Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Unable to find cached file for http://appinternals-servicebroker.apps.FOOBAR.pcf.FOOBAR.com/rvbd/profiler.linux.zip>
   2019-06-24T14:50:13.78-0400 [STG/0] ERR Unable to find cached file for http://appinternals-servicebroker.apps.FOOBAR.pcf.FOOBAR.com/rvbd/**profiler.linux.zip**
   2019-06-24T14:50:13.78-0400 [STG/0] ERR [meta-buildpack] Passing on exit code  1
   2019-06-24T14:50:13.79-0400 [STG/0] ERR Failed to compile droplet: Failed to compile droplet: exit status 1`

I get that offline build pack pinned down a specific version of the software. My understanding is offline bp is unable to download profiler.linux.zip(our artifact) from service broker when it's built by cloud foundry, instead, it will download the latest version from our file server. So when offline bp is used, it will not have the artifact from service broker URL cached thus the failure.

Is there a way to fix this problem? Anyway we can just always download the profiler.zip file from service broker regardless if it's online or offline buildpack?

**Comment by nebhale** [comment]
This has been solved by #734
