### ISSUE TITLE
CF Tasks failing to start with micrometer.

### ISSUE THREAD

**Issue by gm2552** [cloudfoundry/java-buildpack#747]
With the release of build pack 4.21, tasks are failing to start due the fact that tasks to not have the  'cf.instance.index' env variable.  At a high level glace, it appears the CloudFoundryTagsMeterFilterAutoConfiguration class is requiring that this env variable exist when creating an internal bean.  See the following stack information:

```
Initialization of bean failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating bean with name
'meterFilter' defined in class path resource
[org/cloudfoundry/metrics/CloudFoundryTagsMeterFilterAutoConfiguration.class]: Bean
instantiation via factory method failed; nested exception is
org.springframework.beans.BeanInstantiationException: Failed to instantiate
[io.micrometer.core.instrument.config.MeterFilter]: Factory method 'meterFilter' threw
exception; nested exception is java.lang.IllegalStateException: Required key
'cf.instance.index' not found  at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreat
Bean(AbstractAutowireCapableBeanFactory.java:581) ~[spring-beans-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]  at
.
.
.
```

**Comment by xyloman** [comment]
Additional color commentary, if you roll back to buildpack v4.20 then the tasks succeed in starting up.  For those that are following v4.21 comes standard in PAS 2.6.5 which shipped yesterday on Pivotal Network.

**Comment by gm2552** [comment]
+1... Have just verified that pinning to 4.20 still works.

**Comment by xyloman** [comment]
@gm2552 the following workaround would work to avoid having to fallback to v4.20 of the buildpack:

> There is a [configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-metric_writer.md#configuration) to disable the feature by doing something like `cf set-env <APP> JBP_CONFIG_METRIC_WRITER '{ enabled: false }'`. If you'd like this applied to your entire enterprise, you can set a [staging environment variable group](https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html) to the same.

see [here](https://github.com/cloudfoundry/java-buildpack/issues/743#issuecomment-527980058)  for more context.

**Comment by xyloman** [comment]
This does bug the question is there task specific environment arguments that should be tagged on metrics generated from a running task?

**Comment by nebhale** [comment]
Yep, at issue is that a bunch of expected properties are not available in tasks, which is a bug in CAPI certainly, but in the mean time can be worked around.  Solved by https://github.com/cloudfoundry/java-buildpack-metric-writer/commit/58174be8624bf261ec6c8b95bb01ee04adbafb24 in [Metric Write v3.2.0](https://github.com/cloudfoundry/java-buildpack-metric-writer/releases/tag/v3.2.0.RELEASE).
