### ISSUE TITLE
Offline Buildpack 4.21 - Specifying agent version

### ISSUE THREAD

**Issue by jamiechristian11** [cloudfoundry/java-buildpack#750]
I've been trying to get the offline version of the 4.21 buildpack to pick up the 10.5.1 introscope agent by adding a tag to the introscope service as outlined [here](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-introscope_agent.md). I tried specifying both 10.5.1 and 10.5.1_6 ([available agents](https://ca.bintray.com/apm-agents/)), but it is still picking up the 11.1.1 agent. Does this feature work with an offline buildpack?

Here is my introscope user provided service info: 
```
$cf update-user-provided-service introscope -t "introscope-agent=10.5.1_6"
Updating user provided service introscope in org org1 / space space1 as user1...
OK
 
TIP: Use 'cf restage' for any bound apps to ensure your env variable changes take effect

$cf service introscope
Showing info of service introscope in org org1 / space space1 as user1...
 
name:      introscope
service:   user-provided
tags:      introscope-agent=10.5.1_6
 
bound apps:
name                            binding name   status             message
abc-test                                       create succeeded
```

I then tried to restage `abc-test` using java_buildpack_offline (version 4.21), but my app is still grabbing the wrong agent:
```
$cf restage abc-test
This action will cause app downtime.
 
Restaging app abc-test in org org1 / space space1 as user1...
 
Staging app and tracing logs...
   Downloading java_buildpack_offline...
   Downloaded java_buildpack_offline
   Cell <guid> creating container for instance <guid>
   Cell <guid> successfully created container for instance <guid>
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded build artifacts cache (129B)
   Downloaded app package (13.3M)
   -----> Java Buildpack v4.21 (offline) | https://github.com/cloudfoundry/java-buildpack.git#0bc7378
   -----> Downloading Jvmkill Agent 1.16.0_RELEASE from https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0-RELEASE.so (found in cache)
   -----> Downloading Open Jdk JRE 1.8.0_222 from https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-1.8.0_222-bionic.tar.gz (found in cache)
          Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.1s)
          JVM DNS caching disabled in lieu of BOSH DNS caching
   -----> Downloading Open JDK Like Memory Calculator 3.13.0_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-3.13.0-RELEASE.tar.gz (found in cache)
          Loaded Classes: 11361, Threads: 250
   -----> Downloading Client Certificate Mapper 1.11.0_RELEASE from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.11.0-RELEASE.jar (found in cache)
   -----> Downloading Container Security Provider 1.16.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-security-provider/container-security-provider-1.16.0-RELEASE.jar (found in cache)
   -----> Downloading Introscope Agent 11.1.1_0 from https://ca.bintray.com/apm-agents/agent-default-11.1.1_0.tar (found in cache)
          Expanding Introscope Agent to .java-buildpack/introscope_agent (0.6s)
   -----> Downloading Spring Auto Reconfiguration 2.8.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-2.8.0-RELEASE.jar (found in cache)
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading droplet...
   Uploading build artifacts cache...
   Uploaded build artifacts cache (129B)
   Uploaded droplet (104.3M)
   Uploading complete
   Cell <guid> stopping instance <guid>
   Cell <guid> destroying container for instance e
   Cell <guid> successfully destroyed container fo
 
Waiting for app to start...
 
name:              abc-test
requested state:   started
routes:            abc-test.<apps domain>
last uploaded:     Fri 04 Oct 09:06:55 CDT 2019
stack:             cflinuxfs3
buildpacks:        java_buildpack_offline
```

**Comment by DevasiaThomas** [comment]
@jamiechristian11 Looks like the tag doesn't seem to be working, but it seems that you can override the version by providing an env variable in your app manifest or setting the same variable through other means and then restaging your app.
`JBP_CONFIG_INTROSCOPE_AGENT: '{ version: 10.5.1_6 }'`

**Comment by DevasiaThomas** [comment]
@nebhale Mentioned [here](https://github.com/cloudfoundry/java-buildpack/pull/470#issuecomment-320304574) as well, the above is working. But looking at what @jamiechristian11 is talking about, every vendor doc seems to have that tag - but I don't see any code that handles this in vendor specific code files. Is it generic buildpack code? I also noticed that this has been in the docs since the beginning.

**Comment by DevasiaThomas** [comment]
@nebhale Mentioned [here](https://github.com/cloudfoundry/java-buildpack/pull/470#issuecomment-320304574) as well, the above is working. But referring to what @jamiechristian11 tried, I couldn't find code in vendor code files (I checked 6 of them) that handles this specifically. Is this something generic to the java buildpack? If what he tried is not working for Introscope, it shouldn't work for many (or atleast for all of the ones I checked). Also I noticed that this tag has been there in every doc file for all vendors since creation - Is it something that was removed but stayed in the docs?

**Comment by nebhale** [comment]
There are multiple tags in various places without the system.  The tags on a service are only used for detection of the service and cannot be used to describe the version of the dependency being used.

> Existence of a Introscope service is defined as the VCAP_SERVICES payload containing a service who's name, label or tag has introscope as a substring.

The tag listed below is the tag provided by detection to the Cloud Foundry platform where it describes what version of. the dependency has been chosen and contributed to the droplet.  That's an output field, not an input field.

Use of the standard configuration as demonstrated [here](https://github.com/cloudfoundry/java-buildpack/issues/750#issuecomment-542430106) is the correct way to go about choosing the version of a dependency.
