### ISSUE TITLE
Adding c++ native library to java buildpack

### ISSUE THREAD

**Issue by deepuec** [cloudfoundry/java-buildpack#754]
Hello,

We need or-tools c++ system library to run one of our spring boot application. Could anyone help me understand how can we add system libraries to build pack and run app in PCF.

Thank You,
Deepak

**Comment by nebhale** [comment]
In general, applications need to carry any dependencies they need along with them.  Alternately, writing another buildpack and using the multi-buildpack functionality might be appropriate.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
