### ISSUE TITLE
Can we have one more JRE option - GraalVM ?

### ISSUE THREAD

**Issue by lindenquan** [cloudfoundry/java-buildpack#755]
[GraalVM](https://www.graalvm.org/) is mature and production ready. 
It would be awesome java-buildpack supports this JRE.

**Comment by nebhale** [comment]
We have a very similar problem to the Oracle JRE in that we do not have any way to distribute the dependencies legally.  If you'd like to submit a PR that puts in the placeholder behavior, it would be welcomed.

**Comment by lindenquan** [comment]
Thanks for your reply

**Comment by mayrstefan** [comment]
There are two editions of GraalVM
- Enterprise Edition based on Oracle JDK
- Community Edition based on OpenJDK

According to the download page one of the benefits of the community edition is 
> OSI-approved open-source licenses allow you to use for any purpose

Which dependencies have a problematic license?

**Comment by nebhale** [comment]
Use and distribution licenses are two different things and therefore we cannot distribute the binaries (you'll see that we don't even distribute the OpenJDK binaries that we build ourselves).  A contribution for placeholder behavior, pointing at a repository that contains these binaries would be welcomed.
