### ISSUE TITLE
Version pinning not working for SAP Machine

### ISSUE THREAD

**Issue by desgovedarska** [cloudfoundry/java-buildpack#759]
Hi, 
We're trying to create a true offline Java buildpack and we're packaging with the following command:
`bundle exec rake clean package OFFLINE=true PINNED=true`

The packaging passes just fine, but we noticed something strange. Unlike other dependencies where the `PINNED=true` flag prompts the packaging process to overwrite the configuration yml files in `\config` with concrete pinned versions, the versions for SAP Machine in `sap_machine_jre.yml` remain openended:

`jre:
  version: 11.+
  repository_root: "https://sap.github.io/SapMachine/assets/cf/jre/linux/{architecture}"
jvmkill_agent:
  version: 1.+
  repository_root: "{default.repository.root}/jvmkill/{platform}/{architecture}"
memory_calculator:
  version: 3.+
  repository_root: "{default.repository.root}/memory-calculator/{platform}/{architecture}"
  class_count: 
  headroom: 
  stack_threads: 250`

This is also the case for Open JDK. There are downloaded and packaged versions for these dependencies in the buildpack.
My question is - what would be the behaviour of the offline buildpack in that case? My impression was that pinning a version means that only this version will be available during staging and no calls would be made to retrieve newer ones? Is this still the case even though the version is open ended?

Best Regards,
Dessie

**Comment by reshnm** [comment]
@desgovedarska Thank you for creating the issue.
@nebhale Do you have an idea what is the expected behavior for version pinning in the offline buildpack? Is there something we have to do in the SapMachine configuration to support this use case?

**Comment by nebhale** [comment]
Only dependencies that are enabled at packaging time are pinned and included in a given buildpack.  So for example, since [most of the JRE's are disabled](https://github.com/cloudfoundry/java-buildpack/blob/v4.27/config/components.yml#L31-L36), most of them are not pinned.  If the OpenJDK JRE is disabled and the SapMachine JRE enabled, a subsequent build, with pinning, would both pin the version for SapMachine (and not OpenJDK) and include the SapMachine binaries.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
