### ISSUE TITLE
Empty "/deps/<INDEX>" folder when java_buildpack is used as a final buildpack

### ISSUE THREAD

**Issue by stiliyanv** [cloudfoundry/java-buildpack#761]
When I push an application with multiple buildpacks, and java_buildpack is used as a final-buildpack, an empty folder is created in `deps` directory. What is the need for such an empty directory? I believe that this folder should be created during `/bin/supply` script to provide a set of dependencies, but since there is no such script in java_buildpack, is this folder needed?

**Comment by stiliyanv** [comment]
After some research, it looks that this is how CF works according to the documentation [here](https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html#interactions). I guess the buildpacks can't control `deps/<index>` directory.

However, it is still strange why those directories are created for buildpacks without `/bin/supply`.

**Comment by nebhale** [comment]
I agree that this is strange, but I don't think that any further work will be done on this as we migrate to [Cloud Native Buildpacks](https://buildpacks.io).
