### ISSUE TITLE
Zulu integration not working

### ISSUE THREAD

**Issue by mmanciop** [cloudfoundry/java-buildpack#762]
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-zulu_jre.md seems broken to me: I get the following when pushing an app wanting to use the Zulu VM

```
   [Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://cdn.azul.com/zulu/bin/index.yml>
   Zulu JRE error: Unable to find cached file for https://cdn.azul.com/zulu/bin/index.yml
   None of the buildpacks detected a compatible application
```

It seems to me Azul nuked their `index.yml` from the CDN for whatever reason.

**Comment by nebhale** [comment]
I’d agree and in lieu of that you’re likely going to need to create your own with pointers to the official Azul download links.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by mells82** [comment]
The url to the index.yml is now active https://cdn.azul.com/zulu/bin/index.yml
