### ISSUE TITLE
Support disabling auto-reconfiguration

### ISSUE THREAD

**Issue by chrylis** [cloudfoundry/java-buildpack#77]
I do not want CF to reconfigure my Java application for me, but the `autoconfigure: false` option does not appear to be respected in a manifest, and the Maven plugin does not have any option for disabling it. This option is available on buildpacks for other languages (e.g., Ruby).

**Comment by wujek-srujek** [comment]
I would also like to disable auto-reconfiguration, for similar reasons as the original poster: I don't want any magic to happen that I don't understand.
Has it changed? Is it possible to disable it in any other way than forking the buildpack?

**Comment by cgfrost** [comment]
Hi, yes this is now possible.
Any configuration can now be set through an environment variable instead of forking the buildpack to change the config files directly. For example, to disable Auto reconfiguration you should set an environment variable like this one.

```
cf set-env myapp JBP_CONFIG_SPRING_AUTO_RECONFIGURATION '[enabled: false]'
```

More information is in the documentation https://github.com/cloudfoundry/java-buildpack#configuration-and-extension

**Comment by wujek-srujek** [comment]
I am already using this technique for the memory calculator settings. I guess I had better check all the config files and see what is inside them before I ask questions again.
Thank you.

**Comment by wujek-srujek** [comment]
When I put this:
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION "[enabled: false]"
in the env section in the manifest used by cf push, I get this error:

/bin/bash: line 12: unexpected EOF while looking for matching `"'
/bin/bash: line 14: syntax error: unexpected end of file

Without this line, with different vars, it all works. Seems the syntax is not right.

**Comment by cgfrost** [comment]
To do this in a manifest file a different format is required.

Try this:

```
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '[enabled: false]'
```

Chris.


Christopher Frost - Pivotal UK
Java Buildpack Team

**Comment by imarchuang** [comment]
Is there a plan for this auto-reconfiguration library to support partially disabling the services connections? Specifically, in our use case, we need a customized RedisConnectionFactory (as we use SSL connection to Azure Redis service), however, we want this auto-reconfiguration lib to reconfigure our RabbitMQ (as we using PCF provided RabbitMQ service).
