### ISSUE TITLE
ConfigurationUtils Test Failure

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/java-buildpack#770]
on running `bundle exec rake` the tests fail with the error.

```
Failures:

  1) JavaBuildpack::Util::ConfigurationUtils   diagnoses invalid YAML syntax
     Failure/Error:
       expect { described_class.load('test') }
         .to raise_error(/User configuration value in environment variable JBP_CONFIG_TEST has invalid syntax/)

       expected /User configuration value in environment variable JBP_CONFIG_TEST has invalid syntax/ but nothing was raised
     # ./spec/java_buildpack/util/configuration_utils_spec.rb:122:in `block (4 levels) in <top (required)>'

Finished in 38.17 seconds (files took 1.37 seconds to load)
895 examples, 1 failure

Failed examples:

rspec ./spec/java_buildpack/util/configuration_utils_spec.rb:121 # JavaBuildpack::Util::ConfigurationUtils   diagnoses invalid YAML syntax

Randomized with seed 19818

/usr/local/Cellar/ruby/2.6.4_2/bin/ruby -I/usr/local/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.0/lib:/usr/local/lib/ruby/gems/2.6.0/gems/rspec-support-3.9.0/lib /usr/local/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by nebhale** [comment]
I'm unable to reproduce this failure, either [in CI](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/java-buildpack/jobs/java-unit-2.6/builds/87) or locally:

```
➜  ~/d/s/java-buildpack master rbenv shell 2.6.5
➜  ~/d/s/java-buildpack master bundle install
Using rake 13.0.0
Using public_suffix 4.0.1
Using addressable 2.7.0
Using ast 2.4.0
Using bundler 2.0.2
Using safe_yaml 1.0.5
Using crack 0.4.3
Using diff-lcs 1.3
Using hashdiff 1.0.0
Using jaro_winkler 1.5.3
Using parallel 1.18.0
Using parser 2.6.5.0
Using rainbow 3.0.0
Using redcarpet 3.5.0
Using rspec-support 3.9.0
Using rspec-core 3.9.0
Using rspec-expectations 3.9.0
Using rspec-mocks 3.9.0
Using rspec 3.9.0
Using ruby-progressbar 1.10.1
Using unicode-display_width 1.6.0
Using rubocop 0.75.1
Using rubocop-rspec 1.36.0
Using rubyzip 1.3.0
Using tee 1.0.0
Using terminal-table 1.8.0
Using webmock 3.7.6
Using yard 0.9.20
Bundle complete! 10 Gemfile dependencies, 28 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
➜  ~/d/s/java-buildpack master bundle exec rspec --seed 19818       
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 19818
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 20.13 seconds (files took 0.97061 seconds to load)
895 examples, 0 failures

Randomized with seed 19818

Time: 0h:00m:22s                                                                                                                                                                                    
```

Is it possible that there's something odd in your execution environment?

**Comment by nebhale** [comment]
I'm also seeing exactly the error I'd expect when running the test:

![image](https://user-images.githubusercontent.com/60754/72825694-575a8880-3c2c-11ea-8705-8babf7f60dbb.png)

**Comment by vipinvkmenon** [comment]
I still seem to be getting the same error

bundle exec rspec --seed 19818                                                   ✔  10280  10:11:06
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 19818
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.................................................................................................................................................

Failures:

  1) JavaBuildpack::Util::ConfigurationUtils   diagnoses invalid YAML syntax
     Failure/Error:
       expect { described_class.load('test') }
         .to raise_error(/User configuration value in environment variable JBP_CONFIG_TEST has invalid syntax/)

       expected /User configuration value in environment variable JBP_CONFIG_TEST has invalid syntax/ but nothing was raised
     # ./spec/java_buildpack/util/configuration_utils_spec.rb:122:in `block (4 levels) in <top (required)>'

Finished in 28.64 seconds (files took 0.78134 seconds to load)
895 examples, 1 failure

Failed examples:

rspec ./spec/java_buildpack/util/configuration_utils_spec.rb:121 # JavaBuildpack::Util::ConfigurationUtils   diagnoses invalid YAML syntax

Randomized with seed 19818

Anyhow, let me have a look into this. (Possibly environment issue? 🤔 )

**Comment by vipinvkmenon** [comment]
I seem to be getting the same issue in docker as well after pulling the master.

docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app ruby:2.6.5 gem install bundler rspec && bundle exec rspec --seed 19818
Successfully installed bundler-2.1.4
Successfully installed rspec-support-3.9.2
Successfully installed rspec-core-3.9.1
Successfully installed diff-lcs-1.3
Successfully installed rspec-expectations-3.9.0
Successfully installed rspec-mocks-3.9.1
Successfully installed rspec-3.9.0
7 gems installed
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 19818
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.................................................................................................................................................

Failures:

  1) JavaBuildpack::Util::ConfigurationUtils   diagnoses invalid YAML syntax
     Failure/Error:
       expect { described_class.load('test') }
         .to raise_error(/User configuration value in environment variable JBP_CONFIG_TEST has invalid syntax/)

       expected /User configuration value in environment variable JBP_CONFIG_TEST has invalid syntax/ but nothing was raised
     \# ./spec/java_buildpack/util/configuration_utils_spec.rb:122:in `block (4 levels) in <top (required)>'

Finished in 27.25 seconds (files took 1.29 seconds to load)
895 examples, 1 failure

Failed examples:

rspec ./spec/java_buildpack/util/configuration_utils_spec.rb:121 # JavaBuildpack::Util::ConfigurationUtils   diagnoses invalid YAML syntax

Randomized with seed 19818

**Comment by nebhale** [comment]
What do you see for the values of the two variables I identified above when you run the tests in debug mode?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
