### ISSUE TITLE
Add separate autoreconfiguration for spring-boot with java-cfenv

### ISSUE THREAD

**Issue by dyroberts** [cloudfoundry/java-buildpack#779]
In order to preserve existing behaviour for non-boot spring users, create a separate autoreconfiguration jar, used only for boot apps, that uses `java-cfenv` in place of spring-cloud-connector. A new framework definition at `/lib/java_buildpack/framework/spring_boot_auto_reconfiguration.rb` would be added.

Update https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/spring_auto_reconfiguration.rb#L43 to ignore boot apps.

**Comment by dyroberts** [comment]
@nebhale I'd be happy to take a crack at a contribution here; if this idea actually seems like a good one to you. :)

**Comment by nebhale** [comment]
Yeah, why don't you start with a PR to https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration as either another JAR in the project, or a separate branch for the repo, and we'll go from there.

**Comment by SeifMostafa** [comment]
Hello, Still available?

**Comment by dmikusa-pivotal** [comment]
We announced the intended path forward here on Slack recently, sorry, I should have posted it here as well.

The CF JBP has [Spring Auto Reconfiguration (SAR)](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration). Spring Auto Reconfiguration uses [Spring Cloud Connectors (SCC)](https://cloud.spring.io/spring-cloud-connectors/). SCC has been deprecated for a long time. 

We also generally recommend explicit configuration, i.e. directly using java-cfenv, as opposed to relying on the SAR. SAR tends to provide good demo flash, but it's not practical in production usage (too much magic, difficult to debug when something goes wrong, etc...). 

For these reasons, we are planning to deprecate and over a slow period of time eventually remove SAR and by-proxy SCC. The future recommendation will be explicit configuration in your application either manually or using a tool like java-cfenv.

Please let me know if you @SeifMostafa or anyone else has feedback on this plan. We are not scheduled to implement it quite yet, so there's still time to discuss. Thanks.

**Comment by dmikusa-pivotal** [comment]
This deprecation has begun with version 4.49. See the [CloudFoundry Docs](https://docs.cloudfoundry.org/buildpacks/java/configuring-service-connections.html) for usage & migration instructions.

Closing this issue.
