### ISSUE TITLE
CLA?

### ISSUE THREAD

**Issue by chestnutt** [cloudfoundry/java-buildpack#783]
Hi - I submitted a pull request (https://github.com/cloudfoundry/java-buildpack/pull/782), and it says we haven't signed the CLA.  However, if I'm not mistaken, Riverbed did sign the CLA a couple of years ago.

My github profile says I'm part of the Riverbed organization. So I'm not sure what else is needed.

Is there something disconnected between my github account and the Riverbed CLA?

Thanks,
-Dave

**Comment by chestnutt** [comment]
For what it's worth, I just signed the individual contributor CLA, too - in case our previous contact did that instead of a corporate CLA.

**Comment by nebhale** [comment]
CLA says clean for me, which is all I need :)
