### ISSUE TITLE
Unable to find built artifact (executable JAR or WAR) in target/*.[jw]ar, candidates: []

### ISSUE THREAD

**Issue by mefernandez** [cloudfoundry/java-buildpack#785]
Hi,

This is my first time trying to build using `pack`, so I'm not sure if this issue belongs here.

I tried to build a multi-module maven application with:
```
pack build tpv --builder cloudfoundry/cnb:bionic
```

It builds all modules ok, but at the very end `pack` fails with this message:
```
[builder] Cloud Foundry Build System Buildpack v1.2.14
[builder]   unable to find built artifact (executable JAR or WAR) in target/*.[jw]ar, candidates: []
[builder] ERROR: failed to build: exit status 103
```

I think it's because the `target` is inside each sub-module:
```
.
├── pom.xml
├── api
│   ├── pom.xml
│   └── target
└── web
    ├── pom.xml
    ├── target
```

¿How do I tell `pack` command the path to the built artifact?

Thanks,

Mariano.

**Comment by nebhale** [comment]
This issue is for the new Cloud Native Buildpacks and should be opened [there](https://github.com/cloudfoundry/build-system-cnb).  The docs there describe configuration options for this specific behavior.

**Comment by Rvarman0110** [comment]
Hey @nebhale, @mefernandez  I am also facing a similar issue where in my pom.xml there are modules which refers to other pom.xml files like the flow that you guys, 

.
├── pom.xml
├── api
│   ├── pom.xml
│   └── target
└── web
    ├── pom.xml
    ├── target
    
    
    
   **Can I get to know how you guys resolved this issue** 
    I tried using BP_BUILT_MODULE and BP_BUILT_ARTIFACT for Maven

**Comment by dmikusa** [comment]
If you're having issues with the CloudFoundry Java buildpack, please open a new issue on this project.

If you're having issues with Paketo Buildpacks, which is the original post here, please open a new issue here https://github.com/orgs/paketo-buildpacks/discussions.
