### ISSUE TITLE
java agent Instrumented class file not reflected on PCF

### ISSUE THREAD

**Issue by kedargosavisyf** [cloudfoundry/java-buildpack#788]
Hello,

Need some help.

We have a custom java agent written using javaassist that instruments Logger file from logback for info method. The agent works as standalone program from command line. 
Premain is called - transformer is called - instruments the class file - prints the log as updated using instrumentation.   It also works if a sample maven project is created in Eclipse and executed by Providing run configuration having -javaagent in run configuration. 

While pushing on PCF:
The agent in packaged into spring-boot app binary, under  MyApp.jar\BOOT-INF\classes\   This is very Simple Hello Program with one controller.

**Issue is** 
Premain is called - transformer is called - instruments the class file, **However does not print the log as updated using instrumentation**.  

Do we need any specific configuration to get this instrumented file back to PCF?

Appreciate your inputs/queries.

Here is `manifest.yml`

```
applications:
- name: KedarTestApp
  memory: 2G
  disk_quota: 1G
  instances: 1
  path: target/Hello-0.0.1-SNAPSHOT.jar
  env: 
    SPRING_PROFILES_ACTIVE : "dev"
    JAVA_OPTS: -javaagent:BOOT-INF/classes/Agent.jar
```

**Dev Env:** 
JDK8, WIndows 10, cf version 6.26

**Comment by nebhale** [comment]
There's nothing inherently different about running an application on CF versus locally.  The only difference that you might not expect is that we run as an exploded JAR file.  Beyond that, the command is essential `java -cp . <Manifest Main-Class>`.  You might try replicating locally with an exploded JAR setup.

**Comment by kedargosavisyf** [comment]
Thank You Nebhale....above scenario works on local machine with below config from command line. Checking further towards how to push app to PCF  and how to pass this from manifest.mf

mvn spring-boot:run -Dspring-boot.run.agent="\codebase\AgentProcess\Agent.jar"

**Comment by kedargosavisyf** [comment]
Closing this issue: The instrumentation library needs to be added to -cp on manifest, for command option.
