### ISSUE TITLE
Question: how to disable memory calculator and jvmkill?

### ISSUE THREAD

**Issue by chefhoobajoob** [cloudfoundry/java-buildpack#791]
I have an app that used to start successfully and run for days/weeks of usage that used no other memory settings besides the memory property of its cloud foundry application manifest. This app was unaware of the `JAVA_OPTS` environment variable generated by the buildpack, and so was ignoring anything propagated in that way.

Recently I added startup processing that handled the `JAVA_OPTS` variable generated by the buildpack in order to pick up some agent instrumentation, and that change generated a whole new set of startup and runtime instability problems that are stemming from the memory heuristics produced by the memory calculator and then acted upon by the jvmkill agent, in some cases not materializing until after many hours of runtime, depending on usage.

I'm trying to find a way to prevent the memory calculator from explicitly setting any memory parameters at all and rely on the jvm defaults, but I haven't found any documentation indicating this can be done.

Is there a way for an application to disable the memory calculator and jvmkill?

**Comment by nebhale** [comment]
No, the buildpack does not have a way to disable the addition of the memory calculator and `jvmkill`.  A fork of the buildpack would allow you to do it manually, but there are no configuration flags that would enable it.
