### ISSUE TITLE
Question: JNDI support

### ISSUE THREAD

**Issue by INSUNG-BANG** [cloudfoundry/java-buildpack#794]
Hi, 
Referring https://github.com/cloudfoundry/java-buildpack/issues/189 which is 5 years ago issue, It seemed that JNDI connection on CF community build pack was not supported. Is it still not supported at year 2020?

**Comment by INSUNG-BANG** [comment]
> Regarding

**Comment by INSUNG-BANG** [comment]
Issue closed by mistake and question still remained open.

**Comment by nebhale** [comment]
Correct, there has been no change since #189.
