### ISSUE TITLE
.idea artifacts? 

### ISSUE THREAD

**Issue by txpokey** [cloudfoundry/java-buildpack#803]
I noticed that there's a .idea directory and at least one .iml file in the corpus for this buildpack. 
on any project that I've managed or architected, we add these to the .gitignore to *prevent* them from being checked in. IMHO: they dont belong here, esp. since I am an intellij user and I dont need to have them mess up my preferences etc.

**Comment by nebhale** [comment]
We explicitly add them to source control as it ensures that multiple developers on the project all end up with consistent development environments (you'll notice that we do [exclude some bits of the IDEA footprint that are user-specific](https://github.com/cloudfoundry/java-buildpack/blob/master/.gitignore)) and we don't experience the "works on my machine" scenario.
