### ISSUE TITLE
container security provider jar is missing in command class path parameter when dist style zip file is pushed to cloud foundry and causing Client authentication to fail.

### ISSUE THREAD

**Issue by cheranm** [cloudfoundry/java-buildpack#805]
Steps to reproduce the issue.

1. `mtls-sample` (https://github.com/cheranm/mtls-sample) is forked from https://github.com/nebhale/mtls-sample. The forked project demonstrates SSL Termination at application level by using Cloud foundry container to container networking and container instance identity. 

2. Build the project using `mvn package`. 

3. Navigate to server and run `cf push -s cflinuxfs3`. Everything works as expected.

4. Check the command  in status message updated in the console. The command includes `-cp $PWD/.:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.16.0_RELEASE.jar`

```
Updating app with these attributes...
  name:                mtls-sample-server
  path:                C:\downloads\github\mtls-sample\server\target\mtls-sample-server-1.0.0.BUILD-SNAPSHOT.jar
  buildpacks:
   -   java_buildpack_offline_4_28
  command:             JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs= -Djava.security.properties=$P
WD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=19902 -poolType=metaspac
e -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/j
ava $JAVA_OPTS -cp $PWD/.:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.16.0_RELEASE.jar org.springframework.boot.loader.JarLauncher
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              1G
  stack:               cflinuxfs3
```

5. mtls authentication works as expected. Check the SSL handshake between server and client by running openssl. 

```
C:\downloads\github\mtls-sample\server>cf ssh mtls-sample-client -c "openssl s_client -connect mtls-sample-server.apps.internal:8443 -state -debug -cert $CF_INSTANCE_CERT -key $CF_INSTANCE_KEY" > c:\temp\result.txt
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS read server hello
depth=2 C = USA, O = Cloud Foundry, CN = appRootCA
verify return:1
depth=1 C = USA, O = Cloud Foundry, CN = instanceIdentityCA
verify return:1
depth=0 CN = mtls-sample-server.apps.internal
verify return:1
SSL_connect:SSLv3/TLS read server certificate
SSL_connect:SSLv3/TLS read server key exchange
SSL_connect:SSLv3/TLS read server certificate request
SSL_connect:SSLv3/TLS read server done
SSL_connect:SSLv3/TLS write client certificate
SSL_connect:SSLv3/TLS write client key exchange
SSL_connect:SSLv3/TLS write certificate verify
SSL_connect:SSLv3/TLS write change cipher spec
SSL_connect:SSLv3/TLS write finished
SSL_connect:SSLv3/TLS write finished
SSL_connect:SSLv3/TLS read change cipher spec
SSL_connect:SSLv3/TLS read finished
SSL3 alert read:warning:close notify
SSL3 alert write:warning:close notify
```

5. Build the server project using `gradlew bootDistZip`
6. Change the path in `manifest.yml` file to `path: build\distributions\mtls-sample-server-boot-0.0.1-SNAPSHOT.zip`
7. Execute `cf push -s cflinuxfs3`.  The command didn't include `-cp $PWD/.:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.16.0_RELEASE.jar`

```
C:\downloads\github\mtls-sample\server>cf push -s cflinuxfs3
Pushing from manifest to org DEV / space nashua as cmuthuvi@opentext.com...
Using manifest file C:\downloads\github\mtls-sample\server\manifest.yml
Getting app info...
Updating app with these attributes...
  name:                mtls-sample-server
  path:                C:\downloads\github\mtls-sample\server\build\distributions\mtls-sample-server-boot-0.0.1-SNAPSHOT.zip
  buildpacks:
    java_buildpack_offline_4_28
  command:             JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs= -Djava.security.properties=$P
WD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=14935 -poolType=metaspac
e -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 JAVA_OPTS=$JAVA_OPTS JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre ex
ec $PWD/mtls-sample-server-boot-0.0.1-SNAPSHOT/bin/mtls-sample-server
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              1G
  stack:               cflinuxfs3
```

8. mTLS between server and client fails. Run openssl to check the SSL handsake between server and client.

```
C:\downloads\github\mtls-sample\server>cf ssh mtls-sample-client -c "openssl s_client -connect mtls-sample-server.apps.internal:8443 -state -debug -cert $CF_INSTANCE_CERT -key $CF_INSTANCE_KEY" > c:\temp\result.txt
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS read server hello
depth=2 C = USA, O = Cloud Foundry, CN = appRootCA
verify return:1
depth=1 C = USA, O = Cloud Foundry, CN = instanceIdentityCA
verify return:1
depth=0 CN = mtls-sample-server.apps.internal
verify return:1
SSL_connect:SSLv3/TLS read server certificate
SSL_connect:SSLv3/TLS read server key exchange
SSL_connect:SSLv3/TLS read server done
SSL_connect:SSLv3/TLS write client key exchange
SSL_connect:SSLv3/TLS write change cipher spec
SSL_connect:SSLv3/TLS write finished
SSL_connect:SSLv3/TLS write finished
SSL_connect:SSLv3/TLS read change cipher spec
SSL_connect:SSLv3/TLS read finished
```

Please note that `SSL_connect:SSLv3/TLS write client certificate` is missing in the handshake.

**Comment by nebhale** [comment]
This may very well be a problem, but I don't think the lack of a `-cp ...` is the indication of that problem.  DistZip applications manage their class path's internally (😬) and so we make the change to the [startup scripts](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/container/dist_zip_like.rb#L85-L111) (which is quite brittle).  You'd have to `cf ssh` into the application, take a look at the contents of the droplet, and then determine if we've hooked up the classpath correctly.

**Comment by cheranm** [comment]
> You'd have to cf ssh into the application, take a look at the contents of the droplet, and then determine if we've hooked up the classpath correctly.

1. push the jar
2. Ran jar cat /proc/6/cmdline. Output is  given below
/home/vcap/app/.java-buildpack/open_jdk_jre/bin/java-agentpath:/home/vcap/app/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1-Djava.io.tmpdir=/home/vcap/tmp-XX:ActiveProcessorCount=8-Djava.ext.dirs=-Djava.security.properties=/home/vcap/app/.java-buildpack/java_security/java.security-Xmx411327K-Xss1M-XX:ReservedCodeCacheSize=240M-XX:MaxDirectMemorySize=10M-XX:MaxMetaspaceSize=125248K-cp/home/vcap/app/.:/home/vcap/app/.java-buildpack/container_security_provider/container_security_provider-1.16.0_RELEASE.jarorg.springframework.boot.loader.JarLauncher
3 push the zip file. 
4.Ran jar cat /proc/6/cmdline. Output is  given below
/home/vcap/app/.java-buildpack/open_jdk_jre/bin/java-agentpath:/home/vcap/app/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1-Djava.io.tmpdir=/home/vcap/tmp-XX:ActiveProcessorCount=8-Djava.ext.dirs=-Djava.security.properties=/home/vcap/app/.java-buildpack/java_security/java.security-Xmx438311K-Xss1M-XX:ReservedCodeCacheSize=240M-XX:MaxDirectMemorySize=10M-XX:MaxMetaspaceSize=98264K-jar/home/vcap/app/mtls-sample-server-boot-0.0.1-SNAPSHOT/lib/mtls-sample-server-0.0.1-SNAPSHOT.jar

spring_auto_reconfiguration-2.11.0_RELEASE.jar(and folder)  is missing from the droplet java buildpack directory when dist style zip file is pushed.

**Comment by nebhale** [comment]
Security Providers are not added to the classpath prior to Java 9.  Instead they're referenced by pointing `-Djava.ext.dirs=` at a folder containing them.  You'll notice that when pushing a distZip application the command that is created contains this reference (Java Buildpack 4.31.1, although this hasn't changed in years):

```plain
JAVA_OPTS="
  -agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1
  -Djava.io.tmpdir=$TMPDIR 
  -XX:ActiveProcessorCount=$(nproc) 
  -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext
  -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security 
  $JAVA_OPTS" && \
CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE \
  -totMemory=$MEMORY_LIMIT \
  -loadedClasses=16225 \
  -poolType=metaspace \
  -stackThreads=250 \
  -vmOptions="$JAVA_OPTS") && \
echo JVM Memory Configuration: $CALCULATED_MEMORY && \
JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && \
MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT JAVA_OPTS=$JAVA_OPTS JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre \
  exec $PWD/dist-zip-application-1.0.0.BUILD-SNAPSHOT/bin/dist-zip-application
```

The `-Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider` in my example points at the container security provider.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
