### ISSUE TITLE
Change tomcat server configurations to upload files > 10MB

### ISSUE THREAD

**Issue by saranshbansal** [cloudfoundry/java-buildpack#807]
Is there anything that can be done via CLI or do i have to fork and make a new buildpack?
I have to allow uploading files > 10mb but there is a post request size limit of 10mb by default. Please help.

**Comment by zoosm3** [comment]
@saranshbansal This doesn't seem buildpack issue. Do you use an embedded Tomcat on Spring Boot? If yes, you can configure `server.tomcat.max-http-post-size` at  `application.properties`.

https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/common-application-properties.html

**Comment by saranshbansal** [comment]
`spring.servlet.multipart.max-request-size=50MB`
@zoosm3  I used this instead. And it worked.
