### ISSUE TITLE
java-buildpack error

### ISSUE THREAD

**Issue by NTarasau** [cloudfoundry/java-buildpack#808]
Hello,
Buildpack failed with error on stage:
[DownloadCache] - WARN  Unable to download https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/index.yml into cache /tmp: execution expired

We use online version of buildpack around 1 year without any issues before

Could you please check and suggest
![image](https://user-images.githubusercontent.com/42800786/81797554-a009ba80-9517-11ea-8b16-df982404fd21.png)

**Comment by mayrstefan** [comment]
The URLs show downloads for Ubuntu trusty - which is for the cflinuxfs2 stack. cflinuxfs2 support was removed with Java Buildpack 4.22 in September 2019. Maybe you should redeploy your application with a current buildpack and cflinuxfs3 stack.

**Comment by nebhale** [comment]
Confirmed, we don't support `cflinuxfs2` at all.
