### ISSUE TITLE
facing issue while running jar file using cf cli version 6.51

### ISSUE THREAD

**Issue by manzerimam786** [cloudfoundry/java-buildpack#813]
### yml file content
applications:
- name: hello-world-rest-api
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack.git
  command: /bin/java -cp ./target/hello-world-rest-api.jar com.rft.rfda.gaia.Launcher
  disk_quota: 1G
  instances: 1
  memory: 1G
  routes:
  - route: hello-world-rest-api-chipper-turtle-yp.cfapps.io
  timeout: 120
  stack: cflinuxfs3

using Spring Boot Version 2.1.7.RELEASE

I am trying to push jar file while using below command

cf push

getting below error

Error staging application: App staging failed in the buildpack compile phase.

This issue I am gtting from 3 days and my learning omn pcf got stuck here. Please suggest me to overcome this issue !! thanks in advance

**Comment by nebhale** [comment]
A command of `cf push` is unlikely to be pushing a JAR file, rather you are pushing the working directory that you are in.  If you `cf push -p <path-to-JAR>` and don't set the `command` (the buildpack does that for you), you'll be fine.
