### ISSUE TITLE
Was it necessary to change branch name from `master` to `main`? 

### ISSUE THREAD

**Issue by vorbidan** [cloudfoundry/java-buildpack#814]

**Comment by nebhale** [comment]
With the recent pushes for change across our society, it has become clear that “established convention” isn’t a good reason to continue to use `master` as the name for the base branch in a git repository. This RFC draft on [“Terminology, Power and Offensive Language”](https://tools.ietf.org/html/draft-knodel-terminology-01) gives a good summary of some of the reasons this language is unacceptable, as well as providing recommendations on what to use instead. Here at the Cloud Foundry Foundation, [we’re planning](https://lists.cloudfoundry.org/g/cf-dev/topic/75070528#9059) to follow in the footsteps of Drupal, Python, Django, and many others in changing this terminology both internally and in our documentation.

**Comment by vorbidan** [comment]
Thank you Ben, I learned something new today.
