### ISSUE TITLE
Pushing Java app without specifying -path

### ISSUE THREAD

**Issue by hmble2** [cloudfoundry/java-buildpack#819]
For java buildpack is it possible that "path" in manifest.yml doesn't specify executable jar but rather a directory (containing multiple jars) and "command" specify executable command (e.g. java -jar abc.jar).

I have two spring-boot executable jars (one main app and other sidecar app), each would listen on a different port (as @RestController is embedded into both). How do I push this these 2 jars to PCF with sidecar pattern, I am following instructions in https://docs.run.pivotal.io/devguide/sidecars.html however, cannot package two executable jars into single binary as instructed:

```
Packaging Binaries
The Java buildpack requires you to push a .jar file in some cases. If this is the case with your app, you must include the sidecar binary in the .jar file.

To package the sidecar binary with the .jar file, run:

zip JAR -u SIDECAR-BINARY
```

Are there any solution available for this?

**Comment by hmble2** [comment]
FYI @nebhale

**Comment by nebhale** [comment]
The Java Buildpack is designed to execute a single Java application, manifested as an exploded JAR file (which is generally taken care of by the `cf` CLI).  Its design does not enable the use of any other deployment configuration.

**Comment by hmble2** [comment]
Thanks, I embedded other executable jar into main jar and was able to deploy them using sidecar pattern.

**Comment by nebhale** [comment]
Sounds good!
