### ISSUE TITLE
support for checkmarx iast agent

### ISSUE THREAD

**Issue by eli-fin** [cloudfoundry/java-buildpack#821]
Hi,

I'd like to add support for running applications with the Checkmarx IAST java agent.
The agent collects information which is sent to a central server for analysis.

Here's the high-level design of what I intend to do (as a new framework in this buildpack):

1. Check for existence of a bound Checkmarx service (which will include the server URL in it's credentials)
2. Download the agent files from the server
3. Add the java agent, possibly some JVM arguments and some system properties

Before I start implementing, just checking if this is basically OK and for any other input.

Also, please let me know how to fill out the CLA.

Thanks

**Comment by nebhale** [comment]
I believe that everything you've listed looks appropriate.  I've had some trouble finding a "pre-sign" link for the CLA (most people begin the process on submission), but [this](https://api.lfcla.com/v2/repository-provider/github/sign/1797134/9899931/802) might be it.

**Comment by eli-fin** [comment]
Hi @nebhale,

Submitted PR #823.

Tried to follow all the contribution guidelines. Hope all is fine :)
Still working on the CLA, but the code is ready for review.
