### ISSUE TITLE
JavaBuildpack with JDK

### ISSUE THREAD

**Issue by gangov** [cloudfoundry/java-buildpack#824]
Hello, 

can you please tell me how can I include a buildpack with JDK in it. The current buildpack won't work for me, as it has only JRE.

Best regards,

**Comment by eli-fin** [comment]
Hi @gangov,

Haven't tried it myself, but I think this might help:

> To use Oracle JRE instead of OpenJDK without forking java-buildpack, set environment variable and restage:
```bash
cf set-env <app_name> JBP_CONFIG_COMPONENTS '{ jres: [ "JavaBuildpack::Jre::OracleJRE" ] }'
cf set-env <app_name> JBP_CONFIG_ORACLE_JRE '{ jre: { repository_root: "<INTERNAL_REPOSITORY_URI>" } }'
cf restage <app_name>
```
Where `INTERNAL_REPOSITORY_URI` would point to a zip of the JDK you'd like to use.

(source: https://github.com/cloudfoundry/java-buildpack/blob/main/docs/jre-oracle_jre.md#configuration)

**Comment by nebhale** [comment]
You don't even need to switch to Oracle or another JVM provider; instead directly override the default provider's `repository_root`.  In addition, [we provide](https://github.com/cloudfoundry/java-buildpack-dependency-builder#available-artifacts) the [matching JDK](https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64/index.yml) for the JRE variant we use.

```
➜ cf set-env java-main-application JBP_CONFIG_OPEN_JDK_JRE \
  '{ jre: { repository_root: "{default.repository.root}/openjdk-jdk/{platform}/{architecture}" } }'
```

All that being said I would be remiss if I don't say in bold letters, **this is a dangerous thing to do and I strongly recommend against it**.  Compilers, even Java compilers, available in production containers have a long and proven track record of being a security vulnerability.  Security teams across the industry nearly universally forbid JDK's in containers for this reason.
