### ISSUE TITLE
Support for DataDog Agent  as part of  java buildpack

### ISSUE THREAD

**Issue by sureshnepolian** [cloudfoundry/java-buildpack#826]
It is observed that, DataAgent isnt part of the java buildpack. It would be great if we have support for datadog agent as well.

**Comment by nebhale** [comment]
I agree, it would be quite good if Datadog APM was available in the buildpack.  We'd be happy to accept a contribution with such an addition.

**Comment by tylerbenson** [comment]
I added a PR to cover this: #867
