### ISSUE TITLE
newrelic jar agent current version 

### ISSUE THREAD

**Issue by kmacpher67** [cloudfoundry/java-buildpack#827]
New relic supports the notion of "lastest" build can we upgrade the code the builds reference to the download jar file to include current? 

https://download.newrelic.com/newrelic/java-agent/newrelic-agent/

Is it New Relic that controls that release & do they need to add a "current" or who or where is that done at? 

NR JAR files are NVP keyed via this yaml: https://download.run.pivotal.io/new-relic/index.yml

It would be useful to get the "current" 
 cf set-env $app JBP_CONFIG_NEW_RELIC_AGENT "{ version: 'current' }"
would install jar file 6.1.0 (as of this date or whatever it would be at the time of the CO CF deployment.

**Comment by kmacpher67** [comment]
memories coming back to me: 
Ok, i think this is another project in the cloud foundry land that controls this: 

https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/main/new-relic.yml

calls this shell file that builds that  this yaml: https://download.run.pivotal.io/new-relic/index.yml
 file that used to version KEY to URL lookup. 

run:
  path: java-buildpack-dependency-builder/new-relic.sh

So maybe getting the **current** key added is not part of this project: 

current: https://download.run.pivotal.io/new-relic/new-relic-6.1.0.jar

I think i need to create a Issue there perhaps?

**Comment by nebhale** [comment]
With any build, the Java Buildpack looks for the latest version of any given dependency within a wildcard.  This is controlled via configuration [here](https://github.com/cloudfoundry/java-buildpack/blob/main/config/new_relic_agent.yml#L18).  After this many years without any breakage, it's probably time to relax that wildcard to `+` and always follow the latest release.
