### ISSUE TITLE
Cloud foundry| Run jacoco agent

### ISSUE THREAD

**Issue by pank9** [cloudfoundry/java-buildpack#835]
I have deployed the application on cloud foundry and trying to attach jacoco as a java agent to generate the integration report but seems that jacoco is not working. Below are the few steps.
1) Deployed the application on the cloud. using "cf push" command from cli
2)  trying to set the java env using command "cf set-env <APP-Name> JPB_CONFIG_JAVA_OPTS -javaagent:res/org.jacoco.agent-0.8.5-runtime.jar=address=*,port=36320,output=tcpserver" (also tried in manifest file using JBP_CONFIG_JAVA_OPTS: '[java_opts: "-javaagent:BOOT-INF/lib/org.jacoco.agent-0.8.5-runtime.jar=address=*,port=36320,output=tcpserver"]')
 but it is not working
3) tried to run command "java -jar BOOT-INF/lib/jacococli-0.8.5.jar dump --address localhost --port 36321 --destfile target/jacoco.exec" from cli but it is not working it is pointing to my machine path event tried to execute this command from sidecars as below 
    sidecars:
     - name: coveragesidecar
       process_types: [ 'web', 'worker' ]
       command: '    sidecars:
     - name: coveragesidecar
       process_types: [ 'web', 'worker' ]
       command: 'java -javaagent:/BOOT-INF/lib/org.jacoco.agent-0.8.5-runtime.jar=address=*,port=36320,output=tcpserver -jar 
                         target/coverage-test-0.0.1-SNAPSHOT.jar'
       memory: 256MB'

But nothing is working.
My goal is to generate the integration report and download the integration report by running jacoco.

After deploying application I have established SSH connection and tried to execute command on VCAP console but any java command is not getting executed there.

Can anyone help me to get this done? 
I have followed the cloud foundry documentation to get this done but nothing worked out. I have taken the help from doc to create side car but still issue persist

**Comment by amoldixit-Git** [comment]
There is very little documentation available for enabling jacoco agent in CF. I faced similar issue as I was referring this [link](https://github.com/cloudfoundry/java-buildpack/issues/529)

When I use following command
cf push SAPSCPAD101 -b http://github.com/cloudfoundry/java-buildpack.git#529-jacoco
my application is

**Comment by dmikusa-pivotal** [comment]
@amoldixit-Git 

>2020-10-29T00:33:02.49+0530 [STG/0] ERR Failed to clone git repository at http://github.com/cloudfoundry/java-buildpack.git

This error has nothing to do with the JaCoCo support. It's just telling you that Cloud Foundry cannot download the buildpack you told it to use. This happens before the Java buildpack even runs. Your Cloud Foundry may not allow outbound connections to the Internet which would cause the error you're seeing.

The good news is that you don't need that branch anymore. The Java buildpack has had JaCoCo support in the main branch for a while now (Since Feb 2018). You should be able to use any recent version of the JBP including the one that ships with your Cloud Foundry installation.

**Comment by dmikusa-pivotal** [comment]
@pank9 

>I have deployed the application on cloud foundry and trying to attach jacoco as a java agent to generate the integration report but seems that jacoco is not working.

I don't believe that is the way the integration works. The integration with the JBP expects a JaCoCo service to be bound to the app. The service needs an address (IP or DNS) for the agent to connect to. The agent is going to connect and report back the information

Try following the instructions here: https://github.com/cloudfoundry/java-buildpack/blob/main/docs/framework-jacoco_agent.md

To create the service, you'd do something like `cf cups jacoco-service -p "address,excludes,includes,port,output"`. Then fill in the properties when prompted by the cf cli (note: you don't need to set all of those properties, only address is required).

Then bind the service to your app & `cf push` or `cf restage` your app. When the JBP runs, you should see that it includes the JaCoCo agent and configures it for you. The agent should talk back to the address that you configured. No entering the container should be required.

Hope that helps!
