### ISSUE TITLE
Finalize failed with exception #<RuntimeError: Unable to find cached file for https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/bellsoft-jre15.0.1%2B9-linux-amd64.tar.gz>

### ISSUE THREAD

**Issue by asokoloski-m** [cloudfoundry/java-buildpack#839]
Hi all, this error pops up when trying to switch to Java 15 from Java 11 with an offline buildpack.  

Our JBP_CONFIG_OPEN_JDK_JRE value is `{ jre: { version: 15.+ } }`

I may be wrong, but It seems that the file `rakelib/dependency_cache_task.rb` wasn't updated for Java 15, like it was for previous java versions?  Specifically this line: https://github.com/cloudfoundry/java-buildpack/blob/895590c61fc851f48546efbc00a8c600b062eeff/rakelib/dependency_cache_task.rb#L135

Thanks very much!

**Comment by divyamudundi** [comment]
We are having same issue? Is there any workaround for this?

**Comment by asokoloski-m** [comment]
@divyamudundi In the meantime, you can fork the repository, make this change yourself, and use your own repo url as the buildpack reference, like "https://github.com/your-account/java-buildpack.git", I think.  It worked for me.

**Comment by ChrisOr4** [comment]
We are having same issue too.
Nobody can fix this ?
