### ISSUE TITLE
Need Help on Luna Security Provider in java-buildpack

### ISSUE THREAD

**Issue by type4ranjan** [cloudfoundry/java-buildpack#841]
I am trying to use Luna Security Provider in java-buildpack using cf dev on windows machine.I have SafeNet Luna HSMs on the network where I am testing it.

I am new to cloud foundry. I read the docs of Luna Security Provider and executing below steps:
`
PS C:\Users\Administrator> cf create-user-provided-service luna -p '{"client":{"certificate":"-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----","private-key":"-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----"},"servers":[{"name":"test-host-1","certificate":"-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"},{"name":"test-host-2","certificate":"-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"}],"groups":[{"label":"test-group-1","members":["test-serial-number-1","test-serial-number-2"]},{"label":"test-group-2","members":["test-serial-number-3","test-serial-number-4"]}]}'

{client:{certificate:-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----> -----BEGIN CERTIFICATE-----MIIDKTCCAhGgAwIBAgIBADANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHT250YXJpbzEPMA0GA1UEBwwGT3R0YXdhMRMwEQYDVQQKDApNeSBjb21wYW55MREwDwYDVQQDDAhjZmNsaWVudDAeFw0yMDExMDExNDU1MjZaFw0zMDEwMzExNDU1MjZaMFgxCzAJBgNVBAYTAkNBMRAwDgYDVQQIDAdPbnRhcmlvMQ8wDQYDVQQHDAZPdHRhd2ExEzARBgNVBAoMCk15IGNvbXBhbnkxETAPBgNVBAMMCGNmY2xpZW50MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyuN2H6YWcmnwMjzSK86/f1djhsT79ismiGjzcw7QXi2N1YJYEYiI0Lrbg3icpBDOc6OSF7HqKSG8dKf0+aqbEhP6yta5I2X1rQZhIWuaX65eEk/IkDdvUYqUUZQcrKMoUzPKQ6ta/8B9wnMj4dvNxhGHOf3iuPpY/UVtvBVGiTw7R/wIr2X+oPZ5jAFkgSWbi6MYc7jkhfkeVxZtirYdOTxTisAIFbVqTFthE8QH5OVajq7egzVxa25m7TC5fidGXfBl9TgZj15jXjUcs4P6+TzO+YEiGnWTTmCJl9OGaCptGuP92AtXuoQ1kR/G9FV3mbMi2Fn+x06Xn2CSe3WpWQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCLgZL3lP8AmUVse79QlSx+se8nVjzqihJyjXqaPvRv7kF4HT9fnVATHEbrx/I4Cpk00X2e1CYcoAlWt6k3z39FKAXiHuDLaFROPQywBK6CxN6vJnBGdsRkG33BVhjCGrXr3fIdfC01c80tlnRtueV8XvBDyWqMe9PzyUt8Tk4p1Yrtgb/CgZWXOLwGMWUO1cDaPmUldz95pGcK7lW8UwJr/X9WVwp/QqFALssXyxlWC9BaKNHCsp/QMtxLuh2911niPMV0UrPJA1XzKUnIzsF5Ox3x47sv8Rc9JYyyYlD3kLyullURpK2NEpDOlJki26UQhSfQOTkpbiPTEnz3T/M4-----END CERTIFICATE-----

private-key:-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----}> -----BEGIN RSA PRIVATE KEY-----Proc-Type: 4,ENCRYPTEDDEK-Info: DES-EDE3-CBC,7D2DDD6BFC6D9E2Edz8olbWbqibYVwEQ0htfDRRptApcL9ZSk9ZJLoBTveJbVt75WNlhCkYgN6nj1Ghs4ClSnGQw0wdQYJeDWdHSGOxTUIsePtks8a+UA5r9vpBYQcYtEbp/eJXBHLRdtjGlAmTurDRIb5uYN+5FacCurINPpjXe5ZQayLtaSZqiiX6xQZThiCJ0CW3fpH19fBnAlVaj5izbhP7MHCePhIsH/7Sa14kknT6qVCEARwP2rOM0Nhr8FbawsDcMUhYu4Gz5LrQVczTuW1YpYPpwzhc3dtuZjRtFZbp8mcAjccB3/d4R4vsNX3lM6MdrXwU/EqH0HFbghyCzY90wgWel4IIe9pbzG0pK+ff7kojXNy8XsO0uF/GMYrCqLiCdfRN1/RUN6hkbgPNy6ogwl5rybOkBm/Lv5WRNP11bdzR2+es8eJKcD07C2j0W0czQVyo9Hjqgr++rB0j8XEt/BrfOm0cLwdDAB1hoiGxEvlIQYFMHcvpGO2fHsVpSc5vrrCac1sbh8e1oeGA9HnzROUaJqOKEc3My7bLMVbwH/CaU80y7jdG75FlxXqCJD7iYRj6PMwkcIPR15ONX+DMTVAA+peTosvUKEHCrrSVS4Cv0GcpAhK7FiZqjHRSsbu7TmMMv2eEysnJcOHyihTxXPoVLDiksW8nQto/fNa76Bnq0xHBAPzJtZ28RQDZ2eZg705OAR2FsrRKv+KBVEWBwfnjEf1aPnPTRfxAoBQJFFH2wIUzr46YYTa8bK8QbiHjoWVHAVsq7LM8dEXP3EjztLMyh+OLrDZHlvlGiL32zNUjxR4qm+V4utK+fcEW7JQRnVELQNC3hxN+ajYDZF6NQLT8PAKyd04Bisx0zNm0ScE/oe55lBycLSL0NxMnlQdC9EEeQq2qXLF97H9dIOJhnHhSsCmrl9ddVO/L6qp3MS+L2UZUw5bm7gbKt4ets2N5+4SPsPrBZUeKIuaWsMqCsUq5FgqXZVdt/HvcFSOKD/IrlPmEVCJTMXGnLe7f4iVv0/I8TNckrpljl4ome/0DvZi5KXt+xHOib+gjktsFbpkZwkohUIgAXVCLVvepJ7ujESaWAcOlbEDPogLx/S+mr9GaTU+/F8CGLW6YrloDGrV4dU6AY5t2FkEao8R/Bit3o0SGOuX0pV0/HJvPD8P3TeZBD+CcIgD+cUxIPUnhdrigCvtZzgyoVkE8FRGh4uwvKxAb1tZftQ8oX6wJ+minZhBxzPKbrsNO4ngwmpgtHeAgifk3YzP5dx8BTeR8gMVnEs1CrASXQB2+XuKwg7aJnlnXgXBp+RNcEHLfhuqQ2g+B3fZyx2N1M/H86nGaPZHOEt0G16nl+tPEsqNryRr4gtaZXD6G6aPKnQyHtzQu/wXIONacGNtEq7e5G6dWGcGAG3Nq8LtwaVpHAaCNlLNFxOWmscOh7+OFLcafGltI/rC2d8dKPzu0IVmjdi9BttZEgt9O56n4Z7d9kXcgi/55vbIiIvZb8SNV61rmTU1HERDLbIFxKTf//uyVtBagO9SsMy4xmcxmmQfSiqioFMmPf7GAu93q85f20Vvthb7Xg8i9KWqL05zE4nExjMMlaqQ==-----END RSA PRIVATE KEY-----

servers:[{name:test-host-1> 10.164.76.16

certificate:-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----}> -----BEGIN CERTIFICATE-----MIIDKzCCAhOgAwIBAgIBADANBgkqhkiG9w0BAQsFADBZMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHT250YXJpbzEPMA0GA1UEBwwGT3R0YXdhMRYwFAYDVQQKDA1DaHJ5c2FsaXMtSVRTMQ8wDQYDVQQDDAY1NTAwOTEwHhcNMTgwOTE2MTY1MzQ0WhcNMjgwOTE3MTY1MzQ0WjBZMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHT250YXJpbzEPMA0GA1UEBwwGT3R0YXdhMRYwFAYDVQQKDA1DaHJ5c2FsaXMtSVRTMQ8wDQYDVQQDDAY1NTAwOTEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCqWCuY8XKej0wxcLZBc1/yxFRiM8hbsI6Ep3zD9tk3J1K+55wq80b0dZVsUOos80V2EtA3P6fnwigq1C/QhjGx9XTgjylqyrzoEbEbjHyPwMkAMOU4TormTv8WUU1L7HHtguHX9RxrtHmM0VKs5tTN9z9mGJupRcQy9NBB+YjCSPMGNqnbnIsmroUvtBl2tbCGr4JXLN6dAfBO7gzFEWjbU7XDVGfPxUD9f4SxIOQY7eC8mzGEVZQmUpmJIVSXFRnwWEYyYiGgQs4o4+JIRwvd4k1A1OdGDznB6qXUV5MTiF1VKTXmDPsOeXvMQokNM7uElIyQY0C1qz4PnxIPXKjAgMBAAEwDQYJKoZIhvcNAQELBQADggEBADMj1z9Du3Ch3k9ycAa8E2UXWXD+aHTxmn5bWpxANElHan8+BZkNPGnerpqsXIlnEtBoGk5gQV2PDMJ1lXLMqgDKeg2MhkHWaUiVBlE3UZE1aG0NOpmbz7w5o3QiIeWm/sav7EmXVIfHmE0Cg86MJKkDxGfdaOgKfwCXEqxiGElSM2YPuq021X7rUVDffcRBuZ/2NteusPee23DwNVxgQQA2zawbi9n6Zuas2pslM/iHhm/ftpCVzjsSzOy/L7PABisoxMAa2lyzB+7gfDp+8ZjTHxO5JlbHBNa2KDqmszYxo8tWkH8mgYhQ6+/HHR/mY9p8Daoq8Yi6dT+0qcZ3Y3A=-----END CERTIFICATE-----

{name:test-host-2> 10.164.76.16

certificate:-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----}]> -----BEGIN CERTIFICATE-----MIIDKzCCAhOgAwIBAgIBADANBgkqhkiG9w0BAQsFADBZMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHT250YXJpbzEPMA0GA1UEBwwGT3R0YXdhMRYwFAYDVQQKDA1DaHJ5c2FsaXMtSVRTMQ8wDQYDVQQDDAY1NTAwOTEwHhcNMTgwOTE2MTY1MzQ0WhcNMjgwOTE3MTY1MzQ0WjBZMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHT250YXJpbzEPMA0GA1UEBwwGT3R0YXdhMRYwFAYDVQQKDA1DaHJ5c2FsaXMtSVRTMQ8wDQYDVQQDDAY1NTAwOTEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCqWCuY8XKej0wxcLZBc1/yxFRiM8hbsI6Ep3zD9tk3J1K+55wq80b0dZVsUOos80V2EtA3P6fnwigq1C/QhjGx9XTgjylqyrzoEbEbjHyPwMkAMOU4TormTv8WUU1L7HHtguHX9RxrtHmM0VKs5tTN9z9mGJupRcQy9NBB+YjCSPMGNqnbnIsmroUvtBl2tbCGr4JXLN6dAfBO7gzFEWjbU7XDVGfPxUD9f4SxIOQY7eC8mzGEVZQmUpmJIVSXFRnwWEYyYiGgQs4o4+JIRwvd4k1A1OdGDznB6qXUV5MTiF1VKTXmDPsOeXvMQokNM7uElIyQY0C1qz4PnxIPXKjAgMBAAEwDQYJKoZIhvcNAQELBQADggEBADMj1z9Du3Ch3k9ycAa8E2UXWXD+aHTxmn5bWpxANElHan8+BZkNPGnerpqsXIlnEtBoGk5gQV2PDMJ1lXLMqgDKeg2MhkHWaUiVBlE3UZE1aG0NOpmbz7w5o3QiIeWm/sav7EmXVIfHmE0Cg86MJKkDxGfdaOgKfwCXEqxiGElSM2YPuq021X7rUVDffcRBuZ/2NteusPee23DwNVxgQQA2zawbi9n6Zuas2pslM/iHhm/ftpCVzjsSzOy/L7PABisoxMAa2lyzB+7gfDp+8ZjTHxO5JlbHBNa2KDqmszYxo8tWkH8mgYhQ6+/HHR/mY9p8Daoq8Yi6dT+0qcZ3Y3A=-----END CERTIFICATE-----

groups:[{label:test-group-1> HA

members:[test-serial-number-1> 1280780175975

test-serial-number-2]}> 1280780175978

{label:test-group-2>

members:[test-serial-number-3>

test-serial-number-4]}]}>
Creating user provided service luna in org testorg / space testspace as admin...
OK
PS C:\Users\Administrator> cf services
Getting services in org testorg / space testspace as admin...

name   service         plan   bound apps   last operation   broker   upgrade available
luna   user-provided

TIP: Please upgrade to CC API v2.138.0 or higher for individual service upgrades
PS C:\Users\Administrator>`

The service is created but i don't know whether it is working or not. I don’t have any idea to test/verify it.
Can someone please check if the steps are correct and tell any use case to verify that HSM is working correctly?

I tried to search a lot for its detailed documentations with end to end working example but I was not able to find any.

 Thanks in Advance.

**Comment by type4ranjan** [comment]
@nebhale Can you please assign this to person who could help me on this? Thanks

**Comment by dmikusa-pivotal** [comment]
Sorry for the delay here. Creating the service is only part of what's required here. You need to also deploy an application & bind the service you created to the application.

https://docs.cloudfoundry.org/devguide/services/managing-services.html#bind

When the service instance is bound to a Java app and you restage your application, the buildpack will run and the Luna support will execute. You'll see Luna mentioned in the output from the buildpack.

There's more information on using Luna here.

https://github.com/cloudfoundry/java-buildpack/blob/main/docs/framework-luna_security_provider.md

Hope that helps!
