### ISSUE TITLE
Use java-buildpack without app?

### ISSUE THREAD

**Issue by HansKre** [cloudfoundry/java-buildpack#845]
I'm trying to deploy neoj4 which requires JDK v11 and thus looking for a way to use the java-buildpack without providing an app.

I tried following, but it didn't work:

```
cf push my-graph -b java_buildpack_offline -c "mkdir -p target && neo4j.gz && tar -xf neo4j.gz --directory target && target/neo4j-community-4.2.1/bin/neo4j start"
cf set-env my-graph JBP_CONFIG_OPEN_JDK_JRE \
	'{ jre: { repository_root: "{default.repository.root}/openjdk-jdk/linux/x64", version: "15.0.1" } }'
cf my-graph restage
```

Any help would be highly appreciated.

**Comment by ekcasey** [comment]
@HansKre Unfortunately the Java Buildpack doesn't support this type of use case. It is specifically designed to build 12 factor apps. You would need to [`cf push` a docker image](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html) to get something like neo4j running as an app in CF.

I am going to close this issue but feel free to comment or reopen if you have any followup questions.
