### ISSUE TITLE
Multiple JREs in the offline package

### ISSUE THREAD

**Issue by ghaug** [cloudfoundry/java-buildpack#848]
Hi,

we are using the offline package of the Java Buildpack and have the problem that we need to bundle more than one JRE with it. We can't uncomment more than one JRE in the `components.yml` file and a download on deployment is not possible (disabled and no network anyway). We have a little hack in place that additionally bundles SapMachine JRE so our customers can select it if they wish. However, we would prefer a more elegant solution. 

I've made a tiny change that reads `ADD_TO_CACHE` during the bundling process and adds components to the offline cache that are not  specified in `components.yml`. Would there be any interest from your side that I create a pull request?

Thanks and best regards,
Gunter

**Comment by ekcasey** [comment]
@ghaug Thanks! This sounds like a feature that would be broadly useful to `java-buildpack` consumers. I wonder, would it be more intuitive to simply allow multiple JREs in `components.yml` to be uncommented?

**Comment by ghaug** [comment]
Yes, we could allow for multiple JREs in `components.yml` as well. However, we would need to specify a kind of a default JRE because manifests may not specify a JRE. Defining this simply by the order in `components.yml` is probably not a good idea. That's why I thought about this simple solution.

**Comment by ghaug** [comment]
Anyway, as there is general interest, I'll prepare a pull request so we have something to discuss about.

**Comment by ghaug** [comment]
I finally succeeded in creating this [pull request](https://github.com/cloudfoundry/java-buildpack/pull/852). Sorry for the delay.

**Comment by RealCLanger** [comment]
@ekcasey Is there any ETA for when somebody could have a look at this pull request resp. merge it? Thanks a lot in advance!

**Comment by dmikusa-pivotal** [comment]
The PR has been closed, so I'm going to close this issue. Feel free to reopen if there are still outstanding needs here.
