### ISSUE TITLE
Can you update the Azure Application Insights Agent to the latest version?

### ISSUE THREAD

**Issue by jojostation75** [cloudfoundry/java-buildpack#869]
Hi,

The currently Java buildback release say:

Dependency | Version |
|---|---|
Azure Application Insights Agent | 2.6.2 |

Can you update the Azure Application Insights Agent to the latest version, it like 3.0.3 [(InsightAgent-3.0.3)](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)

Thanks

**Comment by dmikusa-pivotal** [comment]
There was a similar request recently, https://github.com/cloudfoundry/java-buildpack/issues/620#issuecomment-824239986. To reiterate what I posted there, the buildpack currently supports both versions, it just defaults to 2.6.x. If you'd like to use 3.0, you can change the config to use it. 

If you are asking to change the default version, please let me know. That would be a larger decision as it could potentially break users' applications that are currently running on 2.6 (given 2.6 -> 3.0 is a major version bump).

**Comment by jojostation75** [comment]
Thanks dmikusa for the quick response.

Could you let me know how to "**change the config to use a certain dependency (e.g Azure Insight Agent) version (3.0) out of the default version**" or a link can guild through?

Much appreciated!

**Comment by dmikusa-pivotal** [comment]
Sorry. It was on the other comment, I should have copied all that through.

>If you wanted to pull in version 3, you could by modifying the [config file](https://github.com/cloudfoundry/java-buildpack/blob/main/config/azure_application_insights_agent.yml#L18). See [this section for instructions on how to modify config](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension) or you can `git clone`, check out a releases branch, modify the config file & build a version of the buildpack you can upload to Cloud Foundry with `cf create-buildpack.

You can basically modify the config file directly, then package up the modified bits into either an offline or online version, or you can use the env variables to change the version on the fly with an existing version of the buildpack. Because it's not the default, using env variables would require Internet access to download the version you set.

**Comment by jojostation75** [comment]
Thanks dmikusa for the detailed instruction! ! I will close this issue.

**Comment by jojostation75** [comment]
Hi dmikusa, Sorry to reopen it. I was following the 1st method to update **config file** by adding following in the manifest.yml
`env:`
      `JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ } }'`
      `JBP_CONFIG_AZURE_APPLICATION_INSIGHTS_AGENT: '{ version: 3.+ }'`

The JAVA version overwrite works fine. In deploy stage it shows:
`JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 ....`

However, in order to use Azure Insight Agent within app, it requires to add agent path to it. like
`JAVA_OPTS: -javaagent:((pathToAgent))/((name_of_package)).jar`

Can you help on:
1. How to find the **package path of build-in Azure insight agent** within this build-pack?
2. what is the package name of **build-in Azure insight agent**?
3. the default repo to fetch **build-in insight agent** is `repository_root: https://java-buildpack.cloudfoundry.org/azure-application-insights`. Do it support Insight Agent version 3+?

Thank you !

**Comment by dmikusa-pivotal** [comment]
For 1 & 2, you shouldn't need to do this. The buildpack will append the `-javaagent` argument if it's invoked correctly. Normally we have the requirements like this documented, but I don't see a page for Azure App Insights. Looking at the code, the agent should be downloaded & added if you have a bound service where the name contains `azure-application-insights` and there is an `instrumentation_key` credential. 

For 3, yes. The repository has both versions in it. See https://java-buildpack.cloudfoundry.org/azure-application-insights/index.yml

If you need more help, please post the full output of running `cf push` for your app  as well as the list of services bound to your app. Thanks

**Comment by jojostation75** [comment]
Thanks Dmikusa! The help really works!

When you say **Looking at the code**, I went through source code found on [Application Insights Java 3.0.4-BETA](https://github.com/Microsoft/ApplicationInsights-Java/releases)

Have some more questions:
1. How/Where did you find out it required a service name `azure-application-insights`? I searched the key words but nothing show up. I tired with different name and not working. So only with this name, the Agent works.
2. How/Where did you find out the service requires the key: `instrumentation_key` ? 

Since by reading the [Azure Insight Agent Doc](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent). It says using `APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=...` in the ENV or using `{
"connectionString": "InstrumentationKey=..."}` . But there is nothing says about `instrumentation_key` and how the value formatted

The two information  `azure-application-insights` and `instrumentation_key` you provided are keys to make it works. If you share some light how did you spot them?

Much appreciated!

**Comment by dmikusa-pivotal** [comment]
>How/Where did you find out it required a service name azure-application-insights? I searched the key words but nothing show up. I tired with different name and not working. So only with this name, the Agent works.
>How/Where did you find out the service requires the key: instrumentation_key ?

This is part of the buildpack, so the code here explains what detection requirements there are for this functionality. In the code, you can see it filtering by `azure-application-insights` and then checking for credential values of `instrumentation_key`.

https://github.com/cloudfoundry/java-buildpack/blob/main/lib/java_buildpack/framework/azure_application_insights_agent.rb#L46-L52

**Comment by jojostation75** [comment]
Thanks you @dmikusa-pivotal !! Much appreciated ! I will close the issue.

**Comment by jojostation75** [comment]
Hi @dmikusa-pivotal  sorry, one last question on this thread:

I overwrite the version with
`JBP_CONFIG_AZURE_APPLICATION_INSIGHTS_AGENT: '{ version: 3.0.3 }'`

but it downloading
` -----> Downloading Azure Application Insights Agent 3.0.3_BETA.3 from https://java-buildpack.cloudfoundry.org/azure-application-insights/azure-applic
ation-insights-3.0.3-BETA.3.jar (0.5s)
`

The [version](https://java-buildpack.cloudfoundry.org/azure-application-insights/index.yml) you shared before do contain 3.0.3 verison

**Question:** 
How to download the exactly the version? E.g 3.0.3 --> not 3.0.3-BETA.3

Thanks!

**Comment by dmikusa-pivotal** [comment]
> How to download the exactly the version? E.g 3.0.3 --> not 3.0.3-BETA.3

Apologizes. That looks like a bug in the version matcher. I'd expect it to pick the exact match, but the version matcher is doing something like this:

1. Iterate through the list
2. Filter on whatever matches the pattern you've defined both 3.0.3 and 3.0.3_BETA.3 match your filter
3. Then it picks the max as defined by the Ruby max function, which ends up being 3.0.3_BETA.3

I was playing around with the unit tests to see if I could get it to match just 3.0.3 but I haven't been able to get it to match. The version doesn't allow a fixed start/end like with Regex `^` or `$`.  Can you open a new issue for this?

**Comment by jojostation75** [comment]
@dmikusa-pivotal  Thanks for testing it!! Closed this thread and Open a new one.

**Comment by JulianMei** [comment]
Hi @dmikusa-pivotal, I'm a Microsoft engineer and I encountered this thread as part of my research on leveraging Application Insights for Java app logging on BTP. Your answers are really helpful! 
I have 2 follow-up questions regarding the approach you described: "Looking at the code, the agent should be downloaded & added if you have a bound service where the name contains azure-application-insights and there is an instrumentation_key credential."  Could you help clarify them? Thank you!
1. Is there restrictions on the type of the bound service? Can I use Application Logging service binding for this purpose?
2. how can I include the " instrumentation_key credential" in the bounded service? Is there a way to manually add the credential?

**Comment by dmikusa-pivotal** [comment]
>Is there restrictions on the type of the bound service? Can I use Application Logging service binding for this purpose?

There are not strong types of services on Cloud Foundry. It's all just JSON that gets exposed through VCAP_SERVICES. So when there's a description like `the name contains azure-application-insights and there is an instrumentation_key credential`, all that needs to happen is that those criteria are met and that will trigger this part of the buildpack to execute.

The name of your service is easy to control. When you create the service on CF you get to pick that, so just pick something that contains `azure-application-insights`. 

The credentials can be set by a service broker, in which case the user wouldn't do anything and the broker would need to set the `instrumentation_key`. You can also set credentials through a CF user-provided service (i.e. `cf cups`). This is a special service entry where the user defines the entire service, not just the name but all the credentials too. If a user takes this approach, then they would need to tell `cf cups` to add an `instrumentation_key` and provide their actual key as the value.

>how can I include the " instrumentation_key credential" in the bounded service? Is there a way to manually add the credential?

You probably want `cf cups my-azure-application-insights -p instrumentation_key`. That will then prompt you for the value , enter your actual key. Then bind the service to your app.
