### ISSUE TITLE
Single quotes added to appd application name

### ISSUE THREAD

**Issue by jeffaholmes** [cloudfoundry/java-buildpack#871]
The PR https://github.com/cloudfoundry/java-buildpack/pull/870 is causing application names to include single quotes at beginning and end, i.e.
my-app
is now
'my-app'
This is considered a new application name by AppDynamics so breaks any monitoring based on previous application name without quotes.

**Comment by dmikusa-pivotal** [comment]
I need more detail. How are you configuring your AppD service? What does `VCAP_SERVICES` look like for you? Thanks
