### ISSUE TITLE
Getting error while use Azul Zulu JDK in PCF microservices

### ISSUE THREAD

**Issue by ajay-dbs** [cloudfoundry/java-buildpack#883]
I need to delete the post

**Comment by dmikusa-pivotal** [comment]
The location to which you point the buildpack, i.e. `repository_root`, must be a valid repository. There is no `index.yml` (at least when I looked just now) at that location.

See https://github.com/cloudfoundry/java-buildpack/blob/main/docs/extending-repositories.md.

**Comment by dmikusa-pivotal** [comment]
Hmm, it looks like there used to be an `index.yml` at that location, but I don't see it any more. Let me ask around and see what I can find.

In the meantime, if you create your own `index.yml`, host it somewhere (doesn't matter) and point to the files at that location (i.e. https://cdn.azul.com/zulu/bin/zulu9.0.7.1-jdk9.0.7-linux_x64.tar.gz), you can work around this.

**Comment by ajay-dbs** [comment]
Hi Dmikusa,
I have followed below link to create the index.yml file - 
https://community.pivotal.io/s/article/How-do-I-use-an-Oracle-JVM-on-PWS?language=en_US

Content of index.yml file is - 
11.0.11: https://nexuscimgmt2.sgp.dbs.com:8443/nexus/repository/SRET/com/dbs/sret/AppD_zulu11.48.21-ca-jdk/11.0.11-linux_x64/AppD_zulu11.48.21-ca-jdk-11.0.11-linux_x64.gz

We have kept Azul Zulu jdk on nexus server and index.yml on another server. And in index.yml file pointing to the Azul zulu jdk.

We have used the below variables in manifest.yml of application- 
JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://nexuscimgmt2.sgp.dbs.com:8443/nexus/repository/SRET/com/dbs/sret/AppD_zulu11.48.21-ca-jdk/11.0.11-linux_x64/AppD_zulu11.48.21-ca-jdk-11.0.11-linux_x64.gz"}, {version: 11.0.+}]'
JBP_CONFIG_COMPONENTS '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

After build and restage the service, application started but not picked up Azul Zulu JDK.
Below are updated logs - 
Using manifest file cloudfoundry/ts/sg/uat.yml

 

Using stack cflinuxfs3...
OK
Updating app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK

 

Using route crui-ts-sg-api-oit.dev.apps.cs.sgp.dbs.com
Uploading crui-ts-sg-api-oit...
Uploading app files from: C:\Users\UDAYKI~1\AppData\Local\Temp\unzipped-app113438339
Uploading 4.1M, 1250 files
Done uploading
OK
Binding service crui_config to app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK
Binding service crui-credhub to app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK
Binding service crui-appdynamics to app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK
Binding service autoscale-uat to app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK

 

Stopping app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK

 

Starting app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
Downloading java_buildpack_offline...
Cell 43ff0961-ef04-484e-87fd-8ef4d604f87d creating container for instance 4fce2905-782c-4bbd-9274-4bb3b47d11a9
Cell 43ff0961-ef04-484e-87fd-8ef4d604f87d successfully created container for instance 4fce2905-782c-4bbd-9274-4bb3b47d11a9
Downloading build artifacts cache...
Downloaded build artifacts cache (131B)
Downloaded app package (192.1M)
[ConfigurationUtils]             WARN  User config value for 'jres' is not valid, existing property not present
-----> Java Buildpack v4.36 (offline) | https://github.com/cloudfoundry/java-buildpack.git#ebf9f057
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.2s)
       JVM DNS caching disabled in lieu of BOSH DNS caching
-----> Downloading Open JDK Like Memory Calculator 3.13.0_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-3.13.0-RELEASE.tar.gz (found in cache)
       Loaded Classes: 48444, Threads: 250
-----> Downloading AppDynamics Agent 21.1.0_31582 from https://packages.appdynamics.com/java/21.1.0.31582/AppServerAgent-21.1.0.31582.zip (found in cache)
       Expanding AppDynamics Agent to .java-buildpack/app_dynamics_agent (0.3s)
-----> Downloading Spring Auto Reconfiguration 2.11.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-2.11.0-RELEASE.jar (found in cache)
[ConfigurationUtils]             WARN  User config value for 'jres' is not valid, existing property not present
Exit status 0
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (131B)
Uploaded droplet (263.7M)
Uploading complete
Cell 43ff0961-ef04-484e-87fd-8ef4d604f87d destroying container for instance 4fce2905-782c-4bbd-9274-4bb3b47d11a9
Cell 43ff0961-ef04-484e-87fd-8ef4d604f87d successfully destroyed container for instance 4fce2905-782c-4bbd-9274-4bb3b47d11a9

 

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

 

App started

 


OK

 

App crui-ts-sg-api-oit was started using this command `JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -javaagent:$PWD/.java-buildpack/app_dynamics_agent/javaagent.jar -Dappdynamics.agent.applicationName=\"$(jq -r -n "$VCAP_APPLICATION | .space_name + \":\" + .application_name | @sh")\" -Dappdynamics.agent.tierName=crui-ts-sg-api-oit -Dappdynamics.agent.nodeName=$(jq -r -n "\"$APPD_CF_NODE_PREFIX\" + ($VCAP_APPLICATION | .application_name) + \":$CF_INSTANCE_INDEX\"") -Dappdynamics.agent.accountAccessKey=ab1f79bb-1720-46c4-b39c-db6e7f2d1a36 -Dappdynamics.agent.accountName=customer1 -Dappdynamics.controller.hostName=appdynamics_1.gtmuat.dbs.com -Dappdynamics.controller.port=8181 -Dappdynamics.controller.ssl.enabled=true -Dappdynamics.agent.uniqueHostId=$(jq -r -n "$VCAP_APPLICATION | .application_id + \":$CF_INSTANCE_INDEX\"") -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=56092 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher`

 

Showing health and status for app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK

 

requested state: started
instances: 1/1
usage: 2G x 1 instances
urls: crui-ts-sg-api-oit.dev.apps.cs.sgp.dbs.com
last uploaded: Wed Jun 9 14:04:14 UTC 2021
stack: cflinuxfs3
buildpack: java_buildpack_offline

**Comment by dmikusa-pivotal** [comment]
> We have used the below variables in manifest.yml of application-
JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://nexuscimgmt2.sgp.dbs.com:8443/nexus/repository/SRET/com/dbs/sret/AppD_zulu11.48.21-ca-jdk/11.0.11-linux_x64/AppD_zulu11.48.21-ca-jdk-11.0.11-linux_x64.gz"}, {version: 11.0.+}]'
JBP_CONFIG_COMPONENTS '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

OK, this needs to be slightly different. The `repository_root` points to the folder where your `index.yml` is located. So the URL that the JBP uses to download the index.yml is `repository_root/index.yml`.

The JBP will then read index.yml, pick the latest version matching the version filter you specify and download the resource referenced from index.yml for that version.

**Comment by mells82** [comment]
Hi Dmikusa,

So does that mean both the Zulu JDK as well as the index.yml should be in the same location?

**Comment by mells82** [comment]
Ok I see what you are saying, the JBP_CONFIG_ZULU_JRE should be setup as

JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "<insert-full-URL-to-index-yml-on-another-server>"}, {version: 11.0.+}]'

**Comment by dmikusa-pivotal** [comment]
It needs to be the full URL to the folder/directory where the index.yml resides. The buildpack will append `/index.yml` to it when it generates the URL to download the index.yml file. So your `repository_root` should *not* end with `/index.yml`.

**Comment by ajay-dbs** [comment]
Hi Team,

Application team has used this variable in manifest.yml file.
JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://appdmom.uat.dbs.com:8051/pcf"}, {version: 11.0.+}]'
JBP_CONFIG_COMPONENTS '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

Here the full URL of index.yml is -- https://appdmom.uat.dbs.com:8051/pcf/index.yml

But application is not picking up Azul Zulu JDK.

Please find the below logs and suggest.

Stopping app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK
Starting app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
Downloading java_buildpack_offline...
Downloaded java_buildpack_offline
Cell e926d44c-97c2-4763-9bbc-525c1765aa47 creating container for instance 3f871cba-da64-4652-9914-214740204dc0
Cell e926d44c-97c2-4763-9bbc-525c1765aa47 successfully created container for instance 3f871cba-da64-4652-9914-214740204dc0
Downloading app package...
Downloading build artifacts cache...
Downloaded build artifacts cache (131B)
Downloaded app package (192.1M)
[ConfigurationUtils] WARN User config value for 'jres' is not valid, existing property not present
-----> Java Buildpack v4.36 (offline) | https://github.com/cloudfoundry/java-buildpack.git#ebf9f057
-----> Downloading Jvmkill Agent 1.16.0_RELEASE from https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0-RELEASE.so (found in cache)
-----> Downloading Open Jdk JRE 1.8.0_282 from https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/bellsoft-jre8u282%2B8-linux-amd64.tar.gz (found in cache)
Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.6s)
JVM DNS caching disabled in lieu of BOSH DNS caching
-----> Downloading Open JDK Like Memory Calculator 3.13.0_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-3.13.0-RELEASE.tar.gz (found in cache)
Loaded Classes: 48444, Threads: 250
-----> Downloading AppDynamics Agent 21.1.0_31582 from https://packages.appdynamics.com/java/21.1.0.31582/AppServerAgent-21.1.0.31582.zip (found in cache)
Expanding AppDynamics Agent to .java-buildpack/app_dynamics_agent (0.4s)
-----> Downloading Client Certificate Mapper 1.11.0_RELEASE from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.11.0-RELEASE.jar (found in cache)
-----> Downloading Container Security Provider 1.18.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-security-provider/container-security-provider-1.18.0-RELEASE.jar (found in cache)
-----> Downloading Spring Auto Reconfiguration 2.11.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-2.11.0-RELEASE.jar (found in cache)
[ConfigurationUtils] WARN User config value for 'jres' is not valid, existing property not present
Exit status 0
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (131B)
Uploaded droplet (263.7M)
Uploading complete
Cell e926d44c-97c2-4763-9bbc-525c1765aa47 stopping instance 3f871cba-da64-4652-9914-214740204dc0
Cell e926d44c-97c2-4763-9bbc-525c1765aa47 destroying container for instance 3f871cba-da64-4652-9914-214740204dc0
Cell e926d44c-97c2-4763-9bbc-525c1765aa47 successfully destroyed container for instance 3f871cba-da64-4652-9914-214740204dc0
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running
App started

OK
App crui-ts-sg-api-oit was started using this command `JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -javaagent:$PWD/.java-buildpack/app_dynamics_agent/javaagent.jar -Dappdynamics.agent.applicationName=\"$(jq -r -n "$VCAP_APPLICATION | .space_name + \":\" + .application_name | @sh")\" -Dappdynamics.agent.tierName=crui-ts-sg-api-oit -Dappdynamics.agent.nodeName=$(jq -r -n "\"$APPD_CF_NODE_PREFIX\" + ($VCAP_APPLICATION | .application_name) + \":$CF_INSTANCE_INDEX\"") -Dappdynamics.agent.accountAccessKey=ab1f79bb-1720-46c4-b39c-db6e7f2d1a36 -Dappdynamics.agent.accountName=customer1 -Dappdynamics.controller.hostName=appdynamics_1.gtmuat.dbs.com -Dappdynamics.controller.port=8181 -Dappdynamics.controller.ssl.enabled=true -Dappdynamics.agent.uniqueHostId=$(jq -r -n "$VCAP_APPLICATION | .application_id + \":$CF_INSTANCE_INDEX\"") -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=56092 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher`
Showing health and status for app crui-ts-sg-api-oit in org crui / space uat as udaykirans...
OK
requested state: started
instances: 1/1
usage: 2G x 1 instances
urls: crui-ts-sg-api-oit.dev.apps.cs.sgp.dbs.com
last uploaded: Thu Jun 10 12:48:08 UTC 2021
stack: cflinuxfs3
buildpack: java_buildpack_offline
state since cpu memory disk details
#0 running 2021-06-10 06:22:16 PM 327.7% 1.1G of 2G 382.4M of 2G

Regards,
Ajay

**Comment by mells82** [comment]
It seems that it is picking the JVM from this path  https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/bellsoft-jre8u282%2B8-linux-amd64.tar.gz. Where is this configured?

**Comment by dmikusa-pivotal** [comment]
@ajay-dbs - This is likely the reason:

>[ConfigurationUtils] WARN User config value for 'jres' is not valid, existing property not present

It's ignoring part of your configuration. Your `JBP_CONFIG_COMPONENTS` looks OK to me, but you're going to want to look more closely at what is going on there. It is not applying that part of the config, so it's not picking your desired JDK.

**Comment by mells82** [comment]
Is it because of a missing ":" between JBP_CONFIG_COMPONENTS and the value ?

Should it be JBP_CONFIG_COMPONENTS: '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

**Comment by mells82** [comment]
> Hi Team,
> 
> Application team has used this variable in manifest.yml file.
> JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://appdmom.uat.dbs.com:8051/pcf"}, {version: 11.0.+}]'
> JBP_CONFIG_COMPONENTS '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

@ajay-dbs since you are adding the env variables in a manifest.yml , it seems the missing colon maybe the problem. Please fix it as 

JBP_CONFIG_COMPONENTS: '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

**Comment by mells82** [comment]
> [Buildpack] ERROR Finalize failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for [https://cdn.azul.com/zulu/bin/index.yml>](https://cdn.azul.com/zulu/bin/index.yml%3E)
> Zulu JRE error: Unable to find cached file for https://cdn.azul.com/zulu/bin/index.yml

BTW the link to https://cdn.azul.com/zulu/bin/index.yml has been restored now.

**Comment by ajay-dbs** [comment]
Hi Mells82,
Application team has used below variables in manifest.yml file and got the error.
Variables:
JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://appdmom.uat.dbs.com:8051/pcf"}, {version: 11.0.+}]'
JBP_CONFIG_COMPONENTS: '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

Error:
[ERR] [ConfigurationUtils] WARN User config value for 'version' is not valid, existing property not present
2021-06-11T13:39:44.508+05:30 [STG/0] [ERR] [Buildpack] ERROR Detect failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://appdmom.uat.dbs.com:8051/pcf/index.yml>
2021-06-11T13:39:44.508+05:30 [STG/0] [ERR] Zulu JRE error: Unable to find cached file for https://appdmom.uat.dbs.com:8051/pcf/index.yml
2021-06-11T13:39:47.484+05:30 [STG/0] [ERR] stat /tmp/buildpacks/674495fe521621eeb364a353eb511ee3/bin/detect: no such file or directory
2021-06-11T13:39:47.505+05:30 [STG/0] [OUT] -----> Nothing to compile
2021-06-11T13:39:47.511+05:30 [STG/0] [ERR] No start command specified by buildpack or via Procfile.
2021-06-11T13:39:47.511+05:30 [STG/0] [ERR] App will not start unless a command is provided at runtime.

Regards,
Ajay

**Comment by dmikusa** [comment]
>[ERR] [ConfigurationUtils] WARN User config value for 'version' is not valid, existing property not present

Is a different but similar error. It seems to now be accepting `jres` which is good. You can see it's actually running the Zulu container now too.

In this case, it now doesn't like the part where you're trying to set  the version to 11.0.+. What you have there isn't quite right.

>JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://appdmom.uat.dbs.com:8051/pcf"}, {version: 11.0.+}]'

should be 

```
JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://appdmom.uat.dbs.com:8051/pcf", version: 11.0.+}]'
```

The `version` and `repository_root` are on the same `jre` object. When in doubt, you can always look at the associated [`config/`](https://github.com/cloudfoundry/java-buildpack/tree/main/config) file. The `JBP_CONFIG_*` config you add, needs to match the format of the config file, as it gets overlaid on top of the config. 

See the structure for Zulu: https://github.com/cloudfoundry/java-buildpack/blob/main/config/zulu_jre.yml#L22-L24

**Comment by ajay-dbs** [comment]
Hi Team,
Application team has used the below variables in manifest.yml file but still throwing the error.

JBP_CONFIG_ZULU_JRE: '[jre: {repository_root: "https://appdmom.uat.dbs.com:8051/pcf", version: 11.0.+}]'
JBP_CONFIG_COMPONENTS: '{jres: ["JavaBuildpack::Jre::ZuluJRE"]}'

Error:-
021-06-14T13:14:15.960+05:30 [STG/0] [ERR] [Buildpack] ERROR Detect failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://appdmom.uat.dbs.com:8051/pcf/index.yml>

2021-06-14T13:14:15.960+05:30 [STG/0] [ERR] Zulu JRE error: Unable to find cached file for https://appdmom.uat.dbs.com:8051/pcf/index.yml
2021-06-14T13:14:16.940+05:30 [STG/0] [ERR] stat /tmp/buildpacks/674495fe521621eeb364a353eb511ee3/bin/detect: no such file or directory
2021-06-14T13:14:16.952+05:30 [STG/0] [OUT] -----> Nothing to compile
2021-06-14T13:14:16.956+05:30 [STG/0] [ERR] No start command specified by buildpack or via Procfile.
2021-06-14T13:14:16.956+05:30 [STG/0] [ERR] App will not start unless a command is provided at runtime.

Regards,
Ajay

**Comment by dmikusa-pivotal** [comment]
>021-06-14T13:14:15.960+05:30 [STG/0] [ERR] [Buildpack] ERROR Detect failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://appdmom.uat.dbs.com:8051/pcf/index.yml>

I recall seeing something like this in the past if the cache got messed up with the app. Try pushing your app under a new name like "my-cool-app-2" or something that's unique & new. If that fixes it, you'll either need to delete and re-push your app or have your administrator clear the buildpacks blobstore cache.

https://apidocs.cloudfoundry.org/16.13.0/blobstores/delete_all_blobs_in_the_buildpack_cache_blobstore.html

Note the latter will clear the cache for *all* buildpacks. While this is not destructive, it will force all buildpacks to redownload all resources the next time an application is staged.

**Comment by ajay-dbs** [comment]
Hi Daniel,

We have tried to clear cache and also tried to deploy app with completely new name as well as route. Still the same issue.

Downloading app package...
   WARNING: buildpack script '/bin/detect' is not executable
   [Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://zulu-index-file.dev.apps.cs.sgp.dbs.com/index.yml>
   Zulu JRE error: Unable to find cached file for https://zulu-index-file.dev.apps.cs.sgp.dbs.com/index.yml
   stat /tmp/buildpacks/674495fe521621eeb364a353eb511ee3/bin/detect: no such file or directory
   -----> Nothing to compile
   No start command specified by buildpack or via Procfile.
   App will not start unless a command is provided at runtime.
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading droplet...
   Uploading build artifacts cache...
   Uploaded build artifacts cache (131B)
   Uploaded droplet (24M)
   Uploading complete
   Cell 9f9105dc-e8ca-40ce-a685-83e92e88670f stopping instance a485e181-a0e0-4cc7-98e4-3a770ff48d41
   Cell 9f9105dc-e8ca-40ce-a685-83e92e88670f destroying container for instance a485e181-a0e0-4cc7-98e4-3a770ff48d41
   Cell 9f9105dc-e8ca-40ce-a685-83e92e88670f successfully destroyed container for instance a485e181-a0e0-4cc7-98e4-3a770ff48d41
Error staging application: Staging error: Start command not specified
FAILED

Even tried to put both files(Azul Zulu JDK and index.yml) in different location in same directory :  https://zulu-index-file.dev.apps.cs.sgp.dbs.com/ but still the same issue.


Regards,
Ajay

**Comment by dmikusa-pivotal** [comment]
>We have tried to clear cache and also tried to deploy app with completely new name as well as route. Still the same issue.

This will normally fix this type of problem, so it's good to know it's not helping here. It probably means there is something different happening.

```
WARNING: buildpack script '/bin/detect' is not executable
[Buildpack] ERROR Detect failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://zulu-index-file.dev.apps.cs.sgp.dbs.com/index.yml>
Zulu JRE error: Unable to find cached file for https://zulu-index-file.dev.apps.cs.sgp.dbs.com/index.yml
stat /tmp/buildpacks/674495fe521621eeb364a353eb511ee3/bin/detect: no such file or directory
```

What worries me, besides the caching error, is the WARNING about `/bin/detect` and the `stat: no such file or directory error. Those should happen, and wouldn't happen with the buildpacks that we package with releases.

Where are you getting your buildpack? Are you downloading it from the Releases page & uploading it to CF? Are you using a URL to the github page? If so, what is the exact URL? Are you getting the buildpack from somewhere else? Are you packaging your own buildpack? If so, please try using the one from the Releases page or another known working buildpack as a baseline test to see if that works as expected, and also please indicate how you are packaging up the buildpack? Any additional details you can provide might help to spot the issue or help with reproducing the issue.

Please continue to push as a new app name while you continue to test because we want to ensure that we're ruling out caching issues. 

Thanks

**Comment by dmikusa-pivotal** [comment]
A couple more questions... Was this working previously and broke recently? If so, what has changed recently? Did you upgrade buildpack versions? Did you change files on your server hosting Zulu? Were there new Zulu updates put onto your server? If it has never worked or this is the first time you're trying it, let us know that as well. 

Thanks

**Comment by ajay-dbs** [comment]
HI Daniel,

We have downloaded java offline buildpack from pivortal and kept in PCF repository and then use buildpack from PCF repository.

This is the first time we are trying to run app with Azul Zulu JDK. By default oracle JDK is used with Bellsoft VM and this Bellsoft VM not supporting Object Instance Tracking. So we are trying to use Azul Zulu JDK.

We have followed below link to change the JDK.
https://community.pivotal.io/s/article/How-do-I-use-an-Oracle-JVM-on-PWS?language=en_US

Regards,
Ajay

**Comment by ajay-dbs** [comment]
Hi Daniel,

Buildpack is bundled with TAS release. It is the JAVA BUILDPACK OFFLINE Latest version. Not using github page. We are running this in offline environment.
Currently we are on TAS 2.9.20 version.

Regards,
Ajay

**Comment by RageZBla** [comment]
@mells82 I think the content of `index.yml` should be 

```
---
1.8.0_212: https://cdn.azul.com/zulu/bin/zulu8.38.0.13-ca-jre8.0.212-linux_x64.tar.gz
1.8.0_222: https://cdn.azul.com/zulu/bin/zulu8.40.0.25-ca-jre8.0.222-linux_x64.tar.gz
1.8.0_232: https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-jre8.0.232-linux_x64.tar.gz
1.8.0_242: https://cdn.azul.com/zulu/bin/zulu8.44.0.11-ca-jre8.0.242-linux_x64.tar.gz
1.8.0_252: https://cdn.azul.com/zulu/bin/zulu8.46.0.19-ca-jre8.0.252-linux_x64.tar.gz
1.8.0_265: https://cdn.azul.com/zulu/bin/zulu8.48.0.53-ca-jre8.0.265-linux_x64.tar.gz
1.8.0_275: https://cdn.azul.com/zulu/bin/zulu8.50.0.51-ca-jre8.0.275-linux_x64.tar.gz
1.8.0_282: https://cdn.azul.com/zulu/bin/zulu8.52.0.23-ca-jre8.0.282-linux_x64.tar.gz
1.8.0_292: https://cdn.azul.com/zulu/bin/zulu8.54.0.21-ca-jre8.0.292-linux_x64.tar.gz
11.0.3: https://cdn.azul.com/zulu/bin/zulu11.31.11-ca-jre11.0.3-linux_x64.tar.gz
11.0.4: https://cdn.azul.com/zulu/bin/zulu11.33.15-ca-jre11.0.4-linux_x64.tar.gz
11.0.5: https://cdn.azul.com/zulu/bin/zulu11.35.15-ca-jre11.0.5-linux_x64.tar.gz
11.0.6: https://cdn.azul.com/zulu/bin/zulu11.37.17-ca-jre11.0.6-linux_x64.tar.gz
11.0.7: https://cdn.azul.com/zulu/bin/zulu11.39.15-ca-jre11.0.7-linux_x64.tar.gz
11.0.8: https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-jre11.0.8-linux_x64.tar.gz
11.0.9: https://cdn.azul.com/zulu/bin/zulu11.43.55-ca-jre11.0.9.1-linux_x64.tar.gz
11.0.10: https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jre11.0.10-linux_x64.tar.gz
11.0.11: https://cdn.azul.com/zulu/bin/zulu11.48.21-ca-jre11.0.11-linux_x64.tar.gz
```

removing the https create issue where the buildpack would not download the jre.

**Comment by dmikusa-pivotal** [comment]
>We have downloaded java offline buildpack from pivortal and kept in PCF repository and then use buildpack from PCF repository.
>This is the first time we are trying to run app with Azul Zulu JDK. By default oracle JDK is used with Bellsoft VM and this Bellsoft VM not supporting Object Instance Tracking. So we are trying to use Azul Zulu JDK.

OK, thanks for this info. Things are making more sense now.

The way that the Tanzu buildpack is packaged, it is done in "offline" mode. [See here, we run this script to package it](https://github.com/cloudfoundry/java-buildpack/blob/main/ci/create-release.sh#L13).

When in "offline" mode, you only get what is packaged into the bundle. The JBP cannot download other things. 

From the docs for "offline":

>It packages the latest version of each dependency (as configured in the config/ directory) and disables remote_downloads. 

https://github.com/cloudfoundry/java-buildpack/#offline-package

It does this because it's meant to run in an offline environment with no Internet access.

**Comment by dmikusa-pivotal** [comment]
I tried in a lab with an offline JBP and I get exactly the same error as you:

```
   2021-06-17T15:21:56.72-0400 [STG/0] ERR [Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: Zulu JRE error: Unable to find cached file for https://cdn.azul.com/zulu/bin/index.yml>
   2021-06-17T15:21:56.72-0400 [STG/0] ERR Zulu JRE error: Unable to find cached file for https://cdn.azul.com/zulu/bin/index.yml
   2021-06-17T15:21:56.72-0400 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 1
```

This is because that file doesn't exist in the offline cache and in offline mode, it will only look in the cache.

If you want to use Azul Zulu in an offline buildpack, you need to package the buildpack yourself with Zulu in it. Otherwise, you need to use an online version of the buildpack.

Using the online buildpack works, but as @RageZBla said the `index.yml` needs to be formatted correctly. At the moment, the index.yml at https://cdn.azul.com/zulu/bin/index.yml isn't formatted correctly. It's missing the protocol, which causes issues. Make sure that your `index.yml` is structured like the example in @RageZBla's comment.

**Comment by sgrinev** [comment]
thanks for the report, index.yml has been updated: https://cdn.azul.com/zulu/bin/index.yml

**Comment by ajay-dbs** [comment]
Hi Team,

We can't use https://cdn.azul.com/zulu/bin/index.yml becasue this is not accessible in PCF due to no internet connectivity.
@sgrinev, can you please package/customize the offline buildpack with Zulu entry as suggested by Daniel and share?

Regards,
Ajay

**Comment by dmikusa-pivotal** [comment]
@ajay-dbs If you are in an offline environment, you need to package the buildpack yourself. For someone else to do it for you, requires legal clearance due to the requirements of redistributing software. Not to mention, the security aspects of distributing trusted software. The easiest way forward is to package the buildpack yourself.

The [process is documented here](https://github.com/cloudfoundry/java-buildpack#building-packages). You do need to package from a computer that has Internet access because it needs to download the dependencies, however, it's only a couple of commands and shouldn't take more than a few minutes with a reasonably fast Internet connection.

**Comment by ajay-dbs** [comment]
Pl

**Comment by ajay-dbs** [comment]
Hi Team,

Please delete this support ticket ASAP. I will be very grateful to you.

Regards,
Ajay
