### ISSUE TITLE
Tomcat 10?

### ISSUE THREAD

**Issue by pvarga88** [cloudfoundry/java-buildpack#885]
Tomcat 10 is required for applications that are built for JakartaEE 9 (jakartaee. namespace instead of javax. )
https://tomcat.apache.org/download-10.cgi

Any plan yet for when  Tomcat 10 will be supported? It's not in the listing:
http://download.pivotal.io.s3.amazonaws.com/tomcat/index.yml

**Comment by dmikusa-pivotal** [comment]
I can add it to the index.yml. I do not want to make it default though, so the buildpack will stick with Tomcat 9 as the default. Adding it to the index would allow you to select Tomcat 10, if you want it though. Is that sufficient for your needs?

**Comment by pvarga88** [comment]
Yes, please! If we can configure it through JBP_CONFIG_TOMCAT that's perfect.

**Comment by dmikusa-pivotal** [comment]
OK, it'll take a little work on our CI system, but I will make this happen. My guess would be sometime next week or the following. I'll let you know when it's done.

**Comment by pvarga88** [comment]
Sounds good. Thanks! Looking forward to it.

**Comment by dmikusa-pivotal** [comment]
Tomcat 10 is now in the index.yml. You should now be able to opt into using it with `JBP_CONFIG_TOMCAT`. Please give it a try.
