### ISSUE TITLE
Memory Calculations are wrong for Datadog Javaagent

### ISSUE THREAD

**Issue by tylerbenson** [cloudfoundry/java-buildpack#887]
The Datadog Javaagent uses a custom classloader to avoid exposing private classes onto the system classpath.  This includes renaming class files with a custom class suffix (`.classdata`).  How can we make it so the memory calculations are more accurate?

cc @dmikusa-pivotal

**Comment by dmikusa-pivotal** [comment]
Thanks for opening this issue. I have this on the roadmap scheduled to be implemented for the next release of the Java buildpack.

**Comment by luke-perry** [comment]
@dmikusa-pivotal Awesome!! :) When is the next release scheduled of the Buildpack (date or general timeframe)?

**Comment by dmikusa-pivotal** [comment]
We are planning to cut the next release shortly after the next quarterly Java updates, which will be the week of 7/19/2021. Exactly when, depends on when that week the upstream vendors cut their releases of OpenJDK, but I hope to have it out by the Friday of that week or Mon next week at the absolute latest.

**Comment by luke-perry** [comment]
Thanks for the update!

**Comment by dmikusa-pivotal** [comment]
OK, lookinig through one of the agent JARs, I see the files mentioned.

```
> unzip -l dd-java-agent-0.82.0.jar | grep -o -e '\.class$' -e '\.classdata' | sort | uniq -c
 345 .class
7092 .classdata
```

Without the agent enabled, I see the output as:

```
  Loaded Classes: 27358, Threads: 250

   start command:   JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc)
         -Djava.ext.dirs= -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" &&
         CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=27488
         -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" &&
         MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp
         $PWD/.:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.18.0_RELEASE.jar org.springframework.boot.loader.JarLauncher
```

From digging through the buildpack, it's actually calculating the count twice. Once right after it installs the memory calculator, that is where you see the `Loaded Classes: xxxx` (compile). It then does it a second time (release) when it generates the start command. In this case, without the DataDog agent enabled it prints a number that's very close, 27488 (+130 classes).

With the DataDog agent enabled:

```
Loaded Classes: 27358, Threads: 250

start command:   JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc)
                 -javaagent:$PWD/.java-buildpack/datadog_javaagent/datadog_javaagent-0.82.0.jar -Ddd.service=\"spring-music\" -Ddd.version=735d6e7a-6e12-4ed4-aaf3-5b5c29baa2be
                 -Djava.ext.dirs= -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" &&
                 CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=30091
                 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" &&
                 MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp
                 $PWD/.:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.18.0_RELEASE.jar org.springframework.boot.loader.JarLauncher
```

I get the same initial class count, which is expected. That's going to be for the JVM + my app. The start command now is different. It's including the DataDog classes (it's not directly + 7437 classes because the total class count is then multiplied by 0.35). If you take the difference though, 30091-27358 you get 2773. Divide that by 0.35, and you end up with 7808. That is roughly the growth I'd expect with the DotaDog agent added. 

I also did a one-off test where I logged the JAR files being inspeced & their class counts:

```
   [OpenJDKLikeMemoryCalculator]    ERROR archive: /tmp/app/.java-buildpack/datadog_javaagent/datadog_javaagent-0.82.0.jar -> 345
   [OpenJDKLikeMemoryCalculator]    ERROR archive: /tmp/app/.java-buildpack/datadog_javaagent/datadog_fakeclasses.jar -> 7092
```

You can see it is finding & counting the fake jar I added and the fake classes to represent the `.classdata` files.

I'll have a PR for this up shortly.

**Comment by dmikusa-pivotal** [comment]
@tylerbenson @luke-perry I have a PR up with what looks like a fix in my tests. It's bumping up the class count as I described above. Can you please give it a try and let me know your feedback? If all looks good, I'll merge it & we'll have it in the upcoming release.

https://github.com/cloudfoundry/java-buildpack/pull/890

**Comment by luke-perry** [comment]
@dmikusa-pivotal Happy to try it out. How do we package the Buildpack from your branch to try it out in our Foundation with a test deployment?

**Comment by dmikusa-pivotal** [comment]
@luke-perry you can `git clone` and check out my PR's branch `datadog_metaspace_fix`, then use [these instructions to package](https://github.com/cloudfoundry/java-buildpack#building-packages) and then `cf create-buildpack` or you can use `cf push -b https://github.com/cloudfoundry/java-buildpack#datadog_metaspace_fix`. That will tell it to pull down the specific testing branch associated with my PR.

**Comment by luke-perry** [comment]
@dmikusa-pivotal We are having issues bundling it ourselves, could you possibly post the zip here?

**Comment by dmikusa-pivotal** [comment]
Did you try the second option? You don't need to package it so long as your CF environment has Internet access.

**Comment by dmikusa-pivotal** [comment]
@luke-perry Did you have a chance to test this? We'll be cutting a release for the JBP Mon or Tue next week, so this week is the last chance to get in feedback as I plan to merge the PR prior to the release. Thanks!

**Comment by luke-perry** [comment]
We were able to get the Buildpack deployed and are validating now!

**Comment by dmikusa-pivotal** [comment]
@luke-perry Excellent! Everything looking OK? We're coming down to the wire here. I'll need to get this merged tomorrow. Thanks!

**Comment by luke-perry** [comment]
@dmikusa-pivotal Looks like we've seen the issue occur with an application using the updated buildpack, so it seems the fix might not resolve this issue. We're double validating right now to ensure nothing else was in play.

**Comment by dmikusa-pivotal** [comment]
Sure. The thing to validate, and if you could provide confirmation/output, is if running the PR branch results in a larger class count and thus a larger metaspace allocation. See the output from [this post](https://github.com/cloudfoundry/java-buildpack/issues/887#issuecomment-873228927).

It's difficult to say 100% that this will solve all OOME: Metaspace issues, but if it's increasing the size of the class count, then we're increasing the metaspace allocation and that's what we want to see.

If that's not enough metaspace, we could look at tuning things more. Right not it's adding a 1-to-1 amount of fake classes, so for every `.classdata` file, there's one fake `.class` file added. We could ramp this up if you need more, so we could add the fake classes in a ratio of 1.5-to-1 or 2-to-1, which would give a larger allocation for metaspace. Let me know if you'd like to go that route, it's a small change.
