### ISSUE TITLE
Please delete support ticket - #883

### ISSUE THREAD

**Issue by ajay-dbs** [cloudfoundry/java-buildpack#888]
Hi Team,

Please delete this ticket - Getting error while use Azul Zulu JDK in PCF microservices
#883 ASAP. There is some confidential data in this ticket so requesting to delete this.

I will be very grateful to you.

Regards,
Ajay

**Comment by dmikusa-pivotal** [comment]
This is not a support ticket system. It's the public issues repository for the Java buildpack. I don't think we can delete the issue, but you can edit or delete your individual posts. You control your posts. If you click the "..." at the top right corner of your post, there should be an edit & delete option.

**Comment by dmikusa-pivotal** [comment]
I did a quick pass and sanitized posts where I saw domain names being used. If there is something else you want to sanitize, let me know.

**Comment by ajay-dbs** [comment]
Hi Daniel,

Thanks for sanitize the domain name entry.
Please also delete ajay-dbs entry from post.

Regards,
Ajay
