### ISSUE TITLE
Datadog Buildpack Detektion is Broken

### ISSUE THREAD

**Issue by Noxaro** [cloudfoundry/java-buildpack#897]
Hi,

with the latest release the detection of the Datadog Application Monitoring Buildpack seems to be broken.
After a restage with Datadog_Application_Monitoring(latest) and Java_Buildpack(latest) a error comes up with the text: "[DatadogJavaagent] ERROR Datadog Buildpack is required, but not found".

With that in mind i took a look into the source code and for me it seems that the Datadog folder name is wrong:
[Diff](https://github.com/cloudfoundry/java-buildpack/compare/v4.39...v4.40#diff-147cc19acd8e3446f89b75f550983e4a7ad9904d1516d0944c7b24cb15ace0c5R30)
The leading dot should not be there.

The folder structure in a running cloudfoundry spring boot app looks like the following: (/home/vcap/app)
drwxr-xr-x 4 vcap vcap  71 Jul 22 09:32 BOOT-INF
drwxr-xr-x 6 vcap vcap 141 Jul 22 09:33 datadog
drwxr-xr-x 6 vcap vcap 115 Jul 22 09:32 .java-buildpack
drwxr-xr-x 3 vcap vcap  80 Jul 22 09:32 META-INF
drwxr-xr-x 3 vcap vcap  29 Feb  1  1980 org
drwxr-xr-x 2 vcap vcap  85 Jul 22 09:32 .profile.d

Best Regards
Fabian

**Comment by dmikusa-pivotal** [comment]
You need to either a.) update your DataDog buildpack or b.) use an older Java buildpack. The upstream buildpack changed the name of the folder. 

Apologizes. I should have listed this in the release notes. I will update them with that info.

**Comment by dmikusa-pivotal** [comment]
See https://github.com/DataDog/datadog-cloudfoundry-buildpack/commit/fec40fe9de492beedb7234e586f904841070dc1b#diff-a64a7d9b82578ca3053416d56631a61e0ceabed87619415663030e3842429e05

**Comment by Noxaro** [comment]
Ok good to know. 
But cloud you please sync such a change with the datadog buildpack or make it also compatible with both versions of it? 
Because this Datadog change is currently not released.

**Comment by dmikusa-pivotal** [comment]
Sorry, I thought they had released that when I was testing. I can make it check both.

I don't have the exact time frame, but we should have a release shortly. We're waiting on the next Java 16 releases. I'll make sure this is included into that release.

**Comment by Noxaro** [comment]
ok thanks  👍 
We will pin the java buildpack version until the fix is released.

**Comment by dmikusa-pivotal** [comment]
Fix committed. As mentioned, we should have a new release of the JBP as soon as the latest Java 16 releases are available from Bellsoft Liberica, which should be any day now. 

You can test by pointing to `cf push -b https://github.com/cloudfoundry/java-buildpack`. This is *only* recommended for testing purposes though as that will run the main branch, not a tagged release.

**Comment by basiszwo** [comment]
FYI: there has been a new release 4.23.0 of the datadog-cloudfoundry-buildpack which includes the missing change for the changed datadog agent directory. See https://github.com/DataDog/datadog-cloudfoundry-buildpack/releases/tag/4.23.0
