### ISSUE TITLE
NoClassDefFoundError in version 4.40

### ISSUE THREAD

**Issue by jhmcstanton** [cloudfoundry/java-buildpack#900]
Some of our teams have received NoClassDefFoundError ~5 minutes after their spring boot apps start, causing crashes. This is happening with apps that are using spring boot 2.1.x. 

Example errors:

```
java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy.
```

```
Handler processing failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/servlet/ModelAndViewDefiningException
```

Folks have reported that this does not happen in spring boot 2.3.5

**Comment by dmikusa-pivotal** [comment]
OK, what do you feel is the relationship between the issue you're seeing here and the Java buildpack?

Once your app has started, the Java buildpack isn't involved anymore. It's finished running. Is there something you feel it's doing to set up your app that is contributing to this problem? Thanks

**Comment by jhmcstanton** [comment]
These apps started getting these issues only after being restaged - no code
changes happened. These errors would occur when picking up the new
buildpacks, so they were typically jumping from 4.37-4.39 to 4.40-4.41.
apps without a restage were unaffected.

**Comment by dmikusa-pivotal** [comment]
While that's interesting, I apologize but there's just not enough information here for us to act on this. If you feel strongly this is an issue, I would suggest one of the following actions:

1. Submit a demo app and step-by-step instructions that we can use to reproduce the issue. This would be something like deploy app A to CF, update the buildpack to x.y.z version, and restage the app. After doing this, you'll see the error you originally mentioned.

2. Investigate to see if you can tie the behavior you're seeing to a change in the buildpack or to something that is just behaving questionably. If you can tie the behavior you're seeing to something that has changed recently or to something that is just behaving questionably then we could take a closer look at the specific code. You can see what's changed recently [here](https://github.com/cloudfoundry/java-buildpack/compare/v4.39...v4.40) (adjust the link to compare different versions).

For what it's worth, I can't recall any recent changes that would impact the classpath we generate, where the classpath could potentially affect how classes are loaded. Most of the recent changes have been specific to integrations with the buildpack and 3rd party services, not with the core buildpack. The only other large change that we made is to bump the version of Java that is included, v4.40 bumps to 1.8.0_302 and 11.0.12_7 (and 4.41 pulls in 16.0.2). I don't see how that would cause your problem, but you may want to try pinning the previous version of Java you used and see if that helps.

Aside from that, you're running what is now a [pretty old version of Spring Boot](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions). That went EOGS in November 2020. You could be hitting issues with the age and lack of updates. That's not something we could help with given it's out of support.

Hope that helps!

**Comment by jhmcstanton** [comment]
Thanks, we appreciate this quick response! I'll try to coordinate some work to reproduce this, the soonest that would happen is tomorrow.

**Comment by dmikusa-pivotal** [comment]
@jhmcstanton - any update on this? Were you able to track down any additional information about the problem? Thanks
