### ISSUE TITLE
Using the ibmjre no longer works with the java_buildpack

### ISSUE THREAD

**Issue by kevin-ortega** [cloudfoundry/java-buildpack#902]
The IBM Java team removed the repo where the java_buildpack was downloading the IBM JRE.  

The index.yml now resides at https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/8.0/sfj/linux/x86_64

Additionally, the url for the jvmkill agent no longer exists.

Just changing the repository_root for the jre in the [config](https://github.com/cloudfoundry/java-buildpack/blob/main/config/ibm_jre.yml) file is not sufficient because the index format has also changed. 

Previously, the format was:
```
1.8.0_sr6fp26: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.6.26/linux/x86_64/ibm-java-jre-8.0-6.26-x86_64-archive.bin
1.8.0_sr6fp30: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.6.30/linux/x86_64/ibm-java-jre-8.0-6.30-x86_64-archive.bin
1.8.0_sr6fp31: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.6.31/linux/x86_64/ibm-java-jre-8.0-6.31-x86_64-archive.bin
```
Now the format  is:
```
8.0.6.35:
    uri: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.6.35/linux/x86_64/ibm-java-sfj-8.0-6.35-x86_64-archive.bin
    sha256sum: d9ad4dd78cde42b44a0e9ba91d6b85fb134b56fb30ef0009153cfba54778978e
    license: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?l=en&la_formnum=&li_formnum=L-SMKR-AVSEUH

8.0.6.36:
    uri: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.6.36/linux/x86_64/ibm-java-sfj-8.0-6.36-x86_64-archive.bin
    sha256sum: aee78edcb2b1eed2e89b60ecfd787c77cc86e1fea646d06e5064f33615379bef
    license: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?l=en&la_formnum=&li_formnum=L-SMKR-AVSEUH
https://github.com/cloudfoundry/java-buildpack/blob/main/config/ibm_jre.yml
```

I think the repo root for the killjvm agent can be changed to https://github.com/ibmruntimes/jvmkill/tree/jvmkill-ibmagent/jvmkill-agent

**Comment by dmikusa-pivotal** [comment]
@kevin-ortega Hi, thanks for raising this up. 

The buildpack won't be able to consume that index.yml file. It needs to retain the same format as the original file. Is there a reason on your end for the change? Would it be possible to have the original format?

**Comment by kevin-ortega** [comment]
@dmikusa-pivotal Hi Daniel, I do not know why the IBM Java team changed the format of the index file.  The liberty buildpack is using the new format and index.yml location.   I am in discussions with the Java team to see if they will continue to maintain the original index.  Since I opened this issue I realized that the repo where the JREs are located still exists and it's the index file that wasn't updated as new JREs were released.   If I can get the Java team to continue to maintain the index then I will close this issue.   I guess an alternative would be to host the index somewhere else but then it would have to be maintained and updated when new JREs are released.

**Comment by kevin-ortega** [comment]
@dmikusa-pivotal Some good news, I did convince the Java team to update the index.yml at https://raw.githubusercontent.com/ibmruntimes/ci.docker/master/ibmjava/meta/jre/linux/x86_64.   So, I think for now the java_buildpack will continue to work with the IBM JRE.  I don't know how long they will keep that index updated.  It still may be a good idea if the java_buildpack worked with the new index format.  

The immediate issue is resolved and this issue can be closed.

**Comment by dmikusa-pivotal** [comment]
@kevin-ortega Thanks so much for checking into this. I'm glad to hear they will keep maintaining it. Let's see how this goes.

If that doesn't work, we can look at hosting the index.yml elsewhere.
