### ISSUE TITLE
Download of the Datadog Agent is broken

### ISSUE THREAD

**Issue by Noxaro** [cloudfoundry/java-buildpack#905]
Hi,

i currently have problems with the latest java buildpack 4.42. 
It tires to download the Datadog agent from a wrong url:

-----> Downloading Datadog Javaagent 0.88.0 from https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.87.0/dd-java-agent-0.88.0.jar Exit status 223

The download path for the agent jar is currently incorrect. It should be one of the following:
https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.87.0/dd-java-agent-0.87.0.jar 
or
https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.88.0/dd-java-agent-0.88.0.jar

Best Regards
Noxaro

**Comment by dmikusa-pivotal** [comment]
Hi, thanks for reporting this issue! 

It looks like the entry in the [index.yml](https://raw.githubusercontent.com/datadog/dd-trace-java/cloudfoundry/index.yml) file for the DataDog Agent is invalid. We do not control that file, so I can't update it, but I can try to reach out to someone at DataDog and see if we can get that updated. I'll keep you posted.

In the meantime, you have a couple of options for working around this. You can set the DataDog version to 0.87.0 and it'll pick the link that works. If you happen to need 0.88.0, you can make your own index.yml file (just copy the one I linked to and fix the link). Then throw that file up on an HTTP server & point the [data dog repository config](https://github.com/cloudfoundry/java-buildpack/blob/main/config/datadog_javaagent.yml#L19) setting to it.

You can modify config using [these instructions](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension).

**Comment by Noxaro** [comment]
An Update from my side:
I've reported this problem as an urgent case to datadog as it looks like they uploaded a broken configuration file here:
https://raw.githubusercontent.com/datadog/dd-trace-java/cloudfoundry/index.yml

**Comment by dmikusa-pivotal** [comment]
I got confirmation from DataDog that this has been resolved. Please reopen if you're still seeing issues.
