### ISSUE TITLE
Please bump up the jprofiler agent jar version

### ISSUE THREAD

**Issue by shivsepra** [cloudfoundry/java-buildpack#914]
Please bump up jprofiler agent to 12.x version.

**Comment by dmikusa-pivotal** [comment]
Short term. Version 12 is present if you would like it, you can specify it.

This is the list of versions at the time I write this comment:

```
10.1.2: https://download.run.pivotal.io/jprofiler/jprofiler-10.1.2.tar.gz
10.1.3: https://download.run.pivotal.io/jprofiler/jprofiler-10.1.3.tar.gz
10.1.4: https://download.run.pivotal.io/jprofiler/jprofiler-10.1.4.tar.gz
10.1.5: https://download.run.pivotal.io/jprofiler/jprofiler-10.1.5.tar.gz
11.0.0: https://download.run.pivotal.io/jprofiler/jprofiler-11.0.tar.gz
11.0.1: https://download.run.pivotal.io/jprofiler/jprofiler-11.0.1.tar.gz
11.0.2: https://download.run.pivotal.io/jprofiler/jprofiler-11.0.2.tar.gz
11.1.0: https://download.run.pivotal.io/jprofiler/jprofiler-11.1.tar.gz
11.1.1: https://download.run.pivotal.io/jprofiler/jprofiler-11.1.1.tar.gz
11.1.2: https://download.run.pivotal.io/jprofiler/jprofiler-11.1.2.tar.gz
11.1.3: https://download.run.pivotal.io/jprofiler/jprofiler-11.1.3.tar.gz
11.1.4: https://download.run.pivotal.io/jprofiler/jprofiler-11.1.4.tar.gz
12.0.0: https://download.run.pivotal.io/jprofiler/jprofiler-12.0.tar.gz
12.0.1: https://download.run.pivotal.io/jprofiler/jprofiler-12.0.1.tar.gz
12.0.2: https://download.run.pivotal.io/jprofiler/jprofiler-12.0.2.tar.gz
12.0.3: https://download.run.pivotal.io/jprofiler/jprofiler-12.0.3.tar.gz
12.0.4: https://download.run.pivotal.io/jprofiler/jprofiler-12.0.4.tar.gz
```

That comes from: https://download.run.pivotal.io/jprofiler/index.yml

To pick a non-default version like version 12, you need to set `JBP_CONFIG_JPROFILER_PROFILER_VERSION` to `12+` (or whatever version you want).

I'm not opposed to switching the default version that we use to 12. From the JProfiler site, the 11 branch is no longer being maintained. Unless there are any strenuous objections, I'll make that change with the next release.

Thanks!

**Comment by shivsepra** [comment]
@dmikusa-pivotal 
I tried to use the configuration to point to a specific jprofiler version. Since we use offline buildpacks, the app fails while restaging.
Unable to find the cached file for https://download.run.pivotal.io/jprofiler/jprofiler-12.0.2.tar.gz.

**Comment by dmikusa-pivotal** [comment]
I've made the change on the `bump-jprofiler-default` branch. If you want to test, you can `cf push -b https://github.com/cloudfoundry/java-buildpack#bump-jprofiler-default`.

If you test and have issues, please let me know. I'll merge & pull this into the next release.
