### ISSUE TITLE
application failed to deploy

### ISSUE THREAD

**Issue by sidnepal2048** [cloudfoundry/java-buildpack#925]
I am getting following error during deployment. Any idea how to fix this?

```
ERROR Finalize failed with exception #<RuntimeError: Unable to find cached file for https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/bellsoft-jre15.0.2%2B10-linux-amd64.tar.gz>
```

Note: I am using java build pack 4.46

**Comment by dmikusa-pivotal** [comment]
The version of Java you are trying to use is not available in that version of the offline buildpack. Java 15 has not been supported for a while now. You should consider upgrading to Java 17.

You likely have an env variable that is set which is telling the buildpack to use this particular version of Java. Look at the output of `cf env` and look at env variables starting with `JBP_CONFIG_*`.
