### ISSUE TITLE
Add support for Traceable Java Agent

### ISSUE THREAD

**Issue by ryandens** [cloudfoundry/java-buildpack#931]
Hi, 
I'd like to add support for the [traceable.ai](https://traceable.ai) java agent as a buildpack. This agent collects data from a user's applications and reports it to the Traceable platform for analysis, in addition to providing runtime protection.

I'd also like to receive instructions for how fill out the Contributor License Agreement.

**Comment by dmikusa-pivotal** [comment]
Fantastic! I would suggest starting with the [Extension Docs](https://github.com/cloudfoundry/java-buildpack/blob/main/docs/extending.md) here. Most likely you'd start with a [Versioned Dependency Component](https://github.com/cloudfoundry/java-buildpack/blob/main/docs/extending-versioned_dependency_component.md). This would be added as a new "framework".

There are a number of existing frameworks that add Java agents, so you can take a look at those as examples also.  See under https://github.com/cloudfoundry/java-buildpack/tree/main/lib/java_buildpack/framework.

There are some general [tips here as well](https://github.com/cloudfoundry/java-buildpack/blob/main/CONTRIBUTING.md).

Let me look into the CLA stuff for you. I'll get you some instructions shortly.

**Comment by ryandens** [comment]
Thank you!

**Comment by dmikusa-pivotal** [comment]
Closing this as there were licensing concerns. See the comments [here](https://github.com/cloudfoundry/java-buildpack/pull/932#issuecomment-1058480279) for details.
