### ISSUE TITLE
Critical CVEs in OpenJDK - update to the latest versions

### ISSUE THREAD

**Issue by maximilianro** [cloudfoundry/java-buildpack#936]
There were some critical vulnerabilities discovered in OpenJDK: https://openjdk.java.net/groups/vulnerability/advisories/2022-04-19 

The OpenJDK versions including a fix were released yesterday. It would be great if you could update the Java versions for 8, 11 and 17 and release a new buildpack version quickly.

**Comment by dmikusa-pivotal** [comment]
OpenJDK & Oracle kick off this process, but it takes the various JVM vendors time to catch up. Usually 1-2 days. We are awaiting releases for Java 8/11/17 from Bellsoft, which is the vendor presently being used in the CF Java buildpack, and anticipate them any time now. As soon as they are ready, we'll cut a release.

**Comment by jlmeier** [comment]
Hi @dmikusa-pivotal
According to the following blog post, the patches for bellsoft are already released. Is there any estimation, when the new buildpack will be available?
https://bell-sw.com/announcements/2022/04/21/liberica-18-0-1-17-0-3-11-0-15-and-8u332-builds-are-generally-available/

**Comment by dmikusa-pivotal** [comment]
It is not a fully automated process. It takes a little time to process. That said, [4.48.3](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.48.3) has been released with the latest OpenJDK release.
