### ISSUE TITLE
Support cflinuxfs4 (Ubuntu Jammy)

### ISSUE THREAD

**Issue by dmikusa** [cloudfoundry/java-buildpack#960]
This is a meta issue that involves a number of smaller issues, but I'm logging this for folks that want to track our efforts. Watch here for updates & when this story closes we should be compatible with cflinuxfs4.

Not an exhaustive list, but some of the items remaining

- [X] Make the buildpack compatible with ruby 3.0
- [X] Adjust CI pipelines to run unit tests against ruby 3.0 to catch any potential regressions
- [x] Update jvmkill agent and make it run on cflinuxfs4
- [x] Update integration tests & ensure running against both stacks in CI

**Comment by pivotal-david-osullivan** [comment]
Closing this as we now support cflinuxfs4
