### ISSUE TITLE
Contrast Security Agent || Plugins Package

### ISSUE THREAD

**Issue by csseifms** [cloudfoundry/java-buildpack#976]
Hello,

[Plugin PKG Code](https://github.com/cloudfoundry/java-buildpack/blob/81b261e1a96ac22259c0e4a75c5abc639a164fdb/lib/java_buildpack/framework/contrast_security_agent.rb#L95) Please elaborate to clarify adding [aspectsecurity](https://github.com/cloudfoundry/java-buildpack/blob/81b261e1a96ac22259c0e4a75c5abc639a164fdb/lib/java_buildpack/framework/contrast_security_agent.rb#L70) because I could not see anything about this from [doc](https://github.com/cloudfoundry/java-buildpack/blob/main/docs/framework-contrast_security_agent.md). 

I am implementing same logic from Ruby to Java. 
Excuse my lack of knowledge in Ruby and please correct me if one of the above links is not correct. 

Do I really need this Plugins to be added in my java implementation? 
Any hints for the correct mapping in java if the answer is "Yes, I have to add it"?
Can you advise how those plugins are used and sourced?

Thanks in advance!
BR,
Seif

**Comment by csseifms** [comment]
@pivotal-david-osullivan do you have any info here to support me?

**Comment by dmikusa** [comment]
I'm not sure that I understand the question you're asking here.

The section of code that you're referencing is building up the contract security configuration file and writing it out. I'm not familiar with Contrast so I don't know what those settings are doing, but the code is writing out the XML config file with those options set. If you need to know more about what the options do, you'd want to ask someone at Contrast Security.

If that does not answer your question, apologizes, please try to clarify what you're asking. Thanksl

**Comment by csseifms** [comment]
Hello @dmikusa, 

Thanks for your answer, Could you please provide me with example for this XML config file that should be the input for Contrast Security please?

Do you know how [aspectsecurity](https://github.com/cloudfoundry/java-buildpack/blob/81b261e1a96ac22259c0e4a75c5abc639a164fdb/lib/java_buildpack/framework/contrast_security_agent.rb#L70) is sourced? I could not find any explanations for that in the documentation and I think I would need it to generate XML config file as input for Contrast Security.

BR, 
Seif

**Comment by dmikusa** [comment]
Sorry, I don't know anything about the content of that file. The buildpack writes it but it's not buildpack-specific. It's something read by the agent when the agent runs. I would suggest looking at Contract Security documentation for information about the file. We pass the config file path to the agent through the `-javaagent` argument, so you might have a look at the agent docs and start there.

Hope that helps!
